// AUTO-GEGENEREERD via scripts/extract_badges.py
// uit docs/reference/deelevaluaties_alle-graden-2.xlsx — niet met de hand aanpassen.
import type { CursusRuw, BadgeRuw } from "./curriculum";

export const cursussen1A: CursusRuw[] = [
  { id: "1A-planning-en-reflectie", stroom: "1A", naam: "Planning en reflectie", volgorde: 0 },
  { id: "1A-klasraad", stroom: "1A", naam: "Klasraad", volgorde: 1 },
  { id: "1A-burgerschap", stroom: "1A", naam: "Burgerschap", volgorde: 2 },
  { id: "1A-ateliers", stroom: "1A", naam: "Ateliers", volgorde: 3 },
  { id: "1A-kring", stroom: "1A", naam: "Kring", volgorde: 4 },
  { id: "1A-actuaronde", stroom: "1A", naam: "Actuaronde", volgorde: 5 },
  { id: "1A-vrije-tekst", stroom: "1A", naam: "Vrije Tekst", volgorde: 6 },
  { id: "1A-boekenronde", stroom: "1A", naam: "Boekenronde", volgorde: 7 },
  { id: "1A-communicatie", stroom: "1A", naam: "Communicatie", volgorde: 8 },
  { id: "1A-onderzoek", stroom: "1A", naam: "Onderzoek", volgorde: 9 },
  { id: "1A-klaskas", stroom: "1A", naam: "Klaskas", volgorde: 10 },
  { id: "1A-levende-wiskunde", stroom: "1A", naam: "Levende Wiskunde", volgorde: 11 },
  { id: "1A-cultuur", stroom: "1A", naam: "Cultuur", volgorde: 12 },
  { id: "1A-exploratie", stroom: "1A", naam: "Exploratie", volgorde: 13 },
  { id: "1A-toonmoment", stroom: "1A", naam: "Toonmoment", volgorde: 14 },
  { id: "1A-welzijn", stroom: "1A", naam: "Welzijn", volgorde: 15 },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes", stroom: "1A", naam: "Vrij initiatief buiten de lijntjes", volgorde: 16 },
];

export const badges1A: BadgeRuw[] = [
  { id: "1A-planning-en-reflectie-d1", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d2", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d3", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d4", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d5", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d6", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d7", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d8", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d9", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 9", volgorde: 8, categorie: "standaard" },
  { id: "1A-planning-en-reflectie-d10", cursusId: "1A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 10", volgorde: 9, categorie: "standaard" },
  { id: "1A-klasraad-d1", cursusId: "1A-klasraad", groep: "Voorzitter", omschrijving: "Voorzitter 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-klasraad-d2", cursusId: "1A-klasraad", groep: "Voorzitter", omschrijving: "Voorzitter 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-klasraad-d3", cursusId: "1A-klasraad", groep: "Voorzitter", omschrijving: "Voorzitter 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-klasraad-d4", cursusId: "1A-klasraad", groep: "Voorzitter", omschrijving: "Voorzitter 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-klasraad-d5", cursusId: "1A-klasraad", groep: "Secretaris", omschrijving: "Secretaris 1", volgorde: 4, categorie: "standaard" },
  { id: "1A-klasraad-d6", cursusId: "1A-klasraad", groep: "Secretaris", omschrijving: "Secretaris 2", volgorde: 5, categorie: "standaard" },
  { id: "1A-klasraad-d7", cursusId: "1A-klasraad", groep: "Secretaris", omschrijving: "Secretaris 3", volgorde: 6, categorie: "standaard" },
  { id: "1A-klasraad-d8", cursusId: "1A-klasraad", groep: "Secretaris", omschrijving: "Secretaris 4", volgorde: 7, categorie: "standaard" },
  { id: "1A-klasraad-d9", cursusId: "1A-klasraad", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 1", volgorde: 8, categorie: "standaard" },
  { id: "1A-klasraad-d10", cursusId: "1A-klasraad", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 2", volgorde: 9, categorie: "standaard" },
  { id: "1A-klasraad-d11", cursusId: "1A-klasraad", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 3", volgorde: 10, categorie: "standaard" },
  { id: "1A-klasraad-d12", cursusId: "1A-klasraad", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 4", volgorde: 11, categorie: "standaard" },
  { id: "1A-klasraad-d13", cursusId: "1A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 1", volgorde: 12, categorie: "standaard" },
  { id: "1A-klasraad-d14", cursusId: "1A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 2", volgorde: 13, categorie: "standaard" },
  { id: "1A-klasraad-d15", cursusId: "1A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 3", volgorde: 14, categorie: "standaard" },
  { id: "1A-klasraad-d16", cursusId: "1A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 4", volgorde: 15, categorie: "standaard" },
  { id: "1A-klasraad-d17", cursusId: "1A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 5", volgorde: 16, categorie: "standaard" },
  { id: "1A-klasraad-d18", cursusId: "1A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 6", volgorde: 17, categorie: "standaard" },
  { id: "1A-klasraad-d19", cursusId: "1A-klasraad", groep: "Vestigingsraad/Keerpuntraad/Leerlingenraad", omschrijving: "Vestigingsraad/Keerpuntraad/Leerlingenraad", volgorde: 18, categorie: "standaard" },
  { id: "1A-burgerschap-d1", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-burgerschap-d2", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-burgerschap-d3", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-burgerschap-d4", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-burgerschap-d5", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-burgerschap-d6", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-burgerschap-d7", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-burgerschap-d8", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-burgerschap-d9", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 9", volgorde: 8, categorie: "standaard" },
  { id: "1A-burgerschap-d10", cursusId: "1A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 10", volgorde: 9, categorie: "standaard" },
  { id: "1A-burgerschap-d11", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 1", volgorde: 10, categorie: "standaard" },
  { id: "1A-burgerschap-d12", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 2", volgorde: 11, categorie: "standaard" },
  { id: "1A-burgerschap-d13", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 3", volgorde: 12, categorie: "standaard" },
  { id: "1A-burgerschap-d14", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 4", volgorde: 13, categorie: "standaard" },
  { id: "1A-burgerschap-d15", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 5", volgorde: 14, categorie: "standaard" },
  { id: "1A-burgerschap-d16", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 6", volgorde: 15, categorie: "standaard" },
  { id: "1A-burgerschap-d17", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 7", volgorde: 16, categorie: "standaard" },
  { id: "1A-burgerschap-d18", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 8", volgorde: 17, categorie: "standaard" },
  { id: "1A-burgerschap-d19", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 9", volgorde: 18, categorie: "standaard" },
  { id: "1A-burgerschap-d20", cursusId: "1A-burgerschap", groep: "Extern burgerschap (2 lestijden)", omschrijving: "Extern burgerschap (2 lestijden) 10", volgorde: 19, categorie: "standaard" },
  { id: "1A-ateliers-d1", cursusId: "1A-ateliers", groep: "Natuur", omschrijving: "Natuur", volgorde: 0, categorie: "standaard" },
  { id: "1A-ateliers-d2", cursusId: "1A-ateliers", groep: "Handvaardigheid, bouw & techniek", omschrijving: "Handvaardigheid, bouw & techniek", volgorde: 1, categorie: "standaard" },
  { id: "1A-ateliers-d3", cursusId: "1A-ateliers", groep: "Kennis", omschrijving: "Kennis", volgorde: 2, categorie: "standaard" },
  { id: "1A-ateliers-d4", cursusId: "1A-ateliers", groep: "Experimenten, wetenschappelijk onderzoek & innovatie", omschrijving: "Experimenten, wetenschappelijk onderzoek & innovatie", volgorde: 3, categorie: "standaard" },
  { id: "1A-ateliers-d5", cursusId: "1A-ateliers", groep: "ICT, digitale & moderne technieken", omschrijving: "ICT, digitale & moderne technieken", volgorde: 4, categorie: "standaard" },
  { id: "1A-ateliers-d6", cursusId: "1A-ateliers", groep: "Expressie, creatie & ontwerp", omschrijving: "Expressie, creatie & ontwerp", volgorde: 5, categorie: "standaard" },
  { id: "1A-ateliers-d7", cursusId: "1A-ateliers", groep: "Welzijn en andere", omschrijving: "Welzijn en andere", volgorde: 6, categorie: "standaard" },
  { id: "1A-ateliers-d8", cursusId: "1A-ateliers", groep: "Eén atelier volgen in elk van de 7 domeinen (graadsbadge)", omschrijving: "Eén atelier volgen in elk van de 7 domeinen (graadsbadge)", volgorde: 7, categorie: "standaard" },
  { id: "1A-kring-d1", cursusId: "1A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-kring-d2", cursusId: "1A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-kring-d3", cursusId: "1A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-kring-d4", cursusId: "1A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-kring-d5", cursusId: "1A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-kring-d6", cursusId: "1A-kring", groep: "Secretaris", omschrijving: "Secretaris 1", volgorde: 5, categorie: "standaard" },
  { id: "1A-kring-d7", cursusId: "1A-kring", groep: "Secretaris", omschrijving: "Secretaris 2", volgorde: 6, categorie: "standaard" },
  { id: "1A-kring-d8", cursusId: "1A-kring", groep: "Secretaris", omschrijving: "Secretaris 3", volgorde: 7, categorie: "standaard" },
  { id: "1A-kring-d9", cursusId: "1A-kring", groep: "Secretaris", omschrijving: "Secretaris 4", volgorde: 8, categorie: "standaard" },
  { id: "1A-kring-d10", cursusId: "1A-kring", groep: "Secretaris", omschrijving: "Secretaris 5", volgorde: 9, categorie: "standaard" },
  { id: "1A-kring-d11", cursusId: "1A-kring", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 1", volgorde: 10, categorie: "standaard" },
  { id: "1A-kring-d12", cursusId: "1A-kring", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 2", volgorde: 11, categorie: "standaard" },
  { id: "1A-kring-d13", cursusId: "1A-kring", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 3", volgorde: 12, categorie: "standaard" },
  { id: "1A-kring-d14", cursusId: "1A-kring", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 4", volgorde: 13, categorie: "standaard" },
  { id: "1A-kring-d15", cursusId: "1A-kring", groep: "Tijdsbewaker", omschrijving: "Tijdsbewaker 5", volgorde: 14, categorie: "standaard" },
  { id: "1A-kring-d16", cursusId: "1A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 1", volgorde: 15, categorie: "standaard" },
  { id: "1A-kring-d17", cursusId: "1A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 2", volgorde: 16, categorie: "standaard" },
  { id: "1A-kring-d18", cursusId: "1A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 3", volgorde: 17, categorie: "standaard" },
  { id: "1A-kring-d19", cursusId: "1A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 4", volgorde: 18, categorie: "standaard" },
  { id: "1A-kring-d20", cursusId: "1A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 5", volgorde: 19, categorie: "standaard" },
  { id: "1A-kring-d21", cursusId: "1A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 6", volgorde: 20, categorie: "standaard" },
  { id: "1A-kring-d22", cursusId: "1A-kring", groep: "Kring Frans", omschrijving: "Kring Frans 1", volgorde: 21, categorie: "standaard" },
  { id: "1A-kring-d23", cursusId: "1A-kring", groep: "Kring Frans", omschrijving: "Kring Frans 2", volgorde: 22, categorie: "standaard" },
  { id: "1A-kring-d24", cursusId: "1A-kring", groep: "Kring Frans", omschrijving: "Kring Frans 3", volgorde: 23, categorie: "standaard" },
  { id: "1A-kring-d25", cursusId: "1A-kring", groep: "Kring Frans", omschrijving: "Kring Frans 4", volgorde: 24, categorie: "standaard" },
  { id: "1A-kring-d26", cursusId: "1A-kring", groep: "Kring Engels", omschrijving: "Kring Engels 1", volgorde: 25, categorie: "standaard" },
  { id: "1A-kring-d27", cursusId: "1A-kring", groep: "Kring Engels", omschrijving: "Kring Engels 2", volgorde: 26, categorie: "standaard" },
  { id: "1A-kring-d28", cursusId: "1A-kring", groep: "Kring Engels", omschrijving: "Kring Engels 3", volgorde: 27, categorie: "standaard" },
  { id: "1A-kring-d29", cursusId: "1A-kring", groep: "Kring Engels", omschrijving: "Kring Engels 4", volgorde: 28, categorie: "standaard" },
  { id: "1A-actuaronde-d1", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-actuaronde-d2", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-actuaronde-d3", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-actuaronde-d4", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-actuaronde-d5", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-actuaronde-d6", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-actuaronde-d7", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-actuaronde-d8", cursusId: "1A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-actuaronde-d9", cursusId: "1A-actuaronde", groep: "Actuaronde Frans", omschrijving: "Actuaronde Frans 1", volgorde: 8, categorie: "standaard" },
  { id: "1A-actuaronde-d10", cursusId: "1A-actuaronde", groep: "Actuaronde Frans", omschrijving: "Actuaronde Frans 2", volgorde: 9, categorie: "standaard" },
  { id: "1A-actuaronde-d11", cursusId: "1A-actuaronde", groep: "Actuaronde Engels", omschrijving: "Actuaronde Engels 1", volgorde: 10, categorie: "standaard" },
  { id: "1A-actuaronde-d12", cursusId: "1A-actuaronde", groep: "Actuaronde Engels", omschrijving: "Actuaronde Engels 2", volgorde: 11, categorie: "standaard" },
  { id: "1A-vrije-tekst-d1", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-vrije-tekst-d2", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-vrije-tekst-d3", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-vrije-tekst-d4", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-vrije-tekst-d5", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-vrije-tekst-d6", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-vrije-tekst-d7", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-vrije-tekst-d8", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-vrije-tekst-d9", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 1", volgorde: 8, categorie: "standaard" },
  { id: "1A-vrije-tekst-d10", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 2", volgorde: 9, categorie: "standaard" },
  { id: "1A-vrije-tekst-d11", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 3", volgorde: 10, categorie: "standaard" },
  { id: "1A-vrije-tekst-d12", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 4", volgorde: 11, categorie: "standaard" },
  { id: "1A-vrije-tekst-d13", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 5", volgorde: 12, categorie: "standaard" },
  { id: "1A-vrije-tekst-d14", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 6", volgorde: 13, categorie: "standaard" },
  { id: "1A-vrije-tekst-d15", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 1", volgorde: 14, categorie: "standaard" },
  { id: "1A-vrije-tekst-d16", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 2", volgorde: 15, categorie: "standaard" },
  { id: "1A-vrije-tekst-d17", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 3", volgorde: 16, categorie: "standaard" },
  { id: "1A-vrije-tekst-d18", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 4", volgorde: 17, categorie: "standaard" },
  { id: "1A-vrije-tekst-d19", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 5", volgorde: 18, categorie: "standaard" },
  { id: "1A-vrije-tekst-d20", cursusId: "1A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 6", volgorde: 19, categorie: "standaard" },
  { id: "1A-boekenronde-d1", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-boekenronde-d2", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-boekenronde-d3", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-boekenronde-d4", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-boekenronde-d5", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-boekenronde-d6", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-boekenronde-d7", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-boekenronde-d8", cursusId: "1A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-boekenronde-d9", cursusId: "1A-boekenronde", groep: "Boekenronde Frans", omschrijving: "Boekenronde Frans 1", volgorde: 8, categorie: "standaard" },
  { id: "1A-boekenronde-d10", cursusId: "1A-boekenronde", groep: "Boekenronde Frans", omschrijving: "Boekenronde Frans 2", volgorde: 9, categorie: "standaard" },
  { id: "1A-boekenronde-d11", cursusId: "1A-boekenronde", groep: "Boekenronde Frans", omschrijving: "Boekenronde Frans 3", volgorde: 10, categorie: "standaard" },
  { id: "1A-boekenronde-d12", cursusId: "1A-boekenronde", groep: "Boekenronde Engels", omschrijving: "Boekenronde Engels 1", volgorde: 11, categorie: "standaard" },
  { id: "1A-boekenronde-d13", cursusId: "1A-boekenronde", groep: "Boekenronde Engels", omschrijving: "Boekenronde Engels 2", volgorde: 12, categorie: "standaard" },
  { id: "1A-boekenronde-d14", cursusId: "1A-boekenronde", groep: "Boekenronde Engels", omschrijving: "Boekenronde Engels 3", volgorde: 13, categorie: "standaard" },
  { id: "1A-communicatie-d1", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie", omschrijving: "Krant/Correspondentie publicatie 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-communicatie-d2", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie", omschrijving: "Krant/Correspondentie publicatie 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-communicatie-d3", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie", omschrijving: "Krant/Correspondentie publicatie 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-communicatie-d4", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie", omschrijving: "Krant/Correspondentie publicatie 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-communicatie-d5", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie", omschrijving: "Krant/Correspondentie publicatie 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-communicatie-d6", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie Frans", omschrijving: "Krant/Correspondentie publicatie Frans 1", volgorde: 5, categorie: "standaard" },
  { id: "1A-communicatie-d7", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie Frans", omschrijving: "Krant/Correspondentie publicatie Frans 2", volgorde: 6, categorie: "standaard" },
  { id: "1A-communicatie-d8", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie Frans", omschrijving: "Krant/Correspondentie publicatie Frans 3", volgorde: 7, categorie: "standaard" },
  { id: "1A-communicatie-d9", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie Engels", omschrijving: "Krant/Correspondentie publicatie Engels 1", volgorde: 8, categorie: "standaard" },
  { id: "1A-communicatie-d10", cursusId: "1A-communicatie", groep: "Krant/Correspondentie publicatie Engels", omschrijving: "Krant/Correspondentie publicatie Engels 2", volgorde: 9, categorie: "standaard" },
  { id: "1A-communicatie-d11", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern", omschrijving: "Activiteit Keerpunt/extern 1", volgorde: 10, categorie: "standaard" },
  { id: "1A-communicatie-d12", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern", omschrijving: "Activiteit Keerpunt/extern 2", volgorde: 11, categorie: "standaard" },
  { id: "1A-communicatie-d13", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern", omschrijving: "Activiteit Keerpunt/extern 3", volgorde: 12, categorie: "standaard" },
  { id: "1A-communicatie-d14", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern", omschrijving: "Activiteit Keerpunt/extern 4", volgorde: 13, categorie: "standaard" },
  { id: "1A-communicatie-d15", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern Frans", omschrijving: "Activiteit Keerpunt/extern Frans 1", volgorde: 14, categorie: "standaard" },
  { id: "1A-communicatie-d16", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern Frans", omschrijving: "Activiteit Keerpunt/extern Frans 2", volgorde: 15, categorie: "standaard" },
  { id: "1A-communicatie-d17", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern Engels", omschrijving: "Activiteit Keerpunt/extern Engels 1", volgorde: 16, categorie: "standaard" },
  { id: "1A-communicatie-d18", cursusId: "1A-communicatie", groep: "Activiteit Keerpunt/extern Engels", omschrijving: "Activiteit Keerpunt/extern Engels 2", volgorde: 17, categorie: "standaard" },
  { id: "1A-onderzoek-d1", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-onderzoek-d2", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-onderzoek-d3", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-onderzoek-d4", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-onderzoek-d5", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-onderzoek-d6", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-onderzoek-d7", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-onderzoek-d8", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-onderzoek-d9", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 9", volgorde: 8, categorie: "standaard" },
  { id: "1A-onderzoek-d10", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 10", volgorde: 9, categorie: "standaard" },
  { id: "1A-onderzoek-d11", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 11", volgorde: 10, categorie: "standaard" },
  { id: "1A-onderzoek-d12", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 12", volgorde: 11, categorie: "standaard" },
  { id: "1A-onderzoek-d13", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 13", volgorde: 12, categorie: "standaard" },
  { id: "1A-onderzoek-d14", cursusId: "1A-onderzoek", groep: "Kwaliteitsvol onderzoek", omschrijving: "Kwaliteitsvol onderzoek 14", volgorde: 13, categorie: "standaard" },
  { id: "1A-onderzoek-d15", cursusId: "1A-onderzoek", groep: "Historisch - Algemene periodisering", omschrijving: "Historisch - Algemene periodisering", volgorde: 14, categorie: "standaard" },
  { id: "1A-onderzoek-d16", cursusId: "1A-onderzoek", groep: "Historisch - Niet-Westerse periodisering", omschrijving: "Historisch - Niet-Westerse periodisering", volgorde: 15, categorie: "standaard" },
  { id: "1A-onderzoek-d17", cursusId: "1A-onderzoek", groep: "Historisch - Prehistorie: politiek, sociaal, economisch, cultureel", omschrijving: "Historisch - Prehistorie: politiek, sociaal, economisch, cultureel", volgorde: 16, categorie: "standaard" },
  { id: "1A-onderzoek-d18", cursusId: "1A-onderzoek", groep: "Historisch - Oude Nabije Oosten: politiek, sociaal, economisch, cultureel", omschrijving: "Historisch - Oude Nabije Oosten: politiek, sociaal, economisch, cultureel", volgorde: 17, categorie: "standaard" },
  { id: "1A-onderzoek-d19", cursusId: "1A-onderzoek", groep: "Historisch - Klassieke Oudheid: politiek, sociaal, economisch, cultureel", omschrijving: "Historisch - Klassieke Oudheid: politiek, sociaal, economisch, cultureel", volgorde: 18, categorie: "standaard" },
  { id: "1A-onderzoek-d20", cursusId: "1A-onderzoek", groep: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", omschrijving: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", volgorde: 19, categorie: "standaard" },
  { id: "1A-onderzoek-d21", cursusId: "1A-onderzoek", groep: "Ruimtelijk - Geografische eenheden: landschappen, reliëf, ondergrond, klimaat, vegetatie", omschrijving: "Ruimtelijk - Geografische eenheden: landschappen, reliëf, ondergrond, klimaat, vegetatie", volgorde: 20, categorie: "standaard" },
  { id: "1A-onderzoek-d22", cursusId: "1A-onderzoek", groep: "Ruimtelijk - Evolutie en verandering", omschrijving: "Ruimtelijk - Evolutie en verandering", volgorde: 21, categorie: "standaard" },
  { id: "1A-onderzoek-d23", cursusId: "1A-onderzoek", groep: "Exacte wetenschappen - Deeltjesmodel", omschrijving: "Exacte wetenschappen - Deeltjesmodel", volgorde: 22, categorie: "standaard" },
  { id: "1A-onderzoek-d24", cursusId: "1A-onderzoek", groep: "Exacte wetenschappen - Krachten, energie, stralingen", omschrijving: "Exacte wetenschappen - Krachten, energie, stralingen", volgorde: 23, categorie: "standaard" },
  { id: "1A-onderzoek-d25", cursusId: "1A-onderzoek", groep: "Exacte wetenschappen - Opbouw en functioneren van organismen", omschrijving: "Exacte wetenschappen - Opbouw en functioneren van organismen", volgorde: 24, categorie: "standaard" },
  { id: "1A-onderzoek-d26", cursusId: "1A-onderzoek", groep: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", omschrijving: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", volgorde: 25, categorie: "standaard" },
  { id: "1A-onderzoek-d27", cursusId: "1A-onderzoek", groep: "Exacte wetenschappen - Biotopen", omschrijving: "Exacte wetenschappen - Biotopen", volgorde: 26, categorie: "standaard" },
  { id: "1A-onderzoek-d28", cursusId: "1A-onderzoek", groep: "Techniek/technologie - Eigenschappen van materialen", omschrijving: "Techniek/technologie - Eigenschappen van materialen", volgorde: 27, categorie: "standaard" },
  { id: "1A-onderzoek-d29", cursusId: "1A-onderzoek", groep: "Techniek/technologie - Technische processen", omschrijving: "Techniek/technologie - Technische processen", volgorde: 28, categorie: "standaard" },
  { id: "1A-onderzoek-d30", cursusId: "1A-onderzoek", groep: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", omschrijving: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", volgorde: 29, categorie: "standaard" },
  { id: "1A-onderzoek-d31", cursusId: "1A-onderzoek", groep: "Duurzaamheid bij technische systemen", omschrijving: "Duurzaamheid bij technische systemen", volgorde: 30, categorie: "standaard" },
  { id: "1A-onderzoek-d32", cursusId: "1A-onderzoek", groep: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", omschrijving: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", volgorde: 31, categorie: "standaard" },
  { id: "1A-onderzoek-d33", cursusId: "1A-onderzoek", groep: "Economie - Gezinsbudget", omschrijving: "Economie - Gezinsbudget", volgorde: 32, categorie: "standaard" },
  { id: "1A-onderzoek-d34", cursusId: "1A-onderzoek", groep: "Economie - Maatschappelijke thema’s", omschrijving: "Economie - Maatschappelijke thema’s", volgorde: 33, categorie: "standaard" },
  { id: "1A-klaskas-d1", cursusId: "1A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-klaskas-d2", cursusId: "1A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-klaskas-d3", cursusId: "1A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-klaskas-d4", cursusId: "1A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-klaskas-d5", cursusId: "1A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-klaskas-d6", cursusId: "1A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d1", cursusId: "1A-levende-wiskunde", groep: "Levende Wiskunde activiteit", omschrijving: "Levende Wiskunde activiteit 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d2", cursusId: "1A-levende-wiskunde", groep: "Levende Wiskunde activiteit", omschrijving: "Levende Wiskunde activiteit 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d3", cursusId: "1A-levende-wiskunde", groep: "Levende Wiskunde activiteit", omschrijving: "Levende Wiskunde activiteit 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d4", cursusId: "1A-levende-wiskunde", groep: "Levende Wiskunde activiteit", omschrijving: "Levende Wiskunde activiteit 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d5", cursusId: "1A-levende-wiskunde", groep: "Levende Wiskunde activiteit", omschrijving: "Levende Wiskunde activiteit 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d6", cursusId: "1A-levende-wiskunde", groep: "Levende Wiskunde activiteit", omschrijving: "Levende Wiskunde activiteit 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d7", cursusId: "1A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 1", volgorde: 6, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d8", cursusId: "1A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 2", volgorde: 7, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d9", cursusId: "1A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 3", volgorde: 8, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d10", cursusId: "1A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 4", volgorde: 9, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d11", cursusId: "1A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 5", volgorde: 10, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d12", cursusId: "1A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 6", volgorde: 11, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d13", cursusId: "1A-levende-wiskunde", groep: "Getallenleer - Schatten en benaderen (graadsbadge)", omschrijving: "Getallenleer - Schatten en benaderen (graadsbadge)", volgorde: 12, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d14", cursusId: "1A-levende-wiskunde", groep: "Getallenleer - Ordenen van getallen (graadsbadge)", omschrijving: "Getallenleer - Ordenen van getallen (graadsbadge)", volgorde: 13, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d15", cursusId: "1A-levende-wiskunde", groep: "Getallenleer - Bewerkingen en rekenregels (graadsbadge)", omschrijving: "Getallenleer - Bewerkingen en rekenregels (graadsbadge)", volgorde: 14, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d16", cursusId: "1A-levende-wiskunde", groep: "Getallenleer - Rekenen met machten (graadsbadge)", omschrijving: "Getallenleer - Rekenen met machten (graadsbadge)", volgorde: 15, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d17", cursusId: "1A-levende-wiskunde", groep: "Meetkunde - Vlakke meetkunde (graadsbadge)", omschrijving: "Meetkunde - Vlakke meetkunde (graadsbadge)", volgorde: 16, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d18", cursusId: "1A-levende-wiskunde", groep: "Meetkunde - Ruimtemeetkunde (graadsbadge)", omschrijving: "Meetkunde - Ruimtemeetkunde (graadsbadge)", volgorde: 17, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d19", cursusId: "1A-levende-wiskunde", groep: "Meetkunde - Transformaties (graadsbadge)", omschrijving: "Meetkunde - Transformaties (graadsbadge)", volgorde: 18, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d20", cursusId: "1A-levende-wiskunde", groep: "Meetkunde - Coördinaten (graadsbadge)", omschrijving: "Meetkunde - Coördinaten (graadsbadge)", volgorde: 19, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d21", cursusId: "1A-levende-wiskunde", groep: "Algebra en analyse - Rekenen met lettervormen (graadsbadge)", omschrijving: "Algebra en analyse - Rekenen met lettervormen (graadsbadge)", volgorde: 20, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d22", cursusId: "1A-levende-wiskunde", groep: "Algebra en analyse - Letters als onbekenden (graadsbadge)", omschrijving: "Algebra en analyse - Letters als onbekenden (graadsbadge)", volgorde: 21, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d23", cursusId: "1A-levende-wiskunde", groep: "Algebra en analyse - Verbanden en evenredigheid (graadsbadge)", omschrijving: "Algebra en analyse - Verbanden en evenredigheid (graadsbadge)", volgorde: 22, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d24", cursusId: "1A-levende-wiskunde", groep: "Algebra en analyse - Vergelijkingen (graadsbadge)", omschrijving: "Algebra en analyse - Vergelijkingen (graadsbadge)", volgorde: 23, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d25", cursusId: "1A-levende-wiskunde", groep: "Statistiek (graadsbadge)", omschrijving: "Statistiek (graadsbadge)", volgorde: 24, categorie: "standaard" },
  { id: "1A-levende-wiskunde-d26", cursusId: "1A-levende-wiskunde", groep: "Verzamelingenleer (graadsbadge)", omschrijving: "Verzamelingenleer (graadsbadge)", volgorde: 25, categorie: "standaard" },
  { id: "1A-cultuur-d1", cursusId: "1A-cultuur", groep: "Kunstbeschouwing - Kunst in de prehistorie", omschrijving: "Kunstbeschouwing - Kunst in de prehistorie", volgorde: 0, categorie: "standaard" },
  { id: "1A-cultuur-d2", cursusId: "1A-cultuur", groep: "Kunstbeschouwing - Kunst in het Oude Nabije Oosten", omschrijving: "Kunstbeschouwing - Kunst in het Oude Nabije Oosten", volgorde: 1, categorie: "standaard" },
  { id: "1A-cultuur-d3", cursusId: "1A-cultuur", groep: "Kunstbeschouwing - Kunst in de Klassieke Oudheid", omschrijving: "Kunstbeschouwing - Kunst in de Klassieke Oudheid", volgorde: 2, categorie: "standaard" },
  { id: "1A-cultuur-d4", cursusId: "1A-cultuur", groep: "Kunstbeschouwing - Niet-Westerse kunst", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 1", volgorde: 3, categorie: "standaard" },
  { id: "1A-cultuur-d5", cursusId: "1A-cultuur", groep: "Kunstbeschouwing - Niet-Westerse kunst", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 2", volgorde: 4, categorie: "standaard" },
  { id: "1A-cultuur-d6", cursusId: "1A-cultuur", groep: "Kunstbeschouwing - Onderwerp naar keuze", omschrijving: "Kunstbeschouwing - Onderwerp naar keuze", volgorde: 5, categorie: "standaard" },
  { id: "1A-cultuur-d7", cursusId: "1A-cultuur", groep: "Vrije expressie - toegepaste kunsten", omschrijving: "Vrije expressie - toegepaste kunsten", volgorde: 6, categorie: "standaard" },
  { id: "1A-cultuur-d8", cursusId: "1A-cultuur", groep: "Vrije expressie - beeldende kunsten", omschrijving: "Vrije expressie - beeldende kunsten", volgorde: 7, categorie: "standaard" },
  { id: "1A-cultuur-d9", cursusId: "1A-cultuur", groep: "Vrije expressie - podiumkunsten", omschrijving: "Vrije expressie - podiumkunsten", volgorde: 8, categorie: "standaard" },
  { id: "1A-cultuur-d10", cursusId: "1A-cultuur", groep: "Vrije expressie - muziek", omschrijving: "Vrije expressie - muziek", volgorde: 9, categorie: "standaard" },
  { id: "1A-cultuur-d11", cursusId: "1A-cultuur", groep: "Vrije expressie - media en audiovisueel", omschrijving: "Vrije expressie - media en audiovisueel", volgorde: 10, categorie: "standaard" },
  { id: "1A-cultuur-d12", cursusId: "1A-cultuur", groep: "Vrije expressie - interdisciplinair of hybride", omschrijving: "Vrije expressie - interdisciplinair of hybride", volgorde: 11, categorie: "standaard" },
  { id: "1A-cultuur-d13", cursusId: "1A-cultuur", groep: "Vrije expressie - literair", omschrijving: "Vrije expressie - literair", volgorde: 12, categorie: "standaard" },
  { id: "1A-exploratie-d1", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-exploratie-d2", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-exploratie-d3", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-exploratie-d4", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-exploratie-d5", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-exploratie-d6", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-exploratie-d7", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-exploratie-d8", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-exploratie-d9", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 9", volgorde: 8, categorie: "standaard" },
  { id: "1A-exploratie-d10", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 10", volgorde: 9, categorie: "standaard" },
  { id: "1A-exploratie-d11", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 11", volgorde: 10, categorie: "standaard" },
  { id: "1A-exploratie-d12", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 12", volgorde: 11, categorie: "standaard" },
  { id: "1A-exploratie-d13", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 13", volgorde: 12, categorie: "standaard" },
  { id: "1A-exploratie-d14", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 14", volgorde: 13, categorie: "standaard" },
  { id: "1A-exploratie-d15", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 15", volgorde: 14, categorie: "standaard" },
  { id: "1A-exploratie-d16", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 16", volgorde: 15, categorie: "standaard" },
  { id: "1A-exploratie-d17", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 17", volgorde: 16, categorie: "standaard" },
  { id: "1A-exploratie-d18", cursusId: "1A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 18", volgorde: 17, categorie: "standaard" },
  { id: "1A-exploratie-d19", cursusId: "1A-exploratie", groep: "Klasreis", omschrijving: "Klasreis 1", volgorde: 18, categorie: "standaard" },
  { id: "1A-exploratie-d20", cursusId: "1A-exploratie", groep: "Klasreis", omschrijving: "Klasreis 2", volgorde: 19, categorie: "standaard" },
  { id: "1A-toonmoment-d1", cursusId: "1A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-toonmoment-d2", cursusId: "1A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-toonmoment-d3", cursusId: "1A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-toonmoment-d4", cursusId: "1A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-toonmoment-d5", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 1", volgorde: 4, categorie: "standaard" },
  { id: "1A-toonmoment-d6", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 2", volgorde: 5, categorie: "standaard" },
  { id: "1A-toonmoment-d7", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 3", volgorde: 6, categorie: "standaard" },
  { id: "1A-toonmoment-d8", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 4", volgorde: 7, categorie: "standaard" },
  { id: "1A-toonmoment-d9", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 5", volgorde: 8, categorie: "standaard" },
  { id: "1A-toonmoment-d10", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 6", volgorde: 9, categorie: "standaard" },
  { id: "1A-toonmoment-d11", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 7", volgorde: 10, categorie: "standaard" },
  { id: "1A-toonmoment-d12", cursusId: "1A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 8", volgorde: 11, categorie: "standaard" },
  { id: "1A-toonmoment-d13", cursusId: "1A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 1", volgorde: 12, categorie: "standaard" },
  { id: "1A-toonmoment-d14", cursusId: "1A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 2", volgorde: 13, categorie: "standaard" },
  { id: "1A-toonmoment-d15", cursusId: "1A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 3", volgorde: 14, categorie: "standaard" },
  { id: "1A-toonmoment-d16", cursusId: "1A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 4", volgorde: 15, categorie: "standaard" },
  { id: "1A-toonmoment-d17", cursusId: "1A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 5", volgorde: 16, categorie: "standaard" },
  { id: "1A-toonmoment-d18", cursusId: "1A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 6", volgorde: 17, categorie: "standaard" },
  { id: "1A-welzijn-d1", cursusId: "1A-welzijn", groep: "Gezondheid", omschrijving: "Gezondheid 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-welzijn-d2", cursusId: "1A-welzijn", groep: "Gezondheid", omschrijving: "Gezondheid 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-welzijn-d3", cursusId: "1A-welzijn", groep: "Gezondheid", omschrijving: "Gezondheid 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-welzijn-d4", cursusId: "1A-welzijn", groep: "Gezondheid - EHBO", omschrijving: "Gezondheid - EHBO", volgorde: 3, categorie: "standaard" },
  { id: "1A-welzijn-d5", cursusId: "1A-welzijn", groep: "Mentale gezondheid", omschrijving: "Mentale gezondheid 1", volgorde: 4, categorie: "standaard" },
  { id: "1A-welzijn-d6", cursusId: "1A-welzijn", groep: "Mentale gezondheid", omschrijving: "Mentale gezondheid 2", volgorde: 5, categorie: "standaard" },
  { id: "1A-welzijn-d7", cursusId: "1A-welzijn", groep: "Gezonde levensstijl", omschrijving: "Gezonde levensstijl 1", volgorde: 6, categorie: "standaard" },
  { id: "1A-welzijn-d8", cursusId: "1A-welzijn", groep: "Gezonde levensstijl", omschrijving: "Gezonde levensstijl 2", volgorde: 7, categorie: "standaard" },
  { id: "1A-welzijn-d9", cursusId: "1A-welzijn", groep: "Gezonde levensstijl", omschrijving: "Gezonde levensstijl 3", volgorde: 8, categorie: "standaard" },
  { id: "1A-welzijn-d10", cursusId: "1A-welzijn", groep: "Gezonde levensstijl", omschrijving: "Gezonde levensstijl 4", volgorde: 9, categorie: "standaard" },
  { id: "1A-welzijn-d11", cursusId: "1A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 1", volgorde: 10, categorie: "standaard" },
  { id: "1A-welzijn-d12", cursusId: "1A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 2", volgorde: 11, categorie: "standaard" },
  { id: "1A-welzijn-d13", cursusId: "1A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 3", volgorde: 12, categorie: "standaard" },
  { id: "1A-welzijn-d14", cursusId: "1A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 4", volgorde: 13, categorie: "standaard" },
  { id: "1A-welzijn-d15", cursusId: "1A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 1", volgorde: 14, categorie: "standaard" },
  { id: "1A-welzijn-d16", cursusId: "1A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 2", volgorde: 15, categorie: "standaard" },
  { id: "1A-welzijn-d17", cursusId: "1A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 3", volgorde: 16, categorie: "standaard" },
  { id: "1A-welzijn-d18", cursusId: "1A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 4", volgorde: 17, categorie: "standaard" },
  { id: "1A-welzijn-d19", cursusId: "1A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 1", volgorde: 18, categorie: "standaard" },
  { id: "1A-welzijn-d20", cursusId: "1A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 2", volgorde: 19, categorie: "standaard" },
  { id: "1A-welzijn-d21", cursusId: "1A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 3", volgorde: 20, categorie: "standaard" },
  { id: "1A-welzijn-d22", cursusId: "1A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 4", volgorde: 21, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d1", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 1", volgorde: 0, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d2", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 2", volgorde: 1, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d3", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 3", volgorde: 2, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d4", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 4", volgorde: 3, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d5", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 5", volgorde: 4, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d6", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 6", volgorde: 5, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d7", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 7", volgorde: 6, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d8", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 8", volgorde: 7, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d9", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 9", volgorde: 8, categorie: "standaard" },
  { id: "1A-vrij-initiatief-buiten-de-lijntjes-d10", cursusId: "1A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 10", volgorde: 9, categorie: "standaard" },
];
