// AUTO-GEGENEREERD via scripts/extract_badges.py
// uit docs/reference/deelevaluaties_alle-graden-2.xlsx — niet met de hand aanpassen.
import type { Cursus, Leerdoel, Rubric } from "./types";

export const cursussen3A: Cursus[] = [
  { id: "3A-c1", stroom: "3A", naam: "Planning en reflectie" },
  { id: "3A-c2", stroom: "3A", naam: "Geïntegreerde opdrachten (GOP)" },
  { id: "3A-c3", stroom: "3A", naam: "Trajecten" },
  { id: "3A-c4", stroom: "3A", naam: "Klaswerking+" },
  { id: "3A-c5", stroom: "3A", naam: "Burgerschapsreis" },
  { id: "3A-c6", stroom: "3A", naam: "De brug naar je (leer)toekomst" },
  { id: "3A-c7", stroom: "3A", naam: "Vrij initiatief buiten de lijntjes" },
];

export const rubrics3A: Rubric[] = [
  { id: "3A-c1-r1", cursusId: "3A-c1", naam: "Planning en reflectie" },
  { id: "3A-c2-r1", cursusId: "3A-c2", naam: "Geïntegreerde opdrachten (GOP)" },
  { id: "3A-c3-r1", cursusId: "3A-c3", naam: "Trajecten" },
  { id: "3A-c4-r1", cursusId: "3A-c4", naam: "Klaswerking+" },
  { id: "3A-c5-r1", cursusId: "3A-c5", naam: "Burgerschapsreis" },
  { id: "3A-c6-r1", cursusId: "3A-c6", naam: "De brug naar je (leer)toekomst" },
  { id: "3A-c7-r1", cursusId: "3A-c7", naam: "Vrij initiatief buiten de lijntjes" },
];

export const leerdoelen3A: Leerdoel[] = [
  { id: "3A-c1-r1-d1", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 1", categorie: "standaard" },
  { id: "3A-c1-r1-d2", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 2", categorie: "standaard" },
  { id: "3A-c1-r1-d3", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 3", categorie: "standaard" },
  { id: "3A-c1-r1-d4", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 4", categorie: "standaard" },
  { id: "3A-c1-r1-d5", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 5", categorie: "standaard" },
  { id: "3A-c1-r1-d6", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 6", categorie: "standaard" },
  { id: "3A-c1-r1-d7", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 7", categorie: "standaard" },
  { id: "3A-c1-r1-d8", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 8", categorie: "standaard" },
  { id: "3A-c1-r1-d9", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 9", categorie: "standaard" },
  { id: "3A-c1-r1-d10", rubricId: "3A-c1-r1", omschrijving: "Coachinggesprek 10", categorie: "standaard" },
  { id: "3A-c2-r1-d1", rubricId: "3A-c2-r1", omschrijving: "GOP - Bruin", categorie: "standaard" },
  { id: "3A-c2-r1-d2", rubricId: "3A-c2-r1", omschrijving: "GOP - Rose", categorie: "standaard" },
  { id: "3A-c2-r1-d3", rubricId: "3A-c2-r1", omschrijving: "GOP - Zwart", categorie: "standaard" },
  { id: "3A-c2-r1-d4", rubricId: "3A-c2-r1", omschrijving: "GOP - Grijs", categorie: "standaard" },
  { id: "3A-c2-r1-d5", rubricId: "3A-c2-r1", omschrijving: "GOP - Wit", categorie: "standaard" },
  { id: "3A-c2-r1-d6", rubricId: "3A-c2-r1", omschrijving: "GOP - Kaki", categorie: "standaard" },
  { id: "3A-c2-r1-d7", rubricId: "3A-c2-r1", omschrijving: "GOP - Lila", categorie: "standaard" },
  { id: "3A-c2-r1-d8", rubricId: "3A-c2-r1", omschrijving: "GOP - Paars", categorie: "standaard" },
  { id: "3A-c2-r1-d9", rubricId: "3A-c2-r1", omschrijving: "GOP - Extra", categorie: "standaard" },
  { id: "3A-c3-r1-d1", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 1", categorie: "standaard" },
  { id: "3A-c3-r1-d2", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 2", categorie: "standaard" },
  { id: "3A-c3-r1-d3", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 3", categorie: "standaard" },
  { id: "3A-c3-r1-d4", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 4", categorie: "standaard" },
  { id: "3A-c3-r1-d5", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 5", categorie: "standaard" },
  { id: "3A-c3-r1-d6", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 6", categorie: "standaard" },
  { id: "3A-c3-r1-d7", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 7", categorie: "standaard" },
  { id: "3A-c3-r1-d8", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 8", categorie: "standaard" },
  { id: "3A-c3-r1-d9", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 9", categorie: "standaard" },
  { id: "3A-c3-r1-d10", rubricId: "3A-c3-r1", omschrijving: "Traject wiskunde en wetenschappen 10", categorie: "standaard" },
  { id: "3A-c4-r1-d1", rubricId: "3A-c4-r1", omschrijving: "Deelname kring & klasraad (jaarbadge) 1", categorie: "standaard" },
  { id: "3A-c4-r1-d2", rubricId: "3A-c4-r1", omschrijving: "Deelname kring & klasraad (jaarbadge) 2", categorie: "standaard" },
  { id: "3A-c4-r1-d3", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 1", categorie: "standaard" },
  { id: "3A-c4-r1-d4", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 2", categorie: "standaard" },
  { id: "3A-c4-r1-d5", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 3", categorie: "standaard" },
  { id: "3A-c4-r1-d6", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 4", categorie: "standaard" },
  { id: "3A-c4-r1-d7", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 5", categorie: "standaard" },
  { id: "3A-c4-r1-d8", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 6", categorie: "standaard" },
  { id: "3A-c4-r1-d9", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 7", categorie: "standaard" },
  { id: "3A-c4-r1-d10", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 8", categorie: "standaard" },
  { id: "3A-c4-r1-d11", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 9", categorie: "standaard" },
  { id: "3A-c4-r1-d12", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 10", categorie: "standaard" },
  { id: "3A-c4-r1-d13", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 11", categorie: "standaard" },
  { id: "3A-c4-r1-d14", rubricId: "3A-c4-r1", omschrijving: "Taken klaswerking (Units) 12", categorie: "standaard" },
  { id: "3A-c5-r1-d1", rubricId: "3A-c5-r1", omschrijving: "Communicatie - Deelname aan voorstellingsdag", categorie: "standaard" },
  { id: "3A-c5-r1-d2", rubricId: "3A-c5-r1", omschrijving: "Vrije tekst - motivatiebrief (Engels of Frans)", categorie: "standaard" },
  { id: "3A-c5-r1-d3", rubricId: "3A-c5-r1", omschrijving: "Exploratie - Deelname aan de selectietweedaagse", categorie: "standaard" },
  { id: "3A-c5-r1-d4", rubricId: "3A-c5-r1", omschrijving: "Klasraad en klaskas - Deelname aan de fondsenwerving", categorie: "standaard" },
  { id: "3A-c5-r1-d5", rubricId: "3A-c5-r1", omschrijving: "Klasraad en klaskas - Inzicht in het budget van de reis", categorie: "standaard" },
  { id: "3A-c5-r1-d6", rubricId: "3A-c5-r1", omschrijving: "GOP met taken die horen bij je reis", categorie: "standaard" },
  { id: "3A-c5-r1-d7", rubricId: "3A-c5-r1", omschrijving: "Exploratie - Deelname aan de reis", categorie: "standaard" },
  { id: "3A-c5-r1-d8", rubricId: "3A-c5-r1", omschrijving: "Burgerschap intern - Inzet voor de groep tijdens de reis", categorie: "standaard" },
  { id: "3A-c5-r1-d9", rubricId: "3A-c5-r1", omschrijving: "Burgerschap extern - Inzet voor de projecten tijdens de reis", categorie: "standaard" },
  { id: "3A-c5-r1-d10", rubricId: "3A-c5-r1", omschrijving: "Cultuur - Verwerking via artistieke creaties", categorie: "standaard" },
  { id: "3A-c5-r1-d11", rubricId: "3A-c5-r1", omschrijving: "Toonmoment - Deelname aan Toonmoment", categorie: "standaard" },
  { id: "3A-c6-r1-d1", rubricId: "3A-c6-r1", omschrijving: "30 dagdelen persoonlijke brug", categorie: "standaard" },
  { id: "3A-c6-r1-d2", rubricId: "3A-c6-r1", omschrijving: "Ervaringsweek - uitvoering (minimaal 8 dagdelen) 1", categorie: "standaard" },
  { id: "3A-c6-r1-d3", rubricId: "3A-c6-r1", omschrijving: "Ervaringsweek - uitvoering (minimaal 8 dagdelen) 2", categorie: "standaard" },
  { id: "3A-c6-r1-d4", rubricId: "3A-c6-r1", omschrijving: "Ervaringsweek - verslag 1", categorie: "standaard" },
  { id: "3A-c6-r1-d5", rubricId: "3A-c6-r1", omschrijving: "Ervaringsweek - verslag 2", categorie: "standaard" },
  { id: "3A-c6-r1-d6", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Goedgekeurd thema", categorie: "standaard" },
  { id: "3A-c6-r1-d7", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Boekenronde 1", categorie: "standaard" },
  { id: "3A-c6-r1-d8", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Boekenronde 2", categorie: "standaard" },
  { id: "3A-c6-r1-d9", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Boekenronde 3", categorie: "standaard" },
  { id: "3A-c6-r1-d10", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Actuaronde 1", categorie: "standaard" },
  { id: "3A-c6-r1-d11", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Actuaronde 2", categorie: "standaard" },
  { id: "3A-c6-r1-d12", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Actuaronde 3", categorie: "standaard" },
  { id: "3A-c6-r1-d13", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Paper", categorie: "standaard" },
  { id: "3A-c6-r1-d14", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Concrete voorstelling", categorie: "standaard" },
  { id: "3A-c6-r1-d15", rubricId: "3A-c6-r1", omschrijving: "Eigen onderzoek - Actuaronde", categorie: "standaard" },
  { id: "3A-c6-r1-d16", rubricId: "3A-c6-r1", omschrijving: "Concrete voorstelling", categorie: "standaard" },
  { id: "3A-c6-r1-d17", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 1", categorie: "standaard" },
  { id: "3A-c6-r1-d18", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 2", categorie: "standaard" },
  { id: "3A-c6-r1-d19", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 3", categorie: "standaard" },
  { id: "3A-c6-r1-d20", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 4", categorie: "standaard" },
  { id: "3A-c6-r1-d21", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 5", categorie: "standaard" },
  { id: "3A-c6-r1-d22", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 6", categorie: "standaard" },
  { id: "3A-c6-r1-d23", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 7", categorie: "standaard" },
  { id: "3A-c6-r1-d24", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 8", categorie: "standaard" },
  { id: "3A-c6-r1-d25", rubricId: "3A-c6-r1", omschrijving: "Lesactiviteit 9", categorie: "standaard" },
  { id: "3A-c6-r1-d26", rubricId: "3A-c6-r1", omschrijving: "Persoonlijke vragenlijst", categorie: "standaard" },
  { id: "3A-c6-r1-d27", rubricId: "3A-c6-r1", omschrijving: "Mondelinge proef & portfolio", categorie: "standaard" },
  { id: "3A-c6-r1-d28", rubricId: "3A-c6-r1", omschrijving: "Extra", categorie: "standaard" },
  { id: "3A-c7-r1-d1", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 1", categorie: "standaard" },
  { id: "3A-c7-r1-d2", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 2", categorie: "standaard" },
  { id: "3A-c7-r1-d3", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 3", categorie: "standaard" },
  { id: "3A-c7-r1-d4", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 4", categorie: "standaard" },
  { id: "3A-c7-r1-d5", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 5", categorie: "standaard" },
  { id: "3A-c7-r1-d6", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 6", categorie: "standaard" },
  { id: "3A-c7-r1-d7", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 7", categorie: "standaard" },
  { id: "3A-c7-r1-d8", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 8", categorie: "standaard" },
  { id: "3A-c7-r1-d9", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 9", categorie: "standaard" },
  { id: "3A-c7-r1-d10", rubricId: "3A-c7-r1", omschrijving: "Vrij initiatief buiten de lijntjes 10", categorie: "standaard" },
];
