// AUTO-GEGENEREERD via scripts/extract_badges.py
// uit docs/reference/deelevaluaties_alle-graden-2.xlsx — niet met de hand aanpassen.
import type { Cursus, Leerdoel, Rubric } from "./types";

export const cursussen2A: Cursus[] = [
  { id: "2A-c1", stroom: "2A", naam: "Planning en reflectie" },
  { id: "2A-c2", stroom: "2A", naam: "Klasraad" },
  { id: "2A-c3", stroom: "2A", naam: "Burgerschap" },
  { id: "2A-c4", stroom: "2A", naam: "Focusateliers & vrije ateliers" },
  { id: "2A-c5", stroom: "2A", naam: "Kring" },
  { id: "2A-c6", stroom: "2A", naam: "Actuaronde" },
  { id: "2A-c7", stroom: "2A", naam: "Vrije Tekst" },
  { id: "2A-c8", stroom: "2A", naam: "Boekenronde" },
  { id: "2A-c9", stroom: "2A", naam: "Communicatie" },
  { id: "2A-c10", stroom: "2A", naam: "Onderzoek" },
  { id: "2A-c11", stroom: "2A", naam: "Klaskas" },
  { id: "2A-c12", stroom: "2A", naam: "Levende Wiskunde" },
  { id: "2A-c13", stroom: "2A", naam: "Cultuur" },
  { id: "2A-c14", stroom: "2A", naam: "Exploratie" },
  { id: "2A-c15", stroom: "2A", naam: "Toonmoment" },
  { id: "2A-c16", stroom: "2A", naam: "Welzijn" },
  { id: "2A-c17", stroom: "2A", naam: "Ervaringsweek" },
  { id: "2A-c18", stroom: "2A", naam: "Vrij initiatief buiten de lijntjes" },
];

export const rubrics2A: Rubric[] = [
  { id: "2A-c1-r1", cursusId: "2A-c1", naam: "Planning en reflectie" },
  { id: "2A-c2-r1", cursusId: "2A-c2", naam: "Klasraad" },
  { id: "2A-c3-r1", cursusId: "2A-c3", naam: "Burgerschap" },
  { id: "2A-c4-r1", cursusId: "2A-c4", naam: "Focusateliers & vrije ateliers" },
  { id: "2A-c5-r1", cursusId: "2A-c5", naam: "Kring" },
  { id: "2A-c6-r1", cursusId: "2A-c6", naam: "Actuaronde" },
  { id: "2A-c7-r1", cursusId: "2A-c7", naam: "Vrije Tekst" },
  { id: "2A-c8-r1", cursusId: "2A-c8", naam: "Boekenronde" },
  { id: "2A-c9-r1", cursusId: "2A-c9", naam: "Communicatie" },
  { id: "2A-c10-r1", cursusId: "2A-c10", naam: "Onderzoek" },
  { id: "2A-c11-r1", cursusId: "2A-c11", naam: "Klaskas" },
  { id: "2A-c12-r1", cursusId: "2A-c12", naam: "Levende Wiskunde" },
  { id: "2A-c13-r1", cursusId: "2A-c13", naam: "Cultuur" },
  { id: "2A-c14-r1", cursusId: "2A-c14", naam: "Exploratie" },
  { id: "2A-c15-r1", cursusId: "2A-c15", naam: "Toonmoment" },
  { id: "2A-c16-r1", cursusId: "2A-c16", naam: "Welzijn" },
  { id: "2A-c17-r1", cursusId: "2A-c17", naam: "Ervaringsweek" },
  { id: "2A-c18-r1", cursusId: "2A-c18", naam: "Vrij initiatief buiten de lijntjes" },
];

export const leerdoelen2A: Leerdoel[] = [
  { id: "2A-c1-r1-d1", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 1", categorie: "standaard" },
  { id: "2A-c1-r1-d2", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 2", categorie: "standaard" },
  { id: "2A-c1-r1-d3", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 3", categorie: "standaard" },
  { id: "2A-c1-r1-d4", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 4", categorie: "standaard" },
  { id: "2A-c1-r1-d5", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 5", categorie: "standaard" },
  { id: "2A-c1-r1-d6", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 6", categorie: "standaard" },
  { id: "2A-c1-r1-d7", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 7", categorie: "standaard" },
  { id: "2A-c1-r1-d8", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 8", categorie: "standaard" },
  { id: "2A-c1-r1-d9", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 9", categorie: "standaard" },
  { id: "2A-c1-r1-d10", rubricId: "2A-c1-r1", omschrijving: "Coachinggesprek 10", categorie: "standaard" },
  { id: "2A-c2-r1-d1", rubricId: "2A-c2-r1", omschrijving: "Voorzitter 1", categorie: "standaard" },
  { id: "2A-c2-r1-d2", rubricId: "2A-c2-r1", omschrijving: "Voorzitter 2", categorie: "standaard" },
  { id: "2A-c2-r1-d3", rubricId: "2A-c2-r1", omschrijving: "Voorzitter 3", categorie: "standaard" },
  { id: "2A-c2-r1-d4", rubricId: "2A-c2-r1", omschrijving: "Voorzitter 4", categorie: "standaard" },
  { id: "2A-c2-r1-d5", rubricId: "2A-c2-r1", omschrijving: "Voorzitter 5", categorie: "standaard" },
  { id: "2A-c2-r1-d6", rubricId: "2A-c2-r1", omschrijving: "Secretaris 1", categorie: "standaard" },
  { id: "2A-c2-r1-d7", rubricId: "2A-c2-r1", omschrijving: "Secretaris 2", categorie: "standaard" },
  { id: "2A-c2-r1-d8", rubricId: "2A-c2-r1", omschrijving: "Secretaris 3", categorie: "standaard" },
  { id: "2A-c2-r1-d9", rubricId: "2A-c2-r1", omschrijving: "Secretaris 4", categorie: "standaard" },
  { id: "2A-c2-r1-d10", rubricId: "2A-c2-r1", omschrijving: "Secretaris 5", categorie: "standaard" },
  { id: "2A-c2-r1-d11", rubricId: "2A-c2-r1", omschrijving: "Deelnemer (wekelijks) 1", categorie: "standaard" },
  { id: "2A-c2-r1-d12", rubricId: "2A-c2-r1", omschrijving: "Deelnemer (wekelijks) 2", categorie: "standaard" },
  { id: "2A-c2-r1-d13", rubricId: "2A-c2-r1", omschrijving: "Deelnemer (wekelijks) 3", categorie: "standaard" },
  { id: "2A-c2-r1-d14", rubricId: "2A-c2-r1", omschrijving: "Deelnemer (wekelijks) 4", categorie: "standaard" },
  { id: "2A-c2-r1-d15", rubricId: "2A-c2-r1", omschrijving: "Deelnemer (wekelijks) 5", categorie: "standaard" },
  { id: "2A-c2-r1-d16", rubricId: "2A-c2-r1", omschrijving: "Vestigingsraad/Keerpuntraad/Leerlingenraad", categorie: "standaard" },
  { id: "2A-c3-r1-d1", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 1", categorie: "standaard" },
  { id: "2A-c3-r1-d2", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 2", categorie: "standaard" },
  { id: "2A-c3-r1-d3", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 3", categorie: "standaard" },
  { id: "2A-c3-r1-d4", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 4", categorie: "standaard" },
  { id: "2A-c3-r1-d5", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 5", categorie: "standaard" },
  { id: "2A-c3-r1-d6", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 6", categorie: "standaard" },
  { id: "2A-c3-r1-d7", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 7", categorie: "standaard" },
  { id: "2A-c3-r1-d8", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 8", categorie: "standaard" },
  { id: "2A-c3-r1-d9", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 9", categorie: "standaard" },
  { id: "2A-c3-r1-d10", rubricId: "2A-c3-r1", omschrijving: "Intern burgerschap 10", categorie: "standaard" },
  { id: "2A-c3-r1-d11", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 1", categorie: "standaard" },
  { id: "2A-c3-r1-d12", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 2", categorie: "standaard" },
  { id: "2A-c3-r1-d13", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 3", categorie: "standaard" },
  { id: "2A-c3-r1-d14", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 4", categorie: "standaard" },
  { id: "2A-c3-r1-d15", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 5", categorie: "standaard" },
  { id: "2A-c3-r1-d16", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 6", categorie: "standaard" },
  { id: "2A-c3-r1-d17", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 7", categorie: "standaard" },
  { id: "2A-c3-r1-d18", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 8", categorie: "standaard" },
  { id: "2A-c3-r1-d19", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 9", categorie: "standaard" },
  { id: "2A-c3-r1-d20", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 10", categorie: "standaard" },
  { id: "2A-c3-r1-d21", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 11", categorie: "standaard" },
  { id: "2A-c3-r1-d22", rubricId: "2A-c3-r1", omschrijving: "Extern burgerschap (per 2 lestijden) 12", categorie: "standaard" },
  { id: "2A-c3-r1-d23", rubricId: "2A-c3-r1", omschrijving: "Werkstuk mensenrechten", categorie: "standaard" },
  { id: "2A-c3-r1-d24", rubricId: "2A-c3-r1", omschrijving: "Bezoek democratisch orgaan 1", categorie: "standaard" },
  { id: "2A-c3-r1-d25", rubricId: "2A-c3-r1", omschrijving: "Bezoek democratisch orgaan 2", categorie: "standaard" },
  { id: "2A-c4-r1-d1", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 1", categorie: "standaard" },
  { id: "2A-c4-r1-d2", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 2", categorie: "standaard" },
  { id: "2A-c4-r1-d3", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 3", categorie: "standaard" },
  { id: "2A-c4-r1-d4", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 4", categorie: "standaard" },
  { id: "2A-c4-r1-d5", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 5", categorie: "standaard" },
  { id: "2A-c4-r1-d6", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 6", categorie: "standaard" },
  { id: "2A-c4-r1-d7", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 7", categorie: "standaard" },
  { id: "2A-c4-r1-d8", rubricId: "2A-c4-r1", omschrijving: "Deelname focusatelier 8", categorie: "standaard" },
  { id: "2A-c4-r1-d9", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Natuur", categorie: "standaard" },
  { id: "2A-c4-r1-d10", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Handvaardigheid, bouw & techniek", categorie: "standaard" },
  { id: "2A-c4-r1-d11", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Kennis", categorie: "standaard" },
  { id: "2A-c4-r1-d12", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Experimenten, wetenschappelijk onderzoek & innovatie", categorie: "standaard" },
  { id: "2A-c4-r1-d13", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - ICT, digitale & moderne technieken", categorie: "standaard" },
  { id: "2A-c4-r1-d14", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Expressie, creatie & ontwerp", categorie: "standaard" },
  { id: "2A-c4-r1-d15", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Welzijn en andere", categorie: "standaard" },
  { id: "2A-c4-r1-d16", rubricId: "2A-c4-r1", omschrijving: "Vrije ateliers - Nadruk ligt op je focus of is gespreid over de domeinen (graadsbadge)", categorie: "standaard" },
  { id: "2A-c5-r1-d1", rubricId: "2A-c5-r1", omschrijving: "Voorzitter 1", categorie: "standaard" },
  { id: "2A-c5-r1-d2", rubricId: "2A-c5-r1", omschrijving: "Voorzitter 2", categorie: "standaard" },
  { id: "2A-c5-r1-d3", rubricId: "2A-c5-r1", omschrijving: "Voorzitter 3", categorie: "standaard" },
  { id: "2A-c5-r1-d4", rubricId: "2A-c5-r1", omschrijving: "Voorzitter 4", categorie: "standaard" },
  { id: "2A-c5-r1-d5", rubricId: "2A-c5-r1", omschrijving: "Voorzitter 5", categorie: "standaard" },
  { id: "2A-c5-r1-d6", rubricId: "2A-c5-r1", omschrijving: "Secretaris 1", categorie: "standaard" },
  { id: "2A-c5-r1-d7", rubricId: "2A-c5-r1", omschrijving: "Secretaris 2", categorie: "standaard" },
  { id: "2A-c5-r1-d8", rubricId: "2A-c5-r1", omschrijving: "Secretaris 3", categorie: "standaard" },
  { id: "2A-c5-r1-d9", rubricId: "2A-c5-r1", omschrijving: "Secretaris 4", categorie: "standaard" },
  { id: "2A-c5-r1-d10", rubricId: "2A-c5-r1", omschrijving: "Secretaris 5", categorie: "standaard" },
  { id: "2A-c5-r1-d11", rubricId: "2A-c5-r1", omschrijving: "Deelnemer (wekelijks) 1", categorie: "standaard" },
  { id: "2A-c5-r1-d12", rubricId: "2A-c5-r1", omschrijving: "Deelnemer (wekelijks) 2", categorie: "standaard" },
  { id: "2A-c5-r1-d13", rubricId: "2A-c5-r1", omschrijving: "Deelnemer (wekelijks) 3", categorie: "standaard" },
  { id: "2A-c5-r1-d14", rubricId: "2A-c5-r1", omschrijving: "Deelnemer (wekelijks) 4", categorie: "standaard" },
  { id: "2A-c5-r1-d15", rubricId: "2A-c5-r1", omschrijving: "Deelnemer (wekelijks) 5", categorie: "standaard" },
  { id: "2A-c5-r1-d16", rubricId: "2A-c5-r1", omschrijving: "Deelnemer (wekelijks) 6", categorie: "standaard" },
  { id: "2A-c5-r1-d17", rubricId: "2A-c5-r1", omschrijving: "Kring Frans 1", categorie: "standaard" },
  { id: "2A-c5-r1-d18", rubricId: "2A-c5-r1", omschrijving: "Kring Frans 2", categorie: "standaard" },
  { id: "2A-c5-r1-d19", rubricId: "2A-c5-r1", omschrijving: "Kring Frans 3", categorie: "standaard" },
  { id: "2A-c5-r1-d20", rubricId: "2A-c5-r1", omschrijving: "Kring Engels 1", categorie: "standaard" },
  { id: "2A-c5-r1-d21", rubricId: "2A-c5-r1", omschrijving: "Kring Engels 2", categorie: "standaard" },
  { id: "2A-c5-r1-d22", rubricId: "2A-c5-r1", omschrijving: "Kring Engels 3", categorie: "standaard" },
  { id: "2A-c6-r1-d1", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 1", categorie: "standaard" },
  { id: "2A-c6-r1-d2", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 2", categorie: "standaard" },
  { id: "2A-c6-r1-d3", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 3", categorie: "standaard" },
  { id: "2A-c6-r1-d4", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 4", categorie: "standaard" },
  { id: "2A-c6-r1-d5", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 5", categorie: "standaard" },
  { id: "2A-c6-r1-d6", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 6", categorie: "standaard" },
  { id: "2A-c6-r1-d7", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 7", categorie: "standaard" },
  { id: "2A-c6-r1-d8", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 8", categorie: "standaard" },
  { id: "2A-c6-r1-d9", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Nederlands 9", categorie: "standaard" },
  { id: "2A-c6-r1-d10", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Frans 1", categorie: "standaard" },
  { id: "2A-c6-r1-d11", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Frans 2", categorie: "standaard" },
  { id: "2A-c6-r1-d12", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Frans 3", categorie: "standaard" },
  { id: "2A-c6-r1-d13", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Engels 1", categorie: "standaard" },
  { id: "2A-c6-r1-d14", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Engels 2", categorie: "standaard" },
  { id: "2A-c6-r1-d15", rubricId: "2A-c6-r1", omschrijving: "Actuaronde Engels 3", categorie: "standaard" },
  { id: "2A-c7-r1-d1", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 1", categorie: "standaard" },
  { id: "2A-c7-r1-d2", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 2", categorie: "standaard" },
  { id: "2A-c7-r1-d3", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 3", categorie: "standaard" },
  { id: "2A-c7-r1-d4", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 4", categorie: "standaard" },
  { id: "2A-c7-r1-d5", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 5", categorie: "standaard" },
  { id: "2A-c7-r1-d6", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 6", categorie: "standaard" },
  { id: "2A-c7-r1-d7", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 7", categorie: "standaard" },
  { id: "2A-c7-r1-d8", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Nederlands 8", categorie: "standaard" },
  { id: "2A-c7-r1-d9", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Frans 1", categorie: "standaard" },
  { id: "2A-c7-r1-d10", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Frans 2", categorie: "standaard" },
  { id: "2A-c7-r1-d11", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Frans 3", categorie: "standaard" },
  { id: "2A-c7-r1-d12", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Frans 4", categorie: "standaard" },
  { id: "2A-c7-r1-d13", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Frans 5", categorie: "standaard" },
  { id: "2A-c7-r1-d14", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Engels 1", categorie: "standaard" },
  { id: "2A-c7-r1-d15", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Engels 2", categorie: "standaard" },
  { id: "2A-c7-r1-d16", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Engels 3", categorie: "standaard" },
  { id: "2A-c7-r1-d17", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Engels 4", categorie: "standaard" },
  { id: "2A-c7-r1-d18", rubricId: "2A-c7-r1", omschrijving: "Vrije tekst Engels 5", categorie: "standaard" },
  { id: "2A-c8-r1-d1", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 1", categorie: "standaard" },
  { id: "2A-c8-r1-d2", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 2", categorie: "standaard" },
  { id: "2A-c8-r1-d3", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 3", categorie: "standaard" },
  { id: "2A-c8-r1-d4", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 4", categorie: "standaard" },
  { id: "2A-c8-r1-d5", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 5", categorie: "standaard" },
  { id: "2A-c8-r1-d6", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 6", categorie: "standaard" },
  { id: "2A-c8-r1-d7", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 7", categorie: "standaard" },
  { id: "2A-c8-r1-d8", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Nederlands 8", categorie: "standaard" },
  { id: "2A-c8-r1-d9", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Frans 1", categorie: "standaard" },
  { id: "2A-c8-r1-d10", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Frans 2", categorie: "standaard" },
  { id: "2A-c8-r1-d11", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Frans 3", categorie: "standaard" },
  { id: "2A-c8-r1-d12", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Engels 1", categorie: "standaard" },
  { id: "2A-c8-r1-d13", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Engels 2", categorie: "standaard" },
  { id: "2A-c8-r1-d14", rubricId: "2A-c8-r1", omschrijving: "Boekenronde Engels 3", categorie: "standaard" },
  { id: "2A-c9-r1-d1", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Nederlands 1", categorie: "standaard" },
  { id: "2A-c9-r1-d2", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Nederlands 2", categorie: "standaard" },
  { id: "2A-c9-r1-d3", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Nederlands 3", categorie: "standaard" },
  { id: "2A-c9-r1-d4", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Frans 1", categorie: "standaard" },
  { id: "2A-c9-r1-d5", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Frans 2", categorie: "standaard" },
  { id: "2A-c9-r1-d6", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Frans 3", categorie: "standaard" },
  { id: "2A-c9-r1-d7", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Engels 1", categorie: "standaard" },
  { id: "2A-c9-r1-d8", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Engels 2", categorie: "standaard" },
  { id: "2A-c9-r1-d9", rubricId: "2A-c9-r1", omschrijving: "Krant/Correspondentie publicatie Engels 3", categorie: "standaard" },
  { id: "2A-c9-r1-d10", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern 1", categorie: "standaard" },
  { id: "2A-c9-r1-d11", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern 2", categorie: "standaard" },
  { id: "2A-c9-r1-d12", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern 3", categorie: "standaard" },
  { id: "2A-c9-r1-d13", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern 4", categorie: "standaard" },
  { id: "2A-c9-r1-d14", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern Frans 1", categorie: "standaard" },
  { id: "2A-c9-r1-d15", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern Frans 2", categorie: "standaard" },
  { id: "2A-c9-r1-d16", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern Engels 1", categorie: "standaard" },
  { id: "2A-c9-r1-d17", rubricId: "2A-c9-r1", omschrijving: "Activiteit Keerpunt/extern Engels 2", categorie: "standaard" },
  { id: "2A-c10-r1-d1", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 1", categorie: "standaard" },
  { id: "2A-c10-r1-d2", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 2", categorie: "standaard" },
  { id: "2A-c10-r1-d3", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 3", categorie: "standaard" },
  { id: "2A-c10-r1-d4", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 4", categorie: "standaard" },
  { id: "2A-c10-r1-d5", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 5", categorie: "standaard" },
  { id: "2A-c10-r1-d6", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 6", categorie: "standaard" },
  { id: "2A-c10-r1-d7", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 7", categorie: "standaard" },
  { id: "2A-c10-r1-d8", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 8", categorie: "standaard" },
  { id: "2A-c10-r1-d9", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 9", categorie: "standaard" },
  { id: "2A-c10-r1-d10", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 10", categorie: "standaard" },
  { id: "2A-c10-r1-d11", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 11", categorie: "standaard" },
  { id: "2A-c10-r1-d12", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 12", categorie: "standaard" },
  { id: "2A-c10-r1-d13", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 13", categorie: "standaard" },
  { id: "2A-c10-r1-d14", rubricId: "2A-c10-r1", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 14", categorie: "standaard" },
  { id: "2A-c10-r1-d15", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen laboreeksen 1", categorie: "standaard" },
  { id: "2A-c10-r1-d16", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen laboreeksen 2", categorie: "standaard" },
  { id: "2A-c10-r1-d17", rubricId: "2A-c10-r1", omschrijving: "Historisch - Algemene periodisering", categorie: "standaard" },
  { id: "2A-c10-r1-d18", rubricId: "2A-c10-r1", omschrijving: "Historisch - Niet-Westerse periodisering", categorie: "standaard" },
  { id: "2A-c10-r1-d19", rubricId: "2A-c10-r1", omschrijving: "Historisch - Historische beeldvorming", categorie: "standaard" },
  { id: "2A-c10-r1-d20", rubricId: "2A-c10-r1", omschrijving: "Historisch - Evalueren van historische bronnen", categorie: "standaard" },
  { id: "2A-c10-r1-d21", rubricId: "2A-c10-r1", omschrijving: "Historisch - Middeleeuwen: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "2A-c10-r1-d22", rubricId: "2A-c10-r1", omschrijving: "Historisch - Vroegmoderne tijd: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "2A-c10-r1-d23", rubricId: "2A-c10-r1", omschrijving: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", categorie: "standaard" },
  { id: "2A-c10-r1-d24", rubricId: "2A-c10-r1", omschrijving: "Ruimtelijk - Demografische en economische processen & gevolgen", categorie: "standaard" },
  { id: "2A-c10-r1-d25", rubricId: "2A-c10-r1", omschrijving: "Ruimtelijk - Evolutie en verandering", categorie: "standaard" },
  { id: "2A-c10-r1-d26", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen - PSE: atoommodel, chemische formules, stoffen en eigenschappen", categorie: "standaard" },
  { id: "2A-c10-r1-d27", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen - Krachten, energie, stralingen, elektriciteit", categorie: "standaard" },
  { id: "2A-c10-r1-d28", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen - Opbouw en functioneren van organismen", categorie: "standaard" },
  { id: "2A-c10-r1-d29", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", categorie: "standaard" },
  { id: "2A-c10-r1-d30", rubricId: "2A-c10-r1", omschrijving: "Exacte wetenschappen - Biotopen & ecosystemen", categorie: "standaard" },
  { id: "2A-c10-r1-d31", rubricId: "2A-c10-r1", omschrijving: "Techniek/technologie - Eigenschappen van materialen", categorie: "standaard" },
  { id: "2A-c10-r1-d32", rubricId: "2A-c10-r1", omschrijving: "Techniek/technologie - Natuurlijke & technische systemen", categorie: "standaard" },
  { id: "2A-c10-r1-d33", rubricId: "2A-c10-r1", omschrijving: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", categorie: "standaard" },
  { id: "2A-c10-r1-d34", rubricId: "2A-c10-r1", omschrijving: "Duurzaamheid bij technische systemen", categorie: "standaard" },
  { id: "2A-c10-r1-d35", rubricId: "2A-c10-r1", omschrijving: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", categorie: "standaard" },
  { id: "2A-c10-r1-d36", rubricId: "2A-c10-r1", omschrijving: "Economie - Gezinsbudget", categorie: "standaard" },
  { id: "2A-c10-r1-d37", rubricId: "2A-c10-r1", omschrijving: "Economie - Maatschappelijke thema’s", categorie: "standaard" },
  { id: "2A-c11-r1-d1", rubricId: "2A-c11-r1", omschrijving: "Klaskas projecten 1", categorie: "standaard" },
  { id: "2A-c11-r1-d2", rubricId: "2A-c11-r1", omschrijving: "Klaskas projecten 2", categorie: "standaard" },
  { id: "2A-c11-r1-d3", rubricId: "2A-c11-r1", omschrijving: "Klaskas projecten 3", categorie: "standaard" },
  { id: "2A-c11-r1-d4", rubricId: "2A-c11-r1", omschrijving: "Klaskas projecten 4", categorie: "standaard" },
  { id: "2A-c11-r1-d5", rubricId: "2A-c11-r1", omschrijving: "Klaskas projecten 5", categorie: "standaard" },
  { id: "2A-c11-r1-d6", rubricId: "2A-c11-r1", omschrijving: "Klaskas projecten 6", categorie: "standaard" },
  { id: "2A-c11-r1-d7", rubricId: "2A-c11-r1", omschrijving: "Klaskas - Economisch onderzoek over productie en consumptie", categorie: "standaard" },
  { id: "2A-c12-r1-d1", rubricId: "2A-c12-r1", omschrijving: "Wiskundelessen gegeven 1", categorie: "standaard" },
  { id: "2A-c12-r1-d2", rubricId: "2A-c12-r1", omschrijving: "Wiskundelessen gegeven 2", categorie: "standaard" },
  { id: "2A-c12-r1-d3", rubricId: "2A-c12-r1", omschrijving: "Wiskundelessen gegeven 3", categorie: "standaard" },
  { id: "2A-c12-r1-d4", rubricId: "2A-c12-r1", omschrijving: "Wiskundig onderzoek: statistiek", categorie: "standaard" },
  { id: "2A-c12-r1-d5", rubricId: "2A-c12-r1", omschrijving: "Wiskundig onderzoek: patronen, algoritmes, AI", categorie: "standaard" },
  { id: "2A-c12-r1-d6", rubricId: "2A-c12-r1", omschrijving: "Wiskundig onderzoek 1", categorie: "standaard" },
  { id: "2A-c12-r1-d7", rubricId: "2A-c12-r1", omschrijving: "Wiskundig onderzoek 2", categorie: "standaard" },
  { id: "2A-c12-r1-d8", rubricId: "2A-c12-r1", omschrijving: "Wiskundig onderzoek 3", categorie: "standaard" },
  { id: "2A-c12-r1-d9", rubricId: "2A-c12-r1", omschrijving: "Wiskundig onderzoek 4", categorie: "standaard" },
  { id: "2A-c12-r1-d10", rubricId: "2A-c12-r1", omschrijving: "Getallenleer - Reële getallen op de getallenas (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d11", rubricId: "2A-c12-r1", omschrijving: "Getallenleer - Rekenen met reële getallen (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d12", rubricId: "2A-c12-r1", omschrijving: "Meetkunde - Ligging van punten, rechten en vlakken (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d13", rubricId: "2A-c12-r1", omschrijving: "Meetkunde - Gelijkvormigheid (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d14", rubricId: "2A-c12-r1", omschrijving: "Meetkunde - Stelling van Pythagoras (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d15", rubricId: "2A-c12-r1", omschrijving: "Meetkunde - Goniometrische getallen in rechthoekige driehoeken (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d16", rubricId: "2A-c12-r1", omschrijving: "Meetkunde - Vectoren (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d17", rubricId: "2A-c12-r1", omschrijving: "Algebra en analyse - Eerstegraadsformules, vergelijkingen en ongelijkheden (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d18", rubricId: "2A-c12-r1", omschrijving: "Algebra en analyse - Functies (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d19", rubricId: "2A-c12-r1", omschrijving: "Algebra en analyse - Eerstegraadsfuncties (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d20", rubricId: "2A-c12-r1", omschrijving: "Algebra en analyse - Tweedegraadsfuncties (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d21", rubricId: "2A-c12-r1", omschrijving: "Algebra en analyse - Stelsel van 2 vergelijkingen (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d22", rubricId: "2A-c12-r1", omschrijving: "Telproblemen en Statistiek - Telproblemen (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d23", rubricId: "2A-c12-r1", omschrijving: "Telproblemen en Statistiek - Data en Statistiek (graadsbadge)", categorie: "standaard" },
  { id: "2A-c12-r1-d24", rubricId: "2A-c12-r1", omschrijving: "Logica (graadsbadge)", categorie: "standaard" },
  { id: "2A-c13-r1-d1", rubricId: "2A-c13-r1", omschrijving: "Kunstbeschouwing - Kunst in prehistorie", categorie: "standaard" },
  { id: "2A-c13-r1-d2", rubricId: "2A-c13-r1", omschrijving: "Kunstbeschouwing - Kunst in Middeleeuwen", categorie: "standaard" },
  { id: "2A-c13-r1-d3", rubricId: "2A-c13-r1", omschrijving: "Kunstbeschouwing - Kunst in Vroegmoderne Tijd", categorie: "standaard" },
  { id: "2A-c13-r1-d4", rubricId: "2A-c13-r1", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 1", categorie: "standaard" },
  { id: "2A-c13-r1-d5", rubricId: "2A-c13-r1", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 2", categorie: "standaard" },
  { id: "2A-c13-r1-d6", rubricId: "2A-c13-r1", omschrijving: "Kunstbeschouwing - Onderwerp naar keuze", categorie: "standaard" },
  { id: "2A-c13-r1-d7", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - toegepaste kunsten (design en ambachten)", categorie: "standaard" },
  { id: "2A-c13-r1-d8", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - beeldende kunsten", categorie: "standaard" },
  { id: "2A-c13-r1-d9", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - podiumkunsten", categorie: "standaard" },
  { id: "2A-c13-r1-d10", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - muziek", categorie: "standaard" },
  { id: "2A-c13-r1-d11", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - media en audiovisuele kunsten", categorie: "standaard" },
  { id: "2A-c13-r1-d12", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - interdisciplinaire en hybride kunsten", categorie: "standaard" },
  { id: "2A-c13-r1-d13", rubricId: "2A-c13-r1", omschrijving: "Vrije expressie - letterkunde (literaire kunsten)", categorie: "standaard" },
  { id: "2A-c14-r1-d1", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 1", categorie: "standaard" },
  { id: "2A-c14-r1-d2", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 2", categorie: "standaard" },
  { id: "2A-c14-r1-d3", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 3", categorie: "standaard" },
  { id: "2A-c14-r1-d4", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 4", categorie: "standaard" },
  { id: "2A-c14-r1-d5", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 5", categorie: "standaard" },
  { id: "2A-c14-r1-d6", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 6", categorie: "standaard" },
  { id: "2A-c14-r1-d7", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 7", categorie: "standaard" },
  { id: "2A-c14-r1-d8", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 8", categorie: "standaard" },
  { id: "2A-c14-r1-d9", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 9", categorie: "standaard" },
  { id: "2A-c14-r1-d10", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 10", categorie: "standaard" },
  { id: "2A-c14-r1-d11", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 11", categorie: "standaard" },
  { id: "2A-c14-r1-d12", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 12", categorie: "standaard" },
  { id: "2A-c14-r1-d13", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 13", categorie: "standaard" },
  { id: "2A-c14-r1-d14", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 14", categorie: "standaard" },
  { id: "2A-c14-r1-d15", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 15", categorie: "standaard" },
  { id: "2A-c14-r1-d16", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 16", categorie: "standaard" },
  { id: "2A-c14-r1-d17", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 17", categorie: "standaard" },
  { id: "2A-c14-r1-d18", rubricId: "2A-c14-r1", omschrijving: "Leerwandelingen & uitstappen 18", categorie: "standaard" },
  { id: "2A-c14-r1-d19", rubricId: "2A-c14-r1", omschrijving: "Klasreis 1", categorie: "standaard" },
  { id: "2A-c14-r1-d20", rubricId: "2A-c14-r1", omschrijving: "Klasreis 2", categorie: "standaard" },
  { id: "2A-c15-r1-d1", rubricId: "2A-c15-r1", omschrijving: "Toonmoment 1", categorie: "standaard" },
  { id: "2A-c15-r1-d2", rubricId: "2A-c15-r1", omschrijving: "Toonmoment 2", categorie: "standaard" },
  { id: "2A-c15-r1-d3", rubricId: "2A-c15-r1", omschrijving: "Toonmoment 3", categorie: "standaard" },
  { id: "2A-c15-r1-d4", rubricId: "2A-c15-r1", omschrijving: "Toonmoment 4", categorie: "standaard" },
  { id: "2A-c15-r1-d5", rubricId: "2A-c15-r1", omschrijving: "Toonmoment 5", categorie: "standaard" },
  { id: "2A-c15-r1-d6", rubricId: "2A-c15-r1", omschrijving: "Toonmoment 6", categorie: "standaard" },
  { id: "2A-c15-r1-d7", rubricId: "2A-c15-r1", omschrijving: "Leerlingenseminars 1", categorie: "standaard" },
  { id: "2A-c15-r1-d8", rubricId: "2A-c15-r1", omschrijving: "Leerlingenseminars 2", categorie: "standaard" },
  { id: "2A-c15-r1-d9", rubricId: "2A-c15-r1", omschrijving: "Leerlingenseminars 3", categorie: "standaard" },
  { id: "2A-c15-r1-d10", rubricId: "2A-c15-r1", omschrijving: "Leerlingenseminars 4", categorie: "standaard" },
  { id: "2A-c15-r1-d11", rubricId: "2A-c15-r1", omschrijving: "Leerlingenseminars 5", categorie: "standaard" },
  { id: "2A-c15-r1-d12", rubricId: "2A-c15-r1", omschrijving: "Leerlingenseminars 6", categorie: "standaard" },
  { id: "2A-c15-r1-d13", rubricId: "2A-c15-r1", omschrijving: "Externe seminars 1", categorie: "standaard" },
  { id: "2A-c15-r1-d14", rubricId: "2A-c15-r1", omschrijving: "Externe seminars 2", categorie: "standaard" },
  { id: "2A-c15-r1-d15", rubricId: "2A-c15-r1", omschrijving: "Externe seminars 3", categorie: "standaard" },
  { id: "2A-c15-r1-d16", rubricId: "2A-c15-r1", omschrijving: "Externe seminars 4", categorie: "standaard" },
  { id: "2A-c15-r1-d17", rubricId: "2A-c15-r1", omschrijving: "Externe seminars 5", categorie: "standaard" },
  { id: "2A-c15-r1-d18", rubricId: "2A-c15-r1", omschrijving: "Externe seminars 6", categorie: "standaard" },
  { id: "2A-c16-r1-d1", rubricId: "2A-c16-r1", omschrijving: "Privacy, auteursrecht, portretrecht, netiquette", categorie: "standaard" },
  { id: "2A-c16-r1-d2", rubricId: "2A-c16-r1", omschrijving: "Digitale identiteit beheren", categorie: "standaard" },
  { id: "2A-c16-r1-d3", rubricId: "2A-c16-r1", omschrijving: "Vooroordelen, machtsmisbruik, groepsdruk in de digitale wereld", categorie: "standaard" },
  { id: "2A-c16-r1-d4", rubricId: "2A-c16-r1", omschrijving: "Veiligheid - Infrastructuur, gereedschappen en materialen", categorie: "standaard" },
  { id: "2A-c16-r1-d5", rubricId: "2A-c16-r1", omschrijving: "Veiligheid - Noodsituaties", categorie: "standaard" },
  { id: "2A-c16-r1-d6", rubricId: "2A-c16-r1", omschrijving: "Veiligheid - Gebruik van openbaar vervoer", categorie: "standaard" },
  { id: "2A-c16-r1-d7", rubricId: "2A-c16-r1", omschrijving: "Respectvol gedrag, verbaal en non-verbaal", categorie: "standaard" },
  { id: "2A-c16-r1-d8", rubricId: "2A-c16-r1", omschrijving: "Gezondheid - Thema 1", categorie: "standaard" },
  { id: "2A-c16-r1-d9", rubricId: "2A-c16-r1", omschrijving: "Gezondheid - Thema 2", categorie: "standaard" },
  { id: "2A-c16-r1-d10", rubricId: "2A-c16-r1", omschrijving: "Gezondheid - Hulpverlenersorganisaties", categorie: "standaard" },
  { id: "2A-c16-r1-d11", rubricId: "2A-c16-r1", omschrijving: "Gezondheid - EHBO", categorie: "standaard" },
  { id: "2A-c16-r1-d12", rubricId: "2A-c16-r1", omschrijving: "Mentale gezondheid - Thema 1", categorie: "standaard" },
  { id: "2A-c16-r1-d13", rubricId: "2A-c16-r1", omschrijving: "Mentale gezondheid - Hulpverleners en hulporganisaties", categorie: "standaard" },
  { id: "2A-c16-r1-d14", rubricId: "2A-c16-r1", omschrijving: "Gezonde levensstijl - Voeding", categorie: "standaard" },
  { id: "2A-c16-r1-d15", rubricId: "2A-c16-r1", omschrijving: "Gezonde levensstijl - Beweging", categorie: "standaard" },
  { id: "2A-c16-r1-d16", rubricId: "2A-c16-r1", omschrijving: "Gezonde levensstijl - Hygiëne", categorie: "standaard" },
  { id: "2A-c16-r1-d17", rubricId: "2A-c16-r1", omschrijving: "Gezonde levensstijl - Ergonomie", categorie: "standaard" },
  { id: "2A-c16-r1-d18", rubricId: "2A-c16-r1", omschrijving: "Individuele sporten 1", categorie: "standaard" },
  { id: "2A-c16-r1-d19", rubricId: "2A-c16-r1", omschrijving: "Individuele sporten 2", categorie: "standaard" },
  { id: "2A-c16-r1-d20", rubricId: "2A-c16-r1", omschrijving: "Individuele sporten 3", categorie: "standaard" },
  { id: "2A-c16-r1-d21", rubricId: "2A-c16-r1", omschrijving: "Individuele sporten 4", categorie: "standaard" },
  { id: "2A-c16-r1-d22", rubricId: "2A-c16-r1", omschrijving: "Interactieve beweging 1", categorie: "standaard" },
  { id: "2A-c16-r1-d23", rubricId: "2A-c16-r1", omschrijving: "Interactieve beweging 2", categorie: "standaard" },
  { id: "2A-c16-r1-d24", rubricId: "2A-c16-r1", omschrijving: "Interactieve beweging 3", categorie: "standaard" },
  { id: "2A-c16-r1-d25", rubricId: "2A-c16-r1", omschrijving: "Interactieve beweging 4", categorie: "standaard" },
  { id: "2A-c16-r1-d26", rubricId: "2A-c16-r1", omschrijving: "Ritmisch expressieve beweging 1", categorie: "standaard" },
  { id: "2A-c16-r1-d27", rubricId: "2A-c16-r1", omschrijving: "Ritmisch expressieve beweging 2", categorie: "standaard" },
  { id: "2A-c16-r1-d28", rubricId: "2A-c16-r1", omschrijving: "Ritmisch expressieve beweging 3", categorie: "standaard" },
  { id: "2A-c16-r1-d29", rubricId: "2A-c16-r1", omschrijving: "Ritmisch expressieve beweging 4", categorie: "standaard" },
  { id: "2A-c17-r1-d1", rubricId: "2A-c17-r1", omschrijving: "Ervaringsweek 3e jaar", categorie: "standaard" },
  { id: "2A-c17-r1-d2", rubricId: "2A-c17-r1", omschrijving: "Ervaringsweek 4e jaar", categorie: "standaard" },
  { id: "2A-c18-r1-d1", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 1", categorie: "standaard" },
  { id: "2A-c18-r1-d2", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 2", categorie: "standaard" },
  { id: "2A-c18-r1-d3", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 3", categorie: "standaard" },
  { id: "2A-c18-r1-d4", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 4", categorie: "standaard" },
  { id: "2A-c18-r1-d5", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 5", categorie: "standaard" },
  { id: "2A-c18-r1-d6", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 6", categorie: "standaard" },
  { id: "2A-c18-r1-d7", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 7", categorie: "standaard" },
  { id: "2A-c18-r1-d8", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 8", categorie: "standaard" },
  { id: "2A-c18-r1-d9", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 9", categorie: "standaard" },
  { id: "2A-c18-r1-d10", rubricId: "2A-c18-r1", omschrijving: "Vrij initiatief buiten de lijntjes 10", categorie: "standaard" },
];
