// AUTO-GEGENEREERD via scripts/extract_badges.py
// uit docs/reference/deelevaluaties_alle-graden-2.xlsx — niet met de hand aanpassen.
import type { Cursus, Leerdoel, Rubric } from "./types";

export const cursussen1B: Cursus[] = [
  { id: "1B-c1", stroom: "1B", naam: "Planning en reflectie" },
  { id: "1B-c2", stroom: "1B", naam: "Klasraad" },
  { id: "1B-c3", stroom: "1B", naam: "Burgerschap" },
  { id: "1B-c4", stroom: "1B", naam: "Ateliers" },
  { id: "1B-c5", stroom: "1B", naam: "Kring" },
  { id: "1B-c6", stroom: "1B", naam: "Actuaronde" },
  { id: "1B-c7", stroom: "1B", naam: "Vrije Tekst" },
  { id: "1B-c8", stroom: "1B", naam: "Boekenronde" },
  { id: "1B-c9", stroom: "1B", naam: "Communicatie" },
  { id: "1B-c10", stroom: "1B", naam: "Onderzoek" },
  { id: "1B-c11", stroom: "1B", naam: "Klaskas" },
  { id: "1B-c12", stroom: "1B", naam: "Levende Wiskunde" },
  { id: "1B-c13", stroom: "1B", naam: "Cultuur" },
  { id: "1B-c14", stroom: "1B", naam: "Exploratie" },
  { id: "1B-c15", stroom: "1B", naam: "Toonmoment" },
  { id: "1B-c16", stroom: "1B", naam: "Welzijn" },
  { id: "1B-c17", stroom: "1B", naam: "Vrij initiatief buiten de lijntjes" },
];

export const rubrics1B: Rubric[] = [
  { id: "1B-c1-r1", cursusId: "1B-c1", naam: "Planning en reflectie" },
  { id: "1B-c2-r1", cursusId: "1B-c2", naam: "Klasraad" },
  { id: "1B-c3-r1", cursusId: "1B-c3", naam: "Burgerschap" },
  { id: "1B-c4-r1", cursusId: "1B-c4", naam: "Ateliers" },
  { id: "1B-c5-r1", cursusId: "1B-c5", naam: "Kring" },
  { id: "1B-c6-r1", cursusId: "1B-c6", naam: "Actuaronde" },
  { id: "1B-c7-r1", cursusId: "1B-c7", naam: "Vrije Tekst" },
  { id: "1B-c8-r1", cursusId: "1B-c8", naam: "Boekenronde" },
  { id: "1B-c9-r1", cursusId: "1B-c9", naam: "Communicatie" },
  { id: "1B-c10-r1", cursusId: "1B-c10", naam: "Onderzoek" },
  { id: "1B-c11-r1", cursusId: "1B-c11", naam: "Klaskas" },
  { id: "1B-c12-r1", cursusId: "1B-c12", naam: "Levende Wiskunde" },
  { id: "1B-c13-r1", cursusId: "1B-c13", naam: "Cultuur" },
  { id: "1B-c14-r1", cursusId: "1B-c14", naam: "Exploratie" },
  { id: "1B-c15-r1", cursusId: "1B-c15", naam: "Toonmoment" },
  { id: "1B-c16-r1", cursusId: "1B-c16", naam: "Welzijn" },
  { id: "1B-c17-r1", cursusId: "1B-c17", naam: "Vrij initiatief buiten de lijntjes" },
];

export const leerdoelen1B: Leerdoel[] = [
  { id: "1B-c1-r1-d1", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 1", categorie: "standaard" },
  { id: "1B-c1-r1-d2", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 2", categorie: "standaard" },
  { id: "1B-c1-r1-d3", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 3", categorie: "standaard" },
  { id: "1B-c1-r1-d4", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 4", categorie: "standaard" },
  { id: "1B-c1-r1-d5", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 5", categorie: "standaard" },
  { id: "1B-c1-r1-d6", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 6", categorie: "standaard" },
  { id: "1B-c1-r1-d7", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 7", categorie: "standaard" },
  { id: "1B-c1-r1-d8", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 8", categorie: "standaard" },
  { id: "1B-c1-r1-d9", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 9", categorie: "standaard" },
  { id: "1B-c1-r1-d10", rubricId: "1B-c1-r1", omschrijving: "Coachinggesprek 10", categorie: "standaard" },
  { id: "1B-c2-r1-d1", rubricId: "1B-c2-r1", omschrijving: "Voorzitter 1", categorie: "standaard" },
  { id: "1B-c2-r1-d2", rubricId: "1B-c2-r1", omschrijving: "Voorzitter 2", categorie: "standaard" },
  { id: "1B-c2-r1-d3", rubricId: "1B-c2-r1", omschrijving: "Voorzitter 3", categorie: "standaard" },
  { id: "1B-c2-r1-d4", rubricId: "1B-c2-r1", omschrijving: "Voorzitter 4", categorie: "standaard" },
  { id: "1B-c2-r1-d5", rubricId: "1B-c2-r1", omschrijving: "Secretaris 1", categorie: "standaard" },
  { id: "1B-c2-r1-d6", rubricId: "1B-c2-r1", omschrijving: "Secretaris 2", categorie: "standaard" },
  { id: "1B-c2-r1-d7", rubricId: "1B-c2-r1", omschrijving: "Secretaris 3", categorie: "standaard" },
  { id: "1B-c2-r1-d8", rubricId: "1B-c2-r1", omschrijving: "Secretaris 4", categorie: "standaard" },
  { id: "1B-c2-r1-d9", rubricId: "1B-c2-r1", omschrijving: "Tijdsbewaker 1", categorie: "standaard" },
  { id: "1B-c2-r1-d10", rubricId: "1B-c2-r1", omschrijving: "Tijdsbewaker 2", categorie: "standaard" },
  { id: "1B-c2-r1-d11", rubricId: "1B-c2-r1", omschrijving: "Tijdsbewaker 3", categorie: "standaard" },
  { id: "1B-c2-r1-d12", rubricId: "1B-c2-r1", omschrijving: "Tijdsbewaker 4", categorie: "standaard" },
  { id: "1B-c2-r1-d13", rubricId: "1B-c2-r1", omschrijving: "Deelnemer (wekelijks) 1", categorie: "standaard" },
  { id: "1B-c2-r1-d14", rubricId: "1B-c2-r1", omschrijving: "Deelnemer (wekelijks) 2", categorie: "standaard" },
  { id: "1B-c2-r1-d15", rubricId: "1B-c2-r1", omschrijving: "Deelnemer (wekelijks) 3", categorie: "standaard" },
  { id: "1B-c2-r1-d16", rubricId: "1B-c2-r1", omschrijving: "Deelnemer (wekelijks) 4", categorie: "standaard" },
  { id: "1B-c2-r1-d17", rubricId: "1B-c2-r1", omschrijving: "Deelnemer (wekelijks) 5", categorie: "standaard" },
  { id: "1B-c2-r1-d18", rubricId: "1B-c2-r1", omschrijving: "Deelnemer (wekelijks) 6", categorie: "standaard" },
  { id: "1B-c2-r1-d19", rubricId: "1B-c2-r1", omschrijving: "Vestigingsraad/Keerpuntraad/Leerlingenraad", categorie: "standaard" },
  { id: "1B-c3-r1-d1", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 1", categorie: "standaard" },
  { id: "1B-c3-r1-d2", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 2", categorie: "standaard" },
  { id: "1B-c3-r1-d3", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 3", categorie: "standaard" },
  { id: "1B-c3-r1-d4", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 4", categorie: "standaard" },
  { id: "1B-c3-r1-d5", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 5", categorie: "standaard" },
  { id: "1B-c3-r1-d6", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 6", categorie: "standaard" },
  { id: "1B-c3-r1-d7", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 7", categorie: "standaard" },
  { id: "1B-c3-r1-d8", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 8", categorie: "standaard" },
  { id: "1B-c3-r1-d9", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 9", categorie: "standaard" },
  { id: "1B-c3-r1-d10", rubricId: "1B-c3-r1", omschrijving: "Intern burgerschap 10", categorie: "standaard" },
  { id: "1B-c3-r1-d11", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 1", categorie: "standaard" },
  { id: "1B-c3-r1-d12", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 2", categorie: "standaard" },
  { id: "1B-c3-r1-d13", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 3", categorie: "standaard" },
  { id: "1B-c3-r1-d14", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 4", categorie: "standaard" },
  { id: "1B-c3-r1-d15", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 5", categorie: "standaard" },
  { id: "1B-c3-r1-d16", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 6", categorie: "standaard" },
  { id: "1B-c3-r1-d17", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 7", categorie: "standaard" },
  { id: "1B-c3-r1-d18", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 8", categorie: "standaard" },
  { id: "1B-c3-r1-d19", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 9", categorie: "standaard" },
  { id: "1B-c3-r1-d20", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 10", categorie: "standaard" },
  { id: "1B-c3-r1-d21", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 11", categorie: "standaard" },
  { id: "1B-c3-r1-d22", rubricId: "1B-c3-r1", omschrijving: "Extern burgerschap (2 lestijden) 12", categorie: "standaard" },
  { id: "1B-c4-r1-d1", rubricId: "1B-c4-r1", omschrijving: "Natuur", categorie: "standaard" },
  { id: "1B-c4-r1-d2", rubricId: "1B-c4-r1", omschrijving: "Handvaardigheid, bouw & techniek", categorie: "standaard" },
  { id: "1B-c4-r1-d3", rubricId: "1B-c4-r1", omschrijving: "Kennis", categorie: "standaard" },
  { id: "1B-c4-r1-d4", rubricId: "1B-c4-r1", omschrijving: "Experimenten, wetenschappelijk onderzoek & innovatie", categorie: "standaard" },
  { id: "1B-c4-r1-d5", rubricId: "1B-c4-r1", omschrijving: "ICT, digitale & moderne technieken", categorie: "standaard" },
  { id: "1B-c4-r1-d6", rubricId: "1B-c4-r1", omschrijving: "Expressie, creatie & ontwerp", categorie: "standaard" },
  { id: "1B-c4-r1-d7", rubricId: "1B-c4-r1", omschrijving: "Welzijn en andere", categorie: "standaard" },
  { id: "1B-c4-r1-d8", rubricId: "1B-c4-r1", omschrijving: "Eén atelier volgen in elk van de 7 domeinen (graadsbadge)", categorie: "standaard" },
  { id: "1B-c5-r1-d1", rubricId: "1B-c5-r1", omschrijving: "Voorzitter 1", categorie: "standaard" },
  { id: "1B-c5-r1-d2", rubricId: "1B-c5-r1", omschrijving: "Voorzitter 2", categorie: "standaard" },
  { id: "1B-c5-r1-d3", rubricId: "1B-c5-r1", omschrijving: "Voorzitter 3", categorie: "standaard" },
  { id: "1B-c5-r1-d4", rubricId: "1B-c5-r1", omschrijving: "Voorzitter 4", categorie: "standaard" },
  { id: "1B-c5-r1-d5", rubricId: "1B-c5-r1", omschrijving: "Voorzitter 5", categorie: "standaard" },
  { id: "1B-c5-r1-d6", rubricId: "1B-c5-r1", omschrijving: "Secretaris 1", categorie: "standaard" },
  { id: "1B-c5-r1-d7", rubricId: "1B-c5-r1", omschrijving: "Secretaris 2", categorie: "standaard" },
  { id: "1B-c5-r1-d8", rubricId: "1B-c5-r1", omschrijving: "Secretaris 3", categorie: "standaard" },
  { id: "1B-c5-r1-d9", rubricId: "1B-c5-r1", omschrijving: "Secretaris 4", categorie: "standaard" },
  { id: "1B-c5-r1-d10", rubricId: "1B-c5-r1", omschrijving: "Secretaris 5", categorie: "standaard" },
  { id: "1B-c5-r1-d11", rubricId: "1B-c5-r1", omschrijving: "Tijdsbewaker 1", categorie: "standaard" },
  { id: "1B-c5-r1-d12", rubricId: "1B-c5-r1", omschrijving: "Tijdsbewaker 2", categorie: "standaard" },
  { id: "1B-c5-r1-d13", rubricId: "1B-c5-r1", omschrijving: "Tijdsbewaker 3", categorie: "standaard" },
  { id: "1B-c5-r1-d14", rubricId: "1B-c5-r1", omschrijving: "Tijdsbewaker 4", categorie: "standaard" },
  { id: "1B-c5-r1-d15", rubricId: "1B-c5-r1", omschrijving: "Tijdsbewaker 5", categorie: "standaard" },
  { id: "1B-c5-r1-d16", rubricId: "1B-c5-r1", omschrijving: "Deelnemer (wekelijks) 1", categorie: "standaard" },
  { id: "1B-c5-r1-d17", rubricId: "1B-c5-r1", omschrijving: "Deelnemer (wekelijks) 2", categorie: "standaard" },
  { id: "1B-c5-r1-d18", rubricId: "1B-c5-r1", omschrijving: "Deelnemer (wekelijks) 3", categorie: "standaard" },
  { id: "1B-c5-r1-d19", rubricId: "1B-c5-r1", omschrijving: "Deelnemer (wekelijks) 4", categorie: "standaard" },
  { id: "1B-c5-r1-d20", rubricId: "1B-c5-r1", omschrijving: "Deelnemer (wekelijks) 5", categorie: "standaard" },
  { id: "1B-c5-r1-d21", rubricId: "1B-c5-r1", omschrijving: "Deelnemer (wekelijks) 6", categorie: "standaard" },
  { id: "1B-c5-r1-d22", rubricId: "1B-c5-r1", omschrijving: "Kring Frans 1", categorie: "standaard" },
  { id: "1B-c5-r1-d23", rubricId: "1B-c5-r1", omschrijving: "Kring Frans 2", categorie: "standaard" },
  { id: "1B-c5-r1-d24", rubricId: "1B-c5-r1", omschrijving: "Kring Frans 3", categorie: "standaard" },
  { id: "1B-c5-r1-d25", rubricId: "1B-c5-r1", omschrijving: "Kring Frans 4", categorie: "standaard" },
  { id: "1B-c5-r1-d26", rubricId: "1B-c5-r1", omschrijving: "Kring Engels 1", categorie: "standaard" },
  { id: "1B-c5-r1-d27", rubricId: "1B-c5-r1", omschrijving: "Kring Engels 2", categorie: "standaard" },
  { id: "1B-c5-r1-d28", rubricId: "1B-c5-r1", omschrijving: "Kring Engels 3", categorie: "standaard" },
  { id: "1B-c5-r1-d29", rubricId: "1B-c5-r1", omschrijving: "Kring Engels 4", categorie: "standaard" },
  { id: "1B-c6-r1-d1", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 1", categorie: "standaard" },
  { id: "1B-c6-r1-d2", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 2", categorie: "standaard" },
  { id: "1B-c6-r1-d3", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 3", categorie: "standaard" },
  { id: "1B-c6-r1-d4", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 4", categorie: "standaard" },
  { id: "1B-c6-r1-d5", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 5", categorie: "standaard" },
  { id: "1B-c6-r1-d6", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 6", categorie: "standaard" },
  { id: "1B-c6-r1-d7", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 7", categorie: "standaard" },
  { id: "1B-c6-r1-d8", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Nederlands 8", categorie: "standaard" },
  { id: "1B-c6-r1-d9", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Frans 1", categorie: "standaard" },
  { id: "1B-c6-r1-d10", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Frans 2", categorie: "standaard" },
  { id: "1B-c6-r1-d11", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Engels 1", categorie: "standaard" },
  { id: "1B-c6-r1-d12", rubricId: "1B-c6-r1", omschrijving: "Actuaronde Engels 2", categorie: "standaard" },
  { id: "1B-c7-r1-d1", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 1", categorie: "standaard" },
  { id: "1B-c7-r1-d2", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 2", categorie: "standaard" },
  { id: "1B-c7-r1-d3", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 3", categorie: "standaard" },
  { id: "1B-c7-r1-d4", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 4", categorie: "standaard" },
  { id: "1B-c7-r1-d5", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 5", categorie: "standaard" },
  { id: "1B-c7-r1-d6", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 6", categorie: "standaard" },
  { id: "1B-c7-r1-d7", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 7", categorie: "standaard" },
  { id: "1B-c7-r1-d8", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Nederlands 8", categorie: "standaard" },
  { id: "1B-c7-r1-d9", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Frans 1", categorie: "standaard" },
  { id: "1B-c7-r1-d10", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Frans 2", categorie: "standaard" },
  { id: "1B-c7-r1-d11", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Frans 3", categorie: "standaard" },
  { id: "1B-c7-r1-d12", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Frans 4", categorie: "standaard" },
  { id: "1B-c7-r1-d13", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Frans 5", categorie: "standaard" },
  { id: "1B-c7-r1-d14", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Frans 6", categorie: "standaard" },
  { id: "1B-c7-r1-d15", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Engels 1", categorie: "standaard" },
  { id: "1B-c7-r1-d16", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Engels 2", categorie: "standaard" },
  { id: "1B-c7-r1-d17", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Engels 3", categorie: "standaard" },
  { id: "1B-c7-r1-d18", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Engels 4", categorie: "standaard" },
  { id: "1B-c7-r1-d19", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Engels 5", categorie: "standaard" },
  { id: "1B-c7-r1-d20", rubricId: "1B-c7-r1", omschrijving: "Vrije tekst Engels 6", categorie: "standaard" },
  { id: "1B-c8-r1-d1", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 1", categorie: "standaard" },
  { id: "1B-c8-r1-d2", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 2", categorie: "standaard" },
  { id: "1B-c8-r1-d3", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 3", categorie: "standaard" },
  { id: "1B-c8-r1-d4", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 4", categorie: "standaard" },
  { id: "1B-c8-r1-d5", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 5", categorie: "standaard" },
  { id: "1B-c8-r1-d6", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 6", categorie: "standaard" },
  { id: "1B-c8-r1-d7", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 7", categorie: "standaard" },
  { id: "1B-c8-r1-d8", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Nederlands 8", categorie: "standaard" },
  { id: "1B-c8-r1-d9", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Frans 1", categorie: "standaard" },
  { id: "1B-c8-r1-d10", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Frans 2", categorie: "standaard" },
  { id: "1B-c8-r1-d11", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Frans 3", categorie: "standaard" },
  { id: "1B-c8-r1-d12", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Engels 1", categorie: "standaard" },
  { id: "1B-c8-r1-d13", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Engels 2", categorie: "standaard" },
  { id: "1B-c8-r1-d14", rubricId: "1B-c8-r1", omschrijving: "Boekenronde Engels 3", categorie: "standaard" },
  { id: "1B-c9-r1-d1", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie 1", categorie: "standaard" },
  { id: "1B-c9-r1-d2", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie 2", categorie: "standaard" },
  { id: "1B-c9-r1-d3", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie 3", categorie: "standaard" },
  { id: "1B-c9-r1-d4", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie 4", categorie: "standaard" },
  { id: "1B-c9-r1-d5", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie 5", categorie: "standaard" },
  { id: "1B-c9-r1-d6", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie Frans 1", categorie: "standaard" },
  { id: "1B-c9-r1-d7", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie Frans 2", categorie: "standaard" },
  { id: "1B-c9-r1-d8", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie Frans 3", categorie: "standaard" },
  { id: "1B-c9-r1-d9", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie Engels 1", categorie: "standaard" },
  { id: "1B-c9-r1-d10", rubricId: "1B-c9-r1", omschrijving: "Krant/Correspondentie publicatie Engels 2", categorie: "standaard" },
  { id: "1B-c9-r1-d11", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern 1", categorie: "standaard" },
  { id: "1B-c9-r1-d12", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern 2", categorie: "standaard" },
  { id: "1B-c9-r1-d13", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern 3", categorie: "standaard" },
  { id: "1B-c9-r1-d14", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern 4", categorie: "standaard" },
  { id: "1B-c9-r1-d15", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern Frans 1", categorie: "standaard" },
  { id: "1B-c9-r1-d16", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern Frans 2", categorie: "standaard" },
  { id: "1B-c9-r1-d17", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern Engels 1", categorie: "standaard" },
  { id: "1B-c9-r1-d18", rubricId: "1B-c9-r1", omschrijving: "Activiteit Keerpunt/extern Engels 2", categorie: "standaard" },
  { id: "1B-c10-r1-d1", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 1", categorie: "standaard" },
  { id: "1B-c10-r1-d2", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 2", categorie: "standaard" },
  { id: "1B-c10-r1-d3", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 3", categorie: "standaard" },
  { id: "1B-c10-r1-d4", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 4", categorie: "standaard" },
  { id: "1B-c10-r1-d5", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 5", categorie: "standaard" },
  { id: "1B-c10-r1-d6", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 6", categorie: "standaard" },
  { id: "1B-c10-r1-d7", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 7", categorie: "standaard" },
  { id: "1B-c10-r1-d8", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 8", categorie: "standaard" },
  { id: "1B-c10-r1-d9", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 9", categorie: "standaard" },
  { id: "1B-c10-r1-d10", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 10", categorie: "standaard" },
  { id: "1B-c10-r1-d11", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 11", categorie: "standaard" },
  { id: "1B-c10-r1-d12", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 12", categorie: "standaard" },
  { id: "1B-c10-r1-d13", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 13", categorie: "standaard" },
  { id: "1B-c10-r1-d14", rubricId: "1B-c10-r1", omschrijving: "Kwaliteitsvol onderzoek 14", categorie: "standaard" },
  { id: "1B-c10-r1-d15", rubricId: "1B-c10-r1", omschrijving: "Historisch - Algemene periodisering", categorie: "standaard" },
  { id: "1B-c10-r1-d16", rubricId: "1B-c10-r1", omschrijving: "Historisch - Niet-Westerse periodisering", categorie: "standaard" },
  { id: "1B-c10-r1-d17", rubricId: "1B-c10-r1", omschrijving: "Historisch - Prehistorie: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "1B-c10-r1-d18", rubricId: "1B-c10-r1", omschrijving: "Historisch - Oude Nabije Oosten: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "1B-c10-r1-d19", rubricId: "1B-c10-r1", omschrijving: "Historisch - Klassieke Oudheid: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "1B-c10-r1-d20", rubricId: "1B-c10-r1", omschrijving: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", categorie: "standaard" },
  { id: "1B-c10-r1-d21", rubricId: "1B-c10-r1", omschrijving: "Ruimtelijk - Geografische eenheden: landschappen, reliëf, ondergrond, klimaat, vegetatie", categorie: "standaard" },
  { id: "1B-c10-r1-d22", rubricId: "1B-c10-r1", omschrijving: "Ruimtelijk - Evolutie en verandering", categorie: "standaard" },
  { id: "1B-c10-r1-d23", rubricId: "1B-c10-r1", omschrijving: "Exacte wetenschappen - Deeltjesmodel", categorie: "standaard" },
  { id: "1B-c10-r1-d24", rubricId: "1B-c10-r1", omschrijving: "Exacte wetenschappen - Krachten, energie, stralingen", categorie: "standaard" },
  { id: "1B-c10-r1-d25", rubricId: "1B-c10-r1", omschrijving: "Exacte wetenschappen - Opbouw en functioneren van organismen", categorie: "standaard" },
  { id: "1B-c10-r1-d26", rubricId: "1B-c10-r1", omschrijving: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", categorie: "standaard" },
  { id: "1B-c10-r1-d27", rubricId: "1B-c10-r1", omschrijving: "Exacte wetenschappen - Biotopen", categorie: "standaard" },
  { id: "1B-c10-r1-d28", rubricId: "1B-c10-r1", omschrijving: "Techniek/technologie - Eigenschappen van materialen", categorie: "standaard" },
  { id: "1B-c10-r1-d29", rubricId: "1B-c10-r1", omschrijving: "Techniek/technologie - Technische processen", categorie: "standaard" },
  { id: "1B-c10-r1-d30", rubricId: "1B-c10-r1", omschrijving: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", categorie: "standaard" },
  { id: "1B-c10-r1-d31", rubricId: "1B-c10-r1", omschrijving: "Duurzaamheid bij technische systemen", categorie: "standaard" },
  { id: "1B-c10-r1-d32", rubricId: "1B-c10-r1", omschrijving: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", categorie: "standaard" },
  { id: "1B-c10-r1-d33", rubricId: "1B-c10-r1", omschrijving: "Economie - Gezinsbudget", categorie: "standaard" },
  { id: "1B-c10-r1-d34", rubricId: "1B-c10-r1", omschrijving: "Economie - Maatschappelijke thema’s", categorie: "standaard" },
  { id: "1B-c11-r1-d1", rubricId: "1B-c11-r1", omschrijving: "Klaskas projecten 1", categorie: "standaard" },
  { id: "1B-c11-r1-d2", rubricId: "1B-c11-r1", omschrijving: "Klaskas projecten 2", categorie: "standaard" },
  { id: "1B-c11-r1-d3", rubricId: "1B-c11-r1", omschrijving: "Klaskas projecten 3", categorie: "standaard" },
  { id: "1B-c11-r1-d4", rubricId: "1B-c11-r1", omschrijving: "Klaskas projecten 4", categorie: "standaard" },
  { id: "1B-c11-r1-d5", rubricId: "1B-c11-r1", omschrijving: "Klaskas projecten 5", categorie: "standaard" },
  { id: "1B-c11-r1-d6", rubricId: "1B-c11-r1", omschrijving: "Klaskas projecten 6", categorie: "standaard" },
  { id: "1B-c12-r1-d1", rubricId: "1B-c12-r1", omschrijving: "Levende Wiskunde activiteit 1", categorie: "standaard" },
  { id: "1B-c12-r1-d2", rubricId: "1B-c12-r1", omschrijving: "Levende Wiskunde activiteit 2", categorie: "standaard" },
  { id: "1B-c12-r1-d3", rubricId: "1B-c12-r1", omschrijving: "Levende Wiskunde activiteit 3", categorie: "standaard" },
  { id: "1B-c12-r1-d4", rubricId: "1B-c12-r1", omschrijving: "Levende Wiskunde activiteit 4", categorie: "standaard" },
  { id: "1B-c12-r1-d5", rubricId: "1B-c12-r1", omschrijving: "Levende Wiskunde activiteit 5", categorie: "standaard" },
  { id: "1B-c12-r1-d6", rubricId: "1B-c12-r1", omschrijving: "Levende Wiskunde activiteit 6", categorie: "standaard" },
  { id: "1B-c12-r1-d7", rubricId: "1B-c12-r1", omschrijving: "Wiskundig onderzoek 1", categorie: "standaard" },
  { id: "1B-c12-r1-d8", rubricId: "1B-c12-r1", omschrijving: "Wiskundig onderzoek 2", categorie: "standaard" },
  { id: "1B-c12-r1-d9", rubricId: "1B-c12-r1", omschrijving: "Wiskundig onderzoek 3", categorie: "standaard" },
  { id: "1B-c12-r1-d10", rubricId: "1B-c12-r1", omschrijving: "Wiskundig onderzoek 4", categorie: "standaard" },
  { id: "1B-c12-r1-d11", rubricId: "1B-c12-r1", omschrijving: "Getallenleer - Schatten en benaderen (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d12", rubricId: "1B-c12-r1", omschrijving: "Getallenleer - Ordenen van getallen (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d13", rubricId: "1B-c12-r1", omschrijving: "Getallenleer - Bewerkingen en rekenregels (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d14", rubricId: "1B-c12-r1", omschrijving: "Getallenleer - Maatgetallen (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d15", rubricId: "1B-c12-r1", omschrijving: "Meetkunde - Vlakke meetkunde (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d16", rubricId: "1B-c12-r1", omschrijving: "Meetkunde - Ruimtemeetkunde (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d17", rubricId: "1B-c12-r1", omschrijving: "Meetkunde - Coördinaten (graadsbadge)", categorie: "standaard" },
  { id: "1B-c12-r1-d18", rubricId: "1B-c12-r1", omschrijving: "Statistiek (graadsbadge)", categorie: "standaard" },
  { id: "1B-c13-r1-d1", rubricId: "1B-c13-r1", omschrijving: "Kunstbeschouwing - Kunst in prehistorie", categorie: "standaard" },
  { id: "1B-c13-r1-d2", rubricId: "1B-c13-r1", omschrijving: "Kunstbeschouwing - Kunst in Oude Nabije Oosten", categorie: "standaard" },
  { id: "1B-c13-r1-d3", rubricId: "1B-c13-r1", omschrijving: "Kunstbeschouwing - Kunst in Klassieke Oudheid", categorie: "standaard" },
  { id: "1B-c13-r1-d4", rubricId: "1B-c13-r1", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 1", categorie: "standaard" },
  { id: "1B-c13-r1-d5", rubricId: "1B-c13-r1", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 2", categorie: "standaard" },
  { id: "1B-c13-r1-d6", rubricId: "1B-c13-r1", omschrijving: "Kunstbeschouwing - Onderwerp naar keuze", categorie: "standaard" },
  { id: "1B-c13-r1-d7", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - toegepaste kunsten", categorie: "standaard" },
  { id: "1B-c13-r1-d8", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - beeldende kunsten", categorie: "standaard" },
  { id: "1B-c13-r1-d9", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - podiumkunsten", categorie: "standaard" },
  { id: "1B-c13-r1-d10", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - muziek", categorie: "standaard" },
  { id: "1B-c13-r1-d11", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - media en audiovisueel", categorie: "standaard" },
  { id: "1B-c13-r1-d12", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - interdisciplinair of hybride", categorie: "standaard" },
  { id: "1B-c13-r1-d13", rubricId: "1B-c13-r1", omschrijving: "Vrije expressie - literair", categorie: "standaard" },
  { id: "1B-c14-r1-d1", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 1", categorie: "standaard" },
  { id: "1B-c14-r1-d2", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 2", categorie: "standaard" },
  { id: "1B-c14-r1-d3", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 3", categorie: "standaard" },
  { id: "1B-c14-r1-d4", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 4", categorie: "standaard" },
  { id: "1B-c14-r1-d5", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 5", categorie: "standaard" },
  { id: "1B-c14-r1-d6", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 6", categorie: "standaard" },
  { id: "1B-c14-r1-d7", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 7", categorie: "standaard" },
  { id: "1B-c14-r1-d8", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 8", categorie: "standaard" },
  { id: "1B-c14-r1-d9", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 9", categorie: "standaard" },
  { id: "1B-c14-r1-d10", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 10", categorie: "standaard" },
  { id: "1B-c14-r1-d11", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 11", categorie: "standaard" },
  { id: "1B-c14-r1-d12", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 12", categorie: "standaard" },
  { id: "1B-c14-r1-d13", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 13", categorie: "standaard" },
  { id: "1B-c14-r1-d14", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 14", categorie: "standaard" },
  { id: "1B-c14-r1-d15", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 15", categorie: "standaard" },
  { id: "1B-c14-r1-d16", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 16", categorie: "standaard" },
  { id: "1B-c14-r1-d17", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 17", categorie: "standaard" },
  { id: "1B-c14-r1-d18", rubricId: "1B-c14-r1", omschrijving: "Leerwandelingen & uitstappen 18", categorie: "standaard" },
  { id: "1B-c14-r1-d19", rubricId: "1B-c14-r1", omschrijving: "Klasreis 1", categorie: "standaard" },
  { id: "1B-c14-r1-d20", rubricId: "1B-c14-r1", omschrijving: "Klasreis 2", categorie: "standaard" },
  { id: "1B-c15-r1-d1", rubricId: "1B-c15-r1", omschrijving: "Toonmoment 1", categorie: "standaard" },
  { id: "1B-c15-r1-d2", rubricId: "1B-c15-r1", omschrijving: "Toonmoment 2", categorie: "standaard" },
  { id: "1B-c15-r1-d3", rubricId: "1B-c15-r1", omschrijving: "Toonmoment 3", categorie: "standaard" },
  { id: "1B-c15-r1-d4", rubricId: "1B-c15-r1", omschrijving: "Toonmoment 4", categorie: "standaard" },
  { id: "1B-c15-r1-d5", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 1", categorie: "standaard" },
  { id: "1B-c15-r1-d6", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 2", categorie: "standaard" },
  { id: "1B-c15-r1-d7", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 3", categorie: "standaard" },
  { id: "1B-c15-r1-d8", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 4", categorie: "standaard" },
  { id: "1B-c15-r1-d9", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 5", categorie: "standaard" },
  { id: "1B-c15-r1-d10", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 6", categorie: "standaard" },
  { id: "1B-c15-r1-d11", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 7", categorie: "standaard" },
  { id: "1B-c15-r1-d12", rubricId: "1B-c15-r1", omschrijving: "Leerlingenseminars 8", categorie: "standaard" },
  { id: "1B-c15-r1-d13", rubricId: "1B-c15-r1", omschrijving: "Externe seminars 1", categorie: "standaard" },
  { id: "1B-c15-r1-d14", rubricId: "1B-c15-r1", omschrijving: "Externe seminars 2", categorie: "standaard" },
  { id: "1B-c15-r1-d15", rubricId: "1B-c15-r1", omschrijving: "Externe seminars 3", categorie: "standaard" },
  { id: "1B-c15-r1-d16", rubricId: "1B-c15-r1", omschrijving: "Externe seminars 4", categorie: "standaard" },
  { id: "1B-c15-r1-d17", rubricId: "1B-c15-r1", omschrijving: "Externe seminars 5", categorie: "standaard" },
  { id: "1B-c15-r1-d18", rubricId: "1B-c15-r1", omschrijving: "Externe seminars 6", categorie: "standaard" },
  { id: "1B-c16-r1-d1", rubricId: "1B-c16-r1", omschrijving: "Gezondheid 1", categorie: "standaard" },
  { id: "1B-c16-r1-d2", rubricId: "1B-c16-r1", omschrijving: "Gezondheid 2", categorie: "standaard" },
  { id: "1B-c16-r1-d3", rubricId: "1B-c16-r1", omschrijving: "Gezondheid 3", categorie: "standaard" },
  { id: "1B-c16-r1-d4", rubricId: "1B-c16-r1", omschrijving: "Gezondheid - EHBO", categorie: "standaard" },
  { id: "1B-c16-r1-d5", rubricId: "1B-c16-r1", omschrijving: "Mentale gezondheid 1", categorie: "standaard" },
  { id: "1B-c16-r1-d6", rubricId: "1B-c16-r1", omschrijving: "Mentale gezondheid 2", categorie: "standaard" },
  { id: "1B-c16-r1-d7", rubricId: "1B-c16-r1", omschrijving: "Gezonde levensstijl 1", categorie: "standaard" },
  { id: "1B-c16-r1-d8", rubricId: "1B-c16-r1", omschrijving: "Gezonde levensstijl 2", categorie: "standaard" },
  { id: "1B-c16-r1-d9", rubricId: "1B-c16-r1", omschrijving: "Gezonde levensstijl 3", categorie: "standaard" },
  { id: "1B-c16-r1-d10", rubricId: "1B-c16-r1", omschrijving: "Gezonde levensstijl 4", categorie: "standaard" },
  { id: "1B-c16-r1-d11", rubricId: "1B-c16-r1", omschrijving: "Individuele sporten 1", categorie: "standaard" },
  { id: "1B-c16-r1-d12", rubricId: "1B-c16-r1", omschrijving: "Individuele sporten 2", categorie: "standaard" },
  { id: "1B-c16-r1-d13", rubricId: "1B-c16-r1", omschrijving: "Individuele sporten 3", categorie: "standaard" },
  { id: "1B-c16-r1-d14", rubricId: "1B-c16-r1", omschrijving: "Individuele sporten 4", categorie: "standaard" },
  { id: "1B-c16-r1-d15", rubricId: "1B-c16-r1", omschrijving: "Interactieve beweging 1", categorie: "standaard" },
  { id: "1B-c16-r1-d16", rubricId: "1B-c16-r1", omschrijving: "Interactieve beweging 2", categorie: "standaard" },
  { id: "1B-c16-r1-d17", rubricId: "1B-c16-r1", omschrijving: "Interactieve beweging 3", categorie: "standaard" },
  { id: "1B-c16-r1-d18", rubricId: "1B-c16-r1", omschrijving: "Interactieve beweging 4", categorie: "standaard" },
  { id: "1B-c16-r1-d19", rubricId: "1B-c16-r1", omschrijving: "Ritmisch expressieve beweging 1", categorie: "standaard" },
  { id: "1B-c16-r1-d20", rubricId: "1B-c16-r1", omschrijving: "Ritmisch expressieve beweging 2", categorie: "standaard" },
  { id: "1B-c16-r1-d21", rubricId: "1B-c16-r1", omschrijving: "Ritmisch expressieve beweging 3", categorie: "standaard" },
  { id: "1B-c16-r1-d22", rubricId: "1B-c16-r1", omschrijving: "Ritmisch expressieve beweging 4", categorie: "standaard" },
  { id: "1B-c17-r1-d1", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 1", categorie: "standaard" },
  { id: "1B-c17-r1-d2", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 2", categorie: "standaard" },
  { id: "1B-c17-r1-d3", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 3", categorie: "standaard" },
  { id: "1B-c17-r1-d4", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 4", categorie: "standaard" },
  { id: "1B-c17-r1-d5", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 5", categorie: "standaard" },
  { id: "1B-c17-r1-d6", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 6", categorie: "standaard" },
  { id: "1B-c17-r1-d7", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 7", categorie: "standaard" },
  { id: "1B-c17-r1-d8", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 8", categorie: "standaard" },
  { id: "1B-c17-r1-d9", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 9", categorie: "standaard" },
  { id: "1B-c17-r1-d10", rubricId: "1B-c17-r1", omschrijving: "Vrij initiatief buiten de lijntjes 10", categorie: "standaard" },
];
