// AUTO-GEGENEREERD via scripts/extract_badges.py
// uit docs/reference/deelevaluaties_alle-graden-2.xlsx — niet met de hand aanpassen.
import type { CursusRuw, BadgeRuw } from "./curriculum";

export const cursussen2A: CursusRuw[] = [
  { id: "2A-planning-en-reflectie", stroom: "2A", naam: "Planning en reflectie", volgorde: 0 },
  { id: "2A-klasraad", stroom: "2A", naam: "Klasraad", volgorde: 1 },
  { id: "2A-burgerschap", stroom: "2A", naam: "Burgerschap", volgorde: 2 },
  { id: "2A-focusateliers-vrije-ateliers", stroom: "2A", naam: "Focusateliers & vrije ateliers", volgorde: 3 },
  { id: "2A-kring", stroom: "2A", naam: "Kring", volgorde: 4 },
  { id: "2A-actuaronde", stroom: "2A", naam: "Actuaronde", volgorde: 5 },
  { id: "2A-vrije-tekst", stroom: "2A", naam: "Vrije Tekst", volgorde: 6 },
  { id: "2A-boekenronde", stroom: "2A", naam: "Boekenronde", volgorde: 7 },
  { id: "2A-communicatie", stroom: "2A", naam: "Communicatie", volgorde: 8 },
  { id: "2A-onderzoek", stroom: "2A", naam: "Onderzoek", volgorde: 9 },
  { id: "2A-klaskas", stroom: "2A", naam: "Klaskas", volgorde: 10 },
  { id: "2A-levende-wiskunde", stroom: "2A", naam: "Levende Wiskunde", volgorde: 11 },
  { id: "2A-cultuur", stroom: "2A", naam: "Cultuur", volgorde: 12 },
  { id: "2A-exploratie", stroom: "2A", naam: "Exploratie", volgorde: 13 },
  { id: "2A-toonmoment", stroom: "2A", naam: "Toonmoment", volgorde: 14 },
  { id: "2A-welzijn", stroom: "2A", naam: "Welzijn", volgorde: 15 },
  { id: "2A-ervaringsweek", stroom: "2A", naam: "Ervaringsweek", volgorde: 16 },
  { id: "2A-vrij-initiatief-buiten-de-lijntjes", stroom: "2A", naam: "Vrij initiatief buiten de lijntjes", volgorde: 17 },
];

export const badges2A: BadgeRuw[] = [
  { id: "2A-planning-en-reflectie-d1", cursusId: "2A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-planning-en-reflectie-d2", cursusId: "2A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-planning-en-reflectie-d3", cursusId: "2A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-planning-en-reflectie-d4", cursusId: "2A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-planning-en-reflectie-d5", cursusId: "2A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-planning-en-reflectie-d6", cursusId: "2A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-klasraad-d1", cursusId: "2A-klasraad", groep: "Voorzitter", omschrijving: "Voorzitter 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-klasraad-d2", cursusId: "2A-klasraad", groep: "Voorzitter", omschrijving: "Voorzitter 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-klasraad-d3", cursusId: "2A-klasraad", groep: "Secretaris", omschrijving: "Secretaris 1", volgorde: 2, categorie: "standaard" },
  { id: "2A-klasraad-d4", cursusId: "2A-klasraad", groep: "Secretaris", omschrijving: "Secretaris 2", volgorde: 3, categorie: "standaard" },
  { id: "2A-klasraad-d5", cursusId: "2A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 1", volgorde: 4, categorie: "standaard" },
  { id: "2A-klasraad-d6", cursusId: "2A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 2", volgorde: 5, categorie: "standaard" },
  { id: "2A-klasraad-d7", cursusId: "2A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 3", volgorde: 6, categorie: "standaard" },
  { id: "2A-klasraad-d8", cursusId: "2A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 4", volgorde: 7, categorie: "standaard" },
  { id: "2A-klasraad-d9", cursusId: "2A-klasraad", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 5", volgorde: 8, categorie: "standaard" },
  { id: "2A-klasraad-d10", cursusId: "2A-klasraad", groep: "Vestigingsraad/Keerpuntraad/Leerlingenraad", omschrijving: "Vestigingsraad/Keerpuntraad/Leerlingenraad", volgorde: 9, categorie: "standaard" },
  { id: "2A-burgerschap-d1", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-burgerschap-d2", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-burgerschap-d3", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-burgerschap-d4", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-burgerschap-d5", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-burgerschap-d6", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-burgerschap-d7", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 7", volgorde: 6, categorie: "standaard" },
  { id: "2A-burgerschap-d8", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 8", volgorde: 7, categorie: "standaard" },
  { id: "2A-burgerschap-d9", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 9", volgorde: 8, categorie: "standaard" },
  { id: "2A-burgerschap-d10", cursusId: "2A-burgerschap", groep: "Intern burgerschap", omschrijving: "Intern burgerschap 10", volgorde: 9, categorie: "standaard" },
  { id: "2A-burgerschap-d11", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 1", volgorde: 10, categorie: "standaard" },
  { id: "2A-burgerschap-d12", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 2", volgorde: 11, categorie: "standaard" },
  { id: "2A-burgerschap-d13", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 3", volgorde: 12, categorie: "standaard" },
  { id: "2A-burgerschap-d14", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 4", volgorde: 13, categorie: "standaard" },
  { id: "2A-burgerschap-d15", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 5", volgorde: 14, categorie: "standaard" },
  { id: "2A-burgerschap-d16", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 6", volgorde: 15, categorie: "standaard" },
  { id: "2A-burgerschap-d17", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 7", volgorde: 16, categorie: "standaard" },
  { id: "2A-burgerschap-d18", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 8", volgorde: 17, categorie: "standaard" },
  { id: "2A-burgerschap-d19", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 9", volgorde: 18, categorie: "standaard" },
  { id: "2A-burgerschap-d20", cursusId: "2A-burgerschap", groep: "Extern burgerschap (per 2 lestijden)", omschrijving: "Extern burgerschap (per 2 lestijden) 10", volgorde: 19, categorie: "standaard" },
  { id: "2A-burgerschap-d21", cursusId: "2A-burgerschap", groep: "Werkstuk mensenrechten", omschrijving: "Werkstuk mensenrechten", volgorde: 20, categorie: "standaard" },
  { id: "2A-burgerschap-d22", cursusId: "2A-burgerschap", groep: "Bezoek democratisch orgaan", omschrijving: "Bezoek democratisch orgaan 1", volgorde: 21, categorie: "standaard" },
  { id: "2A-burgerschap-d23", cursusId: "2A-burgerschap", groep: "Bezoek democratisch orgaan", omschrijving: "Bezoek democratisch orgaan 2", volgorde: 22, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d1", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d2", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d3", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d4", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d5", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d6", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d7", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 7", volgorde: 6, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d8", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Deelname focusatelier", omschrijving: "Deelname focusatelier 8", volgorde: 7, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d9", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Natuur", omschrijving: "Vrije ateliers - Natuur", volgorde: 8, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d10", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Handvaardigheid, bouw & techniek", omschrijving: "Vrije ateliers - Handvaardigheid, bouw & techniek", volgorde: 9, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d11", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Kennis", omschrijving: "Vrije ateliers - Kennis", volgorde: 10, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d12", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Experimenten, wetenschappelijk onderzoek & innovatie", omschrijving: "Vrije ateliers - Experimenten, wetenschappelijk onderzoek & innovatie", volgorde: 11, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d13", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - ICT, digitale & moderne technieken", omschrijving: "Vrije ateliers - ICT, digitale & moderne technieken", volgorde: 12, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d14", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Expressie, creatie & ontwerp", omschrijving: "Vrije ateliers - Expressie, creatie & ontwerp", volgorde: 13, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d15", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Welzijn en andere", omschrijving: "Vrije ateliers - Welzijn en andere", volgorde: 14, categorie: "standaard" },
  { id: "2A-focusateliers-vrije-ateliers-d16", cursusId: "2A-focusateliers-vrije-ateliers", groep: "Vrije ateliers - Nadruk ligt op je focus of is gespreid over de domeinen (graadsbadge)", omschrijving: "Vrije ateliers - Nadruk ligt op je focus of is gespreid over de domeinen (graadsbadge)", volgorde: 15, categorie: "standaard" },
  { id: "2A-kring-d1", cursusId: "2A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-kring-d2", cursusId: "2A-kring", groep: "Voorzitter", omschrijving: "Voorzitter 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-kring-d3", cursusId: "2A-kring", groep: "Secretaris", omschrijving: "Secretaris 1", volgorde: 2, categorie: "standaard" },
  { id: "2A-kring-d4", cursusId: "2A-kring", groep: "Secretaris", omschrijving: "Secretaris 2", volgorde: 3, categorie: "standaard" },
  { id: "2A-kring-d5", cursusId: "2A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 1", volgorde: 4, categorie: "standaard" },
  { id: "2A-kring-d6", cursusId: "2A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 2", volgorde: 5, categorie: "standaard" },
  { id: "2A-kring-d7", cursusId: "2A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 3", volgorde: 6, categorie: "standaard" },
  { id: "2A-kring-d8", cursusId: "2A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 4", volgorde: 7, categorie: "standaard" },
  { id: "2A-kring-d9", cursusId: "2A-kring", groep: "Deelnemer (wekelijks)", omschrijving: "Deelnemer (wekelijks) 5", volgorde: 8, categorie: "standaard" },
  { id: "2A-kring-d10", cursusId: "2A-kring", groep: "Kring Frans", omschrijving: "Kring Frans", volgorde: 9, categorie: "standaard" },
  { id: "2A-kring-d11", cursusId: "2A-kring", groep: "Kring Engels", omschrijving: "Kring Engels", volgorde: 10, categorie: "standaard" },
  { id: "2A-actuaronde-d1", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-actuaronde-d2", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-actuaronde-d3", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-actuaronde-d4", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-actuaronde-d5", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-actuaronde-d6", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-actuaronde-d7", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 7", volgorde: 6, categorie: "standaard" },
  { id: "2A-actuaronde-d8", cursusId: "2A-actuaronde", groep: "Actuaronde Nederlands", omschrijving: "Actuaronde Nederlands 8", volgorde: 7, categorie: "standaard" },
  { id: "2A-actuaronde-d9", cursusId: "2A-actuaronde", groep: "Actuaronde Frans", omschrijving: "Actuaronde Frans 1", volgorde: 8, categorie: "standaard" },
  { id: "2A-actuaronde-d10", cursusId: "2A-actuaronde", groep: "Actuaronde Frans", omschrijving: "Actuaronde Frans 2", volgorde: 9, categorie: "standaard" },
  { id: "2A-actuaronde-d11", cursusId: "2A-actuaronde", groep: "Actuaronde Engels", omschrijving: "Actuaronde Engels 1", volgorde: 10, categorie: "standaard" },
  { id: "2A-actuaronde-d12", cursusId: "2A-actuaronde", groep: "Actuaronde Engels", omschrijving: "Actuaronde Engels 2", volgorde: 11, categorie: "standaard" },
  { id: "2A-vrije-tekst-d1", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-vrije-tekst-d2", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-vrije-tekst-d3", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-vrije-tekst-d4", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-vrije-tekst-d5", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-vrije-tekst-d6", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Nederlands", omschrijving: "Vrije tekst Nederlands 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-vrije-tekst-d7", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 1", volgorde: 6, categorie: "standaard" },
  { id: "2A-vrije-tekst-d8", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 2", volgorde: 7, categorie: "standaard" },
  { id: "2A-vrije-tekst-d9", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Frans", omschrijving: "Vrije tekst Frans 3", volgorde: 8, categorie: "standaard" },
  { id: "2A-vrije-tekst-d10", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 1", volgorde: 9, categorie: "standaard" },
  { id: "2A-vrije-tekst-d11", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 2", volgorde: 10, categorie: "standaard" },
  { id: "2A-vrije-tekst-d12", cursusId: "2A-vrije-tekst", groep: "Vrije tekst Engels", omschrijving: "Vrije tekst Engels 3", volgorde: 11, categorie: "standaard" },
  { id: "2A-boekenronde-d1", cursusId: "2A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-boekenronde-d2", cursusId: "2A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-boekenronde-d3", cursusId: "2A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-boekenronde-d4", cursusId: "2A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-boekenronde-d5", cursusId: "2A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-boekenronde-d6", cursusId: "2A-boekenronde", groep: "Boekenronde Nederlands", omschrijving: "Boekenronde Nederlands 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-boekenronde-d7", cursusId: "2A-boekenronde", groep: "Boekenronde Frans", omschrijving: "Boekenronde Frans 1", volgorde: 6, categorie: "standaard" },
  { id: "2A-boekenronde-d8", cursusId: "2A-boekenronde", groep: "Boekenronde Frans", omschrijving: "Boekenronde Frans 2", volgorde: 7, categorie: "standaard" },
  { id: "2A-boekenronde-d9", cursusId: "2A-boekenronde", groep: "Boekenronde Engels", omschrijving: "Boekenronde Engels 1", volgorde: 8, categorie: "standaard" },
  { id: "2A-boekenronde-d10", cursusId: "2A-boekenronde", groep: "Boekenronde Engels", omschrijving: "Boekenronde Engels 2", volgorde: 9, categorie: "standaard" },
  { id: "2A-communicatie-d1", cursusId: "2A-communicatie", groep: "Krant/Correspondentie publicatie Nederlands", omschrijving: "Krant/Correspondentie publicatie Nederlands", volgorde: 0, categorie: "standaard" },
  { id: "2A-communicatie-d2", cursusId: "2A-communicatie", groep: "Krant/Correspondentie publicatie Frans", omschrijving: "Krant/Correspondentie publicatie Frans", volgorde: 1, categorie: "standaard" },
  { id: "2A-communicatie-d3", cursusId: "2A-communicatie", groep: "Krant/Correspondentie publicatie Engels", omschrijving: "Krant/Correspondentie publicatie Engels", volgorde: 2, categorie: "standaard" },
  { id: "2A-communicatie-d4", cursusId: "2A-communicatie", groep: "Activiteit Keerpunt/extern", omschrijving: "Activiteit Keerpunt/extern 1", volgorde: 3, categorie: "standaard" },
  { id: "2A-communicatie-d5", cursusId: "2A-communicatie", groep: "Activiteit Keerpunt/extern", omschrijving: "Activiteit Keerpunt/extern 2", volgorde: 4, categorie: "standaard" },
  { id: "2A-communicatie-d6", cursusId: "2A-communicatie", groep: "Activiteit Keerpunt/extern Frans", omschrijving: "Activiteit Keerpunt/extern Frans", volgorde: 5, categorie: "standaard" },
  { id: "2A-communicatie-d7", cursusId: "2A-communicatie", groep: "Activiteit Keerpunt/extern Engels", omschrijving: "Activiteit Keerpunt/extern Engels", volgorde: 6, categorie: "standaard" },
  { id: "2A-onderzoek-d1", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-onderzoek-d2", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-onderzoek-d3", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-onderzoek-d4", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-onderzoek-d5", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-onderzoek-d6", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-onderzoek-d7", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 7", volgorde: 6, categorie: "standaard" },
  { id: "2A-onderzoek-d8", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 8", volgorde: 7, categorie: "standaard" },
  { id: "2A-onderzoek-d9", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 9", volgorde: 8, categorie: "standaard" },
  { id: "2A-onderzoek-d10", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 10", volgorde: 9, categorie: "standaard" },
  { id: "2A-onderzoek-d11", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 11", volgorde: 10, categorie: "standaard" },
  { id: "2A-onderzoek-d12", cursusId: "2A-onderzoek", groep: "Kwaliteitsvol onderzoek (individueel en coöperatief)", omschrijving: "Kwaliteitsvol onderzoek (individueel en coöperatief) 12", volgorde: 11, categorie: "standaard" },
  { id: "2A-onderzoek-d13", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen laboreeksen", omschrijving: "Exacte wetenschappen laboreeksen 1", volgorde: 12, categorie: "standaard" },
  { id: "2A-onderzoek-d14", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen laboreeksen", omschrijving: "Exacte wetenschappen laboreeksen 2", volgorde: 13, categorie: "standaard" },
  { id: "2A-onderzoek-d15", cursusId: "2A-onderzoek", groep: "Historisch - Algemene periodisering", omschrijving: "Historisch - Algemene periodisering", volgorde: 14, categorie: "standaard" },
  { id: "2A-onderzoek-d16", cursusId: "2A-onderzoek", groep: "Historisch - Niet-Westerse periodisering", omschrijving: "Historisch - Niet-Westerse periodisering", volgorde: 15, categorie: "standaard" },
  { id: "2A-onderzoek-d17", cursusId: "2A-onderzoek", groep: "Historisch - Historische beeldvorming", omschrijving: "Historisch - Historische beeldvorming", volgorde: 16, categorie: "standaard" },
  { id: "2A-onderzoek-d18", cursusId: "2A-onderzoek", groep: "Historisch - Evalueren van historische bronnen", omschrijving: "Historisch - Evalueren van historische bronnen", volgorde: 17, categorie: "standaard" },
  { id: "2A-onderzoek-d19", cursusId: "2A-onderzoek", groep: "Historisch - Middeleeuwen: politiek, sociaal, economisch, cultureel", omschrijving: "Historisch - Middeleeuwen: politiek, sociaal, economisch, cultureel", volgorde: 18, categorie: "standaard" },
  { id: "2A-onderzoek-d20", cursusId: "2A-onderzoek", groep: "Historisch - Vroegmoderne tijd: politiek, sociaal, economisch, cultureel", omschrijving: "Historisch - Vroegmoderne tijd: politiek, sociaal, economisch, cultureel", volgorde: 19, categorie: "standaard" },
  { id: "2A-onderzoek-d21", cursusId: "2A-onderzoek", groep: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", omschrijving: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", volgorde: 20, categorie: "standaard" },
  { id: "2A-onderzoek-d22", cursusId: "2A-onderzoek", groep: "Ruimtelijk - Demografische en economische processen & gevolgen", omschrijving: "Ruimtelijk - Demografische en economische processen & gevolgen", volgorde: 21, categorie: "standaard" },
  { id: "2A-onderzoek-d23", cursusId: "2A-onderzoek", groep: "Ruimtelijk - Evolutie en verandering", omschrijving: "Ruimtelijk - Evolutie en verandering", volgorde: 22, categorie: "standaard" },
  { id: "2A-onderzoek-d24", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen - PSE: atoommodel, chemische formules, stoffen en eigenschappen", omschrijving: "Exacte wetenschappen - PSE: atoommodel, chemische formules, stoffen en eigenschappen", volgorde: 23, categorie: "standaard" },
  { id: "2A-onderzoek-d25", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen - Krachten, energie, stralingen, elektriciteit", omschrijving: "Exacte wetenschappen - Krachten, energie, stralingen, elektriciteit", volgorde: 24, categorie: "standaard" },
  { id: "2A-onderzoek-d26", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen - Opbouw en functioneren van organismen", omschrijving: "Exacte wetenschappen - Opbouw en functioneren van organismen", volgorde: 25, categorie: "standaard" },
  { id: "2A-onderzoek-d27", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", omschrijving: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", volgorde: 26, categorie: "standaard" },
  { id: "2A-onderzoek-d28", cursusId: "2A-onderzoek", groep: "Exacte wetenschappen - Biotopen & ecosystemen", omschrijving: "Exacte wetenschappen - Biotopen & ecosystemen", volgorde: 27, categorie: "standaard" },
  { id: "2A-onderzoek-d29", cursusId: "2A-onderzoek", groep: "Techniek/technologie - Eigenschappen van materialen", omschrijving: "Techniek/technologie - Eigenschappen van materialen", volgorde: 28, categorie: "standaard" },
  { id: "2A-onderzoek-d30", cursusId: "2A-onderzoek", groep: "Techniek/technologie - Natuurlijke & technische systemen", omschrijving: "Techniek/technologie - Natuurlijke & technische systemen", volgorde: 29, categorie: "standaard" },
  { id: "2A-onderzoek-d31", cursusId: "2A-onderzoek", groep: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", omschrijving: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", volgorde: 30, categorie: "standaard" },
  { id: "2A-onderzoek-d32", cursusId: "2A-onderzoek", groep: "Duurzaamheid bij technische systemen", omschrijving: "Duurzaamheid bij technische systemen", volgorde: 31, categorie: "standaard" },
  { id: "2A-onderzoek-d33", cursusId: "2A-onderzoek", groep: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", omschrijving: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", volgorde: 32, categorie: "standaard" },
  { id: "2A-onderzoek-d34", cursusId: "2A-onderzoek", groep: "Economie - Gezinsbudget", omschrijving: "Economie - Gezinsbudget", volgorde: 33, categorie: "standaard" },
  { id: "2A-onderzoek-d35", cursusId: "2A-onderzoek", groep: "Economie - Maatschappelijke thema’s", omschrijving: "Economie - Maatschappelijke thema’s", volgorde: 34, categorie: "standaard" },
  { id: "2A-klaskas-d1", cursusId: "2A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-klaskas-d2", cursusId: "2A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-klaskas-d3", cursusId: "2A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-klaskas-d4", cursusId: "2A-klaskas", groep: "Klaskas projecten", omschrijving: "Klaskas projecten 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-klaskas-d5", cursusId: "2A-klaskas", groep: "Klaskas - Economisch onderzoek over productie en consumptie", omschrijving: "Klaskas - Economisch onderzoek over productie en consumptie", volgorde: 4, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d1", cursusId: "2A-levende-wiskunde", groep: "Wiskundelessen gegeven", omschrijving: "Wiskundelessen gegeven 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d2", cursusId: "2A-levende-wiskunde", groep: "Wiskundelessen gegeven", omschrijving: "Wiskundelessen gegeven 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d3", cursusId: "2A-levende-wiskunde", groep: "Wiskundig onderzoek: statistiek", omschrijving: "Wiskundig onderzoek: statistiek", volgorde: 2, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d4", cursusId: "2A-levende-wiskunde", groep: "Wiskundig onderzoek: patronen, algoritmes, AI", omschrijving: "Wiskundig onderzoek: patronen, algoritmes, AI", volgorde: 3, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d5", cursusId: "2A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 1", volgorde: 4, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d6", cursusId: "2A-levende-wiskunde", groep: "Wiskundig onderzoek", omschrijving: "Wiskundig onderzoek 2", volgorde: 5, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d7", cursusId: "2A-levende-wiskunde", groep: "Getallenleer - Reële getallen op de getallenas (graadsbadge)", omschrijving: "Getallenleer - Reële getallen op de getallenas (graadsbadge)", volgorde: 6, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d8", cursusId: "2A-levende-wiskunde", groep: "Getallenleer - Rekenen met reële getallen (graadsbadge)", omschrijving: "Getallenleer - Rekenen met reële getallen (graadsbadge)", volgorde: 7, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d9", cursusId: "2A-levende-wiskunde", groep: "Meetkunde - Ligging van punten, rechten en vlakken (graadsbadge)", omschrijving: "Meetkunde - Ligging van punten, rechten en vlakken (graadsbadge)", volgorde: 8, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d10", cursusId: "2A-levende-wiskunde", groep: "Meetkunde - Gelijkvormigheid (graadsbadge)", omschrijving: "Meetkunde - Gelijkvormigheid (graadsbadge)", volgorde: 9, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d11", cursusId: "2A-levende-wiskunde", groep: "Meetkunde - Stelling van Pythagoras (graadsbadge)", omschrijving: "Meetkunde - Stelling van Pythagoras (graadsbadge)", volgorde: 10, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d12", cursusId: "2A-levende-wiskunde", groep: "Meetkunde - Goniometrische getallen in rechthoekige driehoeken (graadsbadge)", omschrijving: "Meetkunde - Goniometrische getallen in rechthoekige driehoeken (graadsbadge)", volgorde: 11, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d13", cursusId: "2A-levende-wiskunde", groep: "Meetkunde - Vectoren (graadsbadge)", omschrijving: "Meetkunde - Vectoren (graadsbadge)", volgorde: 12, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d14", cursusId: "2A-levende-wiskunde", groep: "Algebra en analyse - Eerstegraadsformules, vergelijkingen en ongelijkheden (graadsbadge)", omschrijving: "Algebra en analyse - Eerstegraadsformules, vergelijkingen en ongelijkheden (graadsbadge)", volgorde: 13, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d15", cursusId: "2A-levende-wiskunde", groep: "Algebra en analyse - Functies (graadsbadge)", omschrijving: "Algebra en analyse - Functies (graadsbadge)", volgorde: 14, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d16", cursusId: "2A-levende-wiskunde", groep: "Algebra en analyse - Eerstegraadsfuncties (graadsbadge)", omschrijving: "Algebra en analyse - Eerstegraadsfuncties (graadsbadge)", volgorde: 15, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d17", cursusId: "2A-levende-wiskunde", groep: "Algebra en analyse - Tweedegraadsfuncties (graadsbadge)", omschrijving: "Algebra en analyse - Tweedegraadsfuncties (graadsbadge)", volgorde: 16, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d18", cursusId: "2A-levende-wiskunde", groep: "Algebra en analyse - Stelsel van 2 vergelijkingen (graadsbadge)", omschrijving: "Algebra en analyse - Stelsel van 2 vergelijkingen (graadsbadge)", volgorde: 17, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d19", cursusId: "2A-levende-wiskunde", groep: "Telproblemen en Statistiek - Telproblemen (graadsbadge)", omschrijving: "Telproblemen en Statistiek - Telproblemen (graadsbadge)", volgorde: 18, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d20", cursusId: "2A-levende-wiskunde", groep: "Telproblemen en Statistiek - Data en Statistiek (graadsbadge)", omschrijving: "Telproblemen en Statistiek - Data en Statistiek (graadsbadge)", volgorde: 19, categorie: "standaard" },
  { id: "2A-levende-wiskunde-d21", cursusId: "2A-levende-wiskunde", groep: "Logica (graadsbadge)", omschrijving: "Logica (graadsbadge)", volgorde: 20, categorie: "standaard" },
  { id: "2A-cultuur-d1", cursusId: "2A-cultuur", groep: "Kunstbeschouwing - Kunst in prehistorie", omschrijving: "Kunstbeschouwing - Kunst in prehistorie", volgorde: 0, categorie: "standaard" },
  { id: "2A-cultuur-d2", cursusId: "2A-cultuur", groep: "Kunstbeschouwing - Kunst in Middeleeuwen", omschrijving: "Kunstbeschouwing - Kunst in Middeleeuwen", volgorde: 1, categorie: "standaard" },
  { id: "2A-cultuur-d3", cursusId: "2A-cultuur", groep: "Kunstbeschouwing - Kunst in Vroegmoderne Tijd", omschrijving: "Kunstbeschouwing - Kunst in Vroegmoderne Tijd", volgorde: 2, categorie: "standaard" },
  { id: "2A-cultuur-d4", cursusId: "2A-cultuur", groep: "Kunstbeschouwing - Niet-Westerse kunst", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 1", volgorde: 3, categorie: "standaard" },
  { id: "2A-cultuur-d5", cursusId: "2A-cultuur", groep: "Kunstbeschouwing - Niet-Westerse kunst", omschrijving: "Kunstbeschouwing - Niet-Westerse kunst 2", volgorde: 4, categorie: "standaard" },
  { id: "2A-cultuur-d6", cursusId: "2A-cultuur", groep: "Kunstbeschouwing - Onderwerp naar keuze", omschrijving: "Kunstbeschouwing - Onderwerp naar keuze", volgorde: 5, categorie: "standaard" },
  { id: "2A-cultuur-d7", cursusId: "2A-cultuur", groep: "Vrije expressie - toegepaste kunsten (design en ambachten)", omschrijving: "Vrije expressie - toegepaste kunsten (design en ambachten)", volgorde: 6, categorie: "standaard" },
  { id: "2A-cultuur-d8", cursusId: "2A-cultuur", groep: "Vrije expressie - beeldende kunsten", omschrijving: "Vrije expressie - beeldende kunsten", volgorde: 7, categorie: "standaard" },
  { id: "2A-cultuur-d9", cursusId: "2A-cultuur", groep: "Vrije expressie - podiumkunsten", omschrijving: "Vrije expressie - podiumkunsten", volgorde: 8, categorie: "standaard" },
  { id: "2A-cultuur-d10", cursusId: "2A-cultuur", groep: "Vrije expressie - muziek", omschrijving: "Vrije expressie - muziek", volgorde: 9, categorie: "standaard" },
  { id: "2A-cultuur-d11", cursusId: "2A-cultuur", groep: "Vrije expressie - media en audiovisuele kunsten", omschrijving: "Vrije expressie - media en audiovisuele kunsten", volgorde: 10, categorie: "standaard" },
  { id: "2A-cultuur-d12", cursusId: "2A-cultuur", groep: "Vrije expressie - interdisciplinaire en hybride kunsten", omschrijving: "Vrije expressie - interdisciplinaire en hybride kunsten", volgorde: 11, categorie: "standaard" },
  { id: "2A-cultuur-d13", cursusId: "2A-cultuur", groep: "Vrije expressie - letterkunde (literaire kunsten)", omschrijving: "Vrije expressie - letterkunde (literaire kunsten)", volgorde: 12, categorie: "standaard" },
  { id: "2A-exploratie-d1", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-exploratie-d2", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-exploratie-d3", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-exploratie-d4", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-exploratie-d5", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 5", volgorde: 4, categorie: "standaard" },
  { id: "2A-exploratie-d6", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 6", volgorde: 5, categorie: "standaard" },
  { id: "2A-exploratie-d7", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 7", volgorde: 6, categorie: "standaard" },
  { id: "2A-exploratie-d8", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 8", volgorde: 7, categorie: "standaard" },
  { id: "2A-exploratie-d9", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 9", volgorde: 8, categorie: "standaard" },
  { id: "2A-exploratie-d10", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 10", volgorde: 9, categorie: "standaard" },
  { id: "2A-exploratie-d11", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 11", volgorde: 10, categorie: "standaard" },
  { id: "2A-exploratie-d12", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 12", volgorde: 11, categorie: "standaard" },
  { id: "2A-exploratie-d13", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 13", volgorde: 12, categorie: "standaard" },
  { id: "2A-exploratie-d14", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 14", volgorde: 13, categorie: "standaard" },
  { id: "2A-exploratie-d15", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 15", volgorde: 14, categorie: "standaard" },
  { id: "2A-exploratie-d16", cursusId: "2A-exploratie", groep: "Leerwandelingen & uitstappen", omschrijving: "Leerwandelingen & uitstappen 16", volgorde: 15, categorie: "standaard" },
  { id: "2A-exploratie-d17", cursusId: "2A-exploratie", groep: "Klasreis", omschrijving: "Klasreis 1", volgorde: 16, categorie: "standaard" },
  { id: "2A-exploratie-d18", cursusId: "2A-exploratie", groep: "Klasreis", omschrijving: "Klasreis 2", volgorde: 17, categorie: "standaard" },
  { id: "2A-toonmoment-d1", cursusId: "2A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 1", volgorde: 0, categorie: "standaard" },
  { id: "2A-toonmoment-d2", cursusId: "2A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 2", volgorde: 1, categorie: "standaard" },
  { id: "2A-toonmoment-d3", cursusId: "2A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 3", volgorde: 2, categorie: "standaard" },
  { id: "2A-toonmoment-d4", cursusId: "2A-toonmoment", groep: "Toonmoment", omschrijving: "Toonmoment 4", volgorde: 3, categorie: "standaard" },
  { id: "2A-toonmoment-d5", cursusId: "2A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 1", volgorde: 4, categorie: "standaard" },
  { id: "2A-toonmoment-d6", cursusId: "2A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 2", volgorde: 5, categorie: "standaard" },
  { id: "2A-toonmoment-d7", cursusId: "2A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 3", volgorde: 6, categorie: "standaard" },
  { id: "2A-toonmoment-d8", cursusId: "2A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 4", volgorde: 7, categorie: "standaard" },
  { id: "2A-toonmoment-d9", cursusId: "2A-toonmoment", groep: "Leerlingenseminars", omschrijving: "Leerlingenseminars 5", volgorde: 8, categorie: "standaard" },
  { id: "2A-toonmoment-d10", cursusId: "2A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 1", volgorde: 9, categorie: "standaard" },
  { id: "2A-toonmoment-d11", cursusId: "2A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 2", volgorde: 10, categorie: "standaard" },
  { id: "2A-toonmoment-d12", cursusId: "2A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 3", volgorde: 11, categorie: "standaard" },
  { id: "2A-toonmoment-d13", cursusId: "2A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 4", volgorde: 12, categorie: "standaard" },
  { id: "2A-toonmoment-d14", cursusId: "2A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 5", volgorde: 13, categorie: "standaard" },
  { id: "2A-toonmoment-d15", cursusId: "2A-toonmoment", groep: "Externe seminars", omschrijving: "Externe seminars 6", volgorde: 14, categorie: "standaard" },
  { id: "2A-welzijn-d1", cursusId: "2A-welzijn", groep: "Privacy, auteursrecht, portretrecht, netiquette", omschrijving: "Privacy, auteursrecht, portretrecht, netiquette", volgorde: 0, categorie: "standaard" },
  { id: "2A-welzijn-d2", cursusId: "2A-welzijn", groep: "Digitale identiteit beheren", omschrijving: "Digitale identiteit beheren", volgorde: 1, categorie: "standaard" },
  { id: "2A-welzijn-d3", cursusId: "2A-welzijn", groep: "Vooroordelen, machtsmisbruik, groepsdruk in de digitale wereld", omschrijving: "Vooroordelen, machtsmisbruik, groepsdruk in de digitale wereld", volgorde: 2, categorie: "standaard" },
  { id: "2A-welzijn-d4", cursusId: "2A-welzijn", groep: "Veiligheid - Infrastructuur, gereedschappen en materialen", omschrijving: "Veiligheid - Infrastructuur, gereedschappen en materialen", volgorde: 3, categorie: "standaard" },
  { id: "2A-welzijn-d5", cursusId: "2A-welzijn", groep: "Veiligheid - Noodsituaties", omschrijving: "Veiligheid - Noodsituaties", volgorde: 4, categorie: "standaard" },
  { id: "2A-welzijn-d6", cursusId: "2A-welzijn", groep: "Veiligheid - Gebruik van openbaar vervoer", omschrijving: "Veiligheid - Gebruik van openbaar vervoer", volgorde: 5, categorie: "standaard" },
  { id: "2A-welzijn-d7", cursusId: "2A-welzijn", groep: "Respectvol gedrag, verbaal en non-verbaal", omschrijving: "Respectvol gedrag, verbaal en non-verbaal", volgorde: 6, categorie: "standaard" },
  { id: "2A-welzijn-d8", cursusId: "2A-welzijn", groep: "Gezondheid - Thema 1", omschrijving: "Gezondheid - Thema 1", volgorde: 7, categorie: "standaard" },
  { id: "2A-welzijn-d9", cursusId: "2A-welzijn", groep: "Gezondheid - Thema 2", omschrijving: "Gezondheid - Thema 2", volgorde: 8, categorie: "standaard" },
  { id: "2A-welzijn-d10", cursusId: "2A-welzijn", groep: "Gezondheid - Hulpverlenersorganisaties", omschrijving: "Gezondheid - Hulpverlenersorganisaties", volgorde: 9, categorie: "standaard" },
  { id: "2A-welzijn-d11", cursusId: "2A-welzijn", groep: "Gezondheid - EHBO", omschrijving: "Gezondheid - EHBO", volgorde: 10, categorie: "standaard" },
  { id: "2A-welzijn-d12", cursusId: "2A-welzijn", groep: "Mentale gezondheid - Thema 1", omschrijving: "Mentale gezondheid - Thema 1", volgorde: 11, categorie: "standaard" },
  { id: "2A-welzijn-d13", cursusId: "2A-welzijn", groep: "Mentale gezondheid - Hulpverleners en hulporganisaties", omschrijving: "Mentale gezondheid - Hulpverleners en hulporganisaties", volgorde: 12, categorie: "standaard" },
  { id: "2A-welzijn-d14", cursusId: "2A-welzijn", groep: "Gezonde levensstijl - Voeding", omschrijving: "Gezonde levensstijl - Voeding", volgorde: 13, categorie: "standaard" },
  { id: "2A-welzijn-d15", cursusId: "2A-welzijn", groep: "Gezonde levensstijl - Beweging", omschrijving: "Gezonde levensstijl - Beweging", volgorde: 14, categorie: "standaard" },
  { id: "2A-welzijn-d16", cursusId: "2A-welzijn", groep: "Gezonde levensstijl - Hygiëne", omschrijving: "Gezonde levensstijl - Hygiëne", volgorde: 15, categorie: "standaard" },
  { id: "2A-welzijn-d17", cursusId: "2A-welzijn", groep: "Gezonde levensstijl - Ergonomie", omschrijving: "Gezonde levensstijl - Ergonomie", volgorde: 16, categorie: "standaard" },
  { id: "2A-welzijn-d18", cursusId: "2A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 1", volgorde: 17, categorie: "standaard" },
  { id: "2A-welzijn-d19", cursusId: "2A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 2", volgorde: 18, categorie: "standaard" },
  { id: "2A-welzijn-d20", cursusId: "2A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 3", volgorde: 19, categorie: "standaard" },
  { id: "2A-welzijn-d21", cursusId: "2A-welzijn", groep: "Individuele sporten", omschrijving: "Individuele sporten 4", volgorde: 20, categorie: "standaard" },
  { id: "2A-welzijn-d22", cursusId: "2A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 1", volgorde: 21, categorie: "standaard" },
  { id: "2A-welzijn-d23", cursusId: "2A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 2", volgorde: 22, categorie: "standaard" },
  { id: "2A-welzijn-d24", cursusId: "2A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 3", volgorde: 23, categorie: "standaard" },
  { id: "2A-welzijn-d25", cursusId: "2A-welzijn", groep: "Interactieve beweging", omschrijving: "Interactieve beweging 4", volgorde: 24, categorie: "standaard" },
  { id: "2A-welzijn-d26", cursusId: "2A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 1", volgorde: 25, categorie: "standaard" },
  { id: "2A-welzijn-d27", cursusId: "2A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 2", volgorde: 26, categorie: "standaard" },
  { id: "2A-welzijn-d28", cursusId: "2A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 3", volgorde: 27, categorie: "standaard" },
  { id: "2A-welzijn-d29", cursusId: "2A-welzijn", groep: "Ritmisch expressieve beweging", omschrijving: "Ritmisch expressieve beweging 4", volgorde: 28, categorie: "standaard" },
  { id: "2A-ervaringsweek-d1", cursusId: "2A-ervaringsweek", groep: "Ervaringsweek 3e jaar", omschrijving: "Ervaringsweek 3e jaar", volgorde: 0, categorie: "standaard" },
  { id: "2A-ervaringsweek-d2", cursusId: "2A-ervaringsweek", groep: "Ervaringsweek 4e jaar", omschrijving: "Ervaringsweek 4e jaar", volgorde: 1, categorie: "standaard" },
  { id: "2A-vrij-initiatief-buiten-de-lijntjes-d1", cursusId: "2A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes", volgorde: 0, categorie: "standaard" },
];
