// AUTO-GEGENEREERD via scripts/extract_badgeboeken.py uit "2025 Badgeboek … (1B)".
// Niet met de hand herschikken; regenereer bij een nieuwe badgeboekversie.
import type { Cursus, Leerdoel, Rubric } from "./types";

export const cursussen1B: Cursus[] = [
  { id: "1B-c1", stroom: "1B", naam: "Basisvaardigheden" },
  { id: "1B-c2", stroom: "1B", naam: "Planning en reflectie" },
  { id: "1B-c3", stroom: "1B", naam: "Klasraad" },
  { id: "1B-c4", stroom: "1B", naam: "Burgerschap" },
  { id: "1B-c5", stroom: "1B", naam: "Ateliers" },
  { id: "1B-c6", stroom: "1B", naam: "Kring" },
  { id: "1B-c7", stroom: "1B", naam: "Actua" },
  { id: "1B-c8", stroom: "1B", naam: "Vrije tekst" },
  { id: "1B-c9", stroom: "1B", naam: "Boekenronde" },
  { id: "1B-c10", stroom: "1B", naam: "Communicatie" },
  { id: "1B-c11", stroom: "1B", naam: "Onderzoek" },
  { id: "1B-c12", stroom: "1B", naam: "Klaskas" },
  { id: "1B-c13", stroom: "1B", naam: "Levende Wiskunde" },
  { id: "1B-c14", stroom: "1B", naam: "Cultuur" },
  { id: "1B-c15", stroom: "1B", naam: "Exploratie" },
  { id: "1B-c16", stroom: "1B", naam: "Toonmoment" },
  { id: "1B-c17", stroom: "1B", naam: "Welzijn" },
];

export const rubrics1B: Rubric[] = [
  { id: "1B-c1-r1", cursusId: "1B-c1", naam: "Algemeen welbevinden" },
  { id: "1B-c1-r2", cursusId: "1B-c1", naam: "Intrinsieke motivatie" },
  { id: "1B-c1-r3", cursusId: "1B-c1", naam: "Zelfsturing" },
  { id: "1B-c1-r4", cursusId: "1B-c1", naam: "Planning" },
  { id: "1B-c1-r5", cursusId: "1B-c1", naam: "Afwerking" },
  { id: "1B-c1-r6", cursusId: "1B-c1", naam: "Reflectie" },
  { id: "1B-c1-r7", cursusId: "1B-c1", naam: "Coöperatie" },
  { id: "1B-c1-r8", cursusId: "1B-c1", naam: "Betrokkenheid" },
  { id: "1B-c2-r1", cursusId: "1B-c2", naam: "Planning" },
  { id: "1B-c2-r2", cursusId: "1B-c2", naam: "Reflectie" },
  { id: "1B-c3-r1", cursusId: "1B-c3", naam: "Rollen" },
  { id: "1B-c3-r2", cursusId: "1B-c3", naam: "Deelnemer" },
  { id: "1B-c4-r1", cursusId: "1B-c4", naam: "Burgerschap intern" },
  { id: "1B-c4-r2", cursusId: "1B-c4", naam: "Burgerschap extern" },
  { id: "1B-c5-r1", cursusId: "1B-c5", naam: "Ateliers" },
  { id: "1B-c6-r1", cursusId: "1B-c6", naam: "Rollen" },
  { id: "1B-c6-r2", cursusId: "1B-c6", naam: "Deelnemer" },
  { id: "1B-c7-r1", cursusId: "1B-c7", naam: "Actuaronde" },
  { id: "1B-c8-r1", cursusId: "1B-c8", naam: "VRIJE TEKST schrijfproces" },
  { id: "1B-c9-r1", cursusId: "1B-c9", naam: "Boekenronde" },
  { id: "1B-c10-r1", cursusId: "1B-c10", naam: "Klaskrant en correspondentie" },
  { id: "1B-c10-r2", cursusId: "1B-c10", naam: "Activiteiten over de vestigingen heen, uitwisselingen en taalstages" },
  { id: "1B-c11-r1", cursusId: "1B-c11", naam: "Individuele en coöperatieve onderzoeken: kerndoelen" },
  { id: "1B-c11-r2", cursusId: "1B-c11", naam: "Inzicht in de domeinen" },
  { id: "1B-c12-r1", cursusId: "1B-c12", naam: "Klaskas" },
  { id: "1B-c13-r1", cursusId: "1B-c13", naam: "Een wiskundige kijk op de wereld" },
  { id: "1B-c13-r2", cursusId: "1B-c13", naam: "Wiskundige onderzoeken" },
  { id: "1B-c13-r3", cursusId: "1B-c13", naam: "Inzicht en vaardigheden in wiskundige domeinen" },
  { id: "1B-c14-r1", cursusId: "1B-c14", naam: "Beschouwende opdracht" },
  { id: "1B-c14-r2", cursusId: "1B-c14", naam: "Vrije expressie" },
  { id: "1B-c15-r1", cursusId: "1B-c15", naam: "Leerwandeling of uitstap" },
  { id: "1B-c15-r2", cursusId: "1B-c15", naam: "Klasreis" },
  { id: "1B-c16-r1", cursusId: "1B-c16", naam: "Toonmomenten" },
  { id: "1B-c16-r2", cursusId: "1B-c16", naam: "Leerlingen seminaries" },
  { id: "1B-c16-r3", cursusId: "1B-c16", naam: "Externe seminaries" },
  { id: "1B-c17-r1", cursusId: "1B-c17", naam: "Gezondheid" },
  { id: "1B-c17-r2", cursusId: "1B-c17", naam: "Sport & beweging" },
];

export const leerdoelen1B: Leerdoel[] = [
  { id: "1B-c1-r1-d1", rubricId: "1B-c1-r1", omschrijving: "Je komt graag naar school.", categorie: "standaard", kleuren: { blauw: "Je geeft aan dat je altijd zeer graag naar school komt.", groen: "Je komt meestal graag naar school.", geel: "Je komt af en toe graag naar school.", rood: "Naar school komen is een hele opgave voor je en je vindt schoolgaan niet leuk." } },
  { id: "1B-c1-r1-d2", rubricId: "1B-c1-r1", omschrijving: "Je ervaart school als een veilige plaats.", categorie: "standaard", kleuren: { blauw: "Je ervaart school als een zeer veilige haven.", groen: "Je ervaart school doorgaans als een veilige omgeving.", geel: "Je ervaart school af en toe als een veilige omgeving.", rood: "Je ervaart school als een onveilige plek." } },
  { id: "1B-c1-r1-d3", rubricId: "1B-c1-r1", omschrijving: "Je voelt je gesteund door mentoren en/of peers.", categorie: "standaard", kleuren: { blauw: "Je ervaart in het algemeen een grote steun van mentoren en/of medeleerlingen.", groen: "Je ervaart doorgaans steun van mentoren en/of medeleerlingen. Slechts af en toe is er een situatie waardoor er eens geen steun ervaren wordt.", geel: "Je ervaart steun van mentoren en/of medeleerlingen maar je voelt je ook regelmatig niet gesteund in specifieke situaties.", rood: "Je voelt absoluut geen steun van mentoren en/of medeleerlingen. Je hebt altijd het gevoel er alleen voor te staan." } },
  { id: "1B-c1-r1-d4", rubricId: "1B-c1-r1", omschrijving: "Je durft jezelf te zijn.", categorie: "standaard", kleuren: { blauw: "Je durft altijd volledig jezelf te zijn, je volledig open te stellen en je durft spontaan gevoelens te uiten op een gepaste manier. Je zit op alle vlakken lekker in je vel.", groen: "Je probeert jezelf te zijn en je open te stellen maar af en toe is er terughoudendheid om je gevoelens te uiten op een gepaste manier.", geel: "Je durft vaak jezelf niet te zijn en je niet open te stellen of gevoelens te uiten/onder woorden te brengen. Je zal wel je gevoelens uiten op een gepaste manier als daar specifiek naar gevraagd wordt.", rood: "Je durft jezelf niet te zijn of je open te stellen en je hebt het moeilijk om je te uiten en je gevoelens te delen. Je bent zeer terughoudend als er specifiek naar gevraagd wordt." } },
  { id: "1B-c1-r2-d1", rubricId: "1B-c1-r2", omschrijving: "Je bent gemotiveerd.", categorie: "standaard", kleuren: { blauw: "Jouw motivatie komt bijna helemaal uit jezelf: je bent geboeid door veel verschillende dingen en hebt ook echt zin om die te gaan ontdekken of onderzoeken. Als je aan het werk bent of gaat, hoef je weinig of niet aangespoord te worden: het werk op zich en het proces van ontdekkend leren is voor jou motivatie genoeg.", groen: "Je hebt een brede interesse en bent vaak gemotiveerd voor verschillende soorten werk. Je hoeft niet dikwijls aangespoord te worden om aan het werk te gaan of te blijven.", geel: "Soms ben je geprikkeld door een onderwerp of door de samenwerking met iemand met wie het klikt: dan ben je gemotiveerd, maar het gebeurt nog niet vaak of je kan je motivatie nog niet lang vasthouden. Je hebt nog vaak een duwtje in de rug nodig om aan het werk te gaan of te blijven.", rood: "Je bent zelden uit jezelf gemotiveerd om te werken of te leren. Je doet dingen alleen als ze moeten en dan doe je het absolute minimum. Er is weinig of niets dat je boeit." } },
  { id: "1B-c1-r2-d2", rubricId: "1B-c1-r2", omschrijving: "Je kan anderen motiveren.", categorie: "standaard", kleuren: { blauw: "Je toont echt leiderschap in de manier waarop je anderen motiveert om het beste van zichzelf te geven. Zelfs als ze aanvankelijk minder enthousiast zijn over het werk, slaag je erin om hen toch mee te krijgen, zonder te dwingen of te domineren, door je eigen enthousiasme en inzet.", groen: "Tijdens duo- of groepsopdrachten slaag je erin om anderen te motiveren, ook als die er aanvankelijk niet veel zin in hebben. Je vindt het belangrijk dat jullie werk niet gedaan wordt alleen omdat het moet. Je probeert anderen mee te krijgen in je enthousiasme en slaagt daar ook vaak in.", geel: "Wanneer je samenwerkt met iemand die je goed kent of wanneer het onderwerp je echt ligt, dan slaag je er al regelmatig in om je partner(s) te motiveren voor het werk. Maar het gebeurt nog niet vaak genoeg of je houdt het nog niet dikwijls vol. Je bent nog niet vaak in staat om anderen echt mee te krijgen als je zelf enthousiast over iets bent.", rood: "Je trekt je weinig aan van het groepsgebeuren en probeert anderen zelden te betrekken bij, of te motiveren voor, iets waarmee jullie bezig zijn." } },
  { id: "1B-c1-r3-d1", rubricId: "1B-c1-r3", omschrijving: "Je bent zelfredzaam.", categorie: "standaard", kleuren: { blauw: "Je start volledig zelfstandig op.Je zoekt zelf verschillende hulp alternatieven.", groen: "Je start zelfstandig op maar hebt soms nog hulp nodig.Je durft hulp vragen.", geel: "Je start op indien je hulp krijgt.Je vindt hulp vragen nog moeilijk.", rood: "Je start niet zelfstandig op, ook niet met hulpJe vraagt geen hulp" } },
  { id: "1B-c1-r3-d2", rubricId: "1B-c1-r3", omschrijving: "Je kan problemen oplossingsgericht aanpakken.", categorie: "standaard", kleuren: { blauw: "Je ziet, erkent en analyseert het probleem.Je zoekt volledig zelfstandig oplossingen.Je controleert, stuurt bij en reflecteert over taakuitvoering en de oplossing.", groen: "Je ziet en erkent het probleem.Je zoekt oplossingen en vraagt hulp indien nodig.Je hebt aandacht voor aangereikte oplossingsstrategieën.", geel: "Je ziet een probleem.Je probeert oplossingen te zoeken.Je hebt weinig aandacht voor aangereikte oplossingsstrategieën.", rood: "Je ziet geen probleem.Je zoekt geen oplossingen.Je hebt geen aandacht voor aangereikte oplossingsstrategieën." } },
  { id: "1B-c1-r3-d3", rubricId: "1B-c1-r3", omschrijving: "Taakspanning: je kan doelen bepalen, een opdracht beginnen, volhouden, afwerken en reflecteren.", categorie: "standaard", kleuren: { blauw: "Je start volledig zelfstandig op.Je kan langer dan een uur gericht werken.Je bent niet af te leiden! Je kan perfect omgaan met lukken en mislukken.Je blikt zelfstandig terug op eigen gevolgde zoek- en oplossingsstrategieën, denk- en leerprocessen, taalgebruik, werk, expressieve uitingen, bewegingen en strategieën om kennis te verzamelen.", groen: "Je start zelfstandig op maar hebt soms nog hulp nodig.Je kan met overgave een langere tijd gericht werken.Je wordt niet te snel afgeleid door de omgeving.Je kan omgaan met lukken en mislukken.Kan terugblikken op eigen gevolgde zoek- en oplossingsstrategieën, denk- en leerprocessen, taalgebruik, werk, expressieve uitingen, bewegingen en strategieën om kennis te verzamelen.", geel: "Je start op indien je hulp krijgt.Je kan een korte tijd gericht werken.Je wordt nog snel afgeleid door de omgeving.Je kan moeilijk omgaan met lukken en mislukken.Terugblikken op je eigen gevolgde zoek- en oplossingsstrategieën, denk- en leerprocessen, taalgebruik, werk, expressieve uitingen, bewegingen en strategieën om kennis te verzamelen, vraagt veel inspanning en gebeurt niet bewust.", rood: "Je start niet zelfstandig op, ook niet met hulp.Je kan niet gericht werken.Je wordt bij het minste afgeleid door de omgeving.Je geeft onmiddellijk op.Je blikt niet terug op eigen gevolgde zoek- en oplossingsstrategieën, denk- en leerprocessen, taalgebruik, werk, expressieve uitingen, bewegingen en strategieën om kennis te verzamelen." } },
  { id: "1B-c1-r4-d1", rubricId: "1B-c1-r4", omschrijving: "Je kan een plan opstellen.", categorie: "standaard", kleuren: { blauw: "Je gebruikt spontaan je planningsdocument om taken in te plannen.Je stelt zelf werkschema’s op om werk op langere termijn te plannen.Je plant je tijd in functie van prioriteiten, hoofdzaken en resultaten.", groen: "Je gebruikt de planningsdocumenten.Je maakt gebruik van to-do- lijstjes…Je werkt af en toe een stappenplan uit in functie van een lange opdracht.Je slaagt er meestal in om de prioriteiten te bepalen.", geel: "Je hebt wel een planningsdocument bij, maar gebruikt het te weinig om te plannen.Af en toe maak je gebruik van to-do-lijstjes…Je kan moeilijk prioriteiten bepalen.", rood: "Je hebt zelden weet van een planningsdocument en gebruikt het nooit om te plannen.Je kan nog geen prioriteiten bepalen." } },
  { id: "1B-c1-r4-d2", rubricId: "1B-c1-r4", omschrijving: "Je kan een plan uitvoeren en aanpassen indien nodig.", categorie: "standaard", kleuren: { blauw: "Je pakt spontaan de belangrijkste of dringendste taak aan.Je stuurt je planning bij als het nodig is.Je kan verschillende taken tegelijk organiseren.Je bent altijd op tijd klaar met je werk.", groen: "Je voert de planning uit en houdt de timing in het oog.Je stuurt je planning bij als het nodig is.Je voert belangrijke of dringende taken tijdig uit, eventueel na een herinnering.", geel: "Je werkt volgens planning, maar verliest de timing uit het oog.Je werkt bijvoorbeeld te lang aan een taak, zodat er te weinig tijd over blijft voor een andere taak.Je voert belangrijke of dringende taken te laat uit.", rood: "Je hebt totaal geen planning en overzicht.Je voert belangrijke of dringende taken zelden op tijd uit." } },
  { id: "1B-c1-r4-d3", rubricId: "1B-c1-r4", omschrijving: "Je kan opdrachten plannen.", categorie: "standaard", kleuren: { blauw: "Een stappenplan of scenario bedenken en uitvoeren is voor jou vanzelfsprekend.Je stelt prioriteiten en maakt weloverwogen keuzes.Je houdt je strikt aan de planning en dit geeft jou ruimte om extra’s toe te voegen aan je werk.", groen: "Je voorziet een stappenplan en je houdt je daaraan.Je probeert prioriteiten te stellen.Je houdt je aan de planning.", geel: "Je voelt aan dat een stappenplan belangrijk is maar je hebt hulp nodig bij het opstellen hiervan.Je kan moeilijk prioriteiten stellen.Je houdt je vaak niet aan de planning.", rood: "Je hebt geen stappenplan en denkt daar ook niet aan.Je kan geen prioriteiten stellen.Je houdt je niet aan de planning, je dient te laat of niet in." } },
  { id: "1B-c1-r4-d4", rubricId: "1B-c1-r4", omschrijving: "Je maakt actief gebruik van het badgeboekje.", categorie: "standaard", kleuren: { blauw: "Je komt zelf het badgeboek brengen en vraagt om dit verder om dit verder aan te vullen.", groen: "Je maakt actief gebruik van het badgeboek.", geel: "Je maakt soms gebruik van het badgeboek maar je bent er eigenlijk nog te weinig mee bezig.", rood: "Je maakt te weinig of geen gebruik van het badgeboek." } },
  { id: "1B-c1-r5-d1", rubricId: "1B-c1-r5", omschrijving: "Je komt tot afwerking (volgens de doelen).", categorie: "standaard", kleuren: { blauw: "Je werkt taken altijd volledig af volgens de opdracht en geeft zelfs nog extra en correct onderbouwde info.Je zoekt altijd eerst zelf naar informatie.Je werkt zeer nauwkeurig, hebt oog voor het kleinste detail. Structuur, orde en netheid staan voorop. Je werk overstijgt de opgegeven criteria, excellent! Je controleert je taken en stuurt bij indien nodig.", groen: "Je werkt taken altijd volledig af volgens de opdracht.Je kan zelf eerst naar informatie zoeken, maar doet dat niet altijd.Je werkt zeer ordelijk en gestructureerd.Je mag terecht trots zijn, je werk voldoet aan alle opgegeven criteria.Je controleert je taken.", geel: "Je werkt taken niet altijd volledig af volgens de opdracht.Je zoekt zelf niet naar informatie, maar vraagt steeds hulp aan de mentor, soms aan de medestudenten.Je werkt niet altijd even ordelijk en hebt hulp nodig bij structuur.Je bent (te) snel tevreden, je werk voldoet niet aan alle opgelegde criteria.Je controleert je taken onvolledig.", rood: "Je werkt taken zelden of niet volledig af volgens de opdracht.Je kan zelf niet naar informatie zoeken, je weet niet waar. Je vraagt nooit om hulp of stelt overdreven veel niet-concrete hulpvragen.Je werkt niet ordelijk en ongestructureerd.Je werk voldoet niet aan de opgelegde criteria, je geeft snel op.Je controleert je taken niet." } },
  { id: "1B-c1-r5-d2", rubricId: "1B-c1-r5", omschrijving: "Je streeft naar iets waar je trots op bent (zone van de naaste ontwikkeling).", categorie: "standaard", kleuren: { blauw: "Je bent altijd gemotiveerd om een uitdaging aan te gaan.Je staat altijd open voor nieuwe dingen.Je kan om met lukken en mislukken en blijft opnieuw proberen tot het overstijgende resultaat is bereikt. Je voelt je als persoon iets waard en zoekt succeservaring op.", groen: "Je bent meestal gemotiveerd om een uitdaging aan te gaan Je staat meestal open voor nieuwe dingenJe kan om met lukken en mislukken en probeert tot er een gewenst resultaat isJe voelt je als persoon iets waard en kan genieten van succeservaring.", geel: "Je bent soms gemotiveerd om een uitdaging aan te gaan Je staat soms open voor nieuwe dingen Je kan moeilijk om met lukken en mislukken en geeft uiteindelijk op. Je wil zich als persoon iets waard voelen en wil eens genieten van een succeservaring.", rood: "Je bent zelden gemotiveerd om een uitdaging aan te gaan Je staat zelden open voor nieuwe dingen Je kan niet om met mislukken en je geeft heel snel op. Je voelt zich als persoon niets waard en denkt nooit een succeservaring te kunnen hebben." } },
  { id: "1B-c1-r5-d3", rubricId: "1B-c1-r5", omschrijving: "Je kan omgaan met feedback van mentoren.", categorie: "standaard", kleuren: { blauw: "Je grijpt feedback aan als een dialoog over je werk en een stimulans om verder te zoeken, dieper te graven. Voor jou is je werk een groeiproces en alle reacties zijn welkom om je vooruitgang te stimuleren.", groen: "Je leest of luistert aandachtig naar feedback en bent bereid om je werk grondig te verbeteren als dat nodig is. Je verandert niet alleen kleinigheden, maar maakt volwaardige nieuwe versies.", geel: "Je leest of luistert wel naar feedback maar je houdt er nog te weinig rekening mee. Je tweede versies verschillen weinig van je eerste, op wat details na.", rood: "Je leest of luistert nauwelijks of niet naar feedback en maakt nooit een tweede versie van je werk." } },
  { id: "1B-c1-r5-d4", rubricId: "1B-c1-r5", omschrijving: "Je kan omgaan met feedback van leeftijdsgenoten.", categorie: "standaard", kleuren: { blauw: "Je bent blij met feedback van leeftijdsgenoten en beschouwt die als een uitnodiging om over je werk te praten en na te denken. Je deelt je werk met anderen en beschouwt hun reacties als deel van het proces.", groen: "Je luistert aandachtig naar feedback van je leeftijdsgenoten, beseft dat zij je eerste publiek zijn en probeert rekening te houden met wat er gezegd wordt en je werk aan te passen wanneer dat nodig is.", geel: "Je luistert wel naar feedback van leeftijdsgenoten maar houdt er nog te weinig echt rekening mee.", rood: "Je luistert nauwelijks naar feedback van leeftijdsgenoten of reageert zelfs vijandig of defensief, ook als iemand zich respectvol uitspreekt over je werk." } },
  { id: "1B-c1-r5-d5", rubricId: "1B-c1-r5", omschrijving: "Je kan zelf feedback geven.", categorie: "standaard", kleuren: { blauw: "Je geeft graag en vaak feedback op het werk van anderen en probeert hen echt vooruit te helpen door persoonlijke en goed onderbouwde commentaren. Je houdt van het proces waardoor we elkaars werk beter proberen te maken door er op een open manier over te praten.", groen: "Je hebt echte aandacht voor het werk van anderen en denkt na voor je feedback geeft. Je blijft niet aan de oppervlakte maar probeert dingen te zeggen waar de ander iets aan heeft. Je durft zowel lof als kritiek te geven, maar altijd op een respectvolle manier.", geel: "Je geeft af en toe feedback, maar die is vaak oppervlakkig of niet echt opbouwend. Je probeert wel aandacht op te brengen voor het werk van anderen.", rood: "Je geeft zelden feedback op het werk van anderen, behalve als het verplicht is en toont over het algemeen weinig interesse in wat anderen maken of presenteren." } },
  { id: "1B-c1-r6-d1", rubricId: "1B-c1-r6", omschrijving: "Je kan reflecteren over je leerproces, je studiehouding, je kwaliteiten en je werkpunten.", categorie: "standaard", kleuren: { blauw: "Je kan je werkpunten bepalen, benoemen, aanpakken en bijsturen. Je durft om hulp te vragen en biedt anderen spontaan hulp.", groen: "Je gaat aan de slag met je werkpunten. Je durft om hulp te vragen.", geel: "Je kan je eigen werkpunten benoemen.Je durft af en toe om hulp te vragen.", rood: "Je kan je eigen werkpunten niet benoemenJe durft niet om hulp te vragen." } },
  { id: "1B-c1-r6-d2", rubricId: "1B-c1-r6", omschrijving: "Je weet hoe je het best leert/werkt.", categorie: "standaard", kleuren: { blauw: "Je ontwikkelt je eigen leerstrategieën i.f.v. de taken.", groen: "Je kan jezelf organiseren zodat je de taak zo goed mogelijk aanpakt.", geel: "Je kan benoemen wat je nodig hebt om een taak goed aan te pakken.", rood: "Je weet niet hoe je best een taak aanpakt." } },
  { id: "1B-c1-r6-d3", rubricId: "1B-c1-r6", omschrijving: "Je kent je eigen sterktes en talenten.", categorie: "standaard", kleuren: { blauw: "Je kan je sterktes en talenten actief inzetten en aanwenden.", groen: "Je heb inzicht in je sterktes en talenten.", geel: "Je kan je sterktes en talenten benoemen.", rood: "Je hebt geen idee wat je sterktes en talenten zijn." } },
  { id: "1B-c1-r7-d1", rubricId: "1B-c1-r7", omschrijving: "Je hebt een respectvolle houding (vanuit gelijkwaardigheid en empathie).", categorie: "standaard", kleuren: { blauw: "Je hebt een open houding naar anderen. Je stelt je empathisch op. Je hebt oog voor de anderen. Je toont respect voor de hele school.", groen: "Je hebt een voldoende open houding naar anderen. Je stelt je vaak empathisch op en hebt oog voor de anderen. Je toont voldoende respect voor de hele school.", geel: "Je slaagt er af ent toe in een open houding naar anderen te hebben. Je kan nog groeien in respect voor de hele school.", rood: "Je bent meestal vrij gesloten. Je kan je weinig inleven. Je hebt weinig empathie en respect." } },
  { id: "1B-c1-r7-d2", rubricId: "1B-c1-r7", omschrijving: "Je neemt je verantwoordelijkheid binnen de groep.", categorie: "standaard", kleuren: { blauw: "Je neemt vaak verantwoordelijkheid op in het klasgebeuren bij taken, projecten, als groep. Je neemt de verantwoordelijkheid op om (deel)taken op te nemen en je delegeert het werk.Je toont meestal een correcte houding naar je klasgenoten en mentoren.Je aanvaardt de beslissing van de klasraad zonder protesteren.", groen: "Je neemt je verantwoordelijkheid op in het klasgebeuren. Je neemt zelf de verantwoordelijkheid op om (deel)taken op te nemen.Je toont meestal een correcte houding naar je klasgenoten en mentoren.Je aanvaardt de beslissing van de klasraad maar durft protesteren.", geel: "Je neemt je verantwoordelijkheid niet vaak op in het klasgebeuren. Je voert af en toe (deel)taken uit die aangeboden worden door de groep.Je hebt niet altijd een correcte houding ten opzichte van je klasgenoten en je mentoren.Je schuilt je vaak achter excuses.Je aanvaardt de beslissing van de klasraad maar durft de beslissing niet naleven.", rood: "Je neemt te weinig verantwoordelijkheid op in het klasgebeuren. Je werkt alleen een taak af bij een nadrukkelijke vraag.Je houding past niet in de klaswerking.Je werkt de klasraad tegen.Je aanvaardt beslissingen van de klasraad niet." } },
  { id: "1B-c1-r7-d3", rubricId: "1B-c1-r7", omschrijving: "Je formuleert en respecteert afspraken.", categorie: "standaard", kleuren: { blauw: "Je leeft de afspraken na en bent constructief aanwezig.Je kan goed samenwerken.Je kent de afspraken en kan ze uitleggen.Je helpt anderen om afspraken na te leven en bouwt zo mee aan een positief klimaat op school.Je gebruikt de klasraad om de afspraken te optimaliseren.", groen: "Samenwerken lukt je bij bepaalde opdrachten al goed.Je leeft de afspraken meestal na en maakt groeisprongen in het naleven.Je kent de meeste afspraken maar vergeet soms een detail.Je helpt anderen vaak om afspraken na te leven.Je benut af en toe de klasraad om afspraken te laten naleven.", geel: "Je vindt het moeilijk om samen te werken. Je leeft de essentiële afspraken na, maar hebt regelmatig hulp nodig bij andere afspraken.Je weet van veel afspraken niet eens dat ze bestaan.Je helpt anderen soms om afspraken na te leven.", rood: "Je leeft de afspraken zelden na en bent weinig constructief voor de groep.Je kan moeilijk duiden waarom we afspraken hebben.Je durft anderen meeslepen in het niet-naleven van afspraken." } },
  { id: "1B-c1-r8-d1", rubricId: "1B-c1-r8", omschrijving: "Je bouwt actief mee aan de klasgroep en de school.", categorie: "standaard", kleuren: { blauw: "Je zoekt naar oplossingen en stelt deze voor aan de groep. Je maakt ook duidelijk waar er nog geen oplossing voor gevonden werd en welke stappen ondernomen zullen moeten worden.", groen: "Je zoekt naar oplossingen voor het probleem in groep, bespreekt deze en stelt een besluit voor.", geel: "Je zoekt naar oplossingen voor het probleem maar doet dit zelfstandig en niet binnen de groep.", rood: "Je toont geen interesse in het probleem, idee of in de opdracht." } },
  { id: "1B-c1-r8-d2", rubricId: "1B-c1-r8", omschrijving: "Je zoekt naar oplossingen voor conflicten en problemen.", categorie: "standaard", kleuren: { blauw: "Je bent sterk betrokken in de klaswerking en inspireert daarbij anderen.", groen: "Je bent betrokken in de klaswerking en neemt een actieve rol op.", geel: "Je bent af en toe betrokken in de klaswerking en neemt nog geen actieve rol op.", rood: "Je neemt tijdens de klaswerking eerder een passieve rol op of je stoort de klaswerking." } },
  { id: "1B-c2-r1-d1", rubricId: "1B-c2-r1", omschrijving: "Je bent zelfredzaam en je start zelfstandig op.", categorie: "standaard" },
  { id: "1B-c2-r1-d2", rubricId: "1B-c2-r1", omschrijving: "Je kunt een opdracht in verschillende stukken verdelen.", categorie: "standaard" },
  { id: "1B-c2-r1-d3", rubricId: "1B-c2-r1", omschrijving: "Je kan (onder begeleiding) met een weekplanning of een maandplanning werken.", categorie: "standaard" },
  { id: "1B-c2-r1-d4", rubricId: "1B-c2-r1", omschrijving: "Je kan prioriteiten stellen in je werk en een onderscheid maken tussen hoofd- en bijzaken in je planning.", categorie: "standaard" },
  { id: "1B-c2-r1-d5", rubricId: "1B-c2-r1", omschrijving: "Je kan een plan uitvoeren.", categorie: "standaard" },
  { id: "1B-c2-r1-d6", rubricId: "1B-c2-r1", omschrijving: "Je dient alle taken volgens de opdracht in.", categorie: "standaard" },
  { id: "1B-c2-r1-d7", rubricId: "1B-c2-r1", omschrijving: "Je streeft naar iets waar je trots op bent. Je kan hierbij omgaan met lukken en mislukken en je blijft proberen tot er een gewenst resultaat is.", categorie: "standaard" },
  { id: "1B-c2-r1-d8", rubricId: "1B-c2-r1", omschrijving: "Je kan een plan aanpassen.", categorie: "standaard" },
  { id: "1B-c2-r1-d9", rubricId: "1B-c2-r1", omschrijving: "Je voelt aan wanneer je problemen of obstakels tegenkomt tijdens je leerproces en je bent in staat om hierbij hulp te vragen. Je pakt je problemen oplossingsgericht aan.", categorie: "standaard" },
  { id: "1B-c2-r1-d10", rubricId: "1B-c2-r1", omschrijving: "Je kan je aan deadlines houden.", categorie: "standaard" },
  { id: "1B-c2-r1-d11", rubricId: "1B-c2-r1", omschrijving: "Je maakt actief gebruik van het badgeboekje.", categorie: "standaard" },
  { id: "1B-c2-r2-d1", rubricId: "1B-c2-r2", omschrijving: "Je kan omgaan met de feedback van mentoren.", categorie: "standaard" },
  { id: "1B-c2-r2-d2", rubricId: "1B-c2-r2", omschrijving: "Je kan omgaan met de feedback van leeftijdsgenoten.", categorie: "standaard" },
  { id: "1B-c2-r2-d3", rubricId: "1B-c2-r2", omschrijving: "Je kan zelf feedback geven op een respectvolle manier.", categorie: "standaard" },
  { id: "1B-c2-r2-d4", rubricId: "1B-c2-r2", omschrijving: "Je weet hoe je het best leert/werkt.", categorie: "standaard" },
  { id: "1B-c2-r2-d5", rubricId: "1B-c2-r2", omschrijving: "Je kan reflecteren over je leerproces, je studiehouding, je kwaliteiten en je werkpunten.", categorie: "standaard" },
  { id: "1B-c2-r2-d6", rubricId: "1B-c2-r2", omschrijving: "Je kan terugblikken op je eigen gevolgde zoek- en oplossingsstrategieën.", categorie: "standaard" },
  { id: "1B-c3-r1-d1", rubricId: "1B-c3-r1", omschrijving: "Voorzitter", categorie: "standaard" },
  { id: "1B-c3-r1-d2", rubricId: "1B-c3-r1", omschrijving: "Secretaris", categorie: "standaard" },
  { id: "1B-c3-r1-d3", rubricId: "1B-c3-r1", omschrijving: "Tijdsbewaker", categorie: "standaard" },
  { id: "1B-c3-r2-d1", rubricId: "1B-c3-r2", omschrijving: "Deelnemer", categorie: "standaard" },
  { id: "1B-c4-r1-d1", rubricId: "1B-c4-r1", omschrijving: "Je hebt een respectvolle houding (vanuit gelijkwaardigheid, sociale betrokkenheid en empathie).", categorie: "standaard" },
  { id: "1B-c4-r1-d2", rubricId: "1B-c4-r1", omschrijving: "Je respecteert de afspraken, de leefregels en het materiaal op school.", categorie: "standaard" },
  { id: "1B-c4-r1-d3", rubricId: "1B-c4-r1", omschrijving: "Je neemt respectvol en actief deel aan diensten (‘corvee’) op school.", categorie: "standaard" },
  { id: "1B-c4-r1-d4", rubricId: "1B-c4-r1", omschrijving: "Je neemt actief deel aan activiteiten met de school.", categorie: "standaard" },
  { id: "1B-c4-r1-d5", rubricId: "1B-c4-r1", omschrijving: "Je bouwt respectvol en actief mee aan de klasgroep en de school.", categorie: "standaard" },
  { id: "1B-c4-r1-d6", rubricId: "1B-c4-r1", omschrijving: "Je zoekt naar oplossingen voor conflicten en problemen.", categorie: "standaard" },
  { id: "1B-c4-r2-d1", rubricId: "1B-c4-r2", omschrijving: "Project 1", categorie: "standaard" },
  { id: "1B-c4-r2-d2", rubricId: "1B-c4-r2", omschrijving: "Project 2", categorie: "standaard" },
  { id: "1B-c5-r1-d1", rubricId: "1B-c5-r1", omschrijving: "Natuur", categorie: "standaard" },
  { id: "1B-c5-r1-d2", rubricId: "1B-c5-r1", omschrijving: "Handvaardigheid, bouw & techniek", categorie: "standaard" },
  { id: "1B-c5-r1-d3", rubricId: "1B-c5-r1", omschrijving: "Kennis", categorie: "standaard" },
  { id: "1B-c5-r1-d4", rubricId: "1B-c5-r1", omschrijving: "Experimenten, wetenschappelijk onderzoek & innovatie", categorie: "standaard" },
  { id: "1B-c5-r1-d5", rubricId: "1B-c5-r1", omschrijving: "ICT, digitale & moderne technieken", categorie: "standaard" },
  { id: "1B-c5-r1-d6", rubricId: "1B-c5-r1", omschrijving: "Expressie, creatie & ontwerp", categorie: "standaard" },
  { id: "1B-c5-r1-d7", rubricId: "1B-c5-r1", omschrijving: "Welzijn en andere", categorie: "standaard" },
  { id: "1B-c6-r1-d1", rubricId: "1B-c6-r1", omschrijving: "Voorzitter", categorie: "standaard" },
  { id: "1B-c6-r1-d2", rubricId: "1B-c6-r1", omschrijving: "Secretaris", categorie: "standaard" },
  { id: "1B-c6-r1-d3", rubricId: "1B-c6-r1", omschrijving: "Tijdsbewaker", categorie: "standaard" },
  { id: "1B-c6-r2-d1", rubricId: "1B-c6-r2", omschrijving: "Deelnemers Nederlands", categorie: "standaard" },
  { id: "1B-c6-r2-d2", rubricId: "1B-c6-r2", omschrijving: "Deelnemer Frans", categorie: "standaard" },
  { id: "1B-c6-r2-d3", rubricId: "1B-c6-r2", omschrijving: "Deelnemer Engels", categorie: "standaard" },
  { id: "1B-c7-r1-d1", rubricId: "1B-c7-r1", omschrijving: "NL 1", categorie: "standaard" },
  { id: "1B-c7-r1-d2", rubricId: "1B-c7-r1", omschrijving: "NL 2", categorie: "standaard" },
  { id: "1B-c7-r1-d3", rubricId: "1B-c7-r1", omschrijving: "NL 3", categorie: "standaard" },
  { id: "1B-c7-r1-d4", rubricId: "1B-c7-r1", omschrijving: "NL 4", categorie: "standaard" },
  { id: "1B-c7-r1-d5", rubricId: "1B-c7-r1", omschrijving: "NL 5", categorie: "standaard" },
  { id: "1B-c7-r1-d6", rubricId: "1B-c7-r1", omschrijving: "NL 6", categorie: "standaard" },
  { id: "1B-c7-r1-d7", rubricId: "1B-c7-r1", omschrijving: "FR 1", categorie: "standaard" },
  { id: "1B-c7-r1-d8", rubricId: "1B-c7-r1", omschrijving: "FR 2", categorie: "standaard" },
  { id: "1B-c7-r1-d9", rubricId: "1B-c7-r1", omschrijving: "EN 1", categorie: "standaard" },
  { id: "1B-c7-r1-d10", rubricId: "1B-c7-r1", omschrijving: "EN 2", categorie: "standaard" },
  { id: "1B-c8-r1-d1", rubricId: "1B-c8-r1", omschrijving: "Badge behaald", categorie: "standaard" },
  { id: "1B-c8-r1-d2", rubricId: "1B-c8-r1", omschrijving: "Schrijfproces 1", categorie: "standaard" },
  { id: "1B-c8-r1-d3", rubricId: "1B-c8-r1", omschrijving: "Schrijfproces 2", categorie: "standaard" },
  { id: "1B-c8-r1-d4", rubricId: "1B-c8-r1", omschrijving: "Schrijfproces 3", categorie: "standaard" },
  { id: "1B-c8-r1-d5", rubricId: "1B-c8-r1", omschrijving: "Schrijfproces 4", categorie: "standaard" },
  { id: "1B-c8-r1-d6", rubricId: "1B-c8-r1", omschrijving: "Schrijfproces 5", categorie: "standaard" },
  { id: "1B-c8-r1-d7", rubricId: "1B-c8-r1", omschrijving: "Schrijfproces 6", categorie: "standaard" },
  { id: "1B-c9-r1-d1", rubricId: "1B-c9-r1", omschrijving: "NL 1", categorie: "standaard" },
  { id: "1B-c9-r1-d2", rubricId: "1B-c9-r1", omschrijving: "NL 2", categorie: "standaard" },
  { id: "1B-c9-r1-d3", rubricId: "1B-c9-r1", omschrijving: "NL 3", categorie: "standaard" },
  { id: "1B-c9-r1-d4", rubricId: "1B-c9-r1", omschrijving: "NL 4", categorie: "standaard" },
  { id: "1B-c9-r1-d5", rubricId: "1B-c9-r1", omschrijving: "NL 5", categorie: "standaard" },
  { id: "1B-c9-r1-d6", rubricId: "1B-c9-r1", omschrijving: "NL 6", categorie: "standaard" },
  { id: "1B-c9-r1-d7", rubricId: "1B-c9-r1", omschrijving: "FR 1", categorie: "standaard" },
  { id: "1B-c9-r1-d8", rubricId: "1B-c9-r1", omschrijving: "FR 2", categorie: "standaard" },
  { id: "1B-c9-r1-d9", rubricId: "1B-c9-r1", omschrijving: "EN 1", categorie: "standaard" },
  { id: "1B-c9-r1-d10", rubricId: "1B-c9-r1", omschrijving: "EN 2", categorie: "standaard" },
  { id: "1B-c10-r1-d1", rubricId: "1B-c10-r1", omschrijving: "NL 1", categorie: "standaard" },
  { id: "1B-c10-r1-d2", rubricId: "1B-c10-r1", omschrijving: "NL 2", categorie: "standaard" },
  { id: "1B-c10-r1-d3", rubricId: "1B-c10-r1", omschrijving: "NL 3", categorie: "standaard" },
  { id: "1B-c10-r1-d4", rubricId: "1B-c10-r1", omschrijving: "NL 4", categorie: "standaard" },
  { id: "1B-c10-r1-d5", rubricId: "1B-c10-r1", omschrijving: "NL 5", categorie: "standaard" },
  { id: "1B-c10-r1-d6", rubricId: "1B-c10-r1", omschrijving: "FR 1", categorie: "standaard" },
  { id: "1B-c10-r1-d7", rubricId: "1B-c10-r1", omschrijving: "FR 2", categorie: "standaard" },
  { id: "1B-c10-r1-d8", rubricId: "1B-c10-r1", omschrijving: "FR 3", categorie: "standaard" },
  { id: "1B-c10-r1-d9", rubricId: "1B-c10-r1", omschrijving: "EN 1", categorie: "standaard" },
  { id: "1B-c10-r1-d10", rubricId: "1B-c10-r1", omschrijving: "EN 2", categorie: "standaard" },
  { id: "1B-c10-r2-d1", rubricId: "1B-c10-r2", omschrijving: "NL 1", categorie: "standaard" },
  { id: "1B-c10-r2-d2", rubricId: "1B-c10-r2", omschrijving: "NL 2", categorie: "standaard" },
  { id: "1B-c10-r2-d3", rubricId: "1B-c10-r2", omschrijving: "FR 1", categorie: "standaard" },
  { id: "1B-c10-r2-d4", rubricId: "1B-c10-r2", omschrijving: "EN 1", categorie: "standaard" },
  { id: "1B-c11-r1-d1", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 1", categorie: "standaard" },
  { id: "1B-c11-r1-d2", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 2", categorie: "standaard" },
  { id: "1B-c11-r1-d3", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 3", categorie: "standaard" },
  { id: "1B-c11-r1-d4", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 4", categorie: "standaard" },
  { id: "1B-c11-r1-d5", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 5", categorie: "standaard" },
  { id: "1B-c11-r1-d6", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 6", categorie: "standaard" },
  { id: "1B-c11-r1-d7", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 7", categorie: "standaard" },
  { id: "1B-c11-r1-d8", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 8", categorie: "standaard" },
  { id: "1B-c11-r1-d9", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 9", categorie: "standaard" },
  { id: "1B-c11-r1-d10", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 10", categorie: "standaard" },
  { id: "1B-c11-r1-d11", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 11", categorie: "standaard" },
  { id: "1B-c11-r1-d12", rubricId: "1B-c11-r1", omschrijving: "Individuele en coöperatieve onderzoeken: kerndoelen 12", categorie: "standaard" },
  { id: "1B-c11-r2-d1", rubricId: "1B-c11-r2", omschrijving: "Historisch bewustzijn", categorie: "standaard" },
  { id: "1B-c11-r2-d2", rubricId: "1B-c11-r2", omschrijving: "Algemene periodisering", categorie: "standaard" },
  { id: "1B-c11-r2-d3", rubricId: "1B-c11-r2", omschrijving: "Niet-Westerse periodisering", categorie: "standaard" },
  { id: "1B-c11-r2-d4", rubricId: "1B-c11-r2", omschrijving: "Prehistorie: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "1B-c11-r2-d5", rubricId: "1B-c11-r2", omschrijving: "Oude Nabije Oosten: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "1B-c11-r2-d6", rubricId: "1B-c11-r2", omschrijving: "Klassieke Oudheid: politiek, sociaal, economisch, cultureel", categorie: "standaard" },
  { id: "1B-c11-r2-d7", rubricId: "1B-c11-r2", omschrijving: "Ruimtelijk bewustzijn", categorie: "standaard" },
  { id: "1B-c11-r2-d8", rubricId: "1B-c11-r2", omschrijving: "Lokalisatie en situering: geografisch en schaalniveau", categorie: "standaard" },
  { id: "1B-c11-r2-d9", rubricId: "1B-c11-r2", omschrijving: "Geografische eenheden: landschappen, reliëf, ondergrond, klimaat, vegetatie", categorie: "standaard" },
  { id: "1B-c11-r2-d10", rubricId: "1B-c11-r2", omschrijving: "Evolutie en verandering", categorie: "standaard" },
  { id: "1B-c11-r2-d11", rubricId: "1B-c11-r2", omschrijving: "Exacte wetenschappen", categorie: "standaard" },
  { id: "1B-c11-r2-d12", rubricId: "1B-c11-r2", omschrijving: "Deeltjesmodel", categorie: "standaard" },
  { id: "1B-c11-r2-d13", rubricId: "1B-c11-r2", omschrijving: "Krachten, energie, stralingen", categorie: "standaard" },
  { id: "1B-c11-r2-d14", rubricId: "1B-c11-r2", omschrijving: "Opbouw en functioneren van organismen", categorie: "standaard" },
  { id: "1B-c11-r2-d15", rubricId: "1B-c11-r2", omschrijving: "Voortplanting van planten, dieren, mensen", categorie: "standaard" },
  { id: "1B-c11-r2-d16", rubricId: "1B-c11-r2", omschrijving: "Biotopen", categorie: "standaard" },
  { id: "1B-c11-r2-d17", rubricId: "1B-c11-r2", omschrijving: "Techniek & technologie", categorie: "standaard" },
  { id: "1B-c11-r2-d18", rubricId: "1B-c11-r2", omschrijving: "Eigenschappen van materialen", categorie: "standaard" },
  { id: "1B-c11-r2-d19", rubricId: "1B-c11-r2", omschrijving: "Technische processen", categorie: "standaard" },
  { id: "1B-c11-r2-d20", rubricId: "1B-c11-r2", omschrijving: "Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", categorie: "standaard" },
  { id: "1B-c11-r2-d21", rubricId: "1B-c11-r2", omschrijving: "Duurzaamheid", categorie: "standaard" },
  { id: "1B-c11-r2-d22", rubricId: "1B-c11-r2", omschrijving: "Bij technische systemen", categorie: "standaard" },
  { id: "1B-c11-r2-d23", rubricId: "1B-c11-r2", omschrijving: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", categorie: "standaard" },
  { id: "1B-c11-r2-d24", rubricId: "1B-c11-r2", omschrijving: "Economisch en financieel bewustzijn", categorie: "standaard" },
  { id: "1B-c11-r2-d25", rubricId: "1B-c11-r2", omschrijving: "Gezinsbudget", categorie: "standaard" },
  { id: "1B-c11-r2-d26", rubricId: "1B-c11-r2", omschrijving: "Maatschappelijke thema’s", categorie: "standaard" },
  { id: "1B-c12-r1-d1", rubricId: "1B-c12-r1", omschrijving: "Project 1", categorie: "standaard" },
  { id: "1B-c12-r1-d2", rubricId: "1B-c12-r1", omschrijving: "Project 2", categorie: "standaard" },
  { id: "1B-c12-r1-d3", rubricId: "1B-c12-r1", omschrijving: "Project 3", categorie: "standaard" },
  { id: "1B-c12-r1-d4", rubricId: "1B-c12-r1", omschrijving: "Project 4", categorie: "standaard" },
  { id: "1B-c13-r1-d1", rubricId: "1B-c13-r1", omschrijving: "Een wiskundige kijk op de wereld 1", categorie: "standaard" },
  { id: "1B-c13-r1-d2", rubricId: "1B-c13-r1", omschrijving: "Een wiskundige kijk op de wereld 2", categorie: "standaard" },
  { id: "1B-c13-r1-d3", rubricId: "1B-c13-r1", omschrijving: "Een wiskundige kijk op de wereld 3", categorie: "standaard" },
  { id: "1B-c13-r1-d4", rubricId: "1B-c13-r1", omschrijving: "Een wiskundige kijk op de wereld 4", categorie: "standaard" },
  { id: "1B-c13-r1-d5", rubricId: "1B-c13-r1", omschrijving: "Een wiskundige kijk op de wereld 5", categorie: "standaard" },
  { id: "1B-c13-r1-d6", rubricId: "1B-c13-r1", omschrijving: "Een wiskundige kijk op de wereld 6", categorie: "standaard" },
  { id: "1B-c13-r2-d1", rubricId: "1B-c13-r2", omschrijving: "Wiskundige onderzoeken 1", categorie: "standaard" },
  { id: "1B-c13-r2-d2", rubricId: "1B-c13-r2", omschrijving: "Wiskundige onderzoeken 2", categorie: "standaard" },
  { id: "1B-c13-r2-d3", rubricId: "1B-c13-r2", omschrijving: "Wiskundige onderzoeken 3", categorie: "standaard" },
  { id: "1B-c13-r2-d4", rubricId: "1B-c13-r2", omschrijving: "Wiskundige onderzoeken 4", categorie: "standaard" },
  { id: "1B-c13-r3-d1", rubricId: "1B-c13-r3", omschrijving: "Getallenleer", categorie: "standaard" },
  { id: "1B-c13-r3-d2", rubricId: "1B-c13-r3", omschrijving: "1.2 Ordenen van getallen", categorie: "standaard" },
  { id: "1B-c13-r3-d3", rubricId: "1B-c13-r3", omschrijving: "1.3 Bewerkingen en rekenregels", categorie: "standaard" },
  { id: "1B-c13-r3-d4", rubricId: "1B-c13-r3", omschrijving: "1.4 Maatgetallen", categorie: "standaard" },
  { id: "1B-c13-r3-d5", rubricId: "1B-c13-r3", omschrijving: "Meetkunde", categorie: "standaard" },
  { id: "1B-c13-r3-d6", rubricId: "1B-c13-r3", omschrijving: "2.2 Ruimtemeetkunde", categorie: "standaard" },
  { id: "1B-c13-r3-d7", rubricId: "1B-c13-r3", omschrijving: "2.3 coördinaten", categorie: "standaard" },
  { id: "1B-c13-r3-d8", rubricId: "1B-c13-r3", omschrijving: "Statistiek", categorie: "standaard" },
  { id: "1B-c14-r1-d1", rubricId: "1B-c14-r1", omschrijving: "Kunst in prehistorie", categorie: "standaard" },
  { id: "1B-c14-r1-d2", rubricId: "1B-c14-r1", omschrijving: "Kunst in Oude Nabije Oosten", categorie: "standaard" },
  { id: "1B-c14-r1-d3", rubricId: "1B-c14-r1", omschrijving: "Kunst in Klassieke Oudheid", categorie: "standaard" },
  { id: "1B-c14-r1-d4", rubricId: "1B-c14-r1", omschrijving: "Niet-Westerse kunst", categorie: "standaard" },
  { id: "1B-c14-r1-d5", rubricId: "1B-c14-r1", omschrijving: "Onderwerp naar keuze", categorie: "standaard" },
  { id: "1B-c14-r2-d1", rubricId: "1B-c14-r2", omschrijving: "Toegepaste kunstenArchitectuurModeDesign (grafisch, industrieel, interieur)Sier- en edelsmeedkunstKeramiek", categorie: "standaard" },
  { id: "1B-c14-r2-d2", rubricId: "1B-c14-r2", omschrijving: "Beeldende kunstenSchilderkunstTekenkunstGrafiekBeeldhouwkunstFotografieDigitale kunst", categorie: "standaard" },
  { id: "1B-c14-r2-d3", rubricId: "1B-c14-r2", omschrijving: "PodiumkunstenTheaterDansMuziektheater (opera, musical)Performance", categorie: "standaard" },
  { id: "1B-c14-r2-d4", rubricId: "1B-c14-r2", omschrijving: "MuziekInstrumentale muziekVocale muziek Compositie en muziektheorie", categorie: "standaard" },
  { id: "1B-c14-r2-d5", rubricId: "1B-c14-r2", omschrijving: "Media- en audiovisuele kunstenFilm & televisieAnimatieGames en interactieve media", categorie: "standaard" },
  { id: "1B-c14-r2-d6", rubricId: "1B-c14-r2", omschrijving: "Interdisciplinaire en hybride kunsten Installaties Community art Kunst in de publieke ruimte of artistieke participatieprojecten", categorie: "standaard" },
  { id: "1B-c14-r2-d7", rubricId: "1B-c14-r2", omschrijving: "Letterkunde (literaire kunsten)ProzaPoëzie & Drama (als tekstvorm)", categorie: "standaard" },
  { id: "1B-c15-r1-d1", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 1", categorie: "standaard" },
  { id: "1B-c15-r1-d2", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 2", categorie: "standaard" },
  { id: "1B-c15-r1-d3", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 3", categorie: "standaard" },
  { id: "1B-c15-r1-d4", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 4", categorie: "standaard" },
  { id: "1B-c15-r1-d5", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 5", categorie: "standaard" },
  { id: "1B-c15-r1-d6", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 6", categorie: "standaard" },
  { id: "1B-c15-r1-d7", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 7", categorie: "standaard" },
  { id: "1B-c15-r1-d8", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 8", categorie: "standaard" },
  { id: "1B-c15-r1-d9", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 9", categorie: "standaard" },
  { id: "1B-c15-r1-d10", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 10", categorie: "standaard" },
  { id: "1B-c15-r1-d11", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 11", categorie: "standaard" },
  { id: "1B-c15-r1-d12", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 12", categorie: "standaard" },
  { id: "1B-c15-r1-d13", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 13", categorie: "standaard" },
  { id: "1B-c15-r1-d14", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 14", categorie: "standaard" },
  { id: "1B-c15-r1-d15", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 15", categorie: "standaard" },
  { id: "1B-c15-r1-d16", rubricId: "1B-c15-r1", omschrijving: "Leerwandeling of uitstap 16", categorie: "standaard" },
  { id: "1B-c15-r2-d1", rubricId: "1B-c15-r2", omschrijving: "Klasreis 1", categorie: "standaard" },
  { id: "1B-c15-r2-d2", rubricId: "1B-c15-r2", omschrijving: "Klasreis 2", categorie: "standaard" },
  { id: "1B-c16-r1-d1", rubricId: "1B-c16-r1", omschrijving: "Toonmomenten 1", categorie: "standaard" },
  { id: "1B-c16-r1-d2", rubricId: "1B-c16-r1", omschrijving: "Toonmomenten 2", categorie: "standaard" },
  { id: "1B-c16-r1-d3", rubricId: "1B-c16-r1", omschrijving: "Toonmomenten 3", categorie: "standaard" },
  { id: "1B-c16-r1-d4", rubricId: "1B-c16-r1", omschrijving: "Toonmomenten 4", categorie: "standaard" },
  { id: "1B-c16-r2-d1", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 1", categorie: "standaard" },
  { id: "1B-c16-r2-d2", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 2", categorie: "standaard" },
  { id: "1B-c16-r2-d3", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 3", categorie: "standaard" },
  { id: "1B-c16-r2-d4", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 4", categorie: "standaard" },
  { id: "1B-c16-r2-d5", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 5", categorie: "standaard" },
  { id: "1B-c16-r2-d6", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 6", categorie: "standaard" },
  { id: "1B-c16-r2-d7", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 7", categorie: "standaard" },
  { id: "1B-c16-r2-d8", rubricId: "1B-c16-r2", omschrijving: "Leerlingen seminaries 8", categorie: "standaard" },
  { id: "1B-c16-r3-d1", rubricId: "1B-c16-r3", omschrijving: "Externe seminaries 1", categorie: "standaard" },
  { id: "1B-c16-r3-d2", rubricId: "1B-c16-r3", omschrijving: "Externe seminaries 2", categorie: "standaard" },
  { id: "1B-c16-r3-d3", rubricId: "1B-c16-r3", omschrijving: "Externe seminaries 3", categorie: "standaard" },
  { id: "1B-c16-r3-d4", rubricId: "1B-c16-r3", omschrijving: "Externe seminaries 4", categorie: "standaard" },
  { id: "1B-c16-r3-d5", rubricId: "1B-c16-r3", omschrijving: "Externe seminaries 5", categorie: "standaard" },
  { id: "1B-c16-r3-d6", rubricId: "1B-c16-r3", omschrijving: "Externe seminaries 6", categorie: "standaard" },
  { id: "1B-c17-r1-d1", rubricId: "1B-c17-r1", omschrijving: "Thema’s gezondheid", categorie: "standaard" },
  { id: "1B-c17-r1-d2", rubricId: "1B-c17-r1", omschrijving: "Thema 1", categorie: "standaard" },
  { id: "1B-c17-r1-d3", rubricId: "1B-c17-r1", omschrijving: "Thema 2", categorie: "standaard" },
  { id: "1B-c17-r1-d4", rubricId: "1B-c17-r1", omschrijving: "Thema 3", categorie: "standaard" },
  { id: "1B-c17-r1-d5", rubricId: "1B-c17-r1", omschrijving: "Thema 4 EHBO", categorie: "standaard" },
  { id: "1B-c17-r1-d6", rubricId: "1B-c17-r1", omschrijving: "Mentale gezondheid", categorie: "standaard" },
  { id: "1B-c17-r1-d7", rubricId: "1B-c17-r1", omschrijving: "Gezonde levensstijl", categorie: "standaard" },
  { id: "1B-c17-r1-d8", rubricId: "1B-c17-r1", omschrijving: "Thema 4", categorie: "standaard" },
  { id: "1B-c17-r2-d1", rubricId: "1B-c17-r2", omschrijving: "Individuele sporten", categorie: "standaard" },
  { id: "1B-c17-r2-d2", rubricId: "1B-c17-r2", omschrijving: "Sport 1", categorie: "standaard" },
  { id: "1B-c17-r2-d3", rubricId: "1B-c17-r2", omschrijving: "Sport 2", categorie: "standaard" },
  { id: "1B-c17-r2-d4", rubricId: "1B-c17-r2", omschrijving: "Sport 3", categorie: "standaard" },
  { id: "1B-c17-r2-d5", rubricId: "1B-c17-r2", omschrijving: "Sport 4", categorie: "standaard" },
  { id: "1B-c17-r2-d6", rubricId: "1B-c17-r2", omschrijving: "Interactieve beweging", categorie: "standaard" },
  { id: "1B-c17-r2-d7", rubricId: "1B-c17-r2", omschrijving: "Ritmisch expressieve beweging", categorie: "standaard" },
];
