// AUTO-GEGENEREERD via scripts/extract_badges.py
// uit docs/reference/deelevaluaties_alle-graden-2.xlsx — niet met de hand aanpassen.
import type { CursusRuw, BadgeRuw } from "./curriculum";

export const cursussen3A: CursusRuw[] = [
  { id: "3A-planning-en-reflectie", stroom: "3A", naam: "Planning en reflectie", volgorde: 0 },
  { id: "3A-geintegreerde-opdrachten-gop", stroom: "3A", naam: "Geïntegreerde opdrachten (GOP)", volgorde: 1 },
  { id: "3A-trajecten", stroom: "3A", naam: "Trajecten", volgorde: 2 },
  { id: "3A-klaswerking", stroom: "3A", naam: "Klaswerking+", volgorde: 3 },
  { id: "3A-burgerschapsreis", stroom: "3A", naam: "Burgerschapsreis", volgorde: 4 },
  { id: "3A-de-brug-naar-je-leer-toekomst", stroom: "3A", naam: "De brug naar je (leer)toekomst", volgorde: 5 },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes", stroom: "3A", naam: "Vrij initiatief buiten de lijntjes", volgorde: 6 },
];

export const badges3A: BadgeRuw[] = [
  { id: "3A-planning-en-reflectie-d1", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 1", volgorde: 0, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d2", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 2", volgorde: 1, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d3", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 3", volgorde: 2, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d4", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 4", volgorde: 3, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d5", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 5", volgorde: 4, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d6", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 6", volgorde: 5, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d7", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 7", volgorde: 6, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d8", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 8", volgorde: 7, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d9", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 9", volgorde: 8, categorie: "standaard" },
  { id: "3A-planning-en-reflectie-d10", cursusId: "3A-planning-en-reflectie", groep: "Coachinggesprek", omschrijving: "Coachinggesprek 10", volgorde: 9, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d1", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Bruin", omschrijving: "GOP - Bruin", volgorde: 0, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d2", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Rose", omschrijving: "GOP - Rose", volgorde: 1, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d3", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Zwart", omschrijving: "GOP - Zwart", volgorde: 2, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d4", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Grijs", omschrijving: "GOP - Grijs", volgorde: 3, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d5", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Wit", omschrijving: "GOP - Wit", volgorde: 4, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d6", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Kaki", omschrijving: "GOP - Kaki", volgorde: 5, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d7", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Lila", omschrijving: "GOP - Lila", volgorde: 6, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d8", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Paars", omschrijving: "GOP - Paars", volgorde: 7, categorie: "standaard" },
  { id: "3A-geintegreerde-opdrachten-gop-d9", cursusId: "3A-geintegreerde-opdrachten-gop", groep: "GOP - Extra", omschrijving: "GOP - Extra", volgorde: 8, categorie: "standaard" },
  { id: "3A-trajecten-d1", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 1", volgorde: 0, categorie: "standaard" },
  { id: "3A-trajecten-d2", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 2", volgorde: 1, categorie: "standaard" },
  { id: "3A-trajecten-d3", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 3", volgorde: 2, categorie: "standaard" },
  { id: "3A-trajecten-d4", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 4", volgorde: 3, categorie: "standaard" },
  { id: "3A-trajecten-d5", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 5", volgorde: 4, categorie: "standaard" },
  { id: "3A-trajecten-d6", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 6", volgorde: 5, categorie: "standaard" },
  { id: "3A-trajecten-d7", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 7", volgorde: 6, categorie: "standaard" },
  { id: "3A-trajecten-d8", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 8", volgorde: 7, categorie: "standaard" },
  { id: "3A-trajecten-d9", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 9", volgorde: 8, categorie: "standaard" },
  { id: "3A-trajecten-d10", cursusId: "3A-trajecten", groep: "Traject wiskunde en wetenschappen", omschrijving: "Traject wiskunde en wetenschappen 10", volgorde: 9, categorie: "standaard" },
  { id: "3A-klaswerking-d1", cursusId: "3A-klaswerking", groep: "Deelname kring & klasraad (jaarbadge)", omschrijving: "Deelname kring & klasraad (jaarbadge) 1", volgorde: 0, categorie: "standaard" },
  { id: "3A-klaswerking-d2", cursusId: "3A-klaswerking", groep: "Deelname kring & klasraad (jaarbadge)", omschrijving: "Deelname kring & klasraad (jaarbadge) 2", volgorde: 1, categorie: "standaard" },
  { id: "3A-klaswerking-d3", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 1", volgorde: 2, categorie: "standaard" },
  { id: "3A-klaswerking-d4", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 2", volgorde: 3, categorie: "standaard" },
  { id: "3A-klaswerking-d5", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 3", volgorde: 4, categorie: "standaard" },
  { id: "3A-klaswerking-d6", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 4", volgorde: 5, categorie: "standaard" },
  { id: "3A-klaswerking-d7", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 5", volgorde: 6, categorie: "standaard" },
  { id: "3A-klaswerking-d8", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 6", volgorde: 7, categorie: "standaard" },
  { id: "3A-klaswerking-d9", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 7", volgorde: 8, categorie: "standaard" },
  { id: "3A-klaswerking-d10", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 8", volgorde: 9, categorie: "standaard" },
  { id: "3A-klaswerking-d11", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 9", volgorde: 10, categorie: "standaard" },
  { id: "3A-klaswerking-d12", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 10", volgorde: 11, categorie: "standaard" },
  { id: "3A-klaswerking-d13", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 11", volgorde: 12, categorie: "standaard" },
  { id: "3A-klaswerking-d14", cursusId: "3A-klaswerking", groep: "Taken klaswerking (Units)", omschrijving: "Taken klaswerking (Units) 12", volgorde: 13, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d1", cursusId: "3A-burgerschapsreis", groep: "Communicatie - Deelname aan voorstellingsdag", omschrijving: "Communicatie - Deelname aan voorstellingsdag", volgorde: 0, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d2", cursusId: "3A-burgerschapsreis", groep: "Vrije tekst - motivatiebrief (Engels of Frans)", omschrijving: "Vrije tekst - motivatiebrief (Engels of Frans)", volgorde: 1, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d3", cursusId: "3A-burgerschapsreis", groep: "Exploratie - Deelname aan de selectietweedaagse", omschrijving: "Exploratie - Deelname aan de selectietweedaagse", volgorde: 2, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d4", cursusId: "3A-burgerschapsreis", groep: "Klasraad en klaskas - Deelname aan de fondsenwerving", omschrijving: "Klasraad en klaskas - Deelname aan de fondsenwerving", volgorde: 3, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d5", cursusId: "3A-burgerschapsreis", groep: "Klasraad en klaskas - Inzicht in het budget van de reis", omschrijving: "Klasraad en klaskas - Inzicht in het budget van de reis", volgorde: 4, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d6", cursusId: "3A-burgerschapsreis", groep: "GOP met taken die horen bij je reis", omschrijving: "GOP met taken die horen bij je reis", volgorde: 5, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d7", cursusId: "3A-burgerschapsreis", groep: "Exploratie - Deelname aan de reis", omschrijving: "Exploratie - Deelname aan de reis", volgorde: 6, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d8", cursusId: "3A-burgerschapsreis", groep: "Burgerschap intern - Inzet voor de groep tijdens de reis", omschrijving: "Burgerschap intern - Inzet voor de groep tijdens de reis", volgorde: 7, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d9", cursusId: "3A-burgerschapsreis", groep: "Burgerschap extern - Inzet voor de projecten tijdens de reis", omschrijving: "Burgerschap extern - Inzet voor de projecten tijdens de reis", volgorde: 8, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d10", cursusId: "3A-burgerschapsreis", groep: "Cultuur - Verwerking via artistieke creaties", omschrijving: "Cultuur - Verwerking via artistieke creaties", volgorde: 9, categorie: "standaard" },
  { id: "3A-burgerschapsreis-d11", cursusId: "3A-burgerschapsreis", groep: "Toonmoment - Deelname aan Toonmoment", omschrijving: "Toonmoment - Deelname aan Toonmoment", volgorde: 10, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d1", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "30 dagdelen persoonlijke brug", omschrijving: "30 dagdelen persoonlijke brug", volgorde: 0, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d2", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Ervaringsweek - uitvoering (minimaal 8 dagdelen)", omschrijving: "Ervaringsweek - uitvoering (minimaal 8 dagdelen) 1", volgorde: 1, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d3", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Ervaringsweek - uitvoering (minimaal 8 dagdelen)", omschrijving: "Ervaringsweek - uitvoering (minimaal 8 dagdelen) 2", volgorde: 2, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d4", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Ervaringsweek - verslag", omschrijving: "Ervaringsweek - verslag 1", volgorde: 3, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d5", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Ervaringsweek - verslag", omschrijving: "Ervaringsweek - verslag 2", volgorde: 4, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d6", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Goedgekeurd thema", omschrijving: "Eigen onderzoek - Goedgekeurd thema", volgorde: 5, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d7", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Boekenronde", omschrijving: "Eigen onderzoek - Boekenronde 1", volgorde: 6, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d8", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Boekenronde", omschrijving: "Eigen onderzoek - Boekenronde 2", volgorde: 7, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d9", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Boekenronde", omschrijving: "Eigen onderzoek - Boekenronde 3", volgorde: 8, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d10", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Actuaronde", omschrijving: "Eigen onderzoek - Actuaronde 1", volgorde: 9, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d11", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Actuaronde", omschrijving: "Eigen onderzoek - Actuaronde 2", volgorde: 10, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d12", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Actuaronde", omschrijving: "Eigen onderzoek - Actuaronde 3", volgorde: 11, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d13", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Paper", omschrijving: "Eigen onderzoek - Paper", volgorde: 12, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d14", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Concrete voorstelling", omschrijving: "Eigen onderzoek - Concrete voorstelling", volgorde: 13, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d15", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Eigen onderzoek - Actuaronde", omschrijving: "Eigen onderzoek - Actuaronde", volgorde: 14, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d16", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Concrete voorstelling", omschrijving: "Concrete voorstelling", volgorde: 15, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d17", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 1", volgorde: 16, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d18", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 2", volgorde: 17, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d19", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 3", volgorde: 18, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d20", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 4", volgorde: 19, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d21", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 5", volgorde: 20, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d22", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 6", volgorde: 21, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d23", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 7", volgorde: 22, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d24", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 8", volgorde: 23, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d25", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Lesactiviteit", omschrijving: "Lesactiviteit 9", volgorde: 24, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d26", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Persoonlijke vragenlijst", omschrijving: "Persoonlijke vragenlijst", volgorde: 25, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d27", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Mondelinge proef & portfolio", omschrijving: "Mondelinge proef & portfolio", volgorde: 26, categorie: "standaard" },
  { id: "3A-de-brug-naar-je-leer-toekomst-d28", cursusId: "3A-de-brug-naar-je-leer-toekomst", groep: "Extra", omschrijving: "Extra", volgorde: 27, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d1", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 1", volgorde: 0, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d2", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 2", volgorde: 1, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d3", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 3", volgorde: 2, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d4", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 4", volgorde: 3, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d5", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 5", volgorde: 4, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d6", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 6", volgorde: 5, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d7", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 7", volgorde: 6, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d8", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 8", volgorde: 7, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d9", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 9", volgorde: 8, categorie: "standaard" },
  { id: "3A-vrij-initiatief-buiten-de-lijntjes-d10", cursusId: "3A-vrij-initiatief-buiten-de-lijntjes", groep: "Vrij initiatief buiten de lijntjes", omschrijving: "Vrij initiatief buiten de lijntjes 10", volgorde: 9, categorie: "standaard" },
];
