// AUTO-GEGENEREERD via scripts/extract_deelevaluaties.py
// uit docs/reference/deelevaluaties_alle-graden.xlsx — niet met de hand aanpassen.
import type { Stroom } from "./types";

/**
 * Een *type* deelevaluatie (deelbadge): per stroom en cursus, met het richtaantal en
 * het verplichte aantal dat een leerling moet halen. Dit is de kapstok waaronder
 * leerkrachten in de app hun concrete toetsen/opdrachten aanmaken.
 */
export interface DeelevaluatieType {
  id: string;
  stroom: Stroom;
  cursus: string;
  naam: string;
  /** Richtaantal: hoeveel er in totaal kunnen worden aangeboden. */
  richtaantal: number;
  /** Verplicht aantal om de cursus af te ronden. */
  verplicht: number;
}

export const deelevaluatieTypes: DeelevaluatieType[] = [
  { id: "det-1A-1", stroom: "1A", cursus: "Planning en reflectie", naam: "Coachinggesprek", richtaantal: 10, verplicht: 6 },
  { id: "det-1A-2", stroom: "1A", cursus: "Klasraad", naam: "Voorzitter", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-3", stroom: "1A", cursus: "Klasraad", naam: "Secretaris", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-4", stroom: "1A", cursus: "Klasraad", naam: "Tijdsbewaker", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-5", stroom: "1A", cursus: "Klasraad", naam: "Deelnemer (wekelijks)", richtaantal: 6, verplicht: 5 },
  { id: "det-1A-6", stroom: "1A", cursus: "Klasraad", naam: "Vestigingsraad/Keerpuntraad/Leerlingenraad", richtaantal: 1, verplicht: 0 },
  { id: "det-1A-7", stroom: "1A", cursus: "Burgerschap", naam: "Intern burgerschap", richtaantal: 10, verplicht: 10 },
  { id: "det-1A-8", stroom: "1A", cursus: "Burgerschap", naam: "Extern burgerschap (2 lestijden)", richtaantal: 12, verplicht: 8 },
  { id: "det-1A-9", stroom: "1A", cursus: "Ateliers", naam: "Natuur", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-10", stroom: "1A", cursus: "Ateliers", naam: "Handvaardigheid, bouw & techniek", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-11", stroom: "1A", cursus: "Ateliers", naam: "Kennis", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-12", stroom: "1A", cursus: "Ateliers", naam: "Experimenten, wetenschappelijk onderzoek & innovatie", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-13", stroom: "1A", cursus: "Ateliers", naam: "ICT, digitale & moderne technieken", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-14", stroom: "1A", cursus: "Ateliers", naam: "Expressie, creatie & ontwerp", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-15", stroom: "1A", cursus: "Ateliers", naam: "Welzijn en andere", richtaantal: 5, verplicht: 1 },
  { id: "det-1A-16", stroom: "1A", cursus: "Ateliers", naam: "Eén atelier volgen in elk van de 7 domeinen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-17", stroom: "1A", cursus: "Kring", naam: "Voorzitter", richtaantal: 5, verplicht: 2 },
  { id: "det-1A-18", stroom: "1A", cursus: "Kring", naam: "Secretaris", richtaantal: 5, verplicht: 2 },
  { id: "det-1A-19", stroom: "1A", cursus: "Kring", naam: "Tijdsbewaker", richtaantal: 5, verplicht: 2 },
  { id: "det-1A-20", stroom: "1A", cursus: "Kring", naam: "Deelnemer (wekelijks)", richtaantal: 6, verplicht: 5 },
  { id: "det-1A-21", stroom: "1A", cursus: "Kring", naam: "Kring Frans", richtaantal: 4, verplicht: 2 },
  { id: "det-1A-22", stroom: "1A", cursus: "Kring", naam: "Kring Engels", richtaantal: 4, verplicht: 2 },
  { id: "det-1A-23", stroom: "1A", cursus: "Actuaronde", naam: "Actuarondes Nederlands", richtaantal: 8, verplicht: 6 },
  { id: "det-1A-24", stroom: "1A", cursus: "Actuaronde", naam: "Actuarondes Frans", richtaantal: 2, verplicht: 2 },
  { id: "det-1A-25", stroom: "1A", cursus: "Actuaronde", naam: "Actuarondes Engels", richtaantal: 2, verplicht: 2 },
  { id: "det-1A-26", stroom: "1A", cursus: "Vrije Tekst", naam: "Vrije teksten Nederlands", richtaantal: 10, verplicht: 6 },
  { id: "det-1A-27", stroom: "1A", cursus: "Vrije Tekst", naam: "Vrije teksten Frans", richtaantal: 6, verplicht: 3 },
  { id: "det-1A-28", stroom: "1A", cursus: "Vrije Tekst", naam: "Vrije teksten Engels", richtaantal: 6, verplicht: 3 },
  { id: "det-1A-29", stroom: "1A", cursus: "Boekenronde", naam: "Boekenrondes Nederlands", richtaantal: 8, verplicht: 6 },
  { id: "det-1A-30", stroom: "1A", cursus: "Boekenronde", naam: "Boekenrondes Frans", richtaantal: 3, verplicht: 2 },
  { id: "det-1A-31", stroom: "1A", cursus: "Boekenronde", naam: "Boekenrondes Engels", richtaantal: 3, verplicht: 2 },
  { id: "det-1A-32", stroom: "1A", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties", richtaantal: 5, verplicht: 5 },
  { id: "det-1A-33", stroom: "1A", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Frans", richtaantal: 3, verplicht: 3 },
  { id: "det-1A-34", stroom: "1A", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Engels", richtaantal: 2, verplicht: 2 },
  { id: "det-1A-35", stroom: "1A", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern", richtaantal: 4, verplicht: 2 },
  { id: "det-1A-36", stroom: "1A", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern Frans", richtaantal: 2, verplicht: 1 },
  { id: "det-1A-37", stroom: "1A", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern Engels", richtaantal: 2, verplicht: 1 },
  { id: "det-1A-38", stroom: "1A", cursus: "Onderzoek", naam: "Kwaliteitsvol onderzoek", richtaantal: 14, verplicht: 12 },
  { id: "det-1A-39", stroom: "1A", cursus: "Onderzoek", naam: "Historisch - Algemene periodisering", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-40", stroom: "1A", cursus: "Onderzoek", naam: "Historisch - Niet-Westerse periodisering", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-41", stroom: "1A", cursus: "Onderzoek", naam: "Historisch - Prehistorie: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-42", stroom: "1A", cursus: "Onderzoek", naam: "Historisch - Oude Nabije Oosten: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-43", stroom: "1A", cursus: "Onderzoek", naam: "Historisch - Klassieke Oudheid: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-44", stroom: "1A", cursus: "Onderzoek", naam: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-45", stroom: "1A", cursus: "Onderzoek", naam: "Ruimtelijk - Geografische eenheden: landschappen, reliëf, ondergrond, klimaat, vegetatie", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-46", stroom: "1A", cursus: "Onderzoek", naam: "Ruimtelijk - Evolutie en verandering", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-47", stroom: "1A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Deeltjesmodel", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-48", stroom: "1A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Krachten, energie, stralingen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-49", stroom: "1A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Opbouw en functioneren van organismen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-50", stroom: "1A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-51", stroom: "1A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Biotopen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-52", stroom: "1A", cursus: "Onderzoek", naam: "Techniek/technologie - Eigenschappen van materialen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-53", stroom: "1A", cursus: "Onderzoek", naam: "Techniek/technologie - Technische processen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-54", stroom: "1A", cursus: "Onderzoek", naam: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-55", stroom: "1A", cursus: "Onderzoek", naam: "Duurzaamheid bij technische systemen", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-56", stroom: "1A", cursus: "Onderzoek", naam: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-57", stroom: "1A", cursus: "Onderzoek", naam: "Economie - Gezinsbudget", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-58", stroom: "1A", cursus: "Onderzoek", naam: "Economie - Maatschappelijke thema’s", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-59", stroom: "1A", cursus: "Klaskas", naam: "Klaskas projecten", richtaantal: 6, verplicht: 4 },
  { id: "det-1A-60", stroom: "1A", cursus: "Levende Wiskunde", naam: "Levende Wiskunde activiteit", richtaantal: 6, verplicht: 6 },
  { id: "det-1A-61", stroom: "1A", cursus: "Levende Wiskunde", naam: "Wiskundig onderzoek", richtaantal: 6, verplicht: 6 },
  { id: "det-1A-62", stroom: "1A", cursus: "Levende Wiskunde", naam: "Getallenleer - Schatten en benaderen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-63", stroom: "1A", cursus: "Levende Wiskunde", naam: "Getallenleer - Ordenen van getallen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-64", stroom: "1A", cursus: "Levende Wiskunde", naam: "Getallenleer - Bewerkingen en rekenregels (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-65", stroom: "1A", cursus: "Levende Wiskunde", naam: "Getallenleer - Rekenen met machten (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-66", stroom: "1A", cursus: "Levende Wiskunde", naam: "Meetkunde - Vlakke meetkunde (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-67", stroom: "1A", cursus: "Levende Wiskunde", naam: "Meetkunde - Ruimtemeetkunde (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-68", stroom: "1A", cursus: "Levende Wiskunde", naam: "Meetkunde - Transformaties (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-69", stroom: "1A", cursus: "Levende Wiskunde", naam: "Meetkunde - Coördinaten (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-70", stroom: "1A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Rekenen met lettervormen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-71", stroom: "1A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Letters als onbekenden (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-72", stroom: "1A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Verbanden en evenredigheid (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-73", stroom: "1A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Vergelijkingen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-74", stroom: "1A", cursus: "Levende Wiskunde", naam: "Statistiek (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-75", stroom: "1A", cursus: "Levende Wiskunde", naam: "Verzamelingenleer (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-76", stroom: "1A", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in de prehistorie", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-77", stroom: "1A", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in het Oude Nabije Oosten", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-78", stroom: "1A", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in de Klassieke Oudheid", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-79", stroom: "1A", cursus: "Cultuur", naam: "Kunstbeschouwing - Niet-Westerse kunst", richtaantal: 2, verplicht: 2 },
  { id: "det-1A-80", stroom: "1A", cursus: "Cultuur", naam: "Kunstbeschouwing - Onderwerp naar keuze", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-81", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - toegepaste kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-82", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - beeldende kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-83", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - podiumkunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-84", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - muziek", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-85", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - media en audiovisueel", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-86", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - interdisciplinair of hybride", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-87", stroom: "1A", cursus: "Cultuur", naam: "Vrije expressie - literair", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-88", stroom: "1A", cursus: "Exploratie", naam: "Leerwandelingen & uitstappen", richtaantal: 18, verplicht: 16 },
  { id: "det-1A-89", stroom: "1A", cursus: "Exploratie", naam: "Klasreizen", richtaantal: 2, verplicht: 2 },
  { id: "det-1A-90", stroom: "1A", cursus: "Toonmoment", naam: "Toonmomenten", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-91", stroom: "1A", cursus: "Toonmoment", naam: "Leerlingenseminaries", richtaantal: 8, verplicht: 8 },
  { id: "det-1A-92", stroom: "1A", cursus: "Toonmoment", naam: "Externe seminaries", richtaantal: 6, verplicht: 6 },
  { id: "det-1A-93", stroom: "1A", cursus: "Welzijn", naam: "Gezondheid", richtaantal: 3, verplicht: 3 },
  { id: "det-1A-94", stroom: "1A", cursus: "Welzijn", naam: "Gezondheid - EHBO", richtaantal: 1, verplicht: 1 },
  { id: "det-1A-95", stroom: "1A", cursus: "Welzijn", naam: "Mentale gezondheid", richtaantal: 2, verplicht: 2 },
  { id: "det-1A-96", stroom: "1A", cursus: "Welzijn", naam: "Gezonde levensstijl", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-97", stroom: "1A", cursus: "Welzijn", naam: "Individuele sporten", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-98", stroom: "1A", cursus: "Welzijn", naam: "Interactieve beweging", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-99", stroom: "1A", cursus: "Welzijn", naam: "Ritmisch expressieve beweging", richtaantal: 4, verplicht: 4 },
  { id: "det-1A-100", stroom: "1A", cursus: "Basisfreinetvaardigheden", naam: "Basisfreinetvaardigheden", richtaantal: 6, verplicht: 6 },
  { id: "det-1A-101", stroom: "1A", cursus: "Vrije initiatieven buiten de lijntjes", naam: "Vrije initiatieven buiten de lijntjes", richtaantal: 10, verplicht: 0 },
  { id: "det-1B-102", stroom: "1B", cursus: "Planning en reflectie", naam: "Coachinggesprek", richtaantal: 10, verplicht: 6 },
  { id: "det-1B-103", stroom: "1B", cursus: "Klasraad", naam: "Voorzitter", richtaantal: 4, verplicht: 2 },
  { id: "det-1B-104", stroom: "1B", cursus: "Klasraad", naam: "Secretaris", richtaantal: 4, verplicht: 2 },
  { id: "det-1B-105", stroom: "1B", cursus: "Klasraad", naam: "Tijdsbewaker", richtaantal: 4, verplicht: 2 },
  { id: "det-1B-106", stroom: "1B", cursus: "Klasraad", naam: "Deelnemer (wekelijks)", richtaantal: 6, verplicht: 5 },
  { id: "det-1B-107", stroom: "1B", cursus: "Klasraad", naam: "Vestigingsraad/Keerpuntraad/Leerlingenraad", richtaantal: 1, verplicht: 0 },
  { id: "det-1B-108", stroom: "1B", cursus: "Burgerschap", naam: "Intern burgerschap", richtaantal: 10, verplicht: 10 },
  { id: "det-1B-109", stroom: "1B", cursus: "Burgerschap", naam: "Extern burgerschap (2 lestijden)", richtaantal: 12, verplicht: 8 },
  { id: "det-1B-110", stroom: "1B", cursus: "Ateliers", naam: "Natuur", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-111", stroom: "1B", cursus: "Ateliers", naam: "Handvaardigheid, bouw & techniek", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-112", stroom: "1B", cursus: "Ateliers", naam: "Kennis", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-113", stroom: "1B", cursus: "Ateliers", naam: "Experimenten, wetenschappelijk onderzoek & innovatie", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-114", stroom: "1B", cursus: "Ateliers", naam: "ICT, digitale & moderne technieken", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-115", stroom: "1B", cursus: "Ateliers", naam: "Expressie, creatie & ontwerp", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-116", stroom: "1B", cursus: "Ateliers", naam: "Welzijn en andere", richtaantal: 5, verplicht: 1 },
  { id: "det-1B-117", stroom: "1B", cursus: "Ateliers", naam: "Eén atelier volgen in elk van de 7 domeinen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-118", stroom: "1B", cursus: "Kring", naam: "Voorzitter", richtaantal: 5, verplicht: 2 },
  { id: "det-1B-119", stroom: "1B", cursus: "Kring", naam: "Secretaris", richtaantal: 5, verplicht: 2 },
  { id: "det-1B-120", stroom: "1B", cursus: "Kring", naam: "Tijdsbewaker", richtaantal: 5, verplicht: 2 },
  { id: "det-1B-121", stroom: "1B", cursus: "Kring", naam: "Deelnemer (wekelijks)", richtaantal: 6, verplicht: 5 },
  { id: "det-1B-122", stroom: "1B", cursus: "Kring", naam: "Kring Frans", richtaantal: 4, verplicht: 2 },
  { id: "det-1B-123", stroom: "1B", cursus: "Kring", naam: "Kring Engels", richtaantal: 4, verplicht: 2 },
  { id: "det-1B-124", stroom: "1B", cursus: "Actuaronde", naam: "Actuarondes Nederlands", richtaantal: 8, verplicht: 6 },
  { id: "det-1B-125", stroom: "1B", cursus: "Actuaronde", naam: "Actuarondes Frans", richtaantal: 2, verplicht: 2 },
  { id: "det-1B-126", stroom: "1B", cursus: "Actuaronde", naam: "Actuarondes Engels", richtaantal: 2, verplicht: 2 },
  { id: "det-1B-127", stroom: "1B", cursus: "Vrije Tekst", naam: "Vrije teksten Nederlands", richtaantal: 10, verplicht: 6 },
  { id: "det-1B-128", stroom: "1B", cursus: "Vrije Tekst", naam: "Vrije teksten Frans", richtaantal: 6, verplicht: 3 },
  { id: "det-1B-129", stroom: "1B", cursus: "Vrije Tekst", naam: "Vrije teksten Engels", richtaantal: 6, verplicht: 3 },
  { id: "det-1B-130", stroom: "1B", cursus: "Boekenronde", naam: "Boekenrondes Nederlands", richtaantal: 8, verplicht: 6 },
  { id: "det-1B-131", stroom: "1B", cursus: "Boekenronde", naam: "Boekenrondes Frans", richtaantal: 3, verplicht: 2 },
  { id: "det-1B-132", stroom: "1B", cursus: "Boekenronde", naam: "Boekenrondes Engels", richtaantal: 3, verplicht: 2 },
  { id: "det-1B-133", stroom: "1B", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties", richtaantal: 5, verplicht: 5 },
  { id: "det-1B-134", stroom: "1B", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Frans", richtaantal: 3, verplicht: 3 },
  { id: "det-1B-135", stroom: "1B", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Engels", richtaantal: 2, verplicht: 2 },
  { id: "det-1B-136", stroom: "1B", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern", richtaantal: 4, verplicht: 2 },
  { id: "det-1B-137", stroom: "1B", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern Frans", richtaantal: 2, verplicht: 1 },
  { id: "det-1B-138", stroom: "1B", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern Engels", richtaantal: 2, verplicht: 1 },
  { id: "det-1B-139", stroom: "1B", cursus: "Onderzoek", naam: "Kwaliteitsvol onderzoek", richtaantal: 14, verplicht: 12 },
  { id: "det-1B-140", stroom: "1B", cursus: "Onderzoek", naam: "Historisch - Algemene periodisering", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-141", stroom: "1B", cursus: "Onderzoek", naam: "Historisch - Niet-Westerse periodisering", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-142", stroom: "1B", cursus: "Onderzoek", naam: "Historisch - Prehistorie: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-143", stroom: "1B", cursus: "Onderzoek", naam: "Historisch - Oude Nabije Oosten: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-144", stroom: "1B", cursus: "Onderzoek", naam: "Historisch - Klassieke Oudheid: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-145", stroom: "1B", cursus: "Onderzoek", naam: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-146", stroom: "1B", cursus: "Onderzoek", naam: "Ruimtelijk - Geografische eenheden: landschappen, reliëf, ondergrond, klimaat, vegetatie", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-147", stroom: "1B", cursus: "Onderzoek", naam: "Ruimtelijk - Evolutie en verandering", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-148", stroom: "1B", cursus: "Onderzoek", naam: "Exacte wetenschappen - Deeltjesmodel", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-149", stroom: "1B", cursus: "Onderzoek", naam: "Exacte wetenschappen - Krachten, energie, stralingen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-150", stroom: "1B", cursus: "Onderzoek", naam: "Exacte wetenschappen - Opbouw en functioneren van organismen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-151", stroom: "1B", cursus: "Onderzoek", naam: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-152", stroom: "1B", cursus: "Onderzoek", naam: "Exacte wetenschappen - Biotopen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-153", stroom: "1B", cursus: "Onderzoek", naam: "Techniek/technologie - Eigenschappen van materialen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-154", stroom: "1B", cursus: "Onderzoek", naam: "Techniek/technologie - Technische processen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-155", stroom: "1B", cursus: "Onderzoek", naam: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-156", stroom: "1B", cursus: "Onderzoek", naam: "Duurzaamheid bij technische systemen", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-157", stroom: "1B", cursus: "Onderzoek", naam: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-158", stroom: "1B", cursus: "Onderzoek", naam: "Economie - Gezinsbudget", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-159", stroom: "1B", cursus: "Onderzoek", naam: "Economie - Maatschappelijke thema’s", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-160", stroom: "1B", cursus: "Klaskas", naam: "Klaskas projecten", richtaantal: 6, verplicht: 4 },
  { id: "det-1B-161", stroom: "1B", cursus: "Levende Wiskunde", naam: "Levende Wiskunde activiteit", richtaantal: 6, verplicht: 6 },
  { id: "det-1B-162", stroom: "1B", cursus: "Levende Wiskunde", naam: "Wiskundig onderzoek", richtaantal: 4, verplicht: 4 },
  { id: "det-1B-163", stroom: "1B", cursus: "Levende Wiskunde", naam: "Getallenleer - Schatten en benaderen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-164", stroom: "1B", cursus: "Levende Wiskunde", naam: "Getallenleer - Ordenen van getallen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-165", stroom: "1B", cursus: "Levende Wiskunde", naam: "Getallenleer - Bewerkingen en rekenregels (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-166", stroom: "1B", cursus: "Levende Wiskunde", naam: "Getallenleer - Maatgetallen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-167", stroom: "1B", cursus: "Levende Wiskunde", naam: "Meetkunde - Vlakke meetkunde (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-168", stroom: "1B", cursus: "Levende Wiskunde", naam: "Meetkunde - Ruimtemeetkunde (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-169", stroom: "1B", cursus: "Levende Wiskunde", naam: "Meetkunde - Coördinaten (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-170", stroom: "1B", cursus: "Levende Wiskunde", naam: "Statistiek (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-171", stroom: "1B", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in prehistorie", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-172", stroom: "1B", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in Oude Nabije Oosten", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-173", stroom: "1B", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in Klassieke Oudheid", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-174", stroom: "1B", cursus: "Cultuur", naam: "Kunstbeschouwing - Niet-Westerse kunst", richtaantal: 2, verplicht: 2 },
  { id: "det-1B-175", stroom: "1B", cursus: "Cultuur", naam: "Kunstbeschouwing - Onderwerp naar keuze", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-176", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - toegepaste kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-177", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - beeldende kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-178", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - podiumkunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-179", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - muziek", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-180", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - media en audiovisueel", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-181", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - interdisciplinair of hybride", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-182", stroom: "1B", cursus: "Cultuur", naam: "Vrije expressie - literair", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-183", stroom: "1B", cursus: "Exploratie", naam: "Leerwandelingen & uitstappen", richtaantal: 18, verplicht: 16 },
  { id: "det-1B-184", stroom: "1B", cursus: "Exploratie", naam: "Klasreizen", richtaantal: 2, verplicht: 1 },
  { id: "det-1B-185", stroom: "1B", cursus: "Toonmoment", naam: "Toonmomenten", richtaantal: 4, verplicht: 4 },
  { id: "det-1B-186", stroom: "1B", cursus: "Toonmoment", naam: "Leerlingenseminaries", richtaantal: 8, verplicht: 4 },
  { id: "det-1B-187", stroom: "1B", cursus: "Toonmoment", naam: "Externe seminaries", richtaantal: 6, verplicht: 6 },
  { id: "det-1B-188", stroom: "1B", cursus: "Welzijn", naam: "Gezondheid", richtaantal: 3, verplicht: 3 },
  { id: "det-1B-189", stroom: "1B", cursus: "Welzijn", naam: "Gezondheid - EHBO", richtaantal: 1, verplicht: 1 },
  { id: "det-1B-190", stroom: "1B", cursus: "Welzijn", naam: "Mentale gezondheid", richtaantal: 2, verplicht: 2 },
  { id: "det-1B-191", stroom: "1B", cursus: "Welzijn", naam: "Gezonde levensstijl", richtaantal: 4, verplicht: 4 },
  { id: "det-1B-192", stroom: "1B", cursus: "Welzijn", naam: "Individuele sporten", richtaantal: 4, verplicht: 4 },
  { id: "det-1B-193", stroom: "1B", cursus: "Welzijn", naam: "Interactieve beweging", richtaantal: 4, verplicht: 4 },
  { id: "det-1B-194", stroom: "1B", cursus: "Welzijn", naam: "Ritmisch expressieve beweging", richtaantal: 4, verplicht: 4 },
  { id: "det-1B-195", stroom: "1B", cursus: "Basisfreinetvaardigheden", naam: "Basisfreinetvaardigheden", richtaantal: 6, verplicht: 6 },
  { id: "det-1B-196", stroom: "1B", cursus: "Vrije initiatieven buiten de lijntjes", naam: "Vrije initiatieven buiten de lijntjes", richtaantal: 10, verplicht: 0 },
  { id: "det-2A-197", stroom: "2A", cursus: "Planning en reflectie", naam: "Coachinggesprek", richtaantal: 10, verplicht: 6 },
  { id: "det-2A-198", stroom: "2A", cursus: "Klasraad", naam: "Voorzitter", richtaantal: 5, verplicht: 2 },
  { id: "det-2A-199", stroom: "2A", cursus: "Klasraad", naam: "Secretaris", richtaantal: 5, verplicht: 2 },
  { id: "det-2A-200", stroom: "2A", cursus: "Klasraad", naam: "Deelnemer (wekelijks)", richtaantal: 5, verplicht: 5 },
  { id: "det-2A-201", stroom: "2A", cursus: "Klasraad", naam: "Vestigingsraad/Keerpuntraad/Leerlingenraad", richtaantal: 1, verplicht: 0 },
  { id: "det-2A-202", stroom: "2A", cursus: "Burgerschap", naam: "Intern burgerschap", richtaantal: 10, verplicht: 10 },
  { id: "det-2A-203", stroom: "2A", cursus: "Burgerschap", naam: "Extern burgerschap (per 2 lestijden)", richtaantal: 12, verplicht: 10 },
  { id: "det-2A-204", stroom: "2A", cursus: "Burgerschap", naam: "Werkstuk mensenrechten", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-205", stroom: "2A", cursus: "Burgerschap", naam: "Bezoek democratisch orgaan", richtaantal: 2, verplicht: 2 },
  { id: "det-2A-206", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Deelname focusatelier", richtaantal: 8, verplicht: 8 },
  { id: "det-2A-207", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Natuur", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-208", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Handvaardigheid, bouw & techniek", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-209", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Kennis", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-210", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Experimenten, wetenschappelijk onderzoek & innovatie", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-211", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - ICT, digitale & moderne technieken", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-212", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Expressie, creatie & ontwerp", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-213", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Welzijn en andere", richtaantal: 4, verplicht: 1 },
  { id: "det-2A-214", stroom: "2A", cursus: "Focusateliers & vrije ateliers", naam: "Vrije ateliers - Nadruk ligt op je focus of is gespreid over de domeinen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-215", stroom: "2A", cursus: "Kring", naam: "Voorzitter", richtaantal: 5, verplicht: 2 },
  { id: "det-2A-216", stroom: "2A", cursus: "Kring", naam: "Secretaris", richtaantal: 5, verplicht: 2 },
  { id: "det-2A-217", stroom: "2A", cursus: "Kring", naam: "Deelnemer (wekelijks)", richtaantal: 6, verplicht: 5 },
  { id: "det-2A-218", stroom: "2A", cursus: "Kring", naam: "Kring Frans", richtaantal: 3, verplicht: 1 },
  { id: "det-2A-219", stroom: "2A", cursus: "Kring", naam: "Kring Engels", richtaantal: 3, verplicht: 1 },
  { id: "det-2A-220", stroom: "2A", cursus: "Actuaronde", naam: "Actuarondes Nederlands", richtaantal: 9, verplicht: 8 },
  { id: "det-2A-221", stroom: "2A", cursus: "Actuaronde", naam: "Actuarondes Frans", richtaantal: 3, verplicht: 2 },
  { id: "det-2A-222", stroom: "2A", cursus: "Actuaronde", naam: "Actuarondes Engels", richtaantal: 3, verplicht: 2 },
  { id: "det-2A-223", stroom: "2A", cursus: "Vrije Tekst", naam: "Vrije teksten Nederlands", richtaantal: 10, verplicht: 6 },
  { id: "det-2A-224", stroom: "2A", cursus: "Vrije Tekst", naam: "Vrije teksten Frans", richtaantal: 6, verplicht: 3 },
  { id: "det-2A-225", stroom: "2A", cursus: "Vrije Tekst", naam: "Vrije teksten Engels", richtaantal: 6, verplicht: 3 },
  { id: "det-2A-226", stroom: "2A", cursus: "Boekenronde", naam: "Boekenrondes Nederlands", richtaantal: 8, verplicht: 6 },
  { id: "det-2A-227", stroom: "2A", cursus: "Boekenronde", naam: "Boekenrondes Frans", richtaantal: 3, verplicht: 2 },
  { id: "det-2A-228", stroom: "2A", cursus: "Boekenronde", naam: "Boekenrondes Engels", richtaantal: 3, verplicht: 2 },
  { id: "det-2A-229", stroom: "2A", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Nederlands", richtaantal: 3, verplicht: 1 },
  { id: "det-2A-230", stroom: "2A", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Frans", richtaantal: 3, verplicht: 1 },
  { id: "det-2A-231", stroom: "2A", cursus: "Communicatie", naam: "Krant/Correspondentie publicaties Engels", richtaantal: 3, verplicht: 1 },
  { id: "det-2A-232", stroom: "2A", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern", richtaantal: 4, verplicht: 2 },
  { id: "det-2A-233", stroom: "2A", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern Frans", richtaantal: 2, verplicht: 1 },
  { id: "det-2A-234", stroom: "2A", cursus: "Communicatie", naam: "Activiteit Keerpunt/extern Engels", richtaantal: 2, verplicht: 1 },
  { id: "det-2A-235", stroom: "2A", cursus: "Onderzoek", naam: "Kwaliteitsvol onderzoek (individueel en coöperatief)", richtaantal: 14, verplicht: 12 },
  { id: "det-2A-236", stroom: "2A", cursus: "Onderzoek", naam: "Exacte wetenschappen laboreeksen", richtaantal: 2, verplicht: 2 },
  { id: "det-2A-237", stroom: "2A", cursus: "Onderzoek", naam: "Historisch - Algemene periodisering", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-238", stroom: "2A", cursus: "Onderzoek", naam: "Historisch - Niet-Westerse periodisering", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-239", stroom: "2A", cursus: "Onderzoek", naam: "Historisch - Historische beeldvorming", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-240", stroom: "2A", cursus: "Onderzoek", naam: "Historisch - Evalueren van historische bronnen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-241", stroom: "2A", cursus: "Onderzoek", naam: "Historisch - Middeleeuwen: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-242", stroom: "2A", cursus: "Onderzoek", naam: "Historisch - Vroegmoderne tijd: politiek, sociaal, economisch, cultureel", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-243", stroom: "2A", cursus: "Onderzoek", naam: "Ruimtelijk - Lokalisatie en situering: geografisch en schaalniveau", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-244", stroom: "2A", cursus: "Onderzoek", naam: "Ruimtelijk - Demografische en economische processen & gevolgen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-245", stroom: "2A", cursus: "Onderzoek", naam: "Ruimtelijk - Evolutie en verandering", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-246", stroom: "2A", cursus: "Onderzoek", naam: "Exacte wetenschappen - PSE: atoommodel, chemische formules, stoffen en eigenschappen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-247", stroom: "2A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Krachten, energie, stralingen, elektriciteit", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-248", stroom: "2A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Opbouw en functioneren van organismen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-249", stroom: "2A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Voortplanting van planten, dieren, mensen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-250", stroom: "2A", cursus: "Onderzoek", naam: "Exacte wetenschappen - Biotopen & ecosystemen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-251", stroom: "2A", cursus: "Onderzoek", naam: "Techniek/technologie - Eigenschappen van materialen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-252", stroom: "2A", cursus: "Onderzoek", naam: "Techniek/technologie - Natuurlijke & technische systemen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-253", stroom: "2A", cursus: "Onderzoek", naam: "Techniek/technologie - Uitvoeren van technische systemen: vereisten, ontwerpen, realiseren, evalueren", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-254", stroom: "2A", cursus: "Onderzoek", naam: "Duurzaamheid bij technische systemen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-255", stroom: "2A", cursus: "Onderzoek", naam: "Globale uitdagingen van duurzame ontwikkeling en de impact op lokaal niveau", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-256", stroom: "2A", cursus: "Onderzoek", naam: "Economie - Gezinsbudget", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-257", stroom: "2A", cursus: "Onderzoek", naam: "Economie - Maatschappelijke thema’s", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-258", stroom: "2A", cursus: "Klaskas", naam: "Klaskas projecten", richtaantal: 6, verplicht: 4 },
  { id: "det-2A-259", stroom: "2A", cursus: "Klaskas", naam: "Klaskas - Economisch onderzoek over productie en consumptie", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-260", stroom: "2A", cursus: "Levende Wiskunde", naam: "Wiskundelessen gegeven", richtaantal: 3, verplicht: 2 },
  { id: "det-2A-261", stroom: "2A", cursus: "Levende Wiskunde", naam: "Wiskundig onderzoek: statistiek", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-262", stroom: "2A", cursus: "Levende Wiskunde", naam: "Wiskundig onderzoek: patronen, algoritmes, AI", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-263", stroom: "2A", cursus: "Levende Wiskunde", naam: "Wiskundig onderzoek", richtaantal: 4, verplicht: 2 },
  { id: "det-2A-264", stroom: "2A", cursus: "Levende Wiskunde", naam: "Getallenleer - Reële getallen op de getallenas (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-265", stroom: "2A", cursus: "Levende Wiskunde", naam: "Getallenleer - Rekenen met reële getallen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-266", stroom: "2A", cursus: "Levende Wiskunde", naam: "Meetkunde - Ligging van punten, rechten en vlakken (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-267", stroom: "2A", cursus: "Levende Wiskunde", naam: "Meetkunde - Gelijkvormigheid (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-268", stroom: "2A", cursus: "Levende Wiskunde", naam: "Meetkunde - Stelling van Pythagoras (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-269", stroom: "2A", cursus: "Levende Wiskunde", naam: "Meetkunde - Goniometrische getallen in rechthoekige driehoeken (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-270", stroom: "2A", cursus: "Levende Wiskunde", naam: "Meetkunde - Vectoren (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-271", stroom: "2A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Eerstegraadsformules, vergelijkingen en ongelijkheden (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-272", stroom: "2A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Functies (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-273", stroom: "2A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Eerstegraadsfuncties (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-274", stroom: "2A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Tweedegraadsfuncties (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-275", stroom: "2A", cursus: "Levende Wiskunde", naam: "Algebra en analyse - Stelsel van 2 vergelijkingen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-276", stroom: "2A", cursus: "Levende Wiskunde", naam: "Telproblemen en Statistiek - Telproblemen (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-277", stroom: "2A", cursus: "Levende Wiskunde", naam: "Telproblemen en Statistiek - Data en Statistiek (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-278", stroom: "2A", cursus: "Levende Wiskunde", naam: "Logica (graadsbadge)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-279", stroom: "2A", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in prehistorie", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-280", stroom: "2A", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in Middeleeuwen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-281", stroom: "2A", cursus: "Cultuur", naam: "Kunstbeschouwing - Kunst in Vroegmoderne Tijd", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-282", stroom: "2A", cursus: "Cultuur", naam: "Kunstbeschouwing - Niet-Westerse kunst", richtaantal: 2, verplicht: 2 },
  { id: "det-2A-283", stroom: "2A", cursus: "Cultuur", naam: "Kunstbeschouwing - Onderwerp naar keuze", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-284", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - toegepaste kunsten (design en ambachten)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-285", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - beeldende kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-286", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - podiumkunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-287", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - muziek", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-288", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - media en audiovisuele kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-289", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - interdisciplinaire en hybride kunsten", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-290", stroom: "2A", cursus: "Cultuur", naam: "Vrije expressie - letterkunde (literaire kunsten)", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-291", stroom: "2A", cursus: "Exploratie", naam: "Leerwandelingen & uitstappen", richtaantal: 18, verplicht: 16 },
  { id: "det-2A-292", stroom: "2A", cursus: "Exploratie", naam: "Klasreizen", richtaantal: 2, verplicht: 2 },
  { id: "det-2A-293", stroom: "2A", cursus: "Toonmoment", naam: "Toonmomenten", richtaantal: 6, verplicht: 4 },
  { id: "det-2A-294", stroom: "2A", cursus: "Toonmoment", naam: "Leerlingenseminaries", richtaantal: 6, verplicht: 5 },
  { id: "det-2A-295", stroom: "2A", cursus: "Toonmoment", naam: "Externe seminaries", richtaantal: 6, verplicht: 6 },
  { id: "det-2A-296", stroom: "2A", cursus: "Welzijn", naam: "Privacy, auteursrecht, portretrecht, netiquette", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-297", stroom: "2A", cursus: "Welzijn", naam: "Digitale identiteit beheren", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-298", stroom: "2A", cursus: "Welzijn", naam: "Vooroordelen, machtsmisbruik, groepsdruk in de digitale wereld", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-299", stroom: "2A", cursus: "Welzijn", naam: "Veiligheid - Infrastructuur, gereedschappen en materialen", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-300", stroom: "2A", cursus: "Welzijn", naam: "Veiligheid - Noodsituaties", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-301", stroom: "2A", cursus: "Welzijn", naam: "Veiligheid - Gebruik van openbaar vervoer", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-302", stroom: "2A", cursus: "Welzijn", naam: "Respectvol gedrag, verbaal en non-verbaal", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-303", stroom: "2A", cursus: "Welzijn", naam: "Gezondheid - Thema 1", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-304", stroom: "2A", cursus: "Welzijn", naam: "Gezondheid - Thema 2", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-305", stroom: "2A", cursus: "Welzijn", naam: "Gezondheid - Hulpverlenersorganisaties", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-306", stroom: "2A", cursus: "Welzijn", naam: "Gezondheid - EHBO", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-307", stroom: "2A", cursus: "Welzijn", naam: "Mentale gezondheid - Thema 1", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-308", stroom: "2A", cursus: "Welzijn", naam: "Mentale gezondheid - Hulpverleners en hulporganisaties", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-309", stroom: "2A", cursus: "Welzijn", naam: "Gezonde levensstijl - Voeding", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-310", stroom: "2A", cursus: "Welzijn", naam: "Gezonde levensstijl - Beweging", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-311", stroom: "2A", cursus: "Welzijn", naam: "Gezonde levensstijl - Hygiëne", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-312", stroom: "2A", cursus: "Welzijn", naam: "Gezonde levensstijl - Ergonomie", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-313", stroom: "2A", cursus: "Welzijn", naam: "Individuele sporten", richtaantal: 4, verplicht: 4 },
  { id: "det-2A-314", stroom: "2A", cursus: "Welzijn", naam: "Interactieve beweging", richtaantal: 4, verplicht: 4 },
  { id: "det-2A-315", stroom: "2A", cursus: "Welzijn", naam: "Ritmisch expressieve beweging", richtaantal: 4, verplicht: 4 },
  { id: "det-2A-316", stroom: "2A", cursus: "Ervaringsweek", naam: "Ervaringsweek 3e jaar", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-317", stroom: "2A", cursus: "Ervaringsweek", naam: "Ervaringsweek 4e jaar", richtaantal: 1, verplicht: 1 },
  { id: "det-2A-318", stroom: "2A", cursus: "Basisfreinetvaardigheden", naam: "Basisfreinetvaardigheden", richtaantal: 6, verplicht: 6 },
  { id: "det-2A-319", stroom: "2A", cursus: "Vrije initiatieven buiten de lijntjes", naam: "Vrije initiatieven buiten de lijntjes", richtaantal: 10, verplicht: 0 },
  { id: "det-3A-320", stroom: "3A", cursus: "Planning en reflectie", naam: "Coachinggesprek", richtaantal: 10, verplicht: 10 },
  { id: "det-3A-321", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Bruin", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-322", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Rose", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-323", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Zwart", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-324", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Grijs", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-325", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Wit", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-326", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Kaki", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-327", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Lila", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-328", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Paars", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-329", stroom: "3A", cursus: "Geïntegreerde opdrachten (GOP)", naam: "GOP - Extra", richtaantal: 1, verplicht: 0 },
  { id: "det-3A-330", stroom: "3A", cursus: "Trajecten", naam: "Traject wiskunde en wetenschappen", richtaantal: 10, verplicht: 8 },
  { id: "det-3A-331", stroom: "3A", cursus: "Klaswerking+", naam: "Deelname kring & klasraad (jaarbadge)", richtaantal: 2, verplicht: 2 },
  { id: "det-3A-332", stroom: "3A", cursus: "Klaswerking+", naam: "Taken klaswerking (Units)", richtaantal: 12, verplicht: 10 },
  { id: "det-3A-333", stroom: "3A", cursus: "Burgerschapsreis", naam: "Communicatie - Deelname aan voorstellingsdag", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-334", stroom: "3A", cursus: "Burgerschapsreis", naam: "Vrije tekst - motivatiebrief (Engels of Frans)", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-335", stroom: "3A", cursus: "Burgerschapsreis", naam: "Exploratie - Deelname aan de selectietweedaagse", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-336", stroom: "3A", cursus: "Burgerschapsreis", naam: "Klasraad en klaskas - Deelname aan de fondsenwerving", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-337", stroom: "3A", cursus: "Burgerschapsreis", naam: "Klasraad en klaskas - Inzicht in het budget van de reis", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-338", stroom: "3A", cursus: "Burgerschapsreis", naam: "GOP met taken die horen bij je reis", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-339", stroom: "3A", cursus: "Burgerschapsreis", naam: "Exploratie - Deelname aan de reis", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-340", stroom: "3A", cursus: "Burgerschapsreis", naam: "Burgerschap intern - Inzet voor de groep tijdens de reis", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-341", stroom: "3A", cursus: "Burgerschapsreis", naam: "Burgerschap extern - Inzet voor de projecten tijdens de reis", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-342", stroom: "3A", cursus: "Burgerschapsreis", naam: "Cultuur - Verwerking via artistieke creaties", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-343", stroom: "3A", cursus: "Burgerschapsreis", naam: "Toonmoment - Deelname aan toonmomenten", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-344", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "30 dagdelen persoonlijke brug", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-345", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Ervaringsweek - uitvoering (minimaal 8 dagdelen)", richtaantal: 2, verplicht: 2 },
  { id: "det-3A-346", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Ervaringsweek - verslag", richtaantal: 2, verplicht: 2 },
  { id: "det-3A-347", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Eigen onderzoek - Goedgekeurd thema", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-348", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Eigen onderzoek - Boekenronde", richtaantal: 3, verplicht: 3 },
  { id: "det-3A-349", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Eigen onderzoek - Actuaronde", richtaantal: 3, verplicht: 3 },
  { id: "det-3A-350", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Eigen onderzoek - Paper", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-351", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Eigen onderzoek - Concrete voorstelling", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-352", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Eigen onderzoek - Actuaronde", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-353", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Concrete voorstelling", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-354", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Lesactiviteit", richtaantal: 9, verplicht: 9 },
  { id: "det-3A-355", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Persoonlijke vragenlijst", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-356", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Mondelinge proef & portfolio", richtaantal: 1, verplicht: 1 },
  { id: "det-3A-357", stroom: "3A", cursus: "De brug naar je (leer)toekomst", naam: "Extra", richtaantal: 1, verplicht: 0 },
  { id: "det-3A-358", stroom: "3A", cursus: "Basisfreinetvaardigheden", naam: "Basisfreinetvaardigheden", richtaantal: 6, verplicht: 6 },
  { id: "det-3A-359", stroom: "3A", cursus: "Vrije initiatieven buiten de lijntjes", naam: "Vrije initiatieven buiten de lijntjes", richtaantal: 10, verplicht: 0 },
];
