// AUTO-GEGENEREERD uit docs/reference/doelen2GRA_volledig.xlsx (blad "2A").
// Niet handmatig herschikken; regenereer bij een nieuwe export.
import type { Minimumdoel } from "./minimumdoelen";

export const minimumdoelen2A: Minimumdoel[] = [
  {
    code: "2A.ST.01.01",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.01",
    soort: "standaard",
    omschrijving: "De leerlingen passen technieken voor levensreddend handelen toe in een gesimuleerde leeromgeving.",
    uitleg: "Memorie:\nTechnieken voor levensreddend handelen zoals technieken van reanimatie (BLS) met een automatische externe defibrillator (AED), technieken in geval van verdrinking, verstikking, hart- en ademhalingsstilstand.\n\nHerhaling van levensreddende technieken in beide graden is van belang om die technieken nadien systematisch in een noodsituatie te kunnen toepassen.",
  },
  {
    code: "2A.ST.01.02",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.02",
    soort: "standaard",
    omschrijving: "De leerlingen ontwikkelen gezondheidsvaardigheden in functie van hun fysiek en mentaal welzijn binnen verschillende thema’s.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nGezondheidsvaardigheden inzake voeding, hygiëne, beweging.\n- Voeding zoals ultrabewerkt voedsel, gezonde snacks, duurzame voeding, evenwichtige voeding;\n- Hygiëne zoals basisregels voor hygiëne;\n- Beweging zoals beweegnormen, sedentair gedrag.",
  },
  {
    code: "2A.ST.01.03",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.03",
    soort: "standaard",
    omschrijving: "De leerlingen voeren conform de beweegrichtlijnen in verschillende bewegingsomgevingen activiteiten uit in verschillende individuele, interactieve en ritmisch expressieve bewegingsdomeinen.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals bewegingsomgevingen en bewegingsdomeinen) waarin het minimumdoel aan bod komt.",
  },
  {
    code: "2A.ST.01.04",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.04",
    soort: "standaard",
    omschrijving: "De leerlingen ontwikkelen kracht, lenigheid, uithouding, snelheid, coördinatie en evenwicht, rekening houdend met de evolutie van hun fysieke capaciteiten.",
    uitleg: "",
  },
  {
    code: "2A.ST.01.05",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.05",
    soort: "standaard",
    omschrijving: "De leerlingen voeren motorische basisvaardigheden uit, rekening houdend met ergonomische principes en de evolutie van hun fysieke capaciteiten.",
    uitleg: "Memorie:\nMotorische basisvaardigheden zoals balanceren, wentelen, springen, rollen, klauteren, klimmen, ritmisch bewegen, lopen, vangen, werpen, terugslaan, vallen, mee- en tegengaan in beweging.\n\nErgonomische principes zoals in het geval van heffen, tillen, staan, verplaatsen, rughygiëne.",
  },
  {
    code: "2A.ST.01.06",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.06",
    soort: "standaard",
    omschrijving: "De leerlingen passen tactieken en principes toe met respect voor de afgesproken regels en rollen in sport en spel.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals de bewegingsdomeinen) waarin het minimumdoel aan bod komt.\n\nMemorie:\nRollen in sport en spel zoals de beoefenaar, de coach, de scheidsrechter.",
  },
  {
    code: "2A.ST.01.07",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.07",
    soort: "standaard",
    omschrijving: "De leerlingen hanteren in verschillende rollen in sport en spel principes van verantwoord en veilig gedrag.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals de bewegingsdomeinen) waarin het minimumdoel aan bod komt.",
  },
  {
    code: "2A.ST.02.01",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.01",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie:\n- Herkenbare structuur;\n- Herkenbare samenhang;\n- Standaardnederlands, soms andere taalvariëteiten;\n- Frequente en minder frequente woorden;\n- Figuurlijk taalgebruik;\n- Vrij algemene inhoud;\n- Gemiddelde tot vrij hoge informatiedichtheid;\n- Langere, samengestelde zinnen;\n- Grote variatie aan tekstsoorten met inbegrip van argumentatieve teksten.\n* Bijkomend voor schriftelijke receptie: Teksten met een minder duidelijke lay-out;\n* Bijkomend voor mondelinge receptie: Normaal spreektempo.\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen in functie van begrijpen van teksten.",
  },
  {
    code: "2A.ST.02.02",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.02",
    soort: "standaard",
    omschrijving: "De leerlingen beoordelen doelgericht informatie op betrouwbaarheid, correctheid en bruikbaarheid bij het lezen en luisteren.",
    uitleg: "",
  },
  {
    code: "2A.ST.02.03",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.03",
    soort: "standaard",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie zie 02.01.\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om relevante informatie te selecteren.",
  },
  {
    code: "2A.ST.02.04",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.04",
    soort: "standaard",
    omschrijving: "De leerlingen nemen notities bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie zie 02.01.\n\nMinimumvereisten voor de geproduceerde tekst:\nInhoud en vorm afgestemd op het doel en op de doelgroep.",
  },
  {
    code: "2A.ST.02.05",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.05",
    soort: "standaard",
    omschrijving: "De leerlingen vatten doelgericht een geschreven tekst schriftelijk samen.",
    uitleg: "Tekstkenmerken voor schriftelijke receptie zie 02.01.\n\nMinimumvereisten van de geproduceerde tekst:\n- Herkenbare tekstopbouw;\n- Herkenbare tekststructuur;\n- Herkenbare tekstverbanden;\n- Herformulering op het vlak van woordgebruik en zinsbouw;\n- Taal afgestemd op het doel en de doelgroep.",
  },
  {
    code: "2A.ST.02.06",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.06",
    soort: "standaard",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Minimumvereisten voor productie:\n- Herkenbare tekstopbouw;\n- Gepaste en herkenbare tekststructuur;\n- Herkenbare tekstverbanden;\n- Frequente en minder frequente woorden;\n- Figuurlijk taalgebruik;\n- Gepast register;\n- Vrij algemene inhoud;\n- Gemiddelde informatiedichtheid;\n- Grote variatie aan tekstsoorten.\n* Bijkomend voor schriftelijke productie: Tekstopbouwende elementen; Gepaste lay-out; Standaardnederlands met aandacht voor spelling, interpunctie, woordkeuze, zinsbouw, helderheid, adequaatheid, correctheid en vlotheid;\n* Bijkomend voor mondelinge productie: Gepaste lichaamstaal; Standaardnederlands met aandacht voor uitspraak, intonatie, woordkeuze, zinsbouw, helderheid, adequaatheid, correctheid en vlotheid.\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen (zoals een kaartje met steekwoorden, structuur, schrijfkader, spreekkader, voorleessoftware, presentatiesoftware enz. maar ook talige hulpmiddelen).",
  },
  {
    code: "2A.ST.02.07",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.07",
    soort: "standaard",
    omschrijving: "De leerlingen drukken zich creatief uit met taal.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nZich creatief uitdrukken zoals het gebruiken van lay-out, rijm, ritme, humor en stijlfiguren, het opbouwen van spanning, het spelen met tijd en ruimte, het toepassen van verteltechnieken, het spelen met beeld en taal, het mixen van talen.",
  },
  {
    code: "2A.ST.02.08",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.08",
    soort: "standaard",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken voor receptie zie 02.01.\n\nMinimumvereisten voor productie zie 02.06.\n\nMemorie:\nMondelinge interactie veronderstelt dat leerlingen onvoorbereid of voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context over een vertrouwd onderwerp.",
  },
  {
    code: "2A.ST.02.09",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.09",
    soort: "standaard",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "Voetnoot:\nDit minimumdoel wordt doelgericht ingezet in functie van alle andere minimumdoelen binnen sleutelcompetentie 2. Rekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nStrategieën hebben betrekking op lees-, luister-, spreek- en schrijfvaardigheden (zoals met lees-, luister- spreek- of schrijfdoel rekening houden; voorkennis activeren; inhoud voorspellen; vragen stellen; tussentijds samenvatten, de vermoedelijke betekenis van onbekende woorden en zinnen afleiden uit de context, via taalverwantschap of op basis van woorddelen; bepalen of het achterhalen van de betekenis van een onbekend woord belangrijk is; talige hulpmiddelen gebruiken; afkortingen, symbolen en telegramstijl gebruiken; met de ontvanger rekening houden zoals door het gepast inzetten van lichaamstaal; sleutelwoorden en kernzinnen aanduiden; met de doelen van de interactie rekening houden; inspelen op wat de ander zegt of schrijft; de ander laten uitspreken; op een gepaste manier het woord vragen of nemen; elementen van lichaamstaal en intonatie herkennen en zelf doelgericht inzetten; het register afstemmen op de gesprekspartner of correspondent; taalgebruik aan de ontvanger aanpassen).",
  },
  {
    code: "2A.ST.02.10",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.10",
    soort: "standaard",
    omschrijving: "De leerlingen zetten nieuw- en eerder verworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Tekstkenmerken voor receptie zie 02.01.\n\nMinimumvereisten voor productie zie 02.06.",
  },
  {
    code: "2A.ST.02.11",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.11",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Klanken: intonatie;\n- Woordvorming: tussenklank, verbuiging, vervoeging;\n- Woordsoorten: werkwoord (voltooid deelwoord, infinitief, hulpwerkwoord, zelfstandig werkwoord, koppelwerkwoord), voornaamwoorden (betrekkelijk, onbepaald, wederkerend);\n- Herkomst van woorden: leenwoord;\n- Betekenisrelaties: antoniem;\n- Gevoelswaarde van woorden: eufemisme, dysfemisme;\n- Vormen van humor: ironie;\n- Zinsdelen: werkwoordelijk en naamwoordelijk gezegde, voorzetselvoorwerp, handelend voorwerp;\n- Woordvolgorde: hoofdzin, bijzin, inversie;\n- Zinssoorten: actieve en passieve zinnen, ondergeschikte en nevengeschikte zinnen;\n- Spelling met aandacht voor woorden met veranderlijk woordbeeld;\n- Interpunctietekens: beletselteken, gedachtestreepje.",
  },
  {
    code: "2A.ST.02.12",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.12",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in taalgebruik toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Tekstopbouwende elementen: tussentitel, alinea;\n- Tekststructuren: inleiding, midden, slot;\n- Talige elementen om tekstverbanden uit te drukken;\n- Communicatiemodel: effect, ruis;\n- Verbale en non-verbale communicatie;\n- Van formele tot informele registers;\n- Beleefdheidsconventies;\n- Argumentatieve teksten met inbegrip van: feit en mening, stelling, standpunt, argument, tegenargument, conclusie;\n- Talige middelen om de mate van subjectiviteit of objectiviteit uit te drukken; modaliteit.",
  },
  {
    code: "2A.ST.02.13",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.13",
    soort: "standaard",
    omschrijving: "De leerlingen geven overeenkomsten en verschillen aan in taaluitingen, taalvariëteiten en talen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Cultuurgebonden aspecten van verbale en non-verbale communicatie;\n- Standaardtaal, nationale, regionale, sociale en situationele taalvariëteiten in het Nederlands.",
  },
  {
    code: "2A.ST.02.14",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.14",
    soort: "standaard",
    omschrijving: "De leerlingen verwoorden de eigen beleving en interpretatie van literaire teksten.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nEigen beleving en interpretatie zoals waarom sommige aspecten van de tekst aanspreken, waarom men zich identificeert met een bepaald personage, in welke zin men gelijkaardige ervaringen zelf al heeft meegemaakt, waarom de tekst een bepaalde emotionele reactie teweegbrengt, waarom de uitdrukkingsvorm of stijl aanspreekt.",
  },
  {
    code: "2A.ST.02.15",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.15",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren hoe in literaire teksten betekenissen worden gecreëerd met narratieve, poëticale en theatrale structuren en technieken.",
    uitleg: "Onderliggende (kennis)elementen:\n- Personages: held/protagonist, antiheld/antagonist;\n- Tijd: flashforward, flashback;\n- Elementen van spanningsopbouw;\n- Vertelperspectief: ik-verteller, hij-verteller;\n- Stijlfiguren: vergelijking, metafoor, woordspeling, herhaling, overdrijving;\n- Ritme en alliteratie;\n- Presentatie, vormgeving, opvoering;\n- Tekstkenmerken;\n- Grote variatie aan genres.",
  },
  {
    code: "2A.ST.02.16",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.16",
    soort: "standaard",
    omschrijving: "De leerlingen gaan in interactie over de relevantie van literaire teksten voor hun leefwereld, voor de samenleving waarin ze leven en voor de samenleving waarin de teksten ontstonden.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "2A.ST.03.01",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.01",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\n- Ten minste teksten in het Engels en in het Frans.\n\nTekstkenmerken voor receptie:\n- Tekststructuur met een beperkte mate van complexiteit;\n- Vrij grote en herkenbare samenhang;\n- Hoofdzakelijk frequente woorden, woordcombinaties en vaste uitdrukkingen uit een beperkte waaier aan relevante thema’s binnen het persoonlijke, publieke en educatieve domein;\n- Concrete tot vrij algemene inhoud;\n- Niet al te hoge informatiedichtheid;\n- Zinsbouw met een beperkte mate van complexiteit;\n- Vrij korte en af en toe iets langere teksten;\n- Ruime variatie aan tekstsoorten.\n* Bijkomend voor schriftelijke receptie: Vrij duidelijke lay-out;\n* Bijkomend voor mondelinge receptie: Met een beperkte mate van achtergrondruis; Normaal spreektempo met weinig pauzes; Ondersteunende maar natuurlijke intonatie; Heldere uitspraak, duidelijke articulatie; Met lichte afwijking ten opzichte van de standaardtaal.\n\nMemorie:\nOm het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen veronderstellen we minimaal dat leerlingen de belangrijkste informatie uit de tekst begrijpen.",
  },
  {
    code: "2A.ST.03.02",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.02",
    soort: "standaard",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\n- Ten minste teksten in het Engels en in het Frans.\n\nTekstkenmerken voor receptie zie 03.01.\n\nMemorie:\nOm relevante informatie te selecteren veronderstellen we minimaal dat leerlingen de belangrijkste informatie uit de tekst begrijpen.",
  },
  {
    code: "2A.ST.03.03",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.03",
    soort: "standaard",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Onderliggende (kennis)elementen:\n- In het Engels en in het Frans.\n\nMinimumvereisten voor productie:\n- Gepaste en herkenbare tekststructuur;\n- Duidelijk herkenbare tekstverbanden;\n- Beheersing van frequente woorden, woordcombinaties en vaste uitdrukkingen om zich uit te drukken over een beperkte varia aan relevante thema's, al kunnen lexicale beperkingen leiden tot herhaling of omhaal van woorden;\n- Concrete tot vrij algemene inhoud;\n- Over het algemeen redelijk goede grammaticale beheersing (met merkbare invloed moedertaal);\n- Enkelvoudige zinnen en af en toe zinnen met beperkte complexiteit;\n- Gepast register; Vrij beperkte lengte; Ruime variatie aan tekstsoorten.\n* Bijkomend voor schriftelijke productie: Duidelijk herkenbare tekstopbouw en gebruik van tekstopbouwende elementen (titel, alinea); Gepaste lay-out; Heldere doorlopende tekst die spelling, leestekens en lay-out niet belemmert;\n* Bijkomend voor mondelinge productie: Gepaste lichaamstaal; Uitspraak is over het algemeen duidelijk te verstaan; Kan zich betrekkelijk vlot uitdrukken ondanks regelmatige pauzes.\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen.",
  },
  {
    code: "2A.ST.03.04",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.04",
    soort: "standaard",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Onderliggende (kennis)elementen:\n- In het Engels en in het Frans.\n\nTekstkenmerken voor receptie zie 03.01; Minimumvereisten voor productie zie 03.03.\n\nBijkomend voor mondelinge en schriftelijke interactie:\n- Gepaste beleefdheidsconventies bij taalhandelingen.\n* Bijkomend voor mondelinge interactie: Kan onvoorbereid deelnemen aan een gesprek, maar zal soms moeten vragen om herhaling; Kan een eenvoudig gesprek beginnen, gaande houden en beëindigen; Kan gedeeltelijk herhalen wat iemand anders heeft gezegd om begrip te borgen.",
  },
  {
    code: "2A.ST.03.05",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.05",
    soort: "standaard",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- In het Engels en in het Frans.\n\nVoetnoot:\nDit minimumdoel wordt doelgericht ingezet in functie van alle andere minimumdoelen binnen sleutelcompetentie 3. Rekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nStrategieën hebben betrekking op lees-, luister-, spreek- en schrijfvaardigheden (zoals met lees-, luister-, spreek- of schrijfdoel rekening houden; voorkennis activeren; inhoud voorspellen; vragen stellen; de vermoedelijke betekenis afleiden; talige hulpmiddelen gebruiken; lichaamstaal inzetten; eigen tekst nakijken; om hulp/opheldering vragen; registers aanvaarden en aanpassen).",
  },
  {
    code: "2A.ST.03.06",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.06",
    soort: "standaard",
    omschrijving: "De leerlingen zetten nieuw- en eerder verworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- In het Engels en in het Frans.\n\nTekstkenmerken voor receptie zie 03.01; Minimumvereisten voor productie zie 03.03.",
  },
  {
    code: "2A.ST.03.07",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.07",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\nOnderstaande elementen gelden voor het Frans én het Engels, tenzij gespecificeerd dat ze enkel voor het Frans of het Engels gelden door de aanduiding van respectievelijk [F] of [E]:\n- Voornaamwoorden: met nadruk [F], onbepaald, betrekkelijk, en [F], y [F];\n- Hoofd- en rangtelwoorden;\n- Werkwoorden: onderscheid tussen tijden en wijzen [F]; ind. futur simple [F]; conditionnel présent [F], present perfect simple [E], past continuous [E], going to future [E]; onregelmatige werkwoorden, onpersoonlijke werkwoorden; do om iets te benadrukken [E];\n- Frequente modal verbs [E];\n- Frequente voorzetselgroepen;\n- Genitiefvormen [E];\n- Frequente onderschikkende voegwoorden;\n- Frequente bijwoorden op -ment [F], -ly [E];\n- Betrekkelijke bijzinnen met qui, que, dont, où [F]; met that, who, whose, which, when, where, why [E];\n- The conditional (realis) [E];\n- Uitspraak: specifieke grafieën en klanken; liaison, enchaînement [F]; letters van het alfabet; zinsklemtoon;\n- Spelling van in te zetten woorden.",
  },
  {
    code: "2A.ST.03.08",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.08",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren bij het lezen en beluisteren van teksten kenmerkende aspecten van maatschappijen en culturen waarin de doeltaal wordt gesproken.",
    uitleg: "Onderliggende (kennis)elementen:\n- Teksten in het Engels en in het Frans.",
  },
  {
    code: "2A.ST.03.09",
    stroom: "2A",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.09",
    soort: "standaard",
    omschrijving: "De leerlingen verwoorden de eigen beleving en interpretatie van literaire teksten in de doeltaal.",
    uitleg: "Onderliggende (kennis)elementen:\n- Teksten in het Engels en in het Frans.\n\nVoetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nEigen beleving en interpretatie zoals waarom sommige aspecten van de tekst aanspreken, waarom men zich identificeert met een bepaald personage, in welke zin men gelijkaardige ervaringen zelf al heeft meegemaakt, waarom de tekst een bepaalde emotionele reactie teweegbrengt, waarom de uitdrukkingsvorm of stijl aanspreekt.",
  },
  {
    code: "2A.ST.04.01",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Digitale competenties en mediawijsheid",
    nummer: "04.01",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken courante functionaliteiten van vergelijkbare toepassingen om digitaal te communiceren.",
    uitleg: "Memorie:\nDigitaal communiceren zoals in interactie gaan met mensen, systemen, diensten; synchroon (online meeting, chat), asynchroon (berichtensysteem, sociale media, sms, e-mail, blog, fora, websites).",
  },
  {
    code: "2A.ST.04.02",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Digitale competenties en mediawijsheid",
    nummer: "04.02",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken courante functionaliteiten van vergelijkbare toepassingen om digitale inhouden te creëren.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDigitale inhouden creëren zoals in tekst-, cijfer-, geluid-, grafische, audiovisuele bestanden.",
  },
  {
    code: "2A.ST.04.03",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Digitale competenties en mediawijsheid",
    nummer: "04.03",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken courante functionaliteiten van vergelijkbare toepassingen om digitale inhouden te beheren.",
    uitleg: "Memorie:\nDigitale inhouden beheren zoals met behulp van informatiedragers zoals interne en externe opslag; met behulp van ordeningstechnieken zoals mappenstructuur, ordening op thema.",
  },
  {
    code: "2A.ST.04.04",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Digitale competenties en mediawijsheid",
    nummer: "04.04",
    soort: "standaard",
    omschrijving: "De leerlingen respecteren ethische, sociale en legale regels in hun omgang met digitale technologie.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nEthische, sociale en legale regels zoals:\n- principes van privacy zoals het zich beveiligen, anoniem zijn op het WWW;\n- principes van auteursrecht zoals creative commons;\n- principes van portretrecht;\n- netiquette.",
  },
  {
    code: "2A.ST.04.05",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Digitale competenties en mediawijsheid",
    nummer: "04.05",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren de impact van digitale systemen op de maatschappij vanuit principes van computationeel denken.",
    uitleg: "Memorie:\nDe impact van digitale systemen op de maatschappij vanuit principes van computationeel denken zoals algoritmes die digitale platformen gebruiken bij:\n- het selecteren en presenteren van informatie aan gebruikers;\n- het verzamelen van persoonlijke informatie van gebruikers en die (mis)(ge)bruiken voor eigen doeleinden;\n- het beïnvloeden van de keuzes van gebruikers (vb. gepersonaliseerd aanbod, gepersonaliseerde reclame);\n- het beïnvloeden van de blik op de wereld/opinie van gebruikers;\n- het nemen van beslissingen over gebruikers (vb. over kredietaanvragen, sollicitaties, verzekeringen);\n- het creëren van taalinteractie met behulp van artificiële intelligentie (chatbot);\n- het creëren van kunst (beelden, muziek, poëzie, andere kunstvormen) met behulp van artificiële intelligentie;\n- medische beeldvorming om op basis van een eerste scan eventuele afwijkingen te melden aan artsen.\n\nPrincipes van computationeel denken zoals decompositie, patroonherkenning, abstractie en algoritmen.",
  },
  {
    code: "2A.ST.05.01",
    stroom: "2A",
    competentieNr: 5,
    competentie: "5. Sociaal-relationele competenties",
    nummer: "05.01",
    soort: "standaard",
    omschrijving: "De leerlingen gaan respectvol en constructief met anderen in interactie rekening houdend met elkaars grenzen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nRespectvol en constructief met anderen in interactie gaan zoals:\n- rekening houden met de opvattingen, de fysieke en mentale grenzen en de emoties van anderen;\n- grenzen bewaken;\n- reageren tegen pest- en uitsluitingsgedrag;\n- samenwerken en actief bijdragen aan de uitwerking van een gezamenlijk resultaat;\n- omgaan met emoties;\n- respect tonen voor relationele en seksuele integriteit;\n- sociaal vaardig interageren in informele en formele relaties.",
  },
  {
    code: "2A.ST.06.01",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.01",
    soort: "standaard",
    omschrijving: "De leerlingen leggen de invoering van de reële getallen uit als de vervollediging van de reële getallenas.",
    uitleg: "Onderliggende (kennis)elementen:\n- Getallen met eindige of oneindige doorlopende decimale vorm, met of zonder repeterend deel.",
  },
  {
    code: "2A.ST.06.02",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.02",
    soort: "standaard",
    omschrijving: "De leerlingen ordenen reële getallen.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.03",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.03",
    soort: "standaard",
    omschrijving: "De leerlingen rekenen met reële getallen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Optelling, aftrekking, vermenigvuldiging, deling, machtsverheffing met gehele exponenten, vierkantsworteltrekking met rekenregels en eigenschappen met symbolen;\n- Schatting grootteorde, afronding.\n\nMemorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.04",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.04",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen de onderlinge ligging van twee rechten, twee vlakken en een rechte en een vlak in ruimtelijke situaties.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.05",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.05",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het effect van schaalverandering op vorm, lengte, oppervlakte en inhoud of volume.",
    uitleg: "Onderliggende (kennis)elementen:\n- Gelijkvormigheidsfactor.\n\nMemorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.06",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.06",
    soort: "standaard",
    omschrijving: "De leerlingen passen de stelling van Pythagoras toe om meetkundige problemen op te lossen in het vlak en in de ruimte.",
    uitleg: "Memorie:\n‘In de ruimte’: bv. een ruimtediagonaal in een kubus of balk waarbij leerlingen het geschikte vlak tweemaal moeten kiezen.\n\nHerdruk:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.07",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.07",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken de goniometrische getallen sinus, cosinus en tangens in rechthoekige driehoeken om meetkundige problemen op te lossen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Grondformule van de goniometrie.\n\nMemorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.08",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.08",
    soort: "standaard",
    omschrijving: "De leerlingen passen gelijkvormigheidskenmerken van driehoeken toe om meetkundige problemen op te lossen.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.09",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.09",
    soort: "standaard",
    omschrijving: "De leerlingen tekenen in het vlak de som van vectoren en de vermenigvuldiging van een vector met een getal.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.10",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.10",
    soort: "standaard",
    omschrijving: "De leerlingen lossen eerstegraadsvergelijkingen en -ongelijkheden in één onbekende algebraïsch en grafisch op.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.11",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.11",
    soort: "standaard",
    omschrijving: "De leerlingen drukken bij een formule één variabele uit in functie van een andere.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.12",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.12",
    soort: "standaard",
    omschrijving: "De leerlingen leggen uit wat een functie is en leggen het verband tussen verschillende representaties van een functie: verwoording, tabel, grafiek en voorschrift.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.13",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.13",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het voorschrift, de grafiek, de tabel en de verwoording van een eerstegraadsfunctie als één van de andere representaties gegeven is.",
    uitleg: "Onderliggende (kennis)elementen:\n- Richtingscoëfficiënt;\n- Snijpunt met de y-as.\n\nMemorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.14",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.14",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren kenmerken van eerstegraadsfuncties: domein, bereik, nulwaarden, tekenverloop en stijgen/dalen.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.15",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.15",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren kenmerken van tweedegraadsfuncties van de vorm f(x)=ax²: domein, bereik, nulwaarden, tekenverloop, stijgen/dalen, extremum, toenemende/afnemende stijging/daling en symmetrie ten opzichte van een verticale rechte.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.16",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.16",
    soort: "standaard",
    omschrijving: "De leerlingen lossen stelsels van twee eerstegraadsvergelijkingen in twee onbekenden algebraïsch en grafisch op.",
    uitleg: "Memorie:\nHet is aangewezen om zowel met als zonder context te werken. Werken met contexten kan leerlingen immers motiveren. Wiskunde leren met en zonder contexten is belangrijk om kennis en vaardigheden te transfereren naar gelijkaardige en naar nieuwe situaties.",
  },
  {
    code: "2A.ST.06.17",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.17",
    soort: "standaard",
    omschrijving: "De leerlingen lossen telproblemen op met behulp van boomdiagrammen en venndiagrammen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Somregel, productregel, complementregel.",
  },
  {
    code: "2A.ST.06.18",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.18",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren statistische gegevens aan de hand van voorstellingswijzen en centrum- en spreidingsmaten.",
    uitleg: "Onderliggende (kennis)elementen:\n- Voorstellingswijzen: absolute en relatieve frequentietabel, staafdiagram, cirkeldiagram, lijndiagram, histogram en boxplot;\n- Centrum- en spreidingsmaten: rekenkundig gemiddelde, mediaan, modus, variatiebreedte, interkwartielafstand en standaardafwijking;\n- Misleidingen.",
  },
  {
    code: "2A.ST.06.19",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.19",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen de waarheidswaarde van logische uitspraken met behulp van waarheidstabellen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Tautologie, contradictie.",
  },
  {
    code: "2A.ST.06.20",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.20",
    soort: "standaard",
    omschrijving: "De leerlingen beargumenteren wiskundige redeneringen en maken daarbij ook gebruik van eigenschappen of van een tegenvoorbeeld.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de tweede graad.",
  },
  {
    code: "2A.ST.06.21",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.21",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven fenomenen uit de realiteit aan de hand van wiskundige concepten uit de tweede graad.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.22",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.22",
    soort: "standaard",
    omschrijving: "De leerlingen lossen vraagstukken en problemen op door te mathematiseren en demathematiseren en door gebruik te maken van heuristieken.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de tweede graad.",
  },
  {
    code: "2A.ST.06.23",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.23",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken ICT om berekeningen uit te voeren en grafische voorstellingen te maken.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de tweede graad.",
  },
  {
    code: "2A.ST.06.24",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.24",
    soort: "standaard",
    omschrijving: "De leerlingen leggen uit hoe plantaardige en dierlijke organismen prikkels ontvangen.",
    uitleg: "Memorie:\n- Prikkels zoals inwendige prikkels, uitwendige prikkels;\n- Prikkels ontvangen zoals prikkelwaarneming door receptoren, reacties op prikkels.",
  },
  {
    code: "2A.ST.06.25",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.25",
    soort: "standaard",
    omschrijving: "De leerlingen leggen uit hoe bij plantaardige en dierlijke organismen een prikkel verwerkt wordt.",
    uitleg: "Onderliggende (kennis)elementen:\n- Zenuwstelsel;\n- Hormonen.",
  },
  {
    code: "2A.ST.06.26",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.26",
    soort: "standaard",
    omschrijving: "De leerlingen lichten het onderscheid toe tussen reacties op een prikkel bij plantaardige en dierlijke organismen.",
    uitleg: "Memorie:\n- Reacties op een prikkel bij dierlijke organismen zoals beweging, kliersecretie;\n- Reacties op een prikkel bij plantaardige organismen zoals nastie, tropie.",
  },
  {
    code: "2A.ST.06.27",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.27",
    soort: "standaard",
    omschrijving: "De leerlingen leggen uit dat plantaardige en dierlijke organismen zich kunnen handhaven dankzij homeostase.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.28",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.28",
    soort: "standaard",
    omschrijving: "De leerlingen leggen de hormonale regeling van het voortplantingssysteem bij de mens uit.",
    uitleg: "Memorie:\n- Hormonale regeling zoals vrouwelijke geslachtshormonen, mannelijke geslachtshormonen;\n- Voortplantingssysteem bij de mens zoals de menstruatiecyclus, zaadcel, zygote, embryo, foetus.",
  },
  {
    code: "2A.ST.06.29",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.29",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen eigenschappen van virussen, bacteriën en schimmels en hun positieve en negatieve rol in de natuur.",
    uitleg: "Onderliggende (kennis)elementen:\n- Microbioom.",
  },
  {
    code: "2A.ST.06.30",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.30",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren interacties tussen organismen van dezelfde soort en van verschillende soorten.",
    uitleg: "Memorie:\n- Interacties tussen organismen zoals commensalisme, mutualisme, parasitisme, antibiose.",
  },
  {
    code: "2A.ST.06.31",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.31",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen materie- en energiestromen in een ecosysteem.",
    uitleg: "Memorie:\n- Materie- en energiestromen zoals fotosynthese, ademhaling, watercyclus, C-cyclus, N-cyclus.",
  },
  {
    code: "2A.ST.06.32",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.32",
    soort: "standaard",
    omschrijving: "De leerlingen onderzoeken zuivere stoffen en soorten mengsels in het dagelijkse leven aan de hand van eigenschappen en scheidingstechnieken.",
    uitleg: "Onderliggende (kennis)elementen:\n- Stofeigenschappen: massadichtheid, kookpunt, smeltpunt, deeltjesgrootte, oplosgedrag van stoffen.",
  },
  {
    code: "2A.ST.06.33",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.33",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken een atoommodel om de structuur van atomen en ionen te beschrijven.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.34",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.34",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen de plaats en de eigenschappen van atomen in het PSE.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.35",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.35",
    soort: "standaard",
    omschrijving: "De leerlingen interpreteren de naam en symbolische schrijfwijze van enkelvoudige en samengestelde stoffen.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.36",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.36",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen de chemische binding en de eigenschappen van een stof.",
    uitleg: "Onderliggende (kennis)elementen:\n- Oxiden, basen, zuren, zouten en alkanen.",
  },
  {
    code: "2A.ST.06.37",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.37",
    soort: "standaard",
    omschrijving: "De leerlingen balanceren gegeven eenvoudige chemische reacties en interpreteren ze in termen van materie- en energie-uitwisseling.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.38",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.38",
    soort: "standaard",
    omschrijving: "De leerlingen brengen pH in verband met het zuur, basisch of neutraal karakter van een waterige oplossing en lichten de functie van een zuur-base indicator toe.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.39",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.39",
    soort: "standaard",
    omschrijving: "De leerlingen interpreteren massaconcentratie en molaire concentratie.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.40",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.40",
    soort: "standaard",
    omschrijving: "De leerlingen lossen fysische problemen met en zonder formularium op.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de tweede graad.",
  },
  {
    code: "2A.ST.06.41",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.41",
    soort: "standaard",
    omschrijving: "De leerlingen interpreteren rechtlijnige bewegingen grafisch en eenparig rechtlijnige bewegingen kwantitatief.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.42",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.42",
    soort: "standaard",
    omschrijving: "De leerlingen stellen krachten vectorieel voor en leggen het verband tussen de verandering van bewegingstoestand van een lichaam en de resulterende kracht.",
    uitleg: "Onderliggende (kennis)elementen:\n- Zwaartekracht, gewicht, normaalkracht, veerkracht;\n- Dynamische effecten van een resulterende kracht: versnellen, vertragen, van richting veranderen;\n- Verschil massa en gewicht.",
  },
  {
    code: "2A.ST.06.43",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.43",
    soort: "standaard",
    omschrijving: "De leerlingen verklaren fenomenen of toepassingen uit het dagelijkse leven aan de hand van het concept druk bij vaste stoffen, gassen en vloeistoffen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Druk als grootte van de kracht per oppervlakte;\n- Invloedsfactoren op de totale druk in een vloeistof.",
  },
  {
    code: "2A.ST.06.44",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.44",
    soort: "standaard",
    omschrijving: "De leerlingen stellen de energiebalans van energieomzettingen op aan de hand van de wet van behoud van energie.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.45",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.45",
    soort: "standaard",
    omschrijving: "De leerlingen stellen kwantitatief de energiebalans op van energieomzettingen tussen kinetische, gravitationele of elastische energie in eenvoudige situaties.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.46",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.46",
    soort: "standaard",
    omschrijving: "De leerlingen voeren berekeningen uit in verband met vermogen en rendement bij energieomzettingen in systemen.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.47",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.47",
    soort: "standaard",
    omschrijving: "De leerlingen verklaren het energietransport bij faseovergangen en bij temperatuursveranderingen van stoffen aan de hand van het deeltjesmodel.",
    uitleg: "Onderliggende (kennis)elementen:\n- Absolute temperatuur.",
  },
  {
    code: "2A.ST.06.48",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.48",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren verbanden tussen stroomsterkte, spanning en weerstand in een gelijkstroomkring.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.49",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.49",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken de grootheid vermogen en het Joule-effect om fenomenen in elektrische systemen te verklaren.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.50",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.50",
    soort: "standaard",
    omschrijving: "De leerlingen werken op een veilige en duurzame manier met materialen, stoffen, organismen en technische systemen.",
    uitleg: "",
  },
  {
    code: "2A.ST.06.51",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.51",
    soort: "standaard",
    omschrijving: "De leerlingen voeren onderzoek aan de hand van een wetenschappelijke methode om kennis te ontwikkelen en om vragen te beantwoorden.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de tweede graad.",
  },
  {
    code: "2A.ST.06.52",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.52",
    soort: "standaard",
    omschrijving: "De leerlingen ontwerpen een oplossing voor een probleem door wetenschappen, technologie of wiskunde geïntegreerd aan te wenden.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de tweede graad en de context waarin dit minimumdoel aan bod komt.\n\nMemorie:\nSTEM betekent per definitie dat je geïntegreerd denkt. De mate van integratie is afhankelijk van het probleem. Ook niet-STEM-disciplines kunnen aan bod komen.",
  },
  {
    code: "2A.ST.06.53",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.53",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren de wisselwerking tussen wetenschappen, technologie, wiskunde en de maatschappij aan de hand van maatschappelijke uitdagingen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin dit minimumdoel aan bod komt.",
  },
  {
    code: "2A.ST.07.01",
    stroom: "2A",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.01",
    soort: "standaard",
    omschrijving: "De leerlingen lichten de betekenis, de principes en de werking van de democratische rechtsstaat en hun verantwoordelijkheid daarin toe.",
    uitleg: "Memorie:\nDe democratische rechtsstaat op een bestuursniveau zoals gemeente, provincie, gemeenschap, gewest, federaal, Europese Unie.",
  },
  {
    code: "2A.ST.07.02",
    stroom: "2A",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.02",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over het relationele, gelaagde en dynamische karakter van identiteit.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nHet relationele en dynamische karakter van identiteit zoals gerelateerd aan sociale cohesie, verbondenheid, solidariteit, discriminatie, wij-zij-denken, mensbeeld en wereldbeeld;\nHet gelaagde karakter van identiteit zoals gerelateerd aan:\n- biologische aspecten, persoonlijkheidstrekken, familiale achtergrond;\n- regionale, nationale of supranationale groepen, zoals de Vlaamse, de Belgische, de Europese en de niet-Europese;\n- subculturen, gender-gerelateerde groepen, socio-economische groepen, levensbeschouwelijke groepen.",
  },
  {
    code: "2A.ST.07.03",
    stroom: "2A",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten toe hoe verschillende vormen van diversiteit verrijkend en uitdagend zijn voor het samenleven.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDiversiteit zoals gerelateerd aan fysieke, mentale, cognitieve, socio-economische, culturele, levensbeschouwelijke aspecten;\nVerrijkend zoals culturele verrijking, uitwisseling van ideeën, economische uitwisseling;\nUitdagend zoals meningsverschillen, verschillende belangen, verschillende referentiekaders van waaruit men denkt en handelt, risico van groepsdenken en uitsluiting;\nHet samenleven zoals het samenleven van sociale groepen in vormen als multiculturalisme, monoculturalisme, integratie, assimilatie, inclusie, exclusie.",
  },
  {
    code: "2A.ST.07.04",
    stroom: "2A",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.04",
    soort: "standaard",
    omschrijving: "De leerlingen gaan geïnformeerd, beargumenteerd en constructief in dialoog over maatschappelijke thema’s.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nGeïnformeerd, beargumenteerd en constructief in dialoog gaan zoals door het toepassen van strategieën als actief luisteren, creatief denken, zich inleven, respectvol en duidelijk uitkomen voor zijn mening, een eigen mening onderbouwen, drogredenen herkennen en onderscheiden.",
  },
  {
    code: "2A.ST.08.01",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.01",
    soort: "standaard",
    omschrijving: "De leerlingen bouwen een historisch referentiekader op met structuurbegrippen, scharnierpunten en kenmerken eigen aan de middeleeuwen en de vroegmoderne tijd.",
    uitleg: "Memorie:\nStructuurbegrippen hebben betrekking op tijd, ruimte en maatschappelijke domeinen.\n- Tijd zoals millennium, eeuw, jaar, tijdrekening, chronologie, periode, continuïteit, verandering, breuk, evolutie, revolutie, duur, gelijktijdigheid, ongelijktijdigheid;\n- Ruimte zoals lokaal, regionaal, (West-)Europees, westers en niet-westers, mondiaal, centrum-periferie, open-gesloten ruimte, stedelijk en ruraal, continentaal en maritiem;\n- Maatschappelijke domeinen zoals politiek, sociaal, cultureel, economisch.",
  },
  {
    code: "2A.ST.08.02",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.02",
    soort: "standaard",
    omschrijving: "De leerlingen lichten verbanden toe tussen de maatschappelijke domeinen voor westerse en niet-westerse samenlevingen uit de middeleeuwen en de vroegmoderne tijd.",
    uitleg: "",
  },
  {
    code: "2A.ST.08.03",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten kenmerken toe van interculturele contacten tussen westerse en niet-westerse samenlevingen uit de middeleeuwen en uit de vroegmoderne tijd.",
    uitleg: "",
  },
  {
    code: "2A.ST.08.04",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.04",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken kenmerken van bestudeerde samenlevingen in eenzelfde periode en tussen periodes.",
    uitleg: "Memorie:\nKenmerken hebben betrekking op politieke kenmerken, sociale kenmerken, economische kenmerken, culturele kenmerken:\n- Politiek: staats(her)vorming en veranderende territoriale invulling; imperialisme; (neo)kolonialisme; dekolonisatie; politieke ideologieën; breuklijnen; natie; bestuurlijke organisatie en staatsvorm (zoals totalitaire staat, rechtsstaat, dictatuur, democratie); mensenrechten; supranationale en intergouvernementele organisaties;\n- Sociaal: gelaagde samenleving; nomadische, agrarische, industriële en postindustriële samenleving; sociale bewegingen; verzorgingsstaat; welvaartsstaat; (on)gelijkheid; (on)vrijheid; oorlog, geweld en vrede; genocide; minderheden; wij-zij-denken; burgerrechten; onderdrukking en emancipatie; gezinsorganisatie; demografische processen; migratie; interactie met natuur;\n- Cultureel: tradities en gewoonten; mens- en wereldbeelden; kunst- en cultuuruitingen; culturele en artistieke stromingen; filosofie; levensbeschouwing en levensbeschouwelijke organisatie; secularisatie; moderniteit; multiculturele samenleving; etnocentrisme; diversiteit; fundamentalisme; wetenschappen en technologie; onderwijs; informatie- en communicatie(r)evolutie; propaganda; voedingspatronen; vrijetijdsbeleving;\n- Economisch: economische systemen en theorieën; economische sectoren; industrialisering; kapitalisme; mondialisering; arbeidsorganisatie; productiemethoden; grondstoffen en materialen; energiebronnen; consumptiemaatschappij; vraag en aanbod; concurrentie; transport(r)evolutie; innovatie.",
  },
  {
    code: "2A.ST.08.05",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.05",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken de courante westerse periodisering met andere periodiseringen in tijd en ruimte.",
    uitleg: "Memorie:\nDe zeven periodes van het courante westerse historische referentiekader: de prehistorie, het oude nabije oosten, de klassieke oudheid, de middeleeuwen, de vroegmoderne tijd, de moderne tijd, de hedendaagse tijd.",
  },
  {
    code: "2A.ST.08.06",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.06",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren kritisch historische bronnen met betrekking tot de bestudeerde periodes in functie van een historische vraag.",
    uitleg: "",
  },
  {
    code: "2A.ST.08.07",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.07",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken historische bronnen met betrekking tot de bestudeerde periodes in functie van een historische vraag.",
    uitleg: "",
  },
  {
    code: "2A.ST.08.08",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.08",
    soort: "standaard",
    omschrijving: "De leerlingen beantwoorden een historische vraag aan de hand van historische bronnen met betrekking tot de bestudeerde periodes en historische redeneerwijzen.",
    uitleg: "Memorie:\nHistorische redeneerwijzen zoals causaal redeneren, meerdere perspectieven hanteren, zich inleven in de context van het verleden, continuïteit en verandering analyseren, bewijs gebruiken, actualiseren en historiseren, tussen historische feiten verbanden leggen, historisch contextualiseren, over bronnen reflecteren, de menselijke en structurele (f)actoren (agency) benoemen, veralgemening en stereotypering onderzoeken.",
  },
  {
    code: "2A.ST.08.09",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.09",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren de invloed van de eigen standplaatsgebondenheid en die van anderen op historische beeldvorming met betrekking tot de bestudeerde periodes.",
    uitleg: "",
  },
  {
    code: "2A.ST.08.10",
    stroom: "2A",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.10",
    soort: "standaard",
    omschrijving: "De leerlingen lichten betekenissen toe die men geeft aan historische fenomenen uit de bestudeerde periodes.",
    uitleg: "Onderliggende (kennis)elementen:\n- Persoonlijke betekenisgeving;\n- Collectieve herinneringen.",
  },
  {
    code: "2A.ST.09.01",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.01",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren demografische processen op basis van demografische indicatoren en beïnvloedende factoren.",
    uitleg: "Memorie:\n- Demografische processen zoals bevolkingsgroei, emigratie, immigratie, vergrijzing, demografische transitie;\n- Demografische indicatoren zoals geboortecijfer, sterftecijfer, natuurlijke aangroei, leeftijdsstructuur, migratiesaldo, bevolkingsdichtheid, ontwikkelingsgraad;\n- Beïnvloedende factoren zoals motivatie voor migratie (politieke systemen, oorlogssituatie), geboortebeleid, fysische factoren (klimaat, reliëf, bodemkwaliteit), sociaal-economische factoren (welzijn, welvaart, armoede).",
  },
  {
    code: "2A.ST.09.02",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.02",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren de interactie tussen productie en consumptie op mondiale schaal.",
    uitleg: "",
  },
  {
    code: "2A.ST.09.03",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.03",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren factoren die productie en consumptie beïnvloeden aan de hand van voorbeelden uit landbouw, industrie, ontginning van grondstoffen, energieproductie of diensten.",
    uitleg: "",
  },
  {
    code: "2A.ST.09.04",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.04",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren de impact van mondialisering op demografische processen en op de ruimtelijke interactie tussen productie en consumptie.",
    uitleg: "",
  },
  {
    code: "2A.ST.09.05",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.05",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren ruimtelijke gevolgen van demografische processen, productie en consumptie.",
    uitleg: "Memorie:\n- Ruimtelijke gevolgen zoals veranderingen in structuren en patronen in de bebouwde ruimte, veranderingen in structuren en patronen in de open ruimte.",
  },
  {
    code: "2A.ST.09.06",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.06",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren oorzaken en gevolgen van het versterkt broeikaseffect.",
    uitleg: "Memorie:\n- Oorzaken van het versterkt broeikaseffect zoals evolutie van de belangrijkste broeikasgassen in de atmosfeer en de herkomst ervan;\n- Gevolgen van het versterkt broeikaseffect zoals stijging van het zeepeil, verschuiven van klimaten en verspreidingsgebieden van planten en dieren, spreiding van tropische ziektes, extreme weerfenomenen.",
  },
  {
    code: "2A.ST.09.07",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.07",
    soort: "standaard",
    omschrijving: "De leerlingen zetten terreintechnieken en geografische hulpbronnen met inbegrip van GIS-viewers functioneel in.",
    uitleg: "Memorie:\n- Terreintechnieken zoals bodem-, geluids- of wateronderzoek, verkeersonderzoek, enquête, observatie, terreinkartering;\n- Geografische hulpbronnen zoals kaart, atlas, satellietbeeld, luchtfoto, statistisch bronnenmateriaal, leeftijdshistogram, klimatogram.",
  },
  {
    code: "2A.ST.09.08",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.08",
    soort: "standaard",
    omschrijving: "De leerlingen situeren absoluut en relatief personen, plaatsen, patronen en processen uit de tweede graad op relevante ruimtelijke schaalniveaus.",
    uitleg: "Voetnoot:\nRekening houdend met personen, plaatsen, patronen en processen die in de tweede graad aan bod komen.",
  },
  {
    code: "2A.ST.09.09",
    stroom: "2A",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.09",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren de invloed van de persoonlijke en maatschappelijke context van mensen op ruimtelijke beeldvorming.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nInvloeden zoals:\n- factoren die de beleving en betekenis van een plaats beïnvloeden (persoonlijke, sociale, maatschappelijke, politieke en culturele context);\n- de reële, ervaren en mentale afstand en tijd;\n- de mentale kaart;\n- de cartografische voorstelling op ruimtelijke beeldvorming.",
  },
  {
    code: "2A.ST.13.01",
    stroom: "2A",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.01",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren cyclisch en vakspecifiek over het eigen leerproces en sturen het op basis daarvan doelgericht bij.",
    uitleg: "",
  },
  {
    code: "2A.ST.13.02",
    stroom: "2A",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.02",
    soort: "standaard",
    omschrijving: "De leerlingen zetten (meta)cognitieve leer- en regulatiestrategieën in om zich leerinhouden eigen te maken.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- (Meta)cognitieve leerstrategieën zoals structureren, zich vragen stellen bij de leerinhoud, memoriseren, herhalen, selecteren, relateren, toepassen, inoefenen;\n- (Meta)cognitieve regulatiestrategieën zoals plannen, monitoren, evalueren, bijsturen.",
  },
  {
    code: "2A.ST.13.03",
    stroom: "2A",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.03",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken school- en vaktaal.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- Vaktaal zoals domeinspecifieke terminologie, symbolen.\n\nVoor het leerproces is het belangrijk dat leerlingen schooltaal en vaktaal kunnen gebruiken. Daartoe behoort vakterminologie relevant voor het realiseren van de eindtermen basisvorming en de specifieke eindtermen.",
  },
  {
    code: "2A.ST.13.04",
    stroom: "2A",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.04",
    soort: "standaard",
    omschrijving: "De leerlingen zoeken doelgericht informatie in diverse bronnen en verwerken die op een kritische en systematische manier.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- Bronnen zoals personen, digitale en niet-digitale tijdschriften, encyclopedieën, boeken, audiovisueel materiaal.",
  },
  {
    code: "2A.ST.15.01",
    stroom: "2A",
    competentieNr: 15,
    competentie: "15. Ontwikkeling van initiatief, ambitie, ondernemingszin en loopbaancompetenties",
    nummer: "15.01",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen bewust hun studie- of beroepskeuzeproces.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- Doorlopen van een studie- of beroepskeuzeproces zoals met behulp van de keuzetaken oriënteren, zelfconceptverheldering, exploreren in de breedte, exploreren in de diepte, studiekeuzenabijheid, binding.",
  },
  {
    code: "2A.ST.15.02",
    stroom: "2A",
    competentieNr: 15,
    competentie: "15. Ontwikkeling van initiatief, ambitie, ondernemingszin en loopbaancompetenties",
    nummer: "15.02",
    soort: "standaard",
    omschrijving: "De leerlingen genereren creatieve ideeën om een probleem op te lossen en bespreken de uitvoerbaarheid ervan aan de hand van criteria.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- Ideeën genereren zoals door middel van ideegeneratietechnieken (bv. door middel van een brainstorm, mindmap) en ideeselectietechnieken (bv. van divergent naar convergent denken);\n- Aangereikte of zelf bepaalde criteria zoals tijd, middelen, technische haalbaarheid, ethische principes, duurzaamheidsprincipes, meerwaarde.",
  },
  {
    code: "2A.ST.16.01",
    stroom: "2A",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.01",
    soort: "standaard",
    omschrijving: "De leerlingen brengen kunst- en cultuuruitingen in verband met de context waarin ze voorkomen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- Kunst- en cultuuruitingen zoals dans, film, game, graffiti, kledij, landschap, lied;\n- Context zoals tijd, ruimte, maatschappelijke context.",
  },
  {
    code: "2A.ST.16.02",
    stroom: "2A",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.02",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over eigen beleving bij uiteenlopende kunst- en cultuuruitingen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "2A.ST.16.03",
    stroom: "2A",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten toe hoe een kunstwerk vanuit vorm en inhoud betekenis geeft.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\n- Inhoud zoals:\n  * onderwerp zoals geboorte, dood, liefde, geschiedenis, het leven, het alledaagse, rituelen;\n  * bedoeling zoals decoreren, entertainen, praktisch gebruik, informeren, confirmeren, revolteren.\n- Vorm zoals bouwstenen, technieken, materialen afhankelijk van het gekozen kunstwerk en de gekozen expressievorm zoals beeld, muziek, drama, dans of audiovisuele media, apart of gecombineerd. In het geval van:\n  * Beeld: Bouwstenen zoals compositie, kleur, licht, lijn, ruimte, textuur, vorm; Technieken zoals boetseren, fotograferen, maquettes maken, met textiel werken, schilderen; Materialen zoals klei, licht, papier, recuperatiematerialen, steen, verf.\n  * Muziek: Bouwstenen zoals dynamiek, klankkleur, melodie, ritme, samenklank, structuur, tempo, vorm; Technieken zoals body percussion, improvisatie, samenzang; Materialen zoals instrumenten, lichaam, stem, voorwerpen.\n  * Drama: Bouwstenen zoals rol, ruimte, structuur, samenspel, tijd; Technieken zoals clownerie, figurentheater, improvisatie, mime, teksttheater; Materialen zoals decor, geluid, kostuums, lichaam, taal.\n  * Dans: Bouwstenen zoals kracht, ruimte, relatie, tijd; Technieken zoals bewegingsreeks, choreografie, dansexpressie, dansimprovisatie; Materialen zoals decor, geluid, lichaam, voorwerpen.\n  * Audiovisuele media: Bouwstenen zoals camerabeweging, geluid, kader, licht, montage; Technieken zoals montage, opname, sonorisatie; Materialen zoals microfoon, montageunit, smartphone.",
  },
  {
    code: "2A.ST.16.04",
    stroom: "2A",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.04",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen een artistiek-creatief proces vanuit verbeelding.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nBij het doorlopen van een artistiek-creatief proces kan je denken aan:\n- het selecteren van ideeën zoals bij eigen gedachten en gevoelens stilstaan, artistieke werken bestuderen, indrukken of objecten verzamelen;\n- het koppelen van de eigen bedoeling aan vormgeving via methodes zoals trial and error, try-out;\n- het gebruiken van basistechnieken van de gekozen discipline.",
  },
  {
    code: "2A.UD.01.02.01",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Historisch bewustzijn: uitbreiding",
    nummer: "01.02.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen beoordelen de onderzoekbaarheid van een historische vraag.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.01",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen ontwerpen een oplossing of deeloplossing voor een zelf afgebakende uitdaging.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.02",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen besluiten welke oplossing of deeloplossing voor een zelf afgebakende uitdaging tot uitvoering zal worden gebracht.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.03",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.03",
    soort: "uitbreiding",
    omschrijving: "De leerlingen voeren een ontwerp uit van een oplossing of deeloplossing voor een zelf afgebakende uitdaging.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.04",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.04",
    soort: "uitbreiding",
    omschrijving: "De leerlingen borgen de uitvoering van een oplossing of deeloplossing voor een zelf afgebakende uitdaging, sturen ze bij en sluiten ze af.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.05",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.05",
    soort: "uitbreiding",
    omschrijving: "De leerlingen participeren actief en inclusief aan een groepsproject.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.06",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.06",
    soort: "uitbreiding",
    omschrijving: "De leerlingen reflecteren over de eigen rol en het eigen gedrag bij het samenwerken aan een groepsproject.",
    uitleg: "",
  },
  {
    code: "2A.UD.01.03.07",
    stroom: "2A",
    competentieNr: 1,
    competentie: "1. Algemene doorstroomcompetenties - Ondernemingszin",
    nummer: "01.03.07",
    soort: "uitbreiding",
    omschrijving: "De leerlingen reflecteren over het eigen leer- en werkproces in relatie tot hun zelfconcept.",
    uitleg: "",
  },
  {
    code: "2A.UD.02.08.01",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Nederlands: Algemene uitbreiding",
    nummer: "02.08.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen benoemen taalbeschouwelijke elementen en passen inzicht erin toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "",
  },
  {
    code: "2A.UD.02.08.02",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Nederlands: Algemene uitbreiding",
    nummer: "02.08.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen analyseren hoe in literaire teksten betekenissen worden gecreëerd met narratieve, poëticale en theatrale structuren en technieken.",
    uitleg: "Onderliggende (kennis)elementen:\n- Elementen van spanningsopbouw: spanningsboog, climax, cliffhanger;\n- Middeleeuwen, romantiek, realisme.",
  },
  {
    code: "2A.UD.02.10.01",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Nederlands: literatuur",
    nummer: "02.10.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen analyseren hoe literatuur en de plaats die ze inneemt in de maatschappij evolueren doorheen de tijd.",
    uitleg: "Onderliggende (kennis)elementen:\n- Literair-historische achtergrond van teksten uit twee stromingen of periodes;\n- Adaptatie.",
  },
  {
    code: "2A.UD.02.14.01",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Engels en Frans: algemene uitbreiding",
    nummer: "02.14.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\n- Teksten in het Engels en in het Frans.\n\nTekstkenmerken voor receptie:\n- Tekststructuur met een beperkte mate van complexiteit;\n- Vrij grote en herkenbare samenhang;\n- Hoofdzakelijk frequente woorden, woordcombinaties en vaste uitdrukkingen uit een beperkte waaier aan relevante thema’s binnen het persoonlijke, publieke en educatieve domein;\n- Concrete tot vrij algemene inhoud;\n- Niet al te hoge informatiedichtheid;\n- Zinsbouw met een beperkte mate van complexiteit;\n- Vrij lange teksten;\n- Ruime variatie aan tekstsoorten.\n* Bijkomend voor schriftelijke receptie: Vrij duidelijke lay-out;\n* Bijkomend voor mondelinge receptie: Met een beperkte mate van achtergrondruis; Normaal spreektempo met weinig pauzes; Ondersteunende maar natuurlijke intonatie; Heldere uitspraak, duidelijke articulatie; Met lichte afwijking ten opzichte van de standaardtaal.",
  },
  {
    code: "2A.UD.02.14.02",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Engels en Frans: algemene uitbreiding",
    nummer: "02.14.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\n- Teksten in het Engels en in het Frans;\n- Tekstkenmerken voor receptie.",
  },
  {
    code: "2A.UD.02.14.03",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Engels en Frans: algemene uitbreiding",
    nummer: "02.14.03",
    soort: "uitbreiding",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Onderliggende (kennis)elementen:\n- In het Engels en in het Frans.\n\nMinimumvereisten voor productie:\n- Gepaste en duidelijk herkenbare tekststructuur met een beperkte mate van complexiteit;\n- Duidelijk herkenbare tekstverbanden;\n- Beheersing van hoofdzakelijk frequente woorden, woordcombinaties en vaste uitdrukkingen om zich uit te drukken over een brede waaier aan relevante thema’s binnen het persoonlijke, publieke en educatieve domein al kunnen lexicale beperkingen leiden tot herhaling, tot omhaal van woorden en tot moeite met formulering;\n- Vrij concrete tot vrij algemene of abstracte inhoud;\n- Over het algemeen goede beheersing van eerder en nieuwverworven grammaticale structuren, maar met merkbare invloed vanuit de moedertaal; fouten komen voor, maar begrip van boodschap door ontvanger komt meestal niet in het gedrang;\n- Zinsbouw met een beperkte mate van complexiteit;\n- Gepast register;\n- Vrij korte teksten en af en toe langere teksten;\n- Ruime variatie aan tekstsoorten.\n* Bijkomend voor schriftelijke productie: Duidelijk herkenbare tekstopbouw en tekstopbouwende elementen: titel, alinea; Gepaste lay-out; Heldere doorlopende tekst die over het algemeen te begrijpen is; spelling, leestekengebruik en lay-out staan tekstbegrip niet in de weg;\n* Bijkomend voor mondelinge productie: Gepaste lichaamstaal; Uitspraak is over het algemeen duidelijk te verstaan en begrip van de boodschap komt meestal niet in het gedrang ondanks mogelijke uitspraakfouten; Kan zich betrekkelijk vlot uitdrukken ondanks mogelijke pauzes of herstelacties.\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen.",
  },
  {
    code: "2A.UD.02.14.04",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Engels en Frans: algemene uitbreiding",
    nummer: "02.14.04",
    soort: "uitbreiding",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Onderliggende (kennis)elementen:\n- In het Engels en in het Frans;\n- Tekstkenmerken voor receptie;\n- Minimumvereisten voor productie.\n\nBijkomend voor mondelinge en schriftelijke interactie:\n- Gepaste beleefdheidsconventies bij taalhandelingen.\n* Bijkomend voor mondelinge interactie: Kan onvoorbereid met enig vertrouwen communiceren in minder alledaagse situaties; Kan een gesprek beginnen, gaande houden en beëindigen; Kan ingrijpen in een discussie en de juiste frase gebruiken om aan het woord te komen.",
  },
  {
    code: "2A.UD.02.14.05",
    stroom: "2A",
    competentieNr: 2,
    competentie: "2. Moderne talen - Engels en Frans: algemene uitbreiding",
    nummer: "02.14.05",
    soort: "uitbreiding",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Werkwoorden: ind. plus-que-parfait [F];\n- Gebruik van wijzen na frequente voegwoorden en werkwoorden [F];\n- Voorwaardelijke zinnen: l’hypothèse/la condition (met si + ind. présent + ind. Imparfait) [F].",
  },
  {
    code: "2A.UD.04.01.01",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Kunst en Cultuur - Artistieke expressie",
    nummer: "04.01.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen doorlopen een artistiek proces in functie van een creatie.",
    uitleg: "",
  },
  {
    code: "2A.UD.04.01.02",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Kunst en Cultuur - Artistieke expressie",
    nummer: "04.01.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen creëren artistiek werk met behulp van specifieke bouwstenen, technieken en materialen.",
    uitleg: "",
  },
  {
    code: "2A.UD.04.01.03",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Kunst en Cultuur - Artistieke expressie",
    nummer: "04.01.03",
    soort: "uitbreiding",
    omschrijving: "De leerlingen zetten hun artistieke deskundigheid in voor een gemeenschappelijk project.",
    uitleg: "",
  },
  {
    code: "2A.UD.04.01.04",
    stroom: "2A",
    competentieNr: 4,
    competentie: "4. Kunst en Cultuur - Artistieke expressie",
    nummer: "04.01.04",
    soort: "uitbreiding",
    omschrijving: "De leerlingen gaan in dialoog over elkaars artistiek proces en werk.",
    uitleg: "",
  },
  {
    code: "2A.UD.06.01.01",
    stroom: "2A",
    competentieNr: 6,
    competentie: "6. Wiskunde - Statistiek",
    nummer: "06.01.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen analyseren het verband tussen twee numerieke grootheden in een dataset met behulp van een spreidingsdiagram.",
    uitleg: "Onderliggende (kennis)elementen:\n- Trendlijn;\n- Correlatiecoëfficiënt.",
  },
  {
    code: "2A.UD.15.01.01",
    stroom: "2A",
    competentieNr: 15,
    competentie: "15. Sociale Wetenschappen - Samenleving en politiek: sociale en humane wetenschappen",
    nummer: "15.01.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen lichten toe hoe sociale instituties bijdragen tot socialisatie.",
    uitleg: "",
  },
  {
    code: "2A.UD.15.01.02",
    stroom: "2A",
    competentieNr: 15,
    competentie: "15. Sociale Wetenschappen - Samenleving en politiek: sociale en humane wetenschappen",
    nummer: "15.01.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen lichten sociale structuren en rollenconflicten toe.",
    uitleg: "",
  },
  {
    code: "2A.FR.17.01",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP1",
    soort: "freinet",
    omschrijving: "De leerlingen verdiepen zich in de freinetpedagogie, plaatsen die in haar historische context en evalueren haar actualiteitswaarde. Ze verhouden zich kritisch t.a.v. de emancipatorische principes en de toepassing ervan binnen de school.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
  {
    code: "2A.FR.17.02",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP2",
    soort: "freinet",
    omschrijving: "De leerlingen verdiepen hun inzicht in de principes van democratische besluitvorming en passen die wendbaar toe op klas- en schoolniveau.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
  {
    code: "2A.FR.17.03",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP3",
    soort: "freinet",
    omschrijving: "De leerlingen verdiepen zich in de basisbeginselen van coöperatief samenwerken en passen die wendbaar toe op klas- en schoolniveau.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
  {
    code: "2A.FR.17.04",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP4",
    soort: "freinet",
    omschrijving: "De leerlingen verdiepen hun inzicht in de principes van conflicthantering en passen die wendbaar toe op klas- en schoolniveau.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
  {
    code: "2A.FR.17.05",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP5",
    soort: "freinet",
    omschrijving: "De leerlingen brengen samenlevingsinitiatieven en –problematieken in de ruimere omgeving van de school (bv. gemeente, regio) in kaart en engageren zich actief in burgerschapsprojecten, die ze vervolgens ook kritisch evalueren.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
  {
    code: "2A.FR.17.06",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP6",
    soort: "freinet",
    omschrijving: "De leerlingen verdiepen hun inzicht in de verschillende kennis- en vaardigheidsdomeinen (*) van de samenleving, waarderen het belang van elk van deze domeinen en ontdekken, verkennen en ontwikkelen gaandeweg hun eigen interessegebieden.",
    uitleg: "(*) Het betreft de volgende deelgebieden:\n(1) natuurexploratie, -zorg en -beheer;\n(2) handvaardigheid, bouw en techniek;\n(3) kennisverwerving en -verdieping;\n(4) experimenteren, wetenschappelijk onderzoek en innovatiedenken;\n(5) digitale competentie, mediawijsheid, moderne technologieën;\n(6) expressie, artistieke vormgeving, creatie, ontwerp;\n(7) andere (bijvoorbeeld welzijn, zorg, sport en beweging).\n\nToelichting:\nNaast een verplicht aanbod aan kortlopende ateliers, kan de school in de tweede graad ook een beperkt atelieraanbod op trimester-, semester- of jaarbasis organiseren. De leerlingen kiezen dan een ‘focusatelier’. Zo kunnen sommige leerlingen hun kennis en vaardigheden in een specifiek domein naar keuze ontwikkelen. De formulering van doelen voor het (de) gekozen domein(en) gebeurt in overleg tussen leerlingen en mentoren. Hiervoor kan inspiratie gezocht worden in onder meer de specifieke doelen van wetenschapsdomeinen die niet aan het structuuronderdeel Freinetpedagogie gekoppeld werden, evenwel zonder dat dit leidt tot een selectieve of verplichte studiekeuze.",
  },
  {
    code: "2A.FR.17.07",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP7",
    soort: "freinet",
    omschrijving: "De leerlingen leren onder begeleiding onderzoeksvragen formuleren en deze vervolgens (onder begeleiding) beantwoorden met behulp van specifieke onderzoeksmethoden en -technieken, bronnen, onderzoeksgegevens en resultaten; ze leren over het uitgevoerde onderzoek rapporteren en reflecteren en evalueren het proces.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
  {
    code: "2A.FR.17.08",
    stroom: "2A",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "KP8",
    soort: "freinet",
    omschrijving: "De leerlingen begrijpen vanuit een praktijkervaring extra muros de werking van een socio-economische organisatie; ze schetsen, eventueel met behulp van richtvragen, de werking van de betrokken organisatie en evalueren hun eigen functioneren tijdens de ervaringsweek.",
    uitleg: "Keerpuntleerplandoelen 2de graad doorstroom.",
  },
];
