// AUTO-GEGENEREERD uit docs/reference/doelen1GRB_volledig.xlsx (blad "1B").
// Niet handmatig herschikken; regenereer bij een nieuwe export.
import type { Minimumdoel } from "./minimumdoelen";

export const minimumdoelen1B: Minimumdoel[] = [
  {
    code: "1B.ST.01.01",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.01",
    soort: "standaard",
    omschrijving: "De leerlingen passen technieken voor eerste hulp bij ongevallen toe in een gesimuleerde leeromgeving.",
    uitleg: "Memorie:\nTechnieken voor eerste hulp bij ongevallen zoals verstuiking, wonde, bloedneus, brandwonde.",
  },
  {
    code: "1B.ST.01.02",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.02",
    soort: "standaard",
    omschrijving: "De leerlingen ontwikkelen gezondheidsvaardigheden in functie van hun fysiek en mentaal welzijn binnen verschillende thema’s.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nGezondheidsvaardigheden met betrekking tot:\n- voeding zoals ultrabewerkt voedsel, gezonde snacks, duurzame voeding, evenwichtige voeding;\n- hygiëne zoals basisregels voor lichaams-, mond- en handhygiëne;\n- beweging zoals beweegnormen, sedentair gedrag;\n- seksuele gezondheid en seksuele ontwikkeling in de puberteit;\n- verslavingen: middelen en handelingen.",
  },
  {
    code: "1B.ST.01.03",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.03",
    soort: "standaard",
    omschrijving: "De leerlingen voeren conform de beweegrichtlijnen in verschillende bewegingsomgevingen activiteiten uit in verschillende individuele, interactieve en ritmisch expressieve bewegingsdomeinen.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals bewegingsomgevingen en bewegingsdomeinen) waarin het minimumdoel aan bod komt.\n\nMemorie:\nHet is aangewezen om dit doel in verschillende spelvormen en sporten te realiseren met het oog op het aanwakkeren van de interesse voor en het plezier in beweging en sport in functie van het individueel levenslang bewegen en sporten.\nBewegingsomgevingen zoals sportzaal, sportveld, speelplein, aquatisch milieu.",
  },
  {
    code: "1B.ST.01.04",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.04",
    soort: "standaard",
    omschrijving: "De leerlingen ontwikkelen lenigheid, uithouding, snelheid, coördinatie en evenwicht, rekening houdend met de evolutie van hun fysieke capaciteiten.",
    uitleg: "",
  },
  {
    code: "1B.ST.01.05",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.05",
    soort: "standaard",
    omschrijving: "De leerlingen voeren motorische basisvaardigheden uit, rekening houdend met ergonomische principes en de evolutie van hun fysieke capaciteiten.",
    uitleg: "Memorie:\nMotorische basisvaardigheden zoals balanceren, wentelen, springen, rollen, klauteren, klimmen, ritmisch bewegen, lopen, vangen, werpen, terugslaan, vallen, mee- en tegengaan in beweging.\n\nErgonomische principes zoals van toepassing bij heffen, tillen, staan, verplaatsen, rughygiëne.",
  },
  {
    code: "1B.ST.01.06",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.06",
    soort: "standaard",
    omschrijving: "De leerlingen passen tactieken en principes toe met respect voor de afgesproken regels en rollen in sport en spel.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals de bewegingsdomeinen) waarin het minimumdoel aan bod komt.\n\nMemorie:\nRollen in sport en spel zoals de beoefenaar, de coach, de scheidsrechter, de winnaar, de verliezer.",
  },
  {
    code: "1B.ST.01.07",
    stroom: "1B",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.07",
    soort: "standaard",
    omschrijving: "De leerlingen hanteren in verschillende rollen in sport en spel principes van verantwoord en veilig gedrag.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals de bewegingsdomeinen) waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1B.ST.02.01",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.01",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie:\n- Herkenbare, expliciet aangegeven structuur\n- Grote samenhang\n- Voornamelijk Standaardnederlands\n- Voornamelijk frequente woorden\n- Heel eenvoudig figuurlijk taalgebruik\n- Concrete en herkenbare inhoud\n- Lage informatiedichtheid\n- Tekstsoorten: informatief, persuasief, opiniërend, prescriptief en narratief\n* Bijkomend voor schriftelijke receptie: Duidelijke lay-out\n* Bijkomend voor mondelinge receptie: Laag tot normaal spreektempo\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen in functie van het begrijpen van teksten.",
  },
  {
    code: "1B.ST.02.02",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.02",
    soort: "standaard",
    omschrijving: "De leerlingen beoordelen doelgericht aangereikte informatie op betrouwbaarheid en bruikbaarheid bij het lezen en luisteren.",
    uitleg: "",
  },
  {
    code: "1B.ST.02.03",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.03",
    soort: "standaard",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie.\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om relevante informatie te selecteren.",
  },
  {
    code: "1B.ST.02.04",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.04",
    soort: "standaard",
    omschrijving: "De leerlingen spreken en schrijven doelgericht in eenvoudige communicatieve situaties.",
    uitleg: "Minimumvereisten voor productie:\n- Eenvoudige tekststructuur\n- Redelijk herkenbare samenhang\n- Gepast register\n- Concrete inhoud\n- Variatie aan tekstsoorten\n* Bijkomend voor schriftelijke productie: Gepaste lay-out; Taalgebruik met aandacht voor Standaardnederlands, spelling, interpunctie, woordkeuze, zinsbouw, helderheid, adequaatheid en correctheid\n* Bijkomend voor mondelinge productie: Taalgebruik met aandacht voor Standaardnederlands, uitspraak, intonatie, woordkeuze, zinsbouw, helderheid, adequaatheid en correctheid; Gepaste lichaamstaal\n\nOndersteunende middelen: Met behulp van ondersteunende middelen.\n\nMemorie:\nHet betreft ondersteunende middelen zoals een kaartje met steekwoorden, structuur, schrijfkader, spreekkader, voorleessoftware, presentatiesoftware enz. maar ook talige hulpmiddelen.",
  },
  {
    code: "1B.ST.02.05",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.05",
    soort: "standaard",
    omschrijving: "De leerlingen drukken zich creatief uit met taal.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nZich creatief uitdrukken zoals het gebruiken van eenvoudige technieken, bijvoorbeeld lay-out, rijm en ritme.",
  },
  {
    code: "1B.ST.02.06",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.06",
    soort: "standaard",
    omschrijving: "De leerlingen nemen doelgericht deel aan eenvoudige mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken & Minimumvereisten.\n\nMemorie:\nMondelinge interactie veronderstelt minimaal dat leerlingen voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context.",
  },
  {
    code: "1B.ST.02.07",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.07",
    soort: "standaard",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "Voetnoot:\nDit minimumdoel wordt doelgericht ingezet in functie van alle andere minimumdoelen binnen sleutelcompetentie 2. Rekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nStrategieën hebben betrekking op lees-, luister-, spreek- en schrijfvaardigheden.",
  },
  {
    code: "1B.ST.02.08",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.08",
    soort: "standaard",
    omschrijving: "De leerlingen zetten eerder en nieuwverworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en met de context waarin het minimumdoel aan bod komt.\n\nTekstkenmerken voor receptie & Minimumvereisten voor productie.",
  },
  {
    code: "1B.ST.02.09",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.09",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Onderscheid klank- en schriftbeeld\n- Samenstellingen en afleidingen: meervoud/enkelvoud, verkleinwoord\n- Werkwoorden: stam, uitgang\n- Woordsoorten: zelfstandig naamwoord, werkwoord, lidwoord\n- Zinsdelen: onderwerp, persoonsvorm\n- Zinssoorten: mededelende/vragende/uitroepende zinnen\n- Betekenisrelaties: letterlijk/figuurlijk\n- Heel eenvoudige beeldspraak en vergelijking\n- Spelling van woorden met vast woordbeeld: klankzuivere woorden en hoogfrequente niet-klankzuivere woorden\n- Spelling van woorden met veranderlijk woordbeeld: klinker in open/gesloten lettergreep, verdubbeling medeklinker\n- Hoofdletters\n- Interpunctietekens: punt, vraagteken, uitroepteken\n- Congruentie\n- Werkwoordstijden om verleden, heden en toekomst uit te drukken",
  },
  {
    code: "1B.ST.02.10",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.10",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in taalgebruik toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Tekstopbouwende elementen: titel, afbeeldingen en eenvoudige lay-out\n- Structuuraanduiders: signaalwoorden en verwijswoorden\n- Communicatiemodel: zender, boodschap, ontvanger, kanaal, doel\n- Effecten van non-verbaal gedrag\n- Meest elementaire, alledaagse beleefdheidsconventies\n- Registers\n- Taalhandelingen",
  },
  {
    code: "1B.ST.02.11",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.11",
    soort: "standaard",
    omschrijving: "De leerlingen geven overeenkomsten en verschillen aan in taaluitingen, tussen standaardtaal en regionale taalvariëteiten en tussen talen.",
    uitleg: "",
  },
  {
    code: "1B.ST.02.12",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.12",
    soort: "standaard",
    omschrijving: "De leerlingen verwoorden de eigen beleving en interpretatie van literaire teksten.",
    uitleg: "Tekstkenmerken:\n- Variatie aan genres\n\nVoetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nEigen beleving en interpretatie zoals waarom sommige aspecten van de tekst aanspreken, waarom men zich identificeert met een bepaald personage, in welke zin men gelijkaardige ervaringen zelf al heeft meegemaakt, waarom de tekst een bepaalde emotionele reactie teweegbrengt, waarom de uitdrukkingsvorm of stijl aanspreekt.",
  },
  {
    code: "1B.BG.BG02.01",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "BG02.01",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling haalt bij het lezen en luisteren doelgericht het onderwerp en relevante informatie uit niet-fictionele teksten.",
    uitleg: "Tekstkenmerken voor receptie.\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp te bepalen en informatie te selecteren.",
  },
  {
    code: "1B.BG.BG02.02",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "BG02.02",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling spreekt en schrijft doelgericht in eenvoudige communicatieve situaties.",
    uitleg: "Minimumvereisten voor productie & Ondersteunende middelen.",
  },
  {
    code: "1B.BG.BG02.03",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "BG02.03",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling neemt doelgericht deel aan eenvoudige mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken & Minimumvereisten.\n\nMemorie:\nMondelinge interactie veronderstelt minimaal dat leerlingen voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context.",
  },
  {
    code: "1B.UD.UD02.01",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie.\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen.",
  },
  {
    code: "1B.UD.UD02.02",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen beoordelen doelgericht informatie op betrouwbaarheid, correctheid en bruikbaarheid bij het lezen en luisteren.",
    uitleg: "",
  },
  {
    code: "1B.UD.UD02.03",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.03",
    soort: "uitbreiding",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken & Memorie.",
  },
  {
    code: "1B.UD.UD02.04",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.04",
    soort: "uitbreiding",
    omschrijving: "De leerlingen nemen notities bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken & Minimumvereisten & Memorie.",
  },
  {
    code: "1B.UD.UD02.05",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.05",
    soort: "uitbreiding",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Minimumvereisten voor productie & Ondersteunende middelen & Memorie.",
  },
  {
    code: "1B.UD.UD02.06",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.06",
    soort: "uitbreiding",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken & Minimumvereisten & Memorie.",
  },
  {
    code: "1B.UD.UD02.07",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.07",
    soort: "uitbreiding",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "Voetnoot & Memorie.",
  },
  {
    code: "1B.UD.UD02.08",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.08",
    soort: "uitbreiding",
    omschrijving: "De leerlingen zetten eerder en nieuwverworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Tekstkenmerken & Minimumvereisten & Voetnoot.",
  },
  {
    code: "1B.UD.UD02.09",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.09",
    soort: "uitbreiding",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Klanken: lange en korte klinkers\n- Samenstellingen en afleidingen: voorvoegsel, achtervoegsel\n- Werkwoordstijden: heden, verleden, toekomst, etc.\n- Woordsoorten, zinsdelen, zinssoorten\n- Betekenisrelaties: synoniem, homoniem\n- Beeldspraak, vergelijking, spelling, interpunctie",
  },
  {
    code: "1B.UD.UD02.10",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.10",
    soort: "uitbreiding",
    omschrijving: "De leerlingen passen inzicht in taalgebruik toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\n- Tekstopbouwende elementen, lay-out\n- Tekststructuur\n- Communicatiemodel, effecten of stereotypering\n- Beleefdheidsconventies, registers, taalhandelingen",
  },
  {
    code: "1B.UD.UD02.11",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.11",
    soort: "uitbreiding",
    omschrijving: "De leerlingen geven overeenkomsten en verschillen aan in taaluitingen, tussen standaardtaal, regionale, sociale en situationele taalvariëteiten en tussen talen.",
    uitleg: "",
  },
  {
    code: "1B.UD.UD02.12",
    stroom: "1B",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.12",
    soort: "uitbreiding",
    omschrijving: "De leerlingen verwoorden de eigen beleving en interpretatie van literaire teksten.",
    uitleg: "Onderliggende (kennis)elementen, tekstkenmerken, voetnoot, memorie.",
  },
  {
    code: "1B.ST.03.01",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.01",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het onderwerp en de hoofdgedachte bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\n- Ten minste teksten in het Frans\n\nTekstkenmerken:\n* Tekstkenmerken voor receptie.",
  },
  {
    code: "1B.ST.03.02",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.02",
    soort: "standaard",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "",
  },
  {
    code: "1B.ST.03.03",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.03",
    soort: "standaard",
    omschrijving: "De leerlingen spreken en schrijven doelgericht met behulp van aangereikte zinnen, sleutelwoorden of een voorbeeld.",
    uitleg: "",
  },
  {
    code: "1B.ST.03.04",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.04",
    soort: "standaard",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge interactie.",
    uitleg: "",
  },
  {
    code: "1B.ST.03.05",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.05",
    soort: "standaard",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "",
  },
  {
    code: "1B.ST.03.06",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.06",
    soort: "standaard",
    omschrijving: "De leerlingen zetten eerder en nieuwverworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "",
  },
  {
    code: "1B.ST.03.07",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.07",
    soort: "standaard",
    omschrijving: "De leerlingen identificeren bij het lezen en beluisteren van teksten kenmerkende aspecten van maatschappijen en culturen waarin de doeltaal wordt gesproken.",
    uitleg: "",
  },
  {
    code: "1B.ST.03.08",
    stroom: "1B",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.08",
    soort: "standaard",
    omschrijving: "De leerlingen drukken de eigen beleving en interpretatie van literaire teksten uit.",
    uitleg: "",
  },
  {
    code: "1B.ST.04.01",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.01",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken basisfunctionaliteiten van toepassingen om digitaal te communiceren.",
    uitleg: "Memorie:\nDigitaal communiceren zoals in interactie gaan met mensen, systemen, diensten; synchroon (online meeting, chat), asynchroon (berichtensysteem, sociale media, sms, e-mail, blog, fora, websites).\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals versturen en ontvangen van berichten. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1B.ST.04.02",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.02",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken basisfunctionaliteiten van toepassingen om digitale inhouden te creëren.",
    uitleg: "Memorie:\nDigitale inhouden creëren zoals in tekst-, cijfer-, geluid-, grafische, audiovisuele bestanden, programmacode.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het openen van een document. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1B.ST.04.03",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.03",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken basisfunctionaliteiten van toepassingen om digitale inhouden te beheren aan de hand van een aangereikte structuur.",
    uitleg: "Memorie:\nDigitale inhouden beheren zoals met behulp van informatiedragers zoals interne en externe opslag; met behulp van ordeningstechnieken zoals mappenstructuur, ordening op thema.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het verplaatsen en kopiëren van bestanden. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1B.ST.04.04",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.04",
    soort: "standaard",
    omschrijving: "De leerlingen passen ethische, sociale en legale regels toe bij het gebruiken van digitale technologie.",
    uitleg: "Memorie:\nEthische, sociale en legale regels zoals principes van privacy zoals het zich beveiligen, beschermen van persoonlijke data; principes van auteursrecht zoals gebruik van eigen/andermans werk, rechtenvrij werk; principes van portretrecht; nettiquette.",
  },
  {
    code: "1B.ST.04.05",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.05",
    soort: "standaard",
    omschrijving: "De leerlingen ontwerpen doelgericht een digitaal en niet-digitaal algoritme volgens de principes van computationeel denken en debuggen het.",
    uitleg: "Onderliggende (kennis)elementen:\nBouwstenen van digitale systemen\nPrincipes van computationeel denken: decompositie, patroonherkenning, abstractie, algoritmen.",
  },
  {
    code: "1B.BG.BG04.01",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "BG04.01",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt doelgericht basisfunctionaliteiten van toepassingen om digitaal te communiceren.",
    uitleg: "Memorie:\nDigitaal communiceren zoals in interactie gaan met mensen, systemen, diensten; synchroon (online meeting, chat), asynchroon (berichtensysteem, sociale media, sms, e-mail, blog, fora, websites).\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals versturen en ontvangen van berichten. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1B.BG.BG04.02",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "BG04.02",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt doelgericht basisfunctionaliteiten van toepassingen om digitale inhouden te creëren.",
    uitleg: "Memorie:\nDigitale inhouden creëren zoals in tekst-, cijfer-, geluid-, grafische, audiovisuele bestanden, programmacode.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het openen van een document. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1B.BG.BG04.03",
    stroom: "1B",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "BG04.03",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt doelgericht basisfunctionaliteiten van toepassingen om digitale inhouden te beheren aan de hand van een aangereikte structuur.",
    uitleg: "Memorie:\nDigitale inhouden beheren zoals met behulp van informatiedragers zoals interne en externe opslag; met behulp van ordeningstechnieken zoals mappenstructuur, ordening op thema.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het verplaatsen en kopiëren van bestanden. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1B.ST.05.01",
    stroom: "1B",
    competentieNr: 5,
    competentie: "5. Sociaal-relationele competenties",
    nummer: "05.01",
    soort: "standaard",
    omschrijving: "De leerlingen gaan respectvol en constructief met anderen in interactie rekening houdend met elkaars grenzen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nRespectvol en constructief met anderen in interactie gaan zoals:\nrekening houden met de opvattingen, de fysieke en mentale grenzen en de emoties van anderen;\ngrenzen herkennen en bewaken;\nreageren tegen grensoverschrijdend gedrag;\nsamenwerken en actief bijdragen aan de uitwerking van een gezamenlijk resultaat;\nomgaan met emoties in verschillende situaties;\nrespect tonen voor relationele en seksuele integriteit;\nsociaal vaardig interageren in informele en formele relaties.",
  },
  {
    code: "1B.BG.BG06.01",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.01",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling voert met functioneel gebruik van ICT eenvoudige berekeningen uit met natuurlijke, positieve decimale getallen met maximaal 2 cijfers na de komma, procenten en verhoudingen in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.BG.BG06.02",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.02",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt maatgetallen en eenheden van grootheden in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.BG.BG06.03",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.03",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt informatie uit eenvoudige tabellen en diagrammen in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.BG.BG06.04",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.04",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling berekent de omtrek van een vierhoek en de oppervlakte van een rechthoek in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.01",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.01",
    soort: "standaard",
    omschrijving: "De leerlingen ordenen gehele getallen, decimale getallen en eenvoudige breuken in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.02",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.02",
    soort: "standaard",
    omschrijving: "De leerlingen voeren met functioneel gebruik van ICT eenvoudige berekeningen uit met gehele getallen, decimale getallen, breuken, procenten en verhoudingen in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.03",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.03",
    soort: "standaard",
    omschrijving: "De leerlingen ronden zinvol af en schatten resultaten van bewerkingen in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.04",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.04",
    soort: "standaard",
    omschrijving: "De leerlingen identificeren meetkundige objecten en relaties in het vlak in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.05",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.05",
    soort: "standaard",
    omschrijving: "De leerlingen stellen vlakke meetkundige objecten grafisch voor in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.06",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.06",
    soort: "standaard",
    omschrijving: "De leerlingen berekenen omtrek en oppervlakte van vlakke figuren in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.07",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.07",
    soort: "standaard",
    omschrijving: "De leerlingen benoemen aan de hand van 2D- en 3D-voorstellingen meetkundige objecten in de ruimte in betekenisvolle contexten: kubus, balk, piramide, bol, kegel, cilinder.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.08",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.08",
    soort: "standaard",
    omschrijving: "De leerlingen berekenen met gegeven formule het volume van ruimtefiguren in betekenisvolle contexten: kubus en balk.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.09",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.09",
    soort: "standaard",
    omschrijving: "De leerlingen hanteren coördinaten in het vlak in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.10",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.10",
    soort: "standaard",
    omschrijving: "De leerlingen voeren een beschrijvend statistisch onderzoek uit met niet-gegroepeerde gegevens van één grootheid.",
    uitleg: "Onderliggende (kennis)elementen:\nTabel met absolute frequenties; Staafdiagram, cirkeldiagram, lijndiagram; Mediaan, rekenkundig gemiddelde, modus, variatiebreedte.\n\nMemorie:\nDe omvang van de gegevensset moet relevant zijn om een beschrijvend statistisch onderzoek te kunnen uitvoeren. De gegevensset kan al dan niet worden aangereikt. Het voeren van een beschrijvend statistisch onderzoek veronderstelt een grafische voorstelling, berekeningen en een interpretatie van de resultaten.",
  },
  {
    code: "1B.ST.06.11",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.11",
    soort: "standaard",
    omschrijving: "De leerlingen lossen vraagstukken en problemen op door te mathematiseren en demathematiseren en door gebruik te maken van heuristieken.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de eerste graad.",
  },
  {
    code: "1B.ST.06.12",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.12",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren het belang van fotosynthese.",
    uitleg: "Onderliggende (kennis)elementen:\nEnergieomzetting, stofomzetting en stofuitwisseling; Transport in een organisme.\n\nMemorie:\nEr wordt nadruk gelegd op systeemdenken, vandaar de opname van transport in een organisme. Verder zijn omzettingen en uitwisseling opgenomen die minimaal noodzakelijk zijn om het doel te bereiken.",
  },
  {
    code: "1B.ST.06.13",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.13",
    soort: "standaard",
    omschrijving: "De leerlingen leggen de samenhang tussen de verschillende organisatieniveaus in een plantaardig en dierlijk organisme uit met de cel als basiseenheid.",
    uitleg: "Memorie:\nOrganisatieniveaus zoals cellen, weefsels, organen, stelsels.\nCelonderdelen zoals celwand, celmembraan, celkern, bladgroenkorrels, mitochondriën, cytoplasma.",
  },
  {
    code: "1B.ST.06.14",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.14",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren voortplantingswijzen van planten en dieren.",
    uitleg: "Onderliggende (kennis)elementen:\nAseksuele en seksuele voortplanting.",
  },
  {
    code: "1B.ST.06.15",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.15",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verloop van de voortplanting bij de mens uit.",
    uitleg: "Onderliggende (kennis)elementen:\nFunctie van organen van het voortplantingsstelsel.",
  },
  {
    code: "1B.ST.06.16",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.16",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren voor een biotoop de onderlinge relaties tussen verschillende organismen en de rol van biotische en abiotische factoren.",
    uitleg: "Onderliggende (kennis)elementen:\nBiodiversiteit; Verband tussen kenmerken van een organisme, zijn omgeving en zijn overleven.",
  },
  {
    code: "1B.ST.06.17",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.17",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verschil uit tussen een chemisch en een fysisch verschijnsel aan de hand van het deeltjesmodel.",
    uitleg: "Onderliggende (kennis)elementen:\nFysische verschijnselen: Aggregatietoestanden, faseovergangen; Thermische uitzetting, krimp.\nChemische verschijnselen: Verbindingen en atomen in functie van chemische omzetting.",
  },
  {
    code: "1B.ST.06.18",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.18",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren het verschil tussen zuivere stoffen en mengsels aan de hand van het deeltjesmodel in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1B.ST.06.19",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.19",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven energieomzettingen in systemen.",
    uitleg: "Onderliggende (kennis)elementen:\nEnergievormen: thermische energie, elektrische energie, potentiële energie, kinetische energie, stralingsenergie, chemische energie.",
  },
  {
    code: "1B.ST.06.20",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.20",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren krachten en hun uitwerking in betekenisvolle contexten.",
    uitleg: "Onderliggende (kennis)elementen:\nConstante snelheid als verhouding.",
  },
  {
    code: "1B.ST.06.21",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.21",
    soort: "standaard",
    omschrijving: "De leerlingen passen methodes toe om eigenschappen van materialen en grondstoffen vast te stellen in functie van een probleemstelling.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nMaterialen zoals metalen en niet-metalen, ferro- en non-ferrometalen, natuurlijke en kunstmatige materialen.\nEigenschappen van materialen zoals:\n- elektrisch zoals geleiding;\n- fysisch zoals dichtheid;\n- magnetisch zoals aantrekking en afstoting van ferromagnetische materialen;\n- mechanisch zoals elasticiteit, hardheid;\n- technologisch zoals vervormbaarheid.",
  },
  {
    code: "1B.ST.06.22",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.22",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren principes van de bouw en werking van technische systemen, hun deelsystemen, onderdelen en hun onderlinge samenhang in een energiesysteem en een informatieverwerkend systeem en in minstens 1 van de volgende systemen: een constructiesysteem, een transportsysteem en een biotechnische systeem.",
    uitleg: "Memorie:\nEnergie: principes zoals\n- energieomzettingen in technische systemen;\n- nuttige en niet-nuttige energie in systemen;\n- elektrische stroomkring: componenten van de stroomkring, schematische voorstelling.\nInformatieverwerking: principes zoals\n- functie van sensoren en actuatoren;\n- logica in een besturing.\nIn geval van keuze voor een constructiesysteem, principes zoals\n- stabiliteit, sterkte en stijfheid;\n- verbindingen;\n- krachten op een constructie.\nIn geval van keuze voor een transportsysteem, principes zoals\n- overbrengingen;\n- transportmogelijkheden.\nIn geval van keuze voor een biotechnisch systeem, principes zoals\n- biochemische processen in de voedingsindustrie;\n- conservering van voedingsmiddelen, doel van verschillende verpakkingen.",
  },
  {
    code: "1B.ST.06.23",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.23",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen een technisch proces om een technisch systeem te realiseren vanuit behoefte(n) en criteria.",
    uitleg: "Onderliggende (kennis)elementen:\nOntwerp- en productieproces.\n\nVoetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nFasen van een technisch proces zoals probleemstelling/behoefte onderzoeken, ontwerpen, maken, in gebruik nemen, evalueren.",
  },
  {
    code: "1B.ST.06.24",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.24",
    soort: "standaard",
    omschrijving: "De leerlingen werken op een veilige en duurzame manier met materialen, stoffen, organismen en technische systemen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1B.ST.06.25",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.25",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken met de nodige nauwkeurigheid meetinstrumenten en hulpmiddelen.",
    uitleg: "Memorie:\nMeetinstrumenten en hulpmiddelen zoals chronometer, determineertabel, handgereedschap, lichtmicroscoop, loep, meetlat, proefbuis, thermometer, weegschaal.",
  },
  {
    code: "1B.ST.06.26",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.26",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken gepaste grootheden en eenheden in een correcte weergave.",
    uitleg: "Onderliggende (kennis)elementen:\nGrootteorde en maatbesef van de grootheden tijd, lengte, oppervlakte, inhoud/volume, massa, spanning, kracht, energie.\nHerleiding van courante eenheden.",
  },
  {
    code: "1B.ST.06.27",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.27",
    soort: "standaard",
    omschrijving: "De leerlingen passen een wetenschappelijke methode toe om vragen te beantwoorden.",
    uitleg: "Memorie:\nStappen in een wetenschappelijke methode: onderzoeksvraag opstellen, hypothese formuleren, methode/plan uitvoeren, waarnemingen/data analyseren, concluderen.",
    opmerking: "handmatig toegevoegd (GVH). Ontbreekt in het leerplan.",
  },
  {
    code: "1B.ST.06.28",
    stroom: "1B",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.28",
    soort: "standaard",
    omschrijving: "De leerlingen ontwerpen een oplossing voor een probleem door wetenschappen, technologie of wiskunde geïntegreerd aan te wenden.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de eerste graad en de context waarin dit minimumdoel aan bod komt.\n\nMemorie:\nSTEM betekent per definitie dat je geïntegreerd denkt. De mate van integratie is afhankelijk van het probleem. Ook niet-STEM-disciplines kunnen aan bod komen.",
  },
  {
    code: "1B.ST.07.01",
    stroom: "1B",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.01",
    soort: "standaard",
    omschrijving: "De leerlingen lichten de betekenis, de principes en de werking van de democratische rechtsstaat en hun verantwoordelijkheid daarin toe.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDe democratische rechtsstaat op een bestuursniveau met impact op de leefwereld van leerlingen, zoals gemeente, provincie, gemeenschap, gewest, federaal, Europese Unie. Verantwoordelijkheid van leerlingen zoals een mogelijk individueel of gezamenlijk engagement.",
  },
  {
    code: "1B.ST.07.02",
    stroom: "1B",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.02",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over het relationele, gelaagde en dynamische karakter van identiteit.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nHet relationele en dynamische karakter van identiteit zoals gerelateerd aan verbondenheid, solidariteit, discriminatie, wij-zij-denken. De accenten kunnen afhankelijk zijn van de leefwereld van de leerlingen, de actualiteit ... Het gelaagde karakter van identiteit zoals gerelateerd aan:\n- biologische aspecten, persoonlijkheidstrekken, familiale achtergrond;\n- regionale, nationale of supranationale groepen, zoals de Vlaamse, de Belgische, de Europese en de niet-Europese;\n- subculturen, gender-gerelateerde groepen, socio-economische groepen, levensbeschouwelijke groepen.",
  },
  {
    code: "1B.ST.07.03",
    stroom: "1B",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten toe hoe verschillende vormen van diversiteit verrijkend en uitdagend zijn voor het samenleven.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDiversiteit zoals gerelateerd aan fysieke, mentale, cognitieve, socio-economische, culturele, levensbeschouwelijke aspecten. Verrijkend zoals culturele verrijking, uitwisseling van ideeën, economische uitwisseling. Uitdagend zoals meningsverschillen, verschillende belangen, verschillende referentiekaders van waaruit men denkt en handelt, risico van groepsdenken en uitsluiting.",
  },
  {
    code: "1B.ST.07.04",
    stroom: "1B",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.04",
    soort: "standaard",
    omschrijving: "De leerlingen gaan geïnformeerd, beargumenteerd en constructief in dialoog over maatschappelijke thema’s.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nGeïnformeerd, beargumenteerd en constructief in dialoog gaan zoals door het toepassen van strategieën als actief luisteren, creatief denken, zich inleven, respectvol en duidelijk uitkomen voor zijn mening, een eigen mening onderbouwen.",
  },
  {
    code: "1B.ST.08.01",
    stroom: "1B",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.01",
    soort: "standaard",
    omschrijving: "De leerlingen bouwen een historisch referentiekader op met structuurbegrippen, scharnierpunten en kenmerken eigen aan de prehistorie, het oude nabije oosten en de klassieke oudheid.",
    uitleg: "Onderliggende (kennis)elementen:\nDe zeven periodes van het westerse historisch referentiekader: de prehistorie, het oude nabije oosten, de klassieke oudheid, de middeleeuwen, de vroegmoderne tijd, de moderne tijd en de hedendaagse tijd.\nStructuurbegrippen met betrekking tot de drie dimensies van het historisch referentiekader: tijd, ruimte en de maatschappelijke domeinen (politiek, sociaal, cultureel en economisch).\n\nMemorie:\nStructuurbegrippen met betrekking tot:\n- tijd: zoals millennium, eeuw, jaar, tijdrekening, chronologie, periode, continuïteit, verandering, evolutie, revolutie, duur;\n- ruimte: zoals lokaal, regionaal, stedelijk en ruraal, continentaal en maritiem.\nKenmerken of samenlevingen uit elk van de drie bestudeerde periodes, voor elk van de maatschappelijke domeinen:\n- politiek: zoals stadstaat, rijk, dynastie, republiek, autocratie, aristocratie, democratie, imperialisme, kolonisatie, ambtenaren;\n- sociaal: zoals nomadische samenleving, sedentaire samenleving, standenmaatschappij, patriarchale samenleving, migratie, ongelijkheid, slavernij, burgerrechten, oorlog en vrede;\n- cultureel: zoals mythologie, wetenschappen, filosofie, natuurreligie, polytheïsme, monotheïsme, staatsgodsdienst, kunstuiting, schriftsoorten, cultuur, mondelinge traditie, multiculturele samenleving;\n- economisch: zoals jager-verzamelaar, agrarische (r)evolutie (of: neolithische revolutie), landbouw, ambacht, handel, ruileconomie, geldeconomie.",
  },
  {
    code: "1B.ST.08.02",
    stroom: "1B",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.02",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken historische bronnen met betrekking tot de bestudeerde periodes in functie van een historische vraag.",
    uitleg: "",
  },
  {
    code: "1B.ST.08.03",
    stroom: "1B",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.03",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken kenmerken van bestudeerde samenlevingen in eenzelfde periode en tussen periodes.",
    uitleg: "",
  },
  {
    code: "1B.ST.08.04",
    stroom: "1B",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.04",
    soort: "standaard",
    omschrijving: "De leerlingen lichten the invloed toe van de eigen standplaatsgebondenheid op historische beeldvorming met betrekking tot de bestudeerde periodes.",
    uitleg: "",
  },
  {
    code: "1B.ST.09.01",
    stroom: "1B",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.01",
    soort: "standaard",
    omschrijving: "De leerlingen situeren absoluut en relatief personen, plaatsen en patronen op relevante ruimtelijke schaalniveaus.",
    uitleg: "Voetnoot:\nRekening houdend met personen, plaatsen en patronen die in de eerste graad aan bod komen.",
  },
  {
    code: "1B.ST.09.02",
    stroom: "1B",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.02",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven kenmerken van fysischgeografische en sociaalgeografische landschapsvormende lagen.",
    uitleg: "Memorie:\nLandschapsvormende lagen:\n- fysischgeografisch zoals reliëf, klimaat, vegetatie en bodem;\n- sociaalgeografisch zoals types van bebouwing, verspreiding van bebouwing, infrastructuur, landbouw, industrie.",
  },
  {
    code: "1B.ST.09.03",
    stroom: "1B",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.03",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren relaties tussen landschapsvormende lagen of plaatsen om verschillen tussen landschappen te verklaren.",
    uitleg: "Memorie:\nRelaties zoals tussen bodemgebruik en bodem, landgebruik en helling, bodem en ondergrond, klimaat en vegetatie of woonplaats en werkplaats, wegeninfrastructuur door een natuurgebied, reliëfvormen en bevolkingsspreiding.",
  },
  {
    code: "1B.ST.09.04",
    stroom: "1B",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.04",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren ruimtelijke patronen op verschillende schaalniveaus.",
    uitleg: "Memorie:\nRuimtelijke patronen zoals reliëfeenheden, klimaatzones, vegetatiezones, bevolkingsspreiding.",
  },
  {
    code: "1B.ST.09.05",
    stroom: "1B",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.05",
    soort: "standaard",
    omschrijving: "De leerlingen zetten terreintechnieken en geografische hulpbronnen met inbegrip van GIS-viewers functioneel in.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nTerreintechnieken zoals lokalisatie, oriëntatie, observatie.\nGeografische hulpbronnen zoals digitale en niet-digitale kaarten, atlas, beeldmateriaal.",
  },
  {
    code: "1B.ST.11.01",
    stroom: "1B",
    competentieNr: 11,
    competentie: "11. Economische en financiële competenties",
    nummer: "11.01",
    soort: "standaard",
    omschrijving: "De leerlingen beargumenteren hun keuzegedrag bij aankopen rekening houdend met hun behoeften, met een persoonlijk budget en een beschikbaar gezinsbudget en met factoren die hun koopgedrag beïnvloeden.",
    uitleg: "Onderliggende (kennis)elementen:\nReële en gecreëerde behoeften; Sparen en lenen; Belang van persoonlijk administratiebeheer.\n\nMemorie:\nFactoren zoals bijkomende kosten, status, reclame, verkoopspraktijken, peers, media, sociale media, milieu- en sociale aspecten.",
  },
  {
    code: "1B.ST.11.02",
    stroom: "1B",
    competentieNr: 11,
    competentie: "11. Economische en financiële competenties",
    nummer: "11.02",
    soort: "standaard",
    omschrijving: "De leerlingen beoordelen courante betaalmiddelen en courante verkoopkanalen op het vlak van veiligheid, risico’s en kosten.",
    uitleg: "Onderliggende (kennis)elementen:\nFraude.\n\nMemorie:\nHet beoordelen van courante betaalmiddelen en verkoopkanalen veronderstelt inzicht in modaliteiten en gebruik ervan.",
  },
  {
    code: "1B.ST.11.03",
    stroom: "1B",
    competentieNr: 11,
    competentie: "11. Economische en financiële competenties",
    nummer: "11.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten de rol van gezinnen, bedrijven en overheid in de economie toe.",
    uitleg: "Onderliggende (kennis)elementen:\nInkomsten en uitgaven; Consumeren en produceren; Maatschappelijk verantwoord ondernemen; Profit en non-profit.",
  },
  {
    code: "1B.ST.13.01",
    stroom: "1B",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.01",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over het eigen leerproces en sturen het doelgericht bij.",
    uitleg: "Memorie:\nHet reflecteren over het eigen leerproces bevat een cognitieve, een metacognitieve en een motivationele component.\nHet bijsturen van het eigen leerproces kan gebeuren op basis van de eigen reflectie en van de feedback van anderen.",
  },
  {
    code: "1B.ST.13.02",
    stroom: "1B",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.02",
    soort: "standaard",
    omschrijving: "De leerlingen zetten (meta)cognitieve leer- en regulatiestrategieën in om zich leerinhouden eigen te maken.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nCognitieve leerstrategieën en bijhorende activiteiten zoals structureren, zich vragen stellen bij de leerinhoud, memoriseren, herhalen, selecteren, relateren, toepassen, inoefenen.\nMetacognitieve regulatiestrategieën en bijhorende activiteiten zoals plannen, monitoren, evalueren, bijsturen.",
  },
  {
    code: "1B.ST.13.03",
    stroom: "1B",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.03",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken school- en vaktaal.",
    uitleg: "Voetnoot:\nRelevante vakterminologie. Rekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nVaktaal zoals domeinspecifieke terminologie, symbolen.",
  },
  {
    code: "1B.ST.13.04",
    stroom: "1B",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.04",
    soort: "standaard",
    omschrijving: "De leerlingen zoeken doelgericht informatie in diverse bronnen en verwerken die op een kritische en systematische manier.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDigitale en niet-digitale bronnen zoals personen, tijdschriften, encyclopedieën, boeken, audiovisueel materiaal, websites.\nDe bronnen kunnen worden aangereikt of zelf worden opgezocht en worden beoordeeld op bruikbaarheid en betrouwbaarheid.\nHet kritisch en systematisch verwerken van informatie veronderstelt het beoordelen ervan op bruikbaarheid, betrouwbaarheid en correctheid.\nVerwerken van informatie in functie van het vooropgestelde doel, zoals het beantwoorden van een (onderzoeks)vraag.",
  },
  {
    code: "1B.ST.15.01",
    stroom: "1B",
    competentieNr: 15,
    competentie: "15. Ontwikkeling van initiatief, ambitie, ondernemingszin en loopbaancompetenties",
    nummer: "15.01",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen bewust hun studie- of beroepskeuzeproces.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDoorlopen van een studie- of beroepskeuzeproces zoals met behulp van de keuzetaken oriënteren, zelfconceptverheldering, exploreren in de breedte, exploreren in de diepte, studiekeuzenabijheid, binding.",
  },
  {
    code: "1B.ST.15.02",
    stroom: "1B",
    competentieNr: 15,
    competentie: "15. Ontwikkeling van initiatief, ambitie, ondernemingszin en loopbaancompetenties",
    nummer: "15.02",
    soort: "standaard",
    omschrijving: "De leerlingen genereren creatieve ideeën om een probleem op te lossen en bespreken de uitvoerbaarheid ervan aan de hand van criteria.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nIdeeën genereren zoals door middel van ideegeneratietechnieken (bv. door middel van een brainstorm, mindmap) en ideeselectietechnieken (bv. van divergent naar convergent denken).\nAangereikte of zelf bepaalde criteria zoals meerwaarde, tijd, middelen, technische haalbaarheid, risico’s, ethische principes, duurzaamheidsprincipes.",
  },
  {
    code: "1B.ST.16.01",
    stroom: "1B",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.01",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven kunst- en cultuuruitingen vanuit eigen waarneming.",
    uitleg: "Memorie:\nKunstuitingen zoals dans, theater, film, game, graffiti, kledij, landschap, lied. Cultuuruitingen zoals sociale gewoonten, voorstellingen, rituelen, tradities, uitdrukkingen. Eigen waarneming zoals ervaren en beleven, memoriseren en herkennen en zintuiglijk waarnemen.",
  },
  {
    code: "1B.ST.16.02",
    stroom: "1B",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.02",
    soort: "standaard",
    omschrijving: "De leerlingen brengen kunst- en cultuuruitingen in verband met de context waarin ze voorkomen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nContext zoals tijd, ruimte, maatschappelijke context.",
  },
  {
    code: "1B.ST.16.03",
    stroom: "1B",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.03",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over eigen beleving bij uiteenlopende kunst- en cultuuruitingen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1B.ST.16.04",
    stroom: "1B",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.04",
    soort: "standaard",
    omschrijving: "De leerlingen lichten toe hoe een kunstwerk vanuit vorm en inhoud betekenis geeft.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nInhoud:\nonderwerp bijvoorbeeld geboorte, dood, liefde, geschiedenis, het leven, het alledaagse, rituelen;\nbedoeling bijvoorbeeld decoreren, entertainen, praktisch gebruik, informeren, confirmeren, revolteren.\nVorm zoals bouwstenen, technieken, materialen afhankelijk van het gekozen kunstwerk en de gekozen expressievorm zoals beeld, muziek, drama, dans of audiovisuele media, apart of gecombineerd. In het geval van:\nBeeld\n- Bouwstenen zoals compositie, kleur, licht, lijn, ruimte, textuur, vorm.\n- Technieken zoals boetseren, fotograferen, maquettes maken, met textiel werken, schilderen.\n- Materialen zoals klei, licht, papier, recuperatiematerialen, steen, verf.\nMuziek\n- Bouwstenen zoals dynamiek, klankkleur, melodie, ritme, samenklank, structuur, tempo, vorm.\n- Technieken zoals body percussion, improvisatie, samenzang.\n- Materialen zoals instrumenten, lichaam, stem, voorwerpen.\nDrama\n- Bouwstenen zoals rol, ruimte, structuur, samenspel, tijd.\n- Technieken zoals clownerie, figurentheater, improvisatie, mime, teksttheater.\n- Materialen zoals decor, geluid, kostuums, lichaam, taal.\nDans\n- Bouwstenen zoals kracht, ruimte, relatie, tijd.\n- Technieken zoals bewegingsreeks, choreografie, dansexpressie, dansimprovisatie.\n- Materialen zoals decor, geluid, lichaam, voorwerpen.\nAudiovisuele media\n- Bouwstenen zoals camerabeweging, geluid, kader, licht, montage.\n- Technieken zoals montage, opname, sonorisatie.\n- Materialen zoals microfoon, montageunit, smartphone.",
  },
  {
    code: "1B.ST.16.05",
    stroom: "1B",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.05",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen een artistiek-creatief proces vanuit verbeelding.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nBij het doorlopen van een artistiek-creatief proces kan je denken aan:\n- het selecteren van ideeën zoals bij eigen gedachten en gevoelens stilstaan, artistieke werken bestuderen, indrukken of objecten verzamelen;\n- het koppelen van de eigen bedoeling aan vormgeving via methodes zoals trial and error, try-out;\n- het gebruiken van kunsteigen technieken;\n- het voorstellen of presenteren.",
  },
  {
    code: "1B.FR.17.01",
    stroom: "1B",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F1",
    soort: "freinet",
    omschrijving: "De leerlingen passen de principes van de Freinetpedagogie toe.",
    uitleg: "Toegevoegde freinetspecifieke minimumdoelen in de 1ste graad.",
  },
  {
    code: "1B.FR.17.02",
    stroom: "1B",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F2",
    soort: "freinet",
    omschrijving: "De leerlingen passen de principes van democratische besluitvorming toe op klasniveau (klasraad) en op schoolniveau (leerlingenraad/schoolraad).",
    uitleg: "Toegevoegde freinetspecifieke minimumdoelen in de 1ste graad.",
  },
  {
    code: "1B.FR.17.03",
    stroom: "1B",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F3",
    soort: "freinet",
    omschrijving: "De leerlingen passen de basisbeginselen van coöperatief samenwerken toe op klas- en schoolniveau.",
    uitleg: "Toegevoegde freinetspecifieke minimumdoelen in de 1ste graad.",
  },
  {
    code: "1B.FR.17.04",
    stroom: "1B",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F4",
    soort: "freinet",
    omschrijving: "De leerlingen passen de basisbeginselen van conflicthantering toe op klas- en schoolniveau.",
    uitleg: "Toegevoegde freinetspecifieke minimumdoelen in de 1ste graad.",
  },
  {
    code: "1B.FR.17.05",
    stroom: "1B",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F5",
    soort: "freinet",
    omschrijving: "De leerlingen evalueren zelf uitgevoerde burgerschapsprojecten kritisch met behulp van richtvragen.",
    uitleg: "Toegevoegde freinetspecifieke minimumdoelen in de 1ste graad.",
  },
  {
    code: "1B.FR.17.06",
    stroom: "1B",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F6",
    soort: "freinet",
    omschrijving: "De leerlingen onderzoeken verschillende kennis- en vaardigheidsdomeinen van de samenleving en de waarde van elk van deze domeinen met het oog op de ontdekking van hun eigen interessegebieden.",
    uitleg: "Toegevoegde freinetspecifieke minimumdoelen in de 1ste graad.",
  },
];
