// AUTO-GEGENEREERD uit docs/reference/doelen1GRA_volledig.xlsx (blad "1A", v2.0, 2026-08-29).
// Minimumdoelen en eindtermen — eerste graad A. Niet handmatig herschikken; regenereer bij een nieuwe export.
import type { Minimumdoel } from "./minimumdoelen";

export const minimumdoelen1A: Minimumdoel[] = [
  {
    code: "1A.ST.01.01",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.01",
    soort: "standaard",
    omschrijving: "De leerlingen passen technieken voor eerste hulp bij ongevallen toe in een gesimuleerde leeromgeving.",
    uitleg: "Memorie:\nTechnieken voor eerste hulp bij ongevallen zoals verstuiking, wonde, bloedneus, brandwonde.",
  },
  {
    code: "1A.ST.01.02",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.02",
    soort: "standaard",
    omschrijving: "De leerlingen ontwikkelen gezondheidsvaardigheden in functie van hun fysiek en mentaal welzijn binnen verschillende thema’s.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nGezondheidsvaardigheden met betrekking tot:\nvoeding zoals ultrabewerkt voedsel, gezonde snacks, duurzame voeding, evenwichtige voeding;\nhygiëne zoals basisregels voor lichaams-, mond- en handhygiëne;\nbeweging zoals beweegnormen, sedentair gedrag;\nseksuele gezondheid en seksuele ontwikkeling in de puberteit;\nverslavingen: middelen en handelingen.\n\nHet ontwikkelen van een gezonde levensstijl is een levenslange opdracht. Via deze eindterm krijgen leerlingen handvatten (gezondheidsvaardigheden) aangereikt om later die attitude te bereiken. Bij het formuleren van de eindterm is uitgegaan van een holistische visie op gezondheid. Daarom is ook uitdrukkelijk opgenomen dat de ontwikkeling van gezondheidsvaardigheden in functie staat van het fysieke en mentale welzijn.",
  },
  {
    code: "1A.ST.01.03",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.03",
    soort: "standaard",
    omschrijving: "De leerlingen voeren conform de beweegrichtlijnen in verschillende bewegingsomgevingen activiteiten uit in verschillende individuele, interactieve en ritmisch expressieve bewegingsdomeinen.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals bewegingsomgevingen en bewegingsdomeinen) waarin het minimumdoel aan bod komt.\n\nMemorie:\nHet is aangewezen om dit doel in verschillende spelvormen en sporten te realiseren met het oog op het aanwakkeren van de interesse voor en het plezier in beweging en sport in functie van het individueel levenslang bewegen en sporten.\nBewegingsomgevingen zoals sportzaal, sportveld, speelplein, aquatisch milieu.",
  },
  {
    code: "1A.ST.01.04",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.04",
    soort: "standaard",
    omschrijving: "De leerlingen ontwikkelen lenigheid, uithouding, snelheid, coördinatie en evenwicht, rekening houdend met de evolutie van hun fysieke capaciteiten.",
    uitleg: "",
  },
  {
    code: "1A.ST.01.05",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.05",
    soort: "standaard",
    omschrijving: "De leerlingen voeren motorische basisvaardigheden uit, rekening houdend met ergonomische principes en de evolutie van hun fysieke capaciteiten.",
    uitleg: "Memorie:\nMotorische basisvaardigheden zoals balanceren, wentelen, springen, rollen, klauteren, klimmen, ritmisch bewegen, lopen, vangen, werpen, terugslaan, vallen, mee- en tegengaan in beweging.\n\nErgonomische principes zoals van toepassing bij heffen, tillen, staan, verplaatsen, rughygiëne.",
  },
  {
    code: "1A.ST.01.06",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.06",
    soort: "standaard",
    omschrijving: "De leerlingen passen tactieken en principes toe met respect voor de afgesproken regels en rollen in sport en spel.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals de bewegingsdomeinen) waarin het minimumdoel aan bod komt.\n\nMemorie:\nRollen in sport en spel zoals de beoefenaar, de coach, de scheidsrechter, de winnaar, de verliezer.",
  },
  {
    code: "1A.ST.01.07",
    competentieNr: 1,
    competentie: "1. Competenties op het vlak van lichamelijk, geestelijk en emotioneel bewustzijn en op vlak van lichamelijke, geestelijke en emotionele gezondheid",
    nummer: "01.07",
    soort: "standaard",
    omschrijving: "De leerlingen hanteren in verschillende rollen in sport en spel principes van verantwoord en veilig gedrag.",
    uitleg: "Voetnoot:\nRekening houdend met de context (zoals de bewegingsdomeinen) waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.ST.02.01",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.01",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie:\n- Herkenbare structuur, expliciet aangegeven bij teksten met minder samenhang\n- Grote samenhang\n- Voornamelijk Standaardnederlands\n- Frequente en minder frequente woorden\n- Eenvoudig figuurlijk taalgebruik\n- Concrete inhoud\n- Lage tot gemiddelde informatiedichtheid\n- Tekstsoorten: informatief, persuasief, opiniërend, prescriptief en narratief\n* Bijkomend voor schriftelijke receptie: Duidelijke lay-out\n* Bijkomend voor mondelinge receptie: Normaal spreektempo\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen in functie van het begrijpen van teksten.",
  },
  {
    code: "1A.ST.02.02",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.02",
    soort: "standaard",
    omschrijving: "De leerlingen beoordelen doelgericht informatie op betrouwbaarheid, correctheid en bruikbaarheid bij het lezen en luisteren.",
    uitleg: "",
  },
  {
    code: "1A.ST.02.03",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.03",
    soort: "standaard",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken:\n* Tekstkenmerken voor receptie\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om relevante informatie te selecteren.",
  },
  {
    code: "1A.ST.02.04",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.04",
    soort: "standaard",
    omschrijving: "De leerlingen nemen notities bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken:\n* Tekstkenmerken voor receptie\n\nMinimumvereisten voor de geproduceerde tekst:\nInhoud en vorm afgestemd op het doel en op de doelgroep\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om notities te nemen bij het lezen en beluisteren van teksten.",
  },
  {
    code: "1A.ST.02.05",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.05",
    soort: "standaard",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Minimumvereisten voor productie:\n- Eenvoudige, herkenbare tekststructuur\n- Redelijk herkenbare samenhang\n- Gepast taalgebruik\n- Gepast register\n- Concrete inhoud\n- Grote variatie aan tekstsoorten\n* Bijkomend voor schriftelijke productie: Gepaste lay-out; Verzorgd taalgebruik met aandacht voor Standaardnederlands, spelling, interpunctie, woordkeuze, zinsbouw, helderheid, adequaatheid, correctheid en vlotheid\n* Bijkomend voor mondelinge productie: Verzorgd taalgebruik met aandacht voor Standaardnederlands, uitspraak, intonatie, woordkeuze, zinsbouw, helderheid, adequaatheid, correctheid en vlotheid; Gepaste lichaamstaal\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen\n\nMemorie:\nHet betreft ondersteunende middelen zoals een kaartje met steekwoorden, structuur, schrijfkader, spreekkader, voorleessoftware, presentatiesoftware enz. maar ook talige hulpmiddelen.",
  },
  {
    code: "1A.ST.02.06",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.06",
    soort: "standaard",
    omschrijving: "De leerlingen drukken zich creatief uit met taal.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nZich creatief uitdrukken zoals het gebruiken van eenvoudige technieken, bijvoorbeeld lay-out, rijm en ritme.",
  },
  {
    code: "1A.ST.02.07",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.07",
    soort: "standaard",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken:\n* Tekstkenmerken voor receptie\n\nMinimumvereisten:\n* Minimumvereisten voor productie\n\nMemorie:\nMondelinge interactie veronderstelt minimaal dat leerlingen voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context. In some gevallen kan het evenwel ook onvoorbereid.",
  },
  {
    code: "1A.ST.02.08",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.08",
    soort: "standaard",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning of informatieverwerking en communicatieve handelingen.",
    uitleg: "Voetnoot:\nDit minimumdoel wordt doelgericht ingezet in functie van alle andere minimumdoelen binnen sleutelcompetentie 2. Rekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nStrategieën hebben betrekking op lees-, luister-, spreek- en schrijfvaardigheden. Strategieën zoals met lees-, luister- spreek- of schrijfdoel rekening houden; voorkennis activeren; inhoud voorspellen; vragen stellen; tussentijds samenvatten, de vermoedelijke betekenis van onbekende woorden en zinnen afleiden uit de context, via taalverwantschap of op basis van woorddelen; bepalen of het achterhalen van de betekenis van een onbekend woord belangrijk is; talige hulpmiddelen gebruiken; afkortingen, symbolen en telegramstijl gebruiken; met de ontvanger rekening houden zoals door het gepast inzetten van lichaamstaal; sleutelwoorden en kernzinnen aanduiden; met de doelen van de interactie rekening houden; inspelen op wat de ander zegt of schrijft; de ander laten uitspreken; op een gepaste manier het woord vragen of nemen; elementen van lichaamstaal en intonatie herkennen en zelf doelgericht inzetten; het register afstemmen op de gesprekspartner of correspondent; taalgebruik aan de ontvanger aanpassen; gebruik van compenserende strategieën bij falende communicatie.",
  },
  {
    code: "1A.ST.02.09",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.09",
    soort: "standaard",
    omschrijving: "De leerlingen zetten eerder en nieuwverworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Tekstkenmerken:\n* Tekstkenmerken voor receptie\n\nMinimumvereisten:\n* Minimumvereisten voor productie\n\nVoetnoot:\nRekening houdend met de ontwikkeling van leerlingen en met de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.ST.02.10",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.10",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\nKlanken: lange en korte klinkers\nOnderscheid klank- en schriftbeeld\nSamenstellingen en afleidingen: voorvoegsel, achtervoegsel, meervoud/enkelvoud, verkleinwoord, stam, uitgang\nWerkwoordstijden: onvoltooid tegenwoordige tijd, voltooid tegenwoordige tijd, onvoltooid verleden tijd, voltooid verleden tijd, onvoltooid toekomende tijd; imperatief\nWoordsoorten: zelfstandig naamwoord, bijvoeglijk naamwoord, werkwoord, voornaamwoord (zelfstandig, bijvoeglijk, persoonlijk, bezittelijk, aanwijzend, vragend), lidwoord, voegwoord, voorzetsel, telwoord, bijwoord, tussenwerpsel\nZinsdelen: onderwerp, gezegde (doen- en zijn-relatie), persoonsvorm, lijdend voorwerp, meewerkend voorwerp, bijwoordelijke bepaling\nZinssoorten: ontkennende/bevestigende zinnen, mededelende/vragende/bevelende/uitroepende zinnen, enkelvoudige en samengestelde zinnen\nBetekenisrelaties: synoniem, homoniem, letterlijk/figuurlijk\nBeeldspraak en vergelijking\nSpelling van woorden met vast en veranderlijk woordbeeld\nHoofdletters\nInterpunctietekens: punt, komma, vraagteken, uitrofteken, dubbele punt, spatie, aanhalingsteken\nCongruentie\nDiakritische tekens: trema, koppelteken en apostrof",
    opmerking: "Duplicatiefout in de brontekst: De volledige lijst met Onderliggende (kennis)elementen is twee keer na elkaar letterlijk gekopieerd.",
  },
  {
    code: "1A.ST.02.11",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.11",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in taalgebruik toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen\nTekstopbouwende elementen: titel, benadrukte woorden, lay-out, afbeeldingen\nTekststructuur\nStructuuraanduiders: signaalwoorden en verwijswoorden\nCommunicatiemodel: zender, boodschap, ontvanger, kanaal, context, doel\nEffecten van non-verbale communicatie en of stereotypering\nBeleefdheidsconventies en registers\nTaalhandelingen",
  },
  {
    code: "1A.ST.02.12",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.12",
    soort: "standaard",
    omschrijving: "De leerlingen geven overeenkomsten en verschillen aan in taaluitingen, tussen standaardtaal, regionale, sociale en situationele taalvariëteiten en tussen talen.",
    uitleg: "",
  },
  {
    code: "1A.ST.02.13",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "02.13",
    soort: "standaard",
    omschrijving: "De leerlingen verwoorden de eigen beleving en interpretatie van literaire teksten.",
    uitleg: "Onderliggende (kennis)elementen:\nElementaire literaire en narratieve concepten: verhaallijn, personages, ruimte en tijd\nTekstkenmerken\nVariatie aan genres: fictie en non-fictie\n\nVoetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nEigen beleving en interpretatie zoals waarom sommige aspecten van de tekst aanspreken, waarom men zich identificeert met een bepaald personage, in welke zin men gelijkaardige ervaringen zelf al heeft meegemaakt, waarom de tekst een bepaalde emotionele reactie teweegbrengt, waarom de uitdrukkingsvorm of stijl aanspreekt.",
  },
  {
    code: "1A.BG.02.01",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "BG02.01",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling haalt bij het lezen en luisteren doelgericht het onderwerp en relevante informatie uit niet-fictionele teksten.",
    uitleg: "Tekstkenmerken voor receptie:\nHerkenbare, expliciet aangegeven structuur\nGrote samenhang\nVoornamelijk Standaardnederlands\nVoornamelijk frequente woorden\nHeel eenvoudig figuurlijk taalgebruik\nConcrete en herkenbare inhoud\nLage informatiedichtheid\nVariatie aan tekstsoorten\n* Bijkomend voor schriftelijke receptie:\nDuidelijke lay-out\n* Bijkomend voor mondelinge receptie:\nLaag tot normaal spreektempo\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp te bepalen en informatie te selecteren zoals met lees- of luisterdoel rekening houden; voorkennis activeren; vragen stellen; de vermoedelijke betekenis van onbekende woorden en zinnen afleiden uit de context, via taalverwantschap of op basis van woorddelen; talige hulpmiddelen gebruiken. Tekstsoorten zoals informatief, persuasief, opiniërend, prescriptief, narratief.",
  },
  {
    code: "1A.BG.02.02",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "BG02.02",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling spreekt en schrijft doelgericht in eenvoudige communicatieve situaties.",
    uitleg: "Minimumvereisten voor productie:\nEenvoudige tekststructuur\nRedelijk herkenbare samenhang\nFrequente woorden\nConcrete inhoud\nVariatie aan tekstsoorten\nUitspraak, woordkeuze, zinsbouw, spelling, register en lichaamstaal mogen afwijken zolang ze het overbrengen van de boodschap niet in de weg staan\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen\n\nMemorie:\nHet betreft ondersteunende middelen zoals een kaartje met steekwoorden, structuur, schrijfkader, spreekkader, voorleessoftware, presentatiesoftware enz. maar ook talige hulpmiddelen.",
  },
  {
    code: "1A.BG.02.03",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "BG02.03",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling neemt doelgericht deel aan eenvoudige mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken voor receptie & Minimumvereisten voor productie.\n\nMemorie:\nMondelinge interactie veronderstelt minimaal dat leerlingen voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context.",
  },
  {
    code: "1A.UD.02.01",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.01",
    soort: "uitbreiding",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie:\nHerkenbare structuur\nHerkenbare samenhang\nStandaardnederlands, soms andere taalvariëteiten\nFrequente en minder frequente woorden\nEenvoudig figuurlijk taalgebruik\nConcrete inhoud\nGemiddelde tot vrij hoge informatiedichtheid\nTekstsoorten: informatief, persuasief, opiniërend, prescriptief en narratief\n* Bijkomend voor schriftelijke receptie:\nDuidelijke lay-out\n* Bijkomend voor mondelinge receptie:\nNormaal spreektempo\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen in functie van het begrijpen van teksten.",
  },
  {
    code: "1A.UD.02.02",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.02",
    soort: "uitbreiding",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie.\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om relevante informatie te selecteren.",
  },
  {
    code: "1A.UD.02.03",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.03",
    soort: "uitbreiding",
    omschrijving: "De leerlingen nemen notities bij het lezen en beluisteren van teksten.",
    uitleg: "Tekstkenmerken voor receptie\n\nMinimumvereisten voor de geproduceerde tekst:\nInhoud en vorm afgestemd op het doel en op de doelgroep\n\nMemorie:\nDe leerlingen gebruiken doelgericht strategieën om notities te nemen bij het lezen en beluisteren van teksten.",
  },
  {
    code: "1A.UD.02.04",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.04",
    soort: "uitbreiding",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Minimumvereisten voor productie:\nHerkenbare tekstopbouw\nGepaste en herkenbare tekststructuur\nHerkenbare samenhang\nFrequente en minder frequente woorden\nEenvoudig figuurlijk taalgebruik\nGepast register\nConcrete inhoud\nGrote variatie aan tekstsoorten\n* Bijkomend voor schriftelijke productie:\nTekstopbouwende elementen\nGepaste lay-out\nAfhankelijk van de context Standaardnederlands met aandacht voor spelling, interpunctie, woordkeuze, zinsbouw, helderheid, adequaatheid, correctheid en vlotheid\n* Bijkomend voor mondelinge productie:\nGepaste lichaamstaal\nAfhankelijk van de context Standaardnederlands met aandacht voor uitspraak, intonatie, woordkeuze, zinsbouw, helderheid, adequaatheid, correctheid en vlotheid\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen\n\nMemorie:\nHet betreft ondersteunende middelen zoals een kaartje met steekwoorden, structuur, schrijfkader, spreekkader, voorleessoftware, presentatiesoftware enz. maar ook talige hulpmiddelen.",
  },
  {
    code: "1A.UD.02.05",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.05",
    soort: "uitbreiding",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Tekstkenmerken voor receptie & Minimumvereisten voor productie\n\nMemorie:\nMondelinge interactie veronderstelt minimaal dat leerlingen voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context. In sommige gevallen kan het evenwel ook onvoorbereid.",
  },
  {
    code: "1A.UD.02.06",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.06",
    soort: "uitbreiding",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "Voetnoot:\nDit uitbreidingsdoel wordt doelgericht ingezet in functie van alle andere uitbreidingsdoelen binnen sleutelcompetentie 2. Rekening houdend met de context waarin het uitbreidingsdoel aan bod komt.\n\nMemorie:\nStrategieën hebben betrekking op lees-, luister-, spreek- en schrijfvaardigheden (overeenkomstig MD 02.08).",
  },
  {
    code: "1A.UD.02.07",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.07",
    soort: "uitbreiding",
    omschrijving: "De leerlingen zetten eerder en nieuwverworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Tekstkenmerken voor receptie & Minimumvereisten voor productie\n\nVoetnoot:\nRekening houdend met de ontwikkeling van leerlingen en met de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.UD.02.08",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.08",
    soort: "uitbreiding",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\nZinsdelen: werkwoordelijk en naamwoordelijk gezegde (doen- en zijn-relatie), voorzetselvoorwerp\nZinssoorten: enkelvoudige en samengestelde zinnen (nevengeschikte en ondergeschikte zinnen)",
  },
  {
    code: "1A.UD.02.09",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.09",
    soort: "uitbreiding",
    omschrijving: "De leerlingen analyseren het Standaardnederlands als taalsysteem.",
    uitleg: "Onderliggende (kennis)elementen:\nAangeleerde kenniselementen uit MD 02.10 en UD 02.08",
  },
  {
    code: "1A.UD.02.10",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.10",
    soort: "uitbreiding",
    omschrijving: "De leerlingen passen inzicht in taalgebruik toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.UD.02.11",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.11",
    soort: "uitbreiding",
    omschrijving: "De leerlingen geven overeenkomsten en verschillen aan in taaluitingen, taalvariëteiten en talen.",
    uitleg: "Onderliggende (kennis)elementen:\nNationale taalvariëteiten in het Nederlands",
  },
  {
    code: "1A.UD.02.12",
    competentieNr: 2,
    competentie: "2. Competenties in het Nederlands",
    nummer: "UD02.12",
    soort: "uitbreiding",
    omschrijving: "De leerlingen verwoorden de eigen beleving en interpretatie van literaire teksten.",
    uitleg: "Onderliggende (kennis)elementen:\nElementaire literaire en narratieve concepten: eenvoudige stilistische kenmerken, samenhang vorm – inhoud\nTekstkenmerken: Grote variatie aan genres\n\nVoetnoot:\nRekening houdend met de context waarin het uitbreidingsdoel aan bod komt.\n\nMemorie:\nEigen beleving en interpretatie zoals waarom sommige aspecten van de tekst aanspreken, waarom men zich identificeert met een bepaald personage, in welke zin men gelijkaardige ervaringen zelf al heeft meegemaakt, waarom de tekst een bepaalde emotionele reactie teweegbrengt, waarom de uitdrukkingsvorm of stijl aanspreekt.",
  },
  {
    code: "1A.ST.03.01",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.01",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen het onderwerp, de hoofdgedachte en de hoofdpunten bij het doelgericht lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\nTeksten in het Engels en in het Frans\n\nTekstkenmerken voor receptie:\nEenvoudige, herkenbare tekststructuur; Grote samenhang; Hoofdzakelijk frequente woorden, woordcombinaties en vaste uitdrukkingen uit een beperkte waaier aan relevante thema’s binnen het persoonlijke, publieke en educatieve domein; Concrete inhoud; Lage informatiedichtheid; Eenvoudige zinsbouw; Beperkte lengte; Variatie aan tekstsoorten\n* Bijkomend voor schriftelijke receptie: Duidelijke lay-out\n* Bijkomend voor mondelinge receptie: Geen of weinig achtergrondruis; Normaal spreektempo met pauzes; Ondersteunende maar natuurlijke intonatie; Heldere uitspraak, duidelijke articulatie; Met visuele ondersteuning; Met ondersteuning van non-verbaal gedrag\n\nMemorie:\nHet bepalen van het onderwerp, de hoofdgedachte en de hoofdpunten veronderstelt minimaal dat leerlingen de belangrijkste informatie uit de tekst begrijpen.\nDe leerlingen gebruiken doelgericht strategieën om het onderwerp, de hoofdgedachte en de hoofdpunten te bepalen in functie van het begrijpen van teksten.",
  },
  {
    code: "1A.ST.03.02",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.02",
    soort: "standaard",
    omschrijving: "De leerlingen selecteren relevante informatie bij het lezen en beluisteren van teksten.",
    uitleg: "Onderliggende (kennis)elementen:\nTeksten in het Engels en in het Frans\n\nTekstkenmerken voor receptie.\n\nMemorie:\nHet selecteren van relevante informatie veronderstelt minimaal dat leerlingen de belangrijkste informatie uit de tekst begrijpen.\nDe leerlingen gebruiken doelgericht strategieën om relevante informatie te selecteren.",
  },
  {
    code: "1A.ST.03.03",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.03",
    soort: "standaard",
    omschrijving: "De leerlingen spreken en schrijven doelgericht.",
    uitleg: "Onderliggende (kennis)elementen:\nIn het Engels en in het Frans\n\nMinimumvereisten voor productie:\nEenvoudige, gepaste tekststructuur; Hoogfrequente signaalwoorden: chronologisch verloop, opsomming, oorzaak en tegenstelling; Redelijk herkenbare samenhang; Beheersing van frequente woorden, woordcombinaties en vaste uitdrukkingen die volstaan om te voldoen aan elementaire communicatiebehoeften; Concrete inhoud; Beheersing van bepaalde eenvoudige grammaticale constructies, ondanks het stelselmatig maken van elementaire fouten; begrip van boodschap door ontvanger komt meestal niet in het gedrang; Enkelvoudige zinnen; Gepast register; Beperkte lengte; Variatie aan tekstsoorten\n* Bijkomend voor schriftelijke productie: Duidelijke, gepaste lay-out; Beheersing van de spelling van de meeste frequente woorden uit het aangeleerde lexicale repertoire, ondanks het voorkomen van fouten hiertegen; begrip van boodschap door ontvanger komt meestal niet in het gedrang.\n* Bijkomend voor mondelinge productie: Gepaste lichaamstaal; Uitspraak is over het algemeen voldoende helder om te worden verstaan ondanks een duidelijk accent, maar gesprekspartners zullen regelmatig om herhaling moeten vragen; Vrij gemakkelijk gebruik van frequente woorden, woordcombinaties en vaste uitdrukkingen, ondanks duidelijke aarzelingen en valse start\n\nOndersteunende middelen:\nMet behulp van ondersteunende middelen\n\nMemorie:\nHet betreft ondersteunende middelen die leerlingen zelf voorzien zoals een kaartje met steekwoorden, structuur, schrijfkader, spreekkader, voorleessoftware, presentatiesoftware enz. maar ook talige hulpmiddelen.",
  },
  {
    code: "1A.ST.03.04",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.04",
    soort: "standaard",
    omschrijving: "De leerlingen nemen doelgericht deel aan mondelinge en schriftelijke interactie.",
    uitleg: "Onderliggende (kennis)elementen:\nIn het Engels en in het Frans\n\nTekstkenmerken voor receptie & Minimumvereisten voor productie\n* Bijkomend voor mondelinge en schriftelijke interactie:\nGepaste beleefdheidsconventies bij alledaagse taalhandelingen\n* Bijkomend voor mondelinge interactie:\nDe communicatie is afhankelijk van herhaling, herformulering en herstel; met ondersteuning om het gesprek gaande te houden\n\nMemorie:\nMondelinge interactie veronderstelt dat leerlingen voorbereid aan een gesprek kunnen deelnemen in een vertrouwde context over een vertrouwd onderwerp.",
  },
  {
    code: "1A.ST.03.05",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.05",
    soort: "standaard",
    omschrijving: "De leerlingen zetten doelgericht strategieën in ter ondersteuning van informatieverwerking en communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\nIn het Engels en in het Frans\n\nVoetnoot:\nDit minimumdoel wordt doelgericht ingezet in functie van alle andere minimumdoelen binnen sleutelcompetentie 3. Rekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nStrategieën hebben betrekking op inzicht in taalgebruik toepassen, lees-, luister-, spreek- en schrijfvaardigheden. Strategieën zoals met lees-, luister-, spreek- of schrijfdoel rekening houden; voorkennis activeren; inhoud voorspellen; vragen stellen; de vermoedelijke betekenis van onbekende woorden en zinnen afleiden uit de context of via taalverwantschap; talige hulpmiddelen gebruiken; met ontvanger rekening houden zoals door het gepast inzetten van lichaamstaal; eigen tekst nakijken; ondersteunende middelen gebruiken; met doel interactie rekening houden; inspelen op wat de ander zegt; om hulp/opheldering vragen zoals trager spreken, herhalen, herformuleren en zelf hulp/opheldering bieden; elementen of lichaamstaal en intonatie herkennen en zelf doelgericht inzetten; compenserende strategieën bij falende communicatie.",
  },
  {
    code: "1A.ST.03.06",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.06",
    soort: "standaard",
    omschrijving: "De leerlingen zetten eerder en nieuwverworven woordenschat in ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen:\nIn het Engels en in het Frans\n\nTekstkenmerken voor receptie & Minimumvereisten voor productie\n\nVoetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.ST.03.07",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.07",
    soort: "standaard",
    omschrijving: "De leerlingen passen inzicht in het taalsysteem toe ter ondersteuning van hun communicatieve handelingen.",
    uitleg: "Onderliggende (kennis)elementen (gelden voor het Frans én het Engels, tenzij gespecificeerd met [F] of [E]):\nUitspraak van klanken en klankencombinaties; Intonatie, ritme en woordklemtoon; Articulatie, relatie klank- en schriftbeeld; Zelfstandige naamwoorden: getal, genus [F]; Congruentie: onderwerp-persoonsvorm, bijvoeglijk naamwoord- zelfstandig naamwoord [F], voltooid deelwoord met être [F]; Lidwoorden; Voornaamwoorden: persoonlijk als onderwerp en als lijdend [F] en meewerkend [F] voorwerp; plaats van het persoonlijk voornaamwoord; aanwijzend, bezittelijk, vragend; Frequente hoofd- en rangtelwoorden; Bijvoeglijke naamwoorden: meervoud [F], vrouwelijk [F], plaats, trappen van vergelijking; Werkwoorden: indicatif [F], impératif [F], infinitif [F], conditionnel de politesse [F]; présent [F], passé récent [F], passé composé [F], imparfait [F], futur proche [F], infinitive [E], imperative [E]; present simple [E], present continuous [E], simple past [E], simple future [E]; regelmatige en frequente onregelmatige werkwoorden, les verbes pronominaux [F]; Frequente voorzetsels; Frequente nevenschikkende en hoogfrequente onderschikkende voegwoorden; Ontkennende/bevestigende zinnen; mededelende/vragende/bevelende/ uitroepende zinnen; Spelling of in te zetten woorden",
  },
  {
    code: "1A.ST.03.08",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.08",
    soort: "standaard",
    omschrijving: "De leerlingen identificeren bij het lezen en beluisteren van teksten kenmerkende aspecten van maatschappijen en culturen waarin de doeltaal wordt gesproken.",
    uitleg: "Onderliggende (kennis)elementen:\nTeksten in het Engels en in het Frans",
  },
  {
    code: "1A.ST.03.09",
    competentieNr: 3,
    competentie: "3. Competenties in andere talen",
    nummer: "03.09",
    soort: "standaard",
    omschrijving: "De leerlingen drukken de eigen beleving en interpretatie van literaire teksten uit.",
    uitleg: "Onderliggende (kennis)elementen:\nTeksten in het Engels en in het Frans\n\nVoetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nEigen beleving en interpretatie zoals waarom sommige aspecten van de tekst aanspreken, waarom men zich identificeert met een bepaald personage, in welke zin men gelijkaardige ervaringen zelf al heeft meegemaakt, waarom de tekst een bepaalde emotionele reactie teweegbrengt, waarom de uitdrukkingsvorm of stijl aanspreekt. In functie van leerlingenkenmerken kan de beleving en interpretatie in de doeltaal worden uitgedrukt.",
  },
  {
    code: "1A.ST.04.01",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.01",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken basisfunctionaliteiten van toepassingen om digitaal te communiceren.",
    uitleg: "Memorie:\nDigitaal communiceren zoals in interactie gaan met mensen, systemen, diensten; synchroon (online meeting, chat), asynchroon (berichtensysteem, sociale media, sms, e-mail, blog, fora, websites).\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals versturen en ontvangen van berichten. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1A.ST.04.02",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.02",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken basisfunctionaliteiten van toepassingen om digitale inhouden te creëren.",
    uitleg: "Memorie:\nDigitale inhouden creëren zoals in tekst-, cijfer-, geluid-, grafische, audiovisuele bestanden, programmacode.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het openen van een document. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1A.ST.04.03",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.03",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken basisfunctionaliteiten van toepassingen om digitale inhouden te beheren aan de hand van een aangereikte structuur.",
    uitleg: "Memorie:\nDigitale inhouden beheren zoals met behulp van informatiedragers zoals interne en externe opslag; met behulp van ordeningstechnieken zoals mappenstructuur, ordening op thema.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het verplaatsen en kopiëren van bestanden. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1A.ST.04.04",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.04",
    soort: "standaard",
    omschrijving: "De leerlingen passen ethische, sociale en legale regels toe bij het gebruiken van digitale technologie.",
    uitleg: "Memorie:\nEthische, sociale en legale regels zoals principes van privacy zoals het zich beveiligen, beschermen van persoonlijke data; principes van auteursrecht zoals gebruik van eigen/andermans werk, rechtenvrij werk; principes van portretrecht; nettiquette.",
  },
  {
    code: "1A.ST.04.05",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "04.05",
    soort: "standaard",
    omschrijving: "De leerlingen ontwerpen doelgericht een digitaal en niet-digitaal algoritme volgens de principes van computationeel denken en debuggen het.",
    uitleg: "Onderliggende (kennis)elementen:\nBouwstenen van digitale systemen\nPrincipes van computationeel denken: decompositie, patroonherkenning, abstractie, algoritmen.",
  },
  {
    code: "1A.BG.04.01",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "BG04.01",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt doelgericht basisfunctionaliteiten van toepassingen om digitaal te communiceren.",
    uitleg: "Memorie:\nDigitaal communiceren zoals in interactie gaan met mensen, systemen, diensten; synchroon (online meeting, chat), asynchroon (berichtensysteem, sociale media, sms, e-mail, blog, fora, websites).\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals versturen en ontvangen van berichten. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1A.BG.04.02",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "BG04.02",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt doelgericht basisfunctionaliteiten van toepassingen om digitale inhouden te creëren.",
    uitleg: "Memorie:\nDigitale inhouden creëren zoals in tekst-, cijfer-, geluid-, grafische, audiovisuele bestanden, programmacode.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het openen van een document. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1A.BG.04.03",
    competentieNr: 4,
    competentie: "4. Digitale competentie en mediawijsheid",
    nummer: "BG04.03",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt doelgericht basisfunctionaliteiten van toepassingen om digitale inhouden te beheren aan de hand van een aangereikte structuur.",
    uitleg: "Memorie:\nDigitale inhouden beheren zoals met behulp van informatiedragers zoals interne en externe opslag; met behulp van ordeningstechnieken zoals mappenstructuur, ordening op thema.\n\nBasisfunctionaliteiten zijn de elementen die nodig zijn om een systeem functioneel te gebruiken zoals het verplaatsen en kopiëren van bestanden. Ze onderscheiden zich van courante functionaliteiten die de basiselementen aanvullen met elementen die de gebruikerservaring verbeteren zoals sneltoetsen gebruiken.",
  },
  {
    code: "1A.ST.05.01",
    competentieNr: 5,
    competentie: "5. Sociaal-relationele competenties",
    nummer: "05.01",
    soort: "standaard",
    omschrijving: "De leerlingen gaan respectvol en constructief met anderen in interactie rekening houdend met elkaars grenzen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nRespectvol en constructief met anderen in interactie gaan zoals:\nrekening houden met de opvattingen, de fysieke en mentale grenzen en de emoties van anderen;\ngrenzen herkennen en bewaken;\nreageren tegen grensoverschrijdend gedrag;\nsamenwerken en actief bijdragen aan de uitwerking van een gezamenlijk resultaat;\nomgaan met emoties in verschillende situaties;\nrespect tonen voor relationele en seksuele integriteit;\nsociaal vaardig interageren in informele en formele relaties.",
  },
  {
    code: "1A.ST.06.01",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.01",
    soort: "standaard",
    omschrijving: "De leerlingen rekenen met natuurlijke, gehele en rationale getallen.",
    uitleg: "Onderliggende (kennis)elementen:\nUitbreiding van de natuurlijke getallen (symbool ℕ) naar de gehele getallen (symbool ℤ) en van de gehele getallen naar de rationale getallen (symbool ℚ).\nOptelling, aftrekking, vermenigvuldiging, deling, machtsverheffing met gehele exponenten, procentberekening, met rekenregels, eigenschappen, en volgorde van bewerkingen en symbolen (+, -, ·, :, .ⁿ).\nTegengestelde, omgekeerde en absolute waarde van een getal met symbolen (.⁻¹,∣.∣).\nSchatting grootteorde, afronding.\nDeling met rest bij natuurlijke getallen, grootste gemene deler, kleinste gemene veelvoud, priemgetal.\nVierkantswortel bij natuurlijke getallen met symbool √.",
  },
  {
    code: "1A.ST.06.02",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.02",
    soort: "standaard",
    omschrijving: "De leerlingen zetten rationale getallen om van de ene naar de andere voorstellingswijze: decimale vorm, breuk en procent.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.03",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.03",
    soort: "standaard",
    omschrijving: "De leerlingen ordenen rationale getallen.",
    uitleg: "Onderliggende (kennis)elementen:\nGetallenas\nSymbolen =,≠,<,>,≤,≥",
  },
  {
    code: "1A.ST.06.04",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.04",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren meetkundige objecten met behulp van eigenschappen en meetkundige relaties in het vlak.",
    uitleg: "Onderliggende (kennis)elementen:\nEigenschappen van meetkundige objecten:\nHoeken bij twee evenwijdige rechten en een snijlijn; Hoekensom in driehoeken en vierhoeken; Gelijkzijdige en gelijkbenige driehoeken; Zijden, hoeken en diagonalen in vierhoeken.\nMeetkundige relaties:\nEvenwijdigheid, loodrechte stand, symmetrie met symbolen (∥, ∦, ⟂); Merkwaardige lijnen in driehoeken: bissectrice, hoogtelijn, middelloodlijn en zwaartelijn.\nClassificatie van driehoeken en van vierhoeken.",
  },
  {
    code: "1A.ST.06.05",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.05",
    soort: "standaard",
    omschrijving: "De leerlingen construeren meetkundige objecten met gegeven eigenschappen in het vlak.",
    uitleg: "Onderliggende (kennis)elementen:\nMeetkundige objecten: lijnstukken, merkwaardige lijnen, driehoeken, vierhoeken en cirkels.",
  },
  {
    code: "1A.ST.06.06",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.06",
    soort: "standaard",
    omschrijving: "De leerlingen passen congruentiekenmerken van driehoeken toe.",
    uitleg: "Onderliggende (kennis)elementen:\nCongruentiekenmerken: ZZZ, ZHZ, HZH, ZZ90°\nSymbool ≅",
  },
  {
    code: "1A.ST.06.07",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.07",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen een vlakke figuur en haar beeld onder een transformatie van het vlak.",
    uitleg: "Onderliggende (kennis)elementen:\nTranslatie over een vector, spiegeling om een as, spiegeling om een punt en rotatie rond een centrum over een hoek; Eigenschappen van transformaties; Verband tussen transformaties en congruentie; Verband tussen transformaties en symmetrie.",
  },
  {
    code: "1A.ST.06.08",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.08",
    soort: "standaard",
    omschrijving: "De leerlingen berekenen omtrek en oppervlakte van vlakke figuren: driehoek, trapezium, parallellogram, ruit, rechthoek, vierkant en cirkel.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.09",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.09",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren aan de hand van 2D- en 3D-voorstellingen meetkundige objecten in de ruimte: kubus, balk, piramide, bol, kegel en cilinder.",
    uitleg: "Onderliggende (kennis)elementen:\nSnijdende, kruisende en evenwijdige rechten; Perspectief, aanzichten en verlies van informatie; Herkenning van symmetrie.\n\nMemorie:\nSymmetrie wordt ook in de ruimte ontdekt, maar dat mag worden beperkt tot heel eenvoudige voorbeelden. Het gaat vooral over het besef dat er ook in de ruimte symmetrie bestaat zodat niet het beeld ontstaat dat symmetrie enkel bij vlakke voorstellingen kan voorkomen.",
  },
  {
    code: "1A.ST.06.10",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.10",
    soort: "standaard",
    omschrijving: "De leerlingen berekenen oppervlakte en volume van ruimtefiguren: kubus, balk en cilinder.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.11",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.11",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken letters als onbekenden, als variabelen en voor veralgemeningen.",
    uitleg: "Memorie:\nDeze eindterm wordt best in samenhang gerealiseerd met andere eindtermen zoals 06.08, 06.10, 06.12, 06.13, 06.16, 06.17, 06.21.",
  },
  {
    code: "1A.ST.06.12",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.12",
    soort: "standaard",
    omschrijving: "De leerlingen rekenen met algebraïsche uitdrukkingen.",
    uitleg: "Onderliggende (kennis)elementen:\nOptelling, aftrekking en vermenigvuldiging met eigenschappen en rekenregels; Uitwerking van merkwaardige producten tot een som: (a+b)² en (a+b)(a-b).",
  },
  {
    code: "1A.ST.06.13",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.13",
    soort: "standaard",
    omschrijving: "De leerlingen bepalen de getalwaarde van een algebraïsche uitdrukking.",
    uitleg: "Memorie:\nVoor de eerste graad kan een algebraïsche uitdrukking met maximum 2 variabelen volstaan. De complexiteit van deze eindterm is echter niet enkel afhankelijk van het aantal variabelen in een algebraïsche uitdrukking.",
  },
  {
    code: "1A.ST.06.14",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.14",
    soort: "standaard",
    omschrijving: "De leerlingen hanteren coördinaten in het vlak.",
    uitleg: "Onderliggende (kennis)elementen:\nNotatie (x, y)",
  },
  {
    code: "1A.ST.06.15",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.15",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren recht en omgekeerd evenredige verbanden tussen grootheden.",
    uitleg: "Onderliggende (kennis)elementen:\nTabel en grafiek; Formules y/x=c en x.y=c met c de evenredigheidsfactor.",
  },
  {
    code: "1A.ST.06.16",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.16",
    soort: "standaard",
    omschrijving: "De leerlingen stellen formules op die regelmaat in eenvoudige patronen en schema’s beschrijven.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.17",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.17",
    soort: "standaard",
    omschrijving: "De leerlingen lossen vergelijkingen van de eerste graad op in één onbekende in de verzameling van de rationale getallen.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.18",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.18",
    soort: "standaard",
    omschrijving: "De leerlingen voeren een beschrijvend statistisch onderzoek uit met niet-gegroepeerde gegevens van één grootheid.",
    uitleg: "Onderliggende (kennis)elementen:\nTabel met absolute frequenties; Staafdiagram, cirkeldiagram, lijndiagram; Mediaan, rekenkundig gemiddelde, modus, variatiebreedte.\n\nMemorie:\nDe omvang van de gegevensset moet relevant zijn om een beschrijvend statistisch onderzoek te kunnen uitvoeren. De gegevensset kan al dan niet worden aangereikt. Het voeren van een beschrijvend statistisch onderzoek veronderstelt een grafische voorstelling, berekeningen en een interpretatie van de resultaten.",
  },
  {
    code: "1A.ST.06.19",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.19",
    soort: "standaard",
    omschrijving: "De leerlingen beargumenteren wiskundige redeneringen.",
    uitleg: "Onderliggende (kennis)elementen:\nAls dan-relatie (implicatie, symbool ⇒), als-en-slechts-als-relatie (equivalentie, symbool ⇔).\n\nVoetnoot:\nRekening houdend met concepten van de eerste graad.",
  },
  {
    code: "1A.ST.06.20",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.20",
    soort: "standaard",
    omschrijving: "De leerlingen voeren bewerkingen met twee verzamelingen uit: doorsnede, unie en verschil.",
    uitleg: "Onderliggende (kennis)elementen:\nElement, deelverzameling; Symbolen ∈,∉,⊂,⊄,∩,∪,∖; Venndiagram.",
  },
  {
    code: "1A.ST.06.21",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.21",
    soort: "standaard",
    omschrijving: "De leerlingen lossen vraagstukken en problemen op door te mathematiseren en demathematiseren en door gebruik te maken van heuristieken.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de eerste graad.",
  },
  {
    code: "1A.ST.06.22",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.22",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken ICT om berekeningen uit te voeren en grafische voorstellingen te maken.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de eerste graad.",
  },
  {
    code: "1A.ST.06.23",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.23",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven fenomenen uit de realiteit aan de hand van wiskundige concepten uit de eerste graad.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.24",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.24",
    soort: "standaard",
    omschrijving: "De leerlingen leggen de samenhang tussen de verschillende organisatieniveaus in een plantaardig en dierlijk organisme uit met de cel als basiseenheid.",
    uitleg: "Memorie:\nOrganisatieniveaus zoals cellen, weefsels, organen, stelsels.\nCelonderdelen zoals celwand, celmembraan, celkern, bladgroenkorrels, mitochondriën, cytoplasma.",
  },
  {
    code: "1A.ST.06.25",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.25",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het belang van fotosynthese uit.",
    uitleg: "Onderliggende (kennis)elementen:\nEnergieomzetting, stofomzetting en stofuitwisseling; Transport in een organisme.\n\nMemorie:\nEr wordt nadruk gelegd op systeemdenken, vandaar de opname van transport in een organisme. Verder zijn omzettingen en uitwisseling opgenomen die minimaal noodzakelijk zijn om het doel te bereiken.",
  },
  {
    code: "1A.ST.06.26",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.26",
    soort: "standaard",
    omschrijving: "De leerlingen leggen uit hoe stofomzettingen, stofuitwisselingen en energieomzettingen het functioneren van de mens en dieren mogelijk maken.",
    uitleg: "Onderliggende (kennis)elementen:\nTransport in een organisme; Ademhalingsstelsel, spijsverteringsstelsel, bloedvatenstelsel.\n\nMemorie:\nEr wordt nadruk gelegd op systeemdenken, vandaar de opname van transport in een organisme. Verder zijn de stelsels opgesomd die relevant zijn in functie van de stofomzetting.",
  },
  {
    code: "1A.ST.06.27",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.27",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren voortplantingswijzen van planten en dieren.",
    uitleg: "Onderliggende (kennis)elementen:\nAseksuele en seksuele voortplanting.",
  },
  {
    code: "1A.ST.06.28",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.28",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verloop van de voortplanting bij de mens uit.",
    uitleg: "Onderliggende (kennis)elementen:\nFunctie van organen van het voortplantingsstelsel.",
  },
  {
    code: "1A.ST.06.29",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.29",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren voor een biotoop de onderlinge relaties tussen verschillende organismen en de rol van biotische en abiotische factoren.",
    uitleg: "Onderliggende (kennis)elementen:\nBiodiversiteit; Verband tussen kenmerken van een organisme, zijn omgeving en zijn overleven.",
  },
  {
    code: "1A.ST.06.30",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.30",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verschil uit tussen een chemisch en een fysisch verschijnsel aan de hand van het deeltjesmodel.",
    uitleg: "Onderliggende (kennis)elementen:\nFysische verschijnselen: Aggregatietoestanden, faseovergangen; Thermische uitzetting, krimp.\nChemische verschijnselen: Verbindingen en atomen in functie van chemische omzetting.",
  },
  {
    code: "1A.ST.06.31",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.31",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verschil uit tussen mengsels en zuivere stoffen aan de hand van het deeltjesmodel in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1A.ST.06.32",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.32",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven energieomzettingen in systemen.",
    uitleg: "Onderliggende (kennis)elementen:\nEnergievormen: thermische energie, elektrische energie, potentiële energie, kinetische energie, stralingsenergie, chemische energie.",
  },
  {
    code: "1A.ST.06.33",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.33",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen krachten en hun uitwerking in betekenisvolle contexten.",
    uitleg: "Onderliggende (kennis)elementen:\nGrootte, richting en zin van een kracht.\n\nMemorie:\nKrachten zoals zwaartekracht, wrijvingskracht, trek- en duwkracht.",
  },
  {
    code: "1A.ST.06.34",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.34",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen massadichtheid, volume en massa.",
    uitleg: "Onderliggende (kennis)elementen:\nMassadichtheid als verhouding.",
  },
  {
    code: "1A.ST.06.35",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.35",
    soort: "standaard",
    omschrijving: "De leerlingen leggen het verband tussen constante snelheid, verplaatsing en tijdsduur.",
    uitleg: "Onderliggende (kennis)elementen:\nConstante snelheid als verhouding.",
  },
  {
    code: "1A.ST.06.36",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.36",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren eigenschappen van materialen en grondstoffen in functie van een probleemstelling.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nMaterialen zoals metalen en niet-metalen, ferro- en non-ferrometalen, natuurlijke en kunstmatige materialen.\nEigenschappen van materialen zoals:\n- elektrisch zoals geleiding;\n- fysisch zoals dichtheid;\n- magnetisch zoals aantrekking en afstoting van ferromagnetische materialen;\n- mechanisch zoals elasticiteit, hardheid;\n- technologisch zoals vervormbaarheid.",
  },
  {
    code: "1A.ST.06.37",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.37",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren principes van de bouw en werking van technische systemen, hun deelsystemen, onderdelen en hun onderlinge samenhang in een energiesysteem en een informatieverwerkend systeem en in minstens 1 van de volgende systemen: een constructiesysteem, een transportsysteem en een biotechnische systeem.",
    uitleg: "Memorie:\nEnergie: principes zoals\n- energieomzettingen in technische systemen;\n- nuttige en niet-nuttige energie in systemen;\n- elektrische stroomkring: componenten van de stroomkring, schematische voorstelling.\nInformatieverwerking: principes zoals\n- functie van sensoren en actuatoren;\n- logica in een besturing.\nIn geval van keuze voor een constructiesysteem, principes zoals\n- stabiliteit, sterkte en stijfheid;\n- verbindingen;\n- krachten op een constructie.\nIn geval van keuze voor een transportsysteem, principes zoals\n- overbrengingen;\n- transportmogelijkheden.\nIn geval van keuze voor een biotechnisch systeem, principes zoals\n- biochemische processen in de voedingsindustrie;\n- conservering van voedingsmiddelen, doel van verschillende verpakkingen.",
  },
  {
    code: "1A.ST.06.38",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.38",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen een technisch proces om een technisch systeem te realiseren vanuit behoefte(n) en criteria.",
    uitleg: "Onderliggende (kennis)elementen:\nOntwerp- en productieproces.\n\nVoetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nFasen van een technisch proces zoals probleemstelling/behoefte onderzoeken, ontwerpen, maken, in gebruik nemen, evalueren.",
  },
  {
    code: "1A.ST.06.39",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.39",
    soort: "standaard",
    omschrijving: "De leerlingen werken op een veilige en duurzame manier met materialen, stoffen, organismen en technische systemen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.ST.06.40",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.40",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken met de nodige nauwkeurigheid meetinstrumenten en hulpmiddelen.",
    uitleg: "Memorie:\nMeetinstrumenten en hulpmiddelen zoals chronometer, determineertabel, handgereedschap, lichtmicroscoop, loep, meetlat, proefbuis, thermometer, weegschaal.",
  },
  {
    code: "1A.ST.06.41",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.41",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken gepaste grootheden en eenheden in een correcte weergave.",
    uitleg: "Onderliggende (kennis)elementen:\nGrootteorde en maatbesef van de grootheden tijd, lengte, oppervlakte, inhoud/volume, massa, spanning, kracht, energie.\nHerleiding van courante eenheden.",
  },
  {
    code: "1A.ST.06.42",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.42",
    soort: "standaard",
    omschrijving: "De leerlingen voeren onderzoek aan de hand van een wetenschappelijke methode om kennis te ontwikkelen en om vragen te beantwoorden.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de eerste graad.\n\nMemorie:\nStappen in een wetenschappelijke methode: onderzoeksvraag opstellen, hypothese formuleren, methode/plan uitvoeren, waarnemingen/data analyseren, concluderen.",
  },
  {
    code: "1A.ST.06.43",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.43",
    soort: "standaard",
    omschrijving: "De leerlingen ontwerpen een oplossing voor een probleem door wetenschappen, technologie of wiskunde geïntegreerd aan te wenden.",
    uitleg: "Voetnoot:\nRekening houdend met concepten van de eerste graad en de context waarin dit minimumdoel aan bod komt.\n\nMemorie:\nSTEM betekent per definitie dat je geïntegreerd denkt. De mate van integratie is afhankelijk van het probleem. Ook niet-STEM-disciplines kunnen aan bod komen.",
  },
  {
    code: "1A.ST.06.44",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "06.44",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren de wisselwerking tussen wetenschappen, technologie, wiskunde en de maatschappij aan de hand van maatschappelijke uitdagingen.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin dit minimumdoel aan bod komt.",
  },
  {
    code: "1A.BG.06.01",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.01",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling voert met functioneel gebruik van ICT eenvoudige berekeningen uit met natuurlijke, positieve decimale getallen met maximaal 2 cijfers na de komma, procenten en verhoudingen in betekenisvolle contexten.",
    uitleg: "Onderliggende (kennis)elementen:\nSchatting grootteorde van resultaten, zinvolle afronding; Verhoudingstabel.\n\nMemorie:\nDe leerling is in staat om verhoudingen te gebruiken in realistische contexten. Wanneer bijvoorbeeld in een kookboek een recept staat voor 4 personen kan de leerling met een gegeven verhoudingstabel de benodigde ingrediënten omrekenen naar bijvoorbeeld een recept voor 5 personen.",
  },
  {
    code: "1A.BG.06.02",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.02",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt maatgetallen en eenheden van grootheden in betekenisvolle contexten.",
    uitleg: "Onderliggende (kennis)elementen:\nGrootteorde en maatbesef van de grootheden tijd, lengte, oppervlakte, inhoud/volume en massa.",
  },
  {
    code: "1A.BG.06.03",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.03",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling gebruikt informatie uit eenvoudige tabellen en diagrammen in betekenisvolle contexten.",
    uitleg: "",
  },
  {
    code: "1A.BG.06.04",
    competentieNr: 6,
    competentie: "6. Competenties inzake wiskunde, exacte wetenschappen en technologie/STEM",
    nummer: "BG06.04",
    soort: "basisgeletterdheid",
    omschrijving: "De leerling berekent de omtrek van een vierhoek en de oppervlakte van een rechthoek in betekenisvolle contexten.",
    uitleg: "Onderliggende (kennis)elementen:\nOmtrek van een vierhoek als som van de lengtes van de zijden; Oppervlakte van een rechthoek als product van de lengtes van de lange en korte zijde.",
  },
  {
    code: "1A.ST.07.01",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.01",
    soort: "standaard",
    omschrijving: "De leerlingen lichten de betekenis, de principes en de werking van de democratische rechtsstaat en hun verantwoordelijkheid daarin toe.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDe democratische rechtsstaat op een bestuursniveau met impact op de leefwereld van leerlingen, zoals gemeente, provincie, gemeenschap, gewest, federaal, Europese Unie. Verantwoordelijkheid van leerlingen zoals een mogelijk individueel of gezamenlijk engagement.",
  },
  {
    code: "1A.ST.07.02",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.02",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over het relationele, gelaagde en dynamische karakter van identiteit.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nHet relationele en dynamische karakter van identiteit zoals gerelateerd aan verbondenheid, solidariteit, discriminatie, wij-zij-denken. De accenten kunnen afhankelijk zijn van de leefwereld van de leerlingen, de actualiteit ... Het gelaagde karakter van identiteit zoals gerelateerd aan:\n- biologische aspecten, persoonlijkheidstrekken, familiale achtergrond;\n- regionale, nationale of supranationale groepen, zoals de Vlaamse, de Belgische, de Europese en de niet-Europese;\n- subculturen, gender-gerelateerde groepen, socio-economische groepen, levensbeschouwelijke groepen.",
  },
  {
    code: "1A.ST.07.03",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten toe hoe verschillende vormen van diversiteit verrijkend en uitdagend zijn voor het samenleven.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDiversiteit zoals gerelateerd aan fysieke, mentale, cognitieve, socio-economische, culturele, levensbeschouwelijke aspecten. Verrijkend zoals culturele verrijking, uitwisseling van ideeën, economische uitwisseling. Uitdagend zoals meningsverschillen, verschillende belangen, verschillende referentiekaders van waaruit men denkt en handelt, risico van groepsdenken en uitsluiting.",
  },
  {
    code: "1A.ST.07.04",
    competentieNr: 7,
    competentie: "7. Burgerschapscompetenties met inbegrip van competenties inzake samenleven",
    nummer: "07.04",
    soort: "standaard",
    omschrijving: "De leerlingen gaan geïnformeerd, beargumenteerd en constructief in dialoog over maatschappelijke thema’s.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nGeïnformeerd, beargumenteerd en constructief in dialoog gaan zoals door het toepassen van strategieën als actief luisteren, creatief denken, zich inleven, respectvol en duidelijk uitkomen voor zijn mening, een eigen mening onderbouwen.",
  },
  {
    code: "1A.ST.08.01",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.01",
    soort: "standaard",
    omschrijving: "De leerlingen bouwen een historisch referentiekader op met structuurbegrippen, scharnierpunten en kenmerken eigen aan de prehistorie, het oude nabije oosten en de klassieke oudheid.",
    uitleg: "Onderliggende (kennis)elementen:\nDe zeven periodes van het westerse historisch referentiekader: de prehistorie, het oude nabije oosten, de klassieke oudheid, de middeleeuwen, de vroegmoderne tijd, de moderne tijd en de hedendaagse tijd.\nStructuurbegrippen met betrekking tot de drie dimensies van het historisch referentiekader: tijd, ruimte en de maatschappelijke domeinen (politiek, sociaal, cultureel en economisch).\n\nMemorie:\nStructuurbegrippen met betrekking tot:\n- tijd: zoals millennium, eeuw, jaar, tijdrekening, chronologie, periode, continuïteit, verandering, evolutie, revolutie, duur;\n- ruimte: zoals lokaal, regionaal, stedelijk en ruraal, continentaal en maritiem.\nKenmerken of samenlevingen uit elk van de drie bestudeerde periodes, voor elk van de maatschappelijke domeinen:\n- politiek: zoals stadstaat, rijk, dynastie, republiek, autocratie, aristocratie, democratie, imperialisme, kolonisatie, ambtenaren;\n- sociaal: zoals nomadische samenleving, sedentaire samenleving, standenmaatschappij, patriarchale samenleving, migratie, ongelijkheid, slavernij, burgerrechten, oorlog en vrede;\n- cultureel: zoals mythologie, wetenschappen, filosofie, natuurreligie, polytheïsme, monotheïsme, staatsgodsdienst, kunstuiting, schriftsoorten, cultuur, mondelinge traditie, multiculturele samenleving;\n- economisch: zoals jager-verzamelaar, agrarische (r)evolutie (of: neolithische revolutie), landbouw, ambacht, handel, ruileconomie, geldeconomie.",
  },
  {
    code: "1A.ST.08.02",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.02",
    soort: "standaard",
    omschrijving: "De leerlingen lichten verbanden toe tussen de maatschappelijke domeinen voor samenlevingen uit de prehistorie, het oude nabije oosten en de klassieke oudheid.",
    uitleg: "",
  },
  {
    code: "1A.ST.08.03",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.03",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken kenmerken van bestudeerde samenlevingen in eenzelfde periode en tussen periodes.",
    uitleg: "",
  },
  {
    code: "1A.ST.08.04",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.04",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren beperkingen van de westerse periodisering voor de bestudeerde periodes.",
    uitleg: "Memorie:\nBeperkingen van de periodisering zoals in tijd, ruimte en maatschappelijke domeinen.",
  },
  {
    code: "1A.ST.08.05",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.05",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren kritisch verschillende soorten historische bronnen met betrekking tot de bestudeerde periodes in functie van een historische vraag.",
    uitleg: "Memorie:\nKritisch analyseren zoals rekening houden met standplaatsgebondenheid, perspectief van de auteur/maker, doelpubliek.",
  },
  {
    code: "1A.ST.08.06",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.06",
    soort: "standaard",
    omschrijving: "De leerlingen vergelijken historische bronnen met betrekking tot de bestudeerde periodes in functie van een historische vraag.",
    uitleg: "",
  },
  {
    code: "1A.ST.08.07",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.07",
    soort: "standaard",
    omschrijving: "De leerlingen beantwoorden een historische vraag aan de hand van historische bronnen met betrekking tot de bestudeerde periodes en historische redeneerwijzen.",
    uitleg: "Memorie:\nHistorische redeneerwijzen zoals causaal redeneren, continuïteit en verandering analyseren, zich historisch inleven, meerdere perspectieven in acht nemen, actualiseren en historiseren, bewijs gebruiken, verbanden leggen tussen historische feiten.\n\nHet beantwoorden van een historische vraag gebeurt door gebruik te maken van historische bronnen en historische redeneerwijzen.",
  },
  {
    code: "1A.ST.08.08",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.08",
    soort: "standaard",
    omschrijving: "De leerlingen lichten the invloed toe van de eigen standplaatsgebondenheid op historische beeldvorming met betrekking tot de bestudeerde periodes.",
    uitleg: "",
  },
  {
    code: "1A.ST.08.09",
    competentieNr: 8,
    competentie: "8. Competenties met betrekking tot historisch bewustzijn",
    nummer: "08.09",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren hoe mythevorming rond historische fenomenen historische beeldvorming vervormt.",
    uitleg: "Onderliggende (kennis)elementen:\nOnderscheid tussen verleden en geschiedenis",
  },
  {
    code: "1A.ST.09.01",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.01",
    soort: "standaard",
    omschrijving: "De leerlingen situeren absoluut en relatief personen, plaatsen en patronen op relevante ruimtelijke schaalniveaus.",
    uitleg: "Voetnoot:\nRekening houdend met personen, plaatsen en patronen die in de eerste graad aan bod komen.",
  },
  {
    code: "1A.ST.09.02",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.02",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven kenmerken van fysischgeografische en sociaalgeografische landschapsvormende lagen.",
    uitleg: "Memorie:\nLandschapsvormende lagen:\n- fysischgeografisch zoals reliëf, klimaat, vegetatie en bodem;\n- sociaalgeografisch zoals types van bebouwing, verspreiding van bebouwing, infrastructuur, landbouw, industrie.",
  },
  {
    code: "1A.ST.09.03",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.03",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren relaties tussen landschapsvormende lagen of plaatsen om verschillen tussen landschappen te verklaren.",
    uitleg: "Memorie:\nRelaties zoals tussen bodemgebruik en bodem, landgebruik en helling, bodem en ondergrond, klimaat en vegetatie of woonplaats en werkplaats, wegeninfrastructuur door een natuurgebied, reliëfvormen en bevolkingsspreiding.",
  },
  {
    code: "1A.ST.09.04",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.04",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren ruimtelijke patronen op verschillende schaalniveaus.",
    uitleg: "Memorie:\nRuimtelijke patronen zoals reliëfeenheden, klimaatzones, vegetatiezones, bevolkingsspreiding.",
  },
  {
    code: "1A.ST.09.05",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.05",
    soort: "standaard",
    omschrijving: "De leerlingen illustreren dat landschappen evolueren op korte en lange termijn onder invloed van fysischgeografische en sociaalgeografische veranderingen.",
    uitleg: "Memorie:\nFysischgeografische veranderingen zoals door vulkaanuitbarstingen, aardbevingen, weer, erosie.\nSociaalgeografische veranderingen zoals door bebouwing, infrastructuur, landbouw, industrie, ontginning.",
  },
  {
    code: "1A.ST.09.06",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.06",
    soort: "standaard",
    omschrijving: "De leerlingen analyseren gevolgen van veranderingen in landschappen voor de mens en voor zijn leefomgeving.",
    uitleg: "Memorie:\nVeranderingen zoals stijging van de zeespiegel, vergroting van landbouwpercelen, ontbossing, omzetten van landbouwgebied naar bebouwing, ontharding, stadslandbouw.",
  },
  {
    code: "1A.ST.09.07",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.07",
    soort: "standaard",
    omschrijving: "De leerlingen lokaliseren zichzelf en plaatsen aan de hand van lokalisatie- en oriëntatietechnieken.",
    uitleg: "Memorie:\nGebruik van lokalisatie- en oriëntatietechnieken zoals:\n- kaart: schaal, legende en oriëntatie;\n- windrichtingen en kompas;\n- satellietnavigatiesystemen.",
  },
  {
    code: "1A.ST.09.08",
    competentieNr: 9,
    competentie: "9. Competenties met betrekking tot ruimtelijk bewustzijn",
    nummer: "09.08",
    soort: "standaard",
    omschrijving: "De leerlingen zetten terreintechnieken en geografische hulpbronnen met inbegrip van GIS-viewers functioneel in.",
    uitleg: "Voetnoot:\nRekening houdend met de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nTerreintechnieken zoals lokalisatie, oriëntatie, observatie.\nGeografische hulpbronnen zoals digitale en niet-digitale kaarten, atlas, beeldmateriaal.",
  },
  {
    code: "1A.ST.11.01",
    competentieNr: 11,
    competentie: "11. Economische en financiële competenties",
    nummer: "11.01",
    soort: "standaard",
    omschrijving: "De leerlingen beargumenteren hun keuzegedrag bij aankopen rekening houdend met hun behoeften, met een persoonlijk budget en een beschikbaar gezinsbudget en met factoren die hun koopgedrag beïnvloeden.",
    uitleg: "Onderliggende (kennis)elementen:\nReële en gecreëerde behoeften; Sparen en lenen; Belang van persoonlijk administratiebeheer.\n\nMemorie:\nFactoren zoals bijkomende kosten, status, reclame, verkoopspraktijken, peers, media, sociale media, milieu- en sociale aspecten.",
  },
  {
    code: "1A.ST.11.02",
    competentieNr: 11,
    competentie: "11. Economische en financiële competenties",
    nummer: "11.02",
    soort: "standaard",
    omschrijving: "De leerlingen beoordelen courante betaalmiddelen en courante verkoopkanalen op het vlak van veiligheid, risico’s en kosten.",
    uitleg: "Onderliggende (kennis)elementen:\nFraude.\n\nMemorie:\nHet beoordelen van courante betaalmiddelen en verkoopkanalen veronderstelt inzicht in modaliteiten en gebruik ervan.",
  },
  {
    code: "1A.ST.11.03",
    competentieNr: 11,
    competentie: "11. Economische en financiële competenties",
    nummer: "11.03",
    soort: "standaard",
    omschrijving: "De leerlingen lichten de rol van gezinnen, bedrijven en overheid in de economie toe.",
    uitleg: "Onderliggende (kennis)elementen:\nInkomsten en uitgaven; Consumeren en produceren; Maatschappelijk verantwoord ondernemen; Profit en non-profit.",
  },
  {
    code: "1A.ST.13.01",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.01",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over het eigen leerproces en sturen het doelgericht bij.",
    uitleg: "Memorie:\nHet reflecteren over het eigen leerproces bevat een cognitieve, een metacognitieve en een motivationele component.\nHet bijsturen van het eigen leerproces kan gebeuren op basis van de eigen reflectie en van de feedback van anderen.",
  },
  {
    code: "1A.ST.13.02",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.02",
    soort: "standaard",
    omschrijving: "De leerlingen zetten (meta)cognitieve leer- en regulatiestrategieën in om zich leerinhouden eigen te maken.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nCognitieve leerstrategieën en bijhorende activiteiten zoals structureren, zich vragen stellen bij de leerinhoud, memoriseren, herhalen, selecteren, relateren, toepassen, inoefenen.\nMetacognitieve regulatiestrategieën en bijhorende activiteiten zoals plannen, monitoren, evalueren, bijsturen.",
  },
  {
    code: "1A.ST.13.03",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.03",
    soort: "standaard",
    omschrijving: "De leerlingen gebruiken school- en vaktaal.",
    uitleg: "Voetnoot:\nRelevante vakterminologie. Rekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nVaktaal zoals domeinspecifieke terminologie, symbolen.",
  },
  {
    code: "1A.ST.13.04",
    competentieNr: 13,
    competentie: "13. Leercompetenties met inbegrip van onderzoekscompetenties, innovatiedenken, creativiteit, probleemoplossend en kritisch denken, systeemdenken, informatieverwerking en samenwerken",
    nummer: "13.04",
    soort: "standaard",
    omschrijving: "De leerlingen zoeken doelgericht informatie in diverse bronnen en verwerken die op een kritische en systematische manier.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDigitale en niet-digitale bronnen zoals personen, tijdschriften, encyclopedieën, boeken, audiovisueel materiaal, websites.\nDe bronnen kunnen worden aangereikt of zelf worden opgezocht en worden beoordeeld op bruikbaarheid en betrouwbaarheid.\nHet kritisch en systematisch verwerken van informatie veronderstelt het beoordelen ervan op bruikbaarheid, betrouwbaarheid en correctheid.\nVerwerken van informatie in functie van het vooropgestelde doel, zoals het beantwoorden van een (onderzoeks)vraag.",
  },
  {
    code: "1A.ST.15.01",
    competentieNr: 15,
    competentie: "15. Ontwikkeling van initiatief, ambitie, ondernemingszin en loopbaancompetenties",
    nummer: "15.01",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen bewust hun studie- of beroepskeuzeproces.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nDoorlopen van een studie- of beroepskeuzeproces zoals met behulp van de keuzetaken oriënteren, zelfconceptverheldering, exploreren in de breedte, exploreren in de diepte, studiekeuzenabijheid, binding.",
  },
  {
    code: "1A.ST.15.02",
    competentieNr: 15,
    competentie: "15. Ontwikkeling van initiatief, ambitie, ondernemingszin en loopbaancompetenties",
    nummer: "15.02",
    soort: "standaard",
    omschrijving: "De leerlingen genereren creatieve ideeën om een probleem op te lossen en bespreken de uitvoerbaarheid ervan aan de hand van criteria.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nIdeeën genereren zoals door middel van ideegeneratietechnieken (bv. door middel van een brainstorm, mindmap) en ideeselectietechnieken (bv. van divergent naar convergent denken).\nAangereikte of zelf bepaalde criteria zoals meerwaarde, tijd, middelen, technische haalbaarheid, risico’s, ethische principes, duurzaamheidsprincipes.",
  },
  {
    code: "1A.ST.16.01",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.01",
    soort: "standaard",
    omschrijving: "De leerlingen beschrijven kunst- en cultuuruitingen vanuit eigen waarneming.",
    uitleg: "Memorie:\nKunstuitingen zoals dans, theater, film, game, graffiti, kledij, landschap, lied. Cultuuruitingen zoals sociale gewoonten, voorstellingen, rituelen, tradities, uitdrukkingen. Eigen waarneming zoals ervaren en beleven, memoriseren en herkennen en zintuiglijk waarnemen.",
  },
  {
    code: "1A.ST.16.02",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.02",
    soort: "standaard",
    omschrijving: "De leerlingen brengen kunst- en cultuuruitingen in verband met de context waarin ze voorkomen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nContext zoals tijd, ruimte, maatschappelijke context.",
  },
  {
    code: "1A.ST.16.03",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.03",
    soort: "standaard",
    omschrijving: "De leerlingen reflecteren over eigen beleving bij uiteenlopende kunst- en cultuuruitingen.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.",
  },
  {
    code: "1A.ST.16.04",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.04",
    soort: "standaard",
    omschrijving: "De leerlingen lichten toe hoe een kunstwerk vanuit vorm en inhoud betekenis geeft.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nInhoud:\nonderwerp bijvoorbeeld geboorte, dood, liefde, geschiedenis, het leven, het alledaagse, rituelen;\nbedoeling bijvoorbeeld decoreren, entertainen, praktisch gebruik, informeren, confirmeren, revolteren.\nVorm zoals bouwstenen, technieken, materialen afhankelijk van het gekozen kunstwerk en de gekozen expressievorm zoals beeld, muziek, drama, dans of audiovisuele media, apart of gecombineerd. In het geval van:\nBeeld\n- Bouwstenen zoals compositie, kleur, licht, lijn, ruimte, textuur, vorm.\n- Technieken zoals boetseren, fotograferen, maquettes maken, met textiel werken, schilderen.\n- Materialen zoals klei, licht, papier, recuperatiematerialen, steen, verf.\nMuziek\n- Bouwstenen zoals dynamiek, klankkleur, melodie, ritme, samenklank, structuur, tempo, vorm.\n- Technieken zoals body percussion, improvisatie, samenzang.\n- Materialen zoals instrumenten, lichaam, stem, voorwerpen.\nDrama\n- Bouwstenen zoals rol, ruimte, structuur, samenspel, tijd.\n- Technieken zoals clownerie, figurentheater, improvisatie, mime, teksttheater.\n- Materialen zoals decor, geluid, kostuums, lichaam, taal.\nDans\n- Bouwstenen zoals kracht, ruimte, relatie, tijd.\n- Technieken zoals bewegingsreeks, choreografie, dansexpressie, dansimprovisatie.\n- Materialen zoals decor, geluid, lichaam, voorwerpen.\nAudiovisuele media\n- Bouwstenen zoals camerabeweging, geluid, kader, licht, montage.\n- Technieken zoals montage, opname, sonorisatie.\n- Materialen zoals microfoon, montageunit, smartphone.",
  },
  {
    code: "1A.ST.16.05",
    competentieNr: 16,
    competentie: "16. Cultureel bewustzijn en culturele expressie",
    nummer: "16.05",
    soort: "standaard",
    omschrijving: "De leerlingen doorlopen een artistiek-creatief proces vanuit verbeelding.",
    uitleg: "Voetnoot:\nRekening houdend met de ontwikkeling van leerlingen en de context waarin het minimumdoel aan bod komt.\n\nMemorie:\nBij het doorlopen van een artistiek-creatief proces kan je denken aan:\n- het selecteren van ideeën zoals bij eigen gedachten en gevoelens stilstaan, artistieke werken bestuderen, indrukken of objecten verzamelen;\n- het koppelen van de eigen bedoeling aan vormgeving via methodes zoals trial and error, try-out;\n- het gebruiken van kunsteigen technieken;\n- het voorstellen of presenteren.",
  },
  {
    code: "1A.FR.17.01",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F1",
    soort: "freinet",
    omschrijving: "De leerlingen passen de principes van de Freinetpedagogie toe.",
    uitleg: "De leerlingen passen de principes van de Freinetpedagogie toe.",
  },
  {
    code: "1A.FR.17.02",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F2",
    soort: "freinet",
    omschrijving: "De leerlingen passen de principes van democratische besluitvorming toe op klasniveau (klasraad) en op schoolniveau (leerlingenraad/schoolraad).",
    uitleg: "De leerlingen passen de principes van democratische besluitvorming toe op klasniveau (klasraad) en op schoolniveau (leerlingenraad/schoolraad).",
  },
  {
    code: "1A.FR.17.03",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F3",
    soort: "freinet",
    omschrijving: "De leerlingen passen de basisbeginselen van coöperatief samenwerken toe op klas- en schoolniveau.",
    uitleg: "De leerlingen passen de basisbeginselen van coöperatief samenwerken toe op klas- en schoolniveau.",
  },
  {
    code: "1A.FR.17.04",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F4",
    soort: "freinet",
    omschrijving: "De leerlingen passen de basisbeginselen van conflicthantering toe op klas- en schoolniveau.",
    uitleg: "De leerlingen passen de basisbeginselen van conflicthantering toe op klas- en schoolniveau.",
  },
  {
    code: "1A.FR.17.05",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F5",
    soort: "freinet",
    omschrijving: "De leerlingen evalueren zelf uitgevoerde burgerschapsprojecten kritisch met behulp van richtvragen.",
    uitleg: "De leerlingen evalueren zelf uitgevoerde burgerschapsprojecten kritisch met behulp van richtvragen.",
  },
  {
    code: "1A.FR.17.06",
    competentieNr: 17,
    competentie: "17. Freinetvaardigheden",
    nummer: "F6",
    soort: "freinet",
    omschrijving: "De leerlingen onderzoeken verschillende kennis- en vaardigheidsdomeinen (*) van de samenleving en de waarde van elk van deze domeinen met het oog op de ontdekking van hun eigen interessegebieden.",
    uitleg: "(*) Het betreft de volgende deelgebieden:\n(1) natuurexploratie, -zorg en -beheer;\n(2) handvaardigheid, bouw en techniek;\n(3) kennisverwerving en -verdieping;\n(4) experimenteren, wetenschappelijk onderzoek en innovatiedenken;\n(5) digitale competentie, mediawijsheid, moderne technologieën;\n(6) expressie, artistieke vormgeving, creatie, ontwerp;\n(7) andere (bijvoorbeeld welzijn, zorg, sport en beweging).",
  },
];
