// AUTO-GEGENEREERD via scripts/extract_rubrics.py
// uit docs/reference/rubrics_overzicht.xlsx — niet met de hand aanpassen.
import type { Rubriek } from "./types";

export const rubrieken: Rubriek[] = [
  {
    id: "rbr-1A-1",
    cursus: "Cultuur",
    stroom: "1A",
    naam: "RUBRIC 1: KUNST-CULTUURHOUDING",
    doelen: ["16.01", "16.02", "16.04", "16.03", "02.13", "08.03", "03.09", "07.03", "05.01", "07.04", "08.02", "08.04"],
    criteria: {
      blauw: "Je hebt een open en nieuwsgierige houding voor kunst en cultuur. Je kijkt en luistert aandachtig, stelt vragen, vertelt wat je opmerkt en wat het met je doet, legt verbanden met de tijd, samenleving en cultuur en luistert respectvol naar andere meningen en interpretaties.",
      groen: "Je staat open voor kunst en cultuur. Je kan vertellen wat je opmerkt, wat je ervan vindt en waarom. Je kan eenvoudige verbanden leggen met de context en gaat respectvol om met andere meningen en culturen.",
      geel: "Je probeert open te staan voor kunst en cultuur. Je kan enkele dingen vertellen over wat je ziet, leest, hoort of ervaart, maar verbanden leggen met de context gaat niet zonder hulp en je hebt het moeilijk om een mening te vormen.",
      rood: "Je hecht geen waarde aan kunst en cultuur. Je vertelt niet wat je opmerkt of ervaart, verbanden leg je amper of nooit en je gaat niet respectvol om met andere perspectieven.",
    },
    leerlijn: "1ste graad: Je leert je openstellen voor verschillende vormen van kunst en cultuur. Je vertrekt vanuit je eigen waarneming en beleving: Wat zie, hoor, lees of ervaar ik? Wat doet dit met mij? Geleidelijk leer je je mening uitleggen, eenvoudige verbanden leggen met de context en luisteren naar andere interpretaties.\n\nNaar de 2de graad: Je gaat kunst en cultuur zelfstandiger en kritischer onderzoeken. Je leert je interpretatie beter onderbouwen, correcte kunst- en cultuurbegrippen gebruiken en nadenken over de betekenis en maatschappelijke rol van kunst. Je leert ook duidelijker onderscheid maken tussen de bedoeling van een maker en je eigen reactie op het werk.\n\nVerdieping naar 2e graad (badgeboekje): Er wordt verwacht dat leerlingen kunstenaars en hun denk- en werkwijze kunnen interpreteren, kunst in relatie tot de samenleving begrijpen en hun mening met relevante begrippen onderbouwen.",
  },
  {
    id: "rbr-1A-2",
    cursus: "Cultuur",
    stroom: "1A",
    naam: "RUBRIC 2: CREËREN IN VERSCHILLENDE DOMEINEN",
    doelen: ["02.06", "BG04.02", "04.02", "06.04", "06.05", "06.07", "06.09"],
    criteria: {
      blauw: "Je zet jouw ideeën zelfstandig en creatief om in un werk. Je experimenteert, maakt bewuste keuzes en gebruikt passende materialen, technieken, digitale middelen en/of vormen.",
      groen: "Je bent gemotiveerd om je ideeën vorm te geven. Je gebruikt passende materialen, technieken, digitale middelen en/of vormen met de eventuele nodige hulp.",
      geel: "Je probeert jouw ideeën om te zetten in un creatie, maar hebt nog veel hulp nodig bij het kiezen of gebruiken van materialen, technieken, digitale middelen of vormen.",
      rood: "Je komt niet tot creatie. Je denkt niet na over je keuze in materialen, technieken, digitale middelen en/of vormen lukt nog moeilijk.",
    },
    leerlijn: "1ste graad: Je maakt kennis met verschillende kunst- en expressiedomeinen en probeert uiteenlopende materialen, technieken en middelen uit. Je leert ontdekken welke mogelijkheden bij jouw idee passen. In het begin mag je hierbij nog ondersteuning krijgen; geleidelijk probeer je steeds zelfstandiger keuzes te maken.\n\nNaar de 2de graad: Experimenteren wordt belangrijker. Je gebruikt materialen en technieken niet alleen omdat ze worden aangereikt, maar onderzoekt bewust welke techniek, vorm of medium het beste past bij jouw artistieke bedoeling. Je ontwikkelt zo geleidelijk un persoonlijkere manier van creëren.\n\nVerdieping naar 2e graad (handleiding): De Cultuurhandleiding verwacht expliciet dat leerlingen expressiemogelijkheden verkennen door te experimenteren met materiaal en technieken uit diverse kunstvormen.",
  },
  {
    id: "rbr-1A-3",
    cursus: "Cultuur",
    stroom: "1A",
    naam: "RUBRIC 3 - PROCES: VAN CONCEPT NAAR PRODUCT",
    doelen: ["16.01", "16.05"],
    criteria: {
      blauw: "Je werkt zelfstandig van inspiratie naar un eigen eindproduct. Je kijkt aandachtig naar kunst en cultuur en gebruikt waarnemingen als inspiratie. Je bedenkt un eigen idee, probeert verschillende mogelijkheden uit, stuurt jouw werk bij en werkt jouw idee uit tot un eigen product.",
      groen: "Je kan jouw proces aantonen en komt tot un goed eindproduct. Je beschrijft wat je opmerkt in kunst en cultuur, bedenkt un eigen idee, probeert mogelijkheden uit en werkt jouw idee stap voor stap uit tot un product.",
      geel: "Je hebt nog (te) veel hulp nodig om van idee naar un eigen eindproduct toe te werken. Je kan vertellen wat je opmerkt en hebt un eigen idee, maar hebt soms hulp nodig om mogelijkheden uit te proberen, keuzes te maken of jouw idee verder uit te werken.",
      rood: "Je kwam niet of amper tot un eindproduct. Je slaagt er niet in om un creatief proces af te leggen en van un concept un eindproduct te maken.",
    },
    leerlijn: "1ste graad: Je leert dat un creatief werk niet alleen draait om het eindproduct. Je probeert stap voor stap van waarneming en inspiratie naar un eigen idee en vervolgens naar un product te gaan. Je leert verschillende mogelijkheden uitproberen en je oorspronkelijke idee aanpassen wanneer iets niet werkt.\n\nNaar de 2de graad: Je creatieve proces wordt zelfstandiger en bewuster. Je leert un duidelijk concept ontwikkelen, keuzes onderzoeken en beargumenteren, experimenteren, je ontwerp bijsturen en achteraf uitleggen hoe je product tot stand gekomen is. Het proces moet steeds beter zichtbaar en bespreekbaar worden.\n\nVerdieping naar 2e graad (leerplan): Het leerplan stelt expliciet dat de creatieve activiteit of het proces belangrijker is dan enkel het eindresultaat, en dat creatief leren un proces van ontdekken en transformeren is. In de tweede graad wordt dit nog explicieter: concept – ontwerp – uitvoering – bijsturing – afwerking moeten zorgvuldig doorlopen en geduid worden.",
  },
  {
    id: "rbr-1A-4",
    cursus: "Cultuur",
    stroom: "1A",
    naam: "RUBRIC 4: AFWERKING",
    doelen: ["16.05"],
    criteria: {
      blauw: "Je werkt jouw creatie zeer zorgvuldig af. Je hebt oog voor details, controleert jouw werk, verbetert waar nodig en zorgt ervoor dat alle onderdelen samen un sterk en verzorgd geheel vormen.",
      groen: "Je werkt jouw creatie verzorgd af. Je besteedt aandacht aan details, controleert jouw werk en past nog verbeteringen toe voordat je het als klaar beschouwt.",
      geel: "Het lukt je nog niet jouw creatie verzorgd af te werken. Sommige onderdelen of details ontbreken of zijn nog niet volledig. Je hebt soms hulp nodig om te zien wat je nog kan verbeteren.",
      rood: "Je werkt jouw creatie niet af. jouw werk is nog onvolledig of slordig en je besteedt nog te weinig/geen aandacht aan details en verbeteringen.",
    },
    leerlijn: "1ste graad: Je leert dat un eerste versie niet noodzakelijk un eindversie is. Je controleert je werk, merkt onafgewerkte onderdelen op en leert tijd maken voor details en verbeteringen. Het doel is dat je niet tevreden bent met “het is klaar”, maar leert nadenken over “is het zo goed mogelijk afgewerkt?”\n\nNaar de 2de graad: Afwerking wordt steeds meer gekoppeld aan je artistieke bedoeling en techniek. Je leert niet alleen netjes of volledig werken, maar ook beoordelen of de gekozen afwerking jouw idee, boodschap of vorm versterkt. Je beheerst de gekozen technieken steeds zelfstandiger en verfijnt je product bewust.\n\nVerdieping naar 2e graad (handleiding): De tweede-graadhandleiding verwacht dan ook kwaliteitsvolle opdrachten waarin leerlingen alle stappen zorgvuldig doorlopen, de essentie van hun idee of techniek overbrengen en oog hebben voor de afwerking.",
  },
  {
    id: "rbr-1B-1",
    cursus: "Cultuur",
    stroom: "1B",
    naam: "RUBRIC BASISGELETTERDHEID – DIGITAAL CREËREN",
    doelen: ["BG04.02"],
    criteria: {
      blauw: "Je gebruikt de basisfuncties van een digitale toepassing zelfstandig en doelgericht. Je kiest passende functies en gebruikt ze om een verzorgde digitale inhoud te maken.",
      groen: "Je gebruikt de nodige basisfuncties van een digitale toepassing om een digitale inhoud te maken. Je kan dit meestal zelfstandig.",
      geel: "Je kan enkele basisfuncties van een digitale toepassing gebruiken, maar je hebt nog regelmatig hulp nodig om een digitale inhoud te maken.",
      rood: "Je kan de nodige basisfuncties van een digitale toepassing nog niet gebruiken om een digitale inhoud te maken. Ook met hulp lukt dit nog moeilijk.",
    },
    leerlijn: "1ste graad: Je leert de basisfuncties van digitale toepassingen gebruiken om zelf digitale inhoud te creëren. Je leert bijvoorbeeld tekst invoeren en vormgeven, afbeeldingen toevoegen of bewerken, dia's opmaken, eenvoudige audio of video gebruiken en je werk opslaan. Je hoeft niet alle functies van een programma te kennen: je leert vooral de functies gebruiken die je nodig hebt voor de opdracht.\n\nNaar de 2de graad: Je wordt zelfstandiger in het kiezen en gebruiken van digitale toepassingen. Waar je in de 1ste graad vooral de basisfunctionaliteiten leert gebruiken, wordt in de 2de graad verwacht dat je courante functionaliteiten van vergelijkbare toepassingen kunt inzetten om verschillende soorten digitale inhoud te creëren, zoals tekst, geluid, grafische en audiovisuele bestanden.\n\nSamenhang met leerlijn: In de 1ste graad ligt de nadruk op ontdekken, ervaren en leren creëren, waarna leerlingen in de 2de graad zelfstandiger en bewuster gaan werken.",
  },
  {
    id: "rbr-1B-2",
    cursus: "Cultuur",
    stroom: "1B",
    naam: "RUBRIC 1: KUNST-CULTUURHOUDING",
    doelen: ["16.01", "16.02", "16.04", "16.03", "FR1", "FR3", "02.12", "03.08", "05.01", "07.03", "07.04"],
    criteria: {
      blauw: "Je bent nieuwsgierig naar kunst en cultuur. Je kijkt en luistert aandachtig, stelt vragen en legt uit wat je ervaart en waarom. Je legt verbanden met de context en denkt na over de betekenis van een kunstwerk. Je luistert naar andere meningen en gaat respectvol en constructief in gesprek over verschillen.",
      groen: "Je staat open voor kunst en cultuur. Je vertelt wat je ziet, hoort, leest of ervaart en wat je daarvan vindt. Je legt eenvoudige verbanden met de context. Je luistert naar andere meningen en gaat respectvol om met verschillen.",
      geel: "Je probeert soms open te staan voor kunst en cultuur. Met hulp kan je vertellen wat je ziet, hoort, leest of ervaart en wat je daarvan vindt. Je probeert soms naar andere meningen te luisteren en respectvol met verschillen om te gaan.",
      rood: "Je toont weinig interesse in kunst en cultuur. Je vertelt niet of nauwelijks wat je ziet, hoort, leest of ervaart. Je vindt het moeilijk om naar andere meningen te luisteren en respectvol met verschillen om te gaan.",
    },
    leerlijn: "1ste graad B-stroom: Je leert verschillende vormen van kunst en cultuur ontdekken en ervaren. Je vertrekt vanuit concrete vragen: Wat zie, hoor, lees of ervaar ik? Wat valt mij op? Wat doet dit met mij? Wat vind ik ervan? Je leert hierover vertellen en eenvoudige verbanden leggen met de omgeving, tijd, cultuur of samenleving. Je ontdekt dat andere mensen iets anders kunnen ervaren of denken en leert hier respectvol mee omgaan.\n\nNaar de 2de graad: Je leert kunst en cultuur steeds zelfstandiger onderzoeken. Je gaat verder dan vertellen wat je ziet of voelt: je leert uitleggen waarom je iets vindt, verbanden leggen met de context en nadenken over vorm, inhoud en betekenis. Je leert je eigen mening beter onderbouwen en respectvol in gesprek gaan met mensen die een andere mening of achtergrond hebben.\n\nSamenhang met leerlijn: In de eerste graad ligt de nadruk op ontdekken en ervaren, terwijl in de tweede graad meer zelfstandigheid, onderzoek en onderbouwing wordt verwacht.",
  },
  {
    id: "rbr-1B-3",
    cursus: "Cultuur",
    stroom: "1B",
    naam: "RUBRIC 2: CREËREN IN VERSCHILLENDE DOMEINEN",
    doelen: ["02.05", "04.02", "06.04", "06.05", "06.07", "06.09"],
    criteria: {
      blauw: "Je zet jouw ideeën zelfstandig en creatief om in un eigen werk. Je probeert verschillende mogelijkheden uit en kiest bewust passende materialen, technieken, digitale middelen en/of vormen. Je kan uitleggen waarom je deze keuzes hebt gemaakt.",
      groen: "Je zet jouw ideeën om in un eigen creatie. Je gebruikt passende materialen, technieken, digitale middelen en/of vormen. Met beperkte hulp maak je keuzes die passen bij jouw idee en de opdracht.",
      geel: "Je probeert jouw idee vorm te geven. Je gebruikt enkele materialen, technieken, digitale middelen en/of vormen, maar hebt nog te veel hulp nodig om ze te kiezen of te gebruiken.",
      rood: "Je komt niet of nauwelijks tot un eigen creatie. Je probeert materialen, technieken, digitale middelen en/of vormen niet uit. Ook met hulp lukt het moeilijk om jouw idee vorm te geven.",
    },
    leerlijn: "1ste graad B-stroom: Je maakt kennis met verschillende manieren om jezelf creatief uit te drukken, bijvoorbeeld met taal, beeld, vorm, digitale middelen en verschillende materialen en technieken. Je probeert mogelijkheden uit en ontdekt wat je nodig hebt om jouw idee vorm te geven. Je mag hierbij ondersteuning krijgen. Geleidelijk leer je zelf materialen, technieken en middelen kiezen en gebruiken.\n\nNaar de 2de graad: Je gaat steeds zelfstandiger creëren en experimenteren. Je probeert niet alleen technieken of materialen uit omdat ze worden aangereikt, maar leert nadenken over welke mogelijkheden het beste passen bij wat je wilt maken of uitdrukken. Je leert bewuster keuzes maken en deze keuzes uitleggen.",
  },
  {
    id: "rbr-1B-4",
    cursus: "Cultuur",
    stroom: "1B",
    naam: "RUBRIC 3 - PROCES: VAN CONCEPT NAAR PRODUCT",
    doelen: ["16.05"],
    criteria: {
      blauw: "Je werkt zelfstandig van un eigen idee naar un eindproduct. Je probeert verschillende mogelijkheden uit, maakt bewuste keuzes en past je werk aan wanneer dat nodig is. Je kan duidelijk uitleggen welke stappen je hebt gezet en hoe jouw idee tijdens het maken veranderd is.",
      groen: "Je werkt stap voor stap van un eigen idee naar un eindproduct. Je probeert mogelijkheden uit, maakt keuzes en past je werk aan wanneer dat nodig is. Je kan met beperkte hulp tonen hoe je te werk bent gegaan.",
      geel: "Je hebt un idee en probeert eraan te werken, maar hebt nog te veel hulp nodig. Je slaat soms stappen over of vindt het moeilijk om mogelijkheden uit te proberen, keuzes te maken of je werk aan te passen.",
      rood: "Je komt niet of nauwelijks tot un eigen idee of eindproduct. Je doorloopt de verschillende stappen van het creatieve proces niet, ook niet met hulp.",
    },
    leerlijn: "1ste graad B-stroom: Je leert dat creëren uit verschillende stappen bestaat. Je vertrekt vanuit je verbeelding en bedenkt wat je wilt maken. Daarna probeer je mogelijkheden uit, maak je keuzes en werk je jouw idee stap voor stap uit. Wanneer iets niet lukt, leer je iets anders proberen of je idee aanpassen. Het proces is dus even belangrijk als het eindproduct.\n\nNaar de 2de graad: Je leert je creatieve proces steeds zelfstandiger en bewuster aanpakken. Je ontwikkelt un duidelijker idee of concept, onderzoekt verschillende mogelijkheden, experimenteert en stuurt je werk bij. Je leert ook beter uitleggen welke keuzes je hebt gemaakt en hoe jouw oorspronkelijke idee tijdens het proces veranderd is.",
  },
  {
    id: "rbr-1B-5",
    cursus: "Cultuur",
    stroom: "1B",
    naam: "RUBRIC 4: AFWERKING",
    doelen: ["16.05"],
    criteria: {
      blauw: "Je werkt jouw creatie zeer zorgvuldig af. Je hebt oog voor details, controleert jouw werk, verbetert waar nodig en zorgt ervoor dat alle onderdelen samen un sterk en verzorgd geheel vormen.",
      groen: "Je werkt jouw creatie verzorgd af. Je besteedt aandacht aan details, controleert jouw werk en past nog verbeteringen toe voordat je het als klaar beschouwt.",
      geel: "Het lukt je nog niet jouw creatie verzorgd af te werken. Sommige onderdelen of details ontbreken of zijn nog niet volledig. Je hebt soms hulp nodig om te zien wat je nog kan verbeteren.",
      rood: "Je werkt jouw creatie niet af. jouw werk is nog onvolledig of slordig en je besteedt nog te weinig/geen aandacht aan details en verbeteringen.",
    },
    leerlijn: "1ste graad: Je leert dat un eerste versie niet noodzakelijk un eindversie is. Je controleert je werk, merkt onafgewerkte onderdelen op en leert tijd maken voor details en verbeteringen. Het doel is dat je niet tevreden bent met “het is klaar”, maar leert nadenken over “is het zo goed mogelijk afgewerkt?”\n\nNaar de 2de graad: Afwerking wordt steeds meer gekoppeld aan je artistieke bedoeling en techniek. Je leert niet alleen netjes of volledig werken, maar ook beoordelen of de gekozen afwerking jouw idee, boodschap of vorm versterkt. Je beheerst de gekozen technieken steeds zelfstandiger en verfijnt je product bewust.\n\nVerdieping naar 2e graad (handleiding): De tweede-graadhandleiding verwacht dan ook kwaliteitsvolle opdrachten waarin leerlingen alle stappen zorgvuldig doorlopen, de essentie van hun idee of techniek overbrengen en oog hebben voor de afwerking.",
  },
  {
    id: "rbr-2A-1",
    cursus: "Cultuur",
    stroom: "2A",
    naam: "RUBRIC 1: KUNST-CULTUURHOUDING",
    doelen: ["16.01", "16.02", "16.03", "13.03", "05.01", "U04.01.04", "07.03", "07.04", "08.02", "08.03", "08.04"],
    criteria: {
      blauw: "Je staat nieuwsgierig en kritisch tegenover verschillende vormen van kunst en cultuur. Je kijkt, luistert en onderzoekt aandachtig, legt verbanden met context en samenleving en gebruikt passende kunstbegrippen om je eigen interpretatie te onderbouwen. Je staat open for andere perspectieven en kan op un respectvolle manier in discussie gaan over kunst en cultuur.",
      groen: "Je staat open for verschillende vormen van kunst en cultuur. Je kan uitleggen wat je ziet, wat het met je doet en welke betekenis je eraan geeft. Je legt verbanden met de context en gebruikt passende kunstbegrippen.",
      geel: "Je probeert je open te stellen for kunst en cultuur, maar jouw waarneming en interpretatie blijven soms oppervlakkig. Je hebt nog hulp nodig om verbanden te leggen, jouw mening te onderbouwen of passende kunstbegrippen te gebruiken.",
      rood: "Je toont weinig interesse for kunst en cultuur. Je hebt geen onderzoekende houding tegenover kunst- en cultuuruitingen. Je vormt geen eigen mening over kunst en cultuur.",
    },
    leerlijn: "Van 1ste naar 2de graad: In de 1ste graad leerde je je openstellen for kunst en cultuur en vertrekken vanuit je eigen waarneming en beleving. In de 2de graad ga je un stap verder: je onderzoekt kunst- en cultuuruitingen kritischer, legt zelfstandig verbanden met tijd, ruimte en samenleving en onderzoekt hoe vorm en inhoud betekenis creëren. Je leert je eigen interpretatie onderbouwen met correcte kunst- en cultuurbegrippen en maakt steeds beter onderscheid tussen de bedoeling van de maker en je eigen reactie.\n\nNaar de 3de graad: Je groeit verder naar un zelfstandige, kritische kunstbeschouwer die verschillende interpretaties kan onderzoeken, kunst in un bredere maatschappelijke en culturele context kan plaatsen en hierover genuanceerd in dialoog kan gaan.\n\nVerdieping (badgeboekje): Inzicht verwerven in kunstenaars en hun denk- en werkwijze, de maatschappelijke/emanciperende rol van kunst begrijpen, onderscheid maken tussen de boodschap van de maker en de eigen reactie en de eigen mening met relevante begrippen onderbouwen.",
  },
  {
    id: "rbr-2A-2",
    cursus: "Cultuur",
    stroom: "2A",
    naam: "RUBRIC 2: CREËREN IN VERSCHILLENDE DOMEINEN",
    doelen: ["02.07", "04.02", "15.02", "U04.01.02", "U04.01.03"],
    criteria: {
      blauw: "Je zet jouw ideeën zelfstandig om in un persoonlijk creatie. Je experimenteert bewust met verschillende materialen, technieken en kunstvormen en maakt doordachte keuzes die idee, boodschap of emoties versterken.",
      groen: "Je zet jouw ideeën om in un eigen creatie. Je experimenteert met materialen en technieken en maak passende keuzes om je idee vorm te geven.",
      geel: "Het lukt je nog niet om creatieve ideeën vorm te geven. Je experimenteert nog te weinig en hebt regelmatig hulp nodig bij het kiezen en gebruiken van materialen en technieken.",
      rood: "Je komt niet of nauwelijks tot un eigen creatie. Je experimenteert niet met materialen, technieken of mogelijkheden en het lukt je niet om jouw ideeën vorm te geven.",
    },
    leerlijn: "Van 1ste naar 2de graad: In de 1ste graad maakte je kennis met verschillende kunst- en expressiedomeinen en probeerde je uiteenlopende materialen en technieken uit. In de 2de graad wordt experimenteren doelgerichter. Je onderzoekt welke materialen, technieken, bouwstenen en kunstvormen het beste passen bij wat je wilt uitdrukken. Je maakt steeds zelfstandiger artistieke keuzes en leert deze ook uitleggen.\n\nNaar de 3de graad: Je ontwikkelt steeds meer un persoonlijke artistieke taal. Experimenteren wordt niet alleen un manier om technieken te leren kennen, maar un middel om un eigen boodschap, idee, stijl of visie vorm te geven.\n\nVerdieping (badgeboekje): Leerlingen moeten expressiemogelijkheden verkennen door te experimenteren met materiaal en technieken uit verschillende kunstvormen.",
  },
  {
    id: "rbr-2A-3",
    cursus: "Cultuur",
    stroom: "2A",
    naam: "RUBRIC 3 - PROCES: VAN CONCEPT NAAR PRODUCT",
    doelen: ["13.02", "15.02", "16.04", "U04.01.01", "U04.01.04", "U04.01.03 (bij groepswerk)"],
    criteria: {
      blauw: "Je doorloopt je creatieve proces zelfstandig en bewust. Je ontwikkelt un eigen concept, onderzoekt en experimenteert, maakt bewuste keuzes, je stuurt je werk bij en kan uitleggen hoe je idee tijdens het proces geëvolueerd is.",
      groen: "Je kan je creatieve proces aantonen. Je werkt van un eigen concept via ontwerp en experiment naar un eindproduct, stuurt bij waar nodig en kan je belangrijkste keuzes uitleggen.",
      geel: "Je creatieve proces is onvoldoende zichtbaar, je hebt nog veel hulp nodig om je concept te ontwikkelen, te experimenteren, keuzes te maken of je werk bij te sturen.",
      rood: "Je creatieve proces is niet zichtbaar. Je gaat te snel van opdracht naar eindproduct en slaat belangrijke stappen over zoals: concept, ontwerp, experiment en bijsturing over.",
    },
    leerlijn: "Van 1ste naar 2de graad: In de 1ste graad leerde je dat creëren meer is dan alleen un eindproduct maken. In de 2de graad wordt je creatieve proces bewuster en zelfstandiger. Je ontwikkelt un concept, onderzoekt mogelijkheden, maakt un ontwerp, experimenteert, voert uit, evalueert en stuurt bij. Je houdt je proces zichtbaar en kunt uitleggen waarom je bepaalde keuzes hebt gemaakt en hoe je idee onderweg veranderde.\n\nNaar de 3de graad: Je leert steeds zelfstandiger un artistiek proces sturen. Je gebruikt experiment en feedback bewust om je werk inhoudelijk en artistiek te verdiepen and kunt kritisch reflecteren over je eigen ontwikkeling als maker.\n\nVerdieping (badgeboekje): Het badgeboekje stelt expliciet dat het concept even belangrijk is als het eindresultaat en dat leerlingen concept → ontwerp → uitvoering → bijsturing → afwerking zorgvuldig moeten doorlopen én duiden.",
  },
  {
    id: "rbr-2A-4",
    cursus: "Cultuur",
    stroom: "2A",
    naam: "RUBRIC 4: AFWERKING",
    doelen: ["16.04", "U04.01.01", "U04.01.02"],
    criteria: {
      blauw: "Je werk is kwaliteitsvol en doordacht. je beheerst de gekozen technieken, hebt oog for details and blijft je werk kritisch bekijken en verfijnen. De afwerking versterkt je oorspronkelijke idee of boodschap.",
      groen: "Je komt tot un verzorgd en afgewerkt product. Je past de gekozen technieken correct toe, hebt aandacht for details and verbetert je werk waar nodig.",
      geel: "Je product is deels afgewerkt, maar mist nog zorg, detail of technische beheersing. Je hebt soms hulp nodig om te zien wat je nog kan verbeteren.",
      rood: "Je product is niet afgewerkt. Onderdelen ontbreken of zijn slordig uitgevoerd and je besteedt onvoldoende aandacht aan techniek, details en verbetering.",
    },
    leerlijn: "Van 1ste naar 2de graad: In de 1ste graad leerde je je werk controleren, details verzorgen en verbeteringen uitvoeren. In de 2de graad gaat afwerking verder dan “netjes werken”. Je leert technieken steeds beter beheersen en beoordeelt kritisch of materiaal, techniek en afwerking passen bij je concept. Je verfijnt je werk totdat vorm, techniek en inhoud un samenhangend geheel vormen.\n\nNaar de 3de graad: Je gebruikt technische beheersing en afwerking steeds bewuster als artistieke keuze. De manier waarop je un werk uitvoert en afwerkt wordt un onderdeel van jouw persoonlijke artistieke taal en versterkt de betekenis van jouw werk.\n\nVerdieping (badgeboekje): Kwaliteitsvolle opdrachten moeten de verschillende processtappen zorgvuldig doorlopen, de essentie van het idee of de techniek overbrengen én oog hebben for afwerking.",
  },
  {
    id: "rbr-1A-5",
    cursus: "Vrije Tekst",
    stroom: "1A",
    naam: "RUBRIC BASISGELETTERDHEID 1: lezen, luisteren, spreken en schrijven in het Nederlands",
    doelen: ["BG02.01", "BG02.02", "BG02.03"],
    criteria: {
      blauw: "Je begrijpt bij het lezen en luisteren vlot waarover een tekst gaat en haalt zelfstandig de belangrijke informatie eruit. Je spreekt en schrijft duidelijk en doelgericht en neemt actief deel aan eenvoudige gesprekken en schriftelijke communicatie.",
      groen: "Je begrijpt bij het lezen en luisteren waarover een eenvoudige tekst gaat en haalt de belangrijkste informatie eruit. Je kan in eenvoudige situaties duidelijk genoeg spreken en schrijven om je boodschap over te brengen. Je neemt deel aan eenvoudige gesprekken en schriftelijke communicatie, eventueel met hulpmiddelen.",
      geel: "Je begrijpt een deel van wat je leest of hoort, maar hebt nog regelmatig hulp nodig om het onderwerp of belangrijke informatie te vinden. Ook bij spreken, schrijven en communiceren heb je nog ondersteuning nodig om je boodschap duidelijk over te brengen.",
      rood: "Je vindt het nog moeilijk om te begrijpen waarover een eenvoudige tekst gaat of belangrijke informatie eruit te halen. Ook met hulp lukt het nog onvoldoende om een eenvoudige boodschap mondeling of schriftelijk over te brengen of deel te nemen aan eenvoudige communicatie.",
    },
    leerlijn: "1ste graad – basisgeletterdheid: Je leert de basisvaardigheden die je nodig hebt om het Nederlands functioneel te gebruiken. Bij eenvoudige, herkenbare teksten leer je bepalen waarover de tekst gaat en relevante informatie terugvinden. Je leert zelf een eenvoudige boodschap mondeling en schriftelijk overbrengen en deelnemen aan eenvoudige communicatie met anderen. Je mag hierbij ondersteunende middelen gebruiken. Voor schrijven verwachten we een eenvoudige tekststructuur, redelijk herkenbare samenhang, frequente woorden en concrete inhoud. Taalfouten zijn toegestaan zolang ze het begrijpen van je boodschap niet in de weg staan.\n\nVerdere ontwikkeling: Vanuit dit basisniveau leer je steeds zelfstandiger en doelgerichter lezen, luisteren, spreken en schrijven. Teksten worden gevarieerder en complexer en je leert informatie nauwkeuriger verwerken. Bij spreken en schrijven werk je verder aan structuur, samenhang, woordenschat, correctheid en het aanpassen van je taal aan doel, publiek en situatie.",
  },
  {
    id: "rbr-1A-6",
    cursus: "Vrije Tekst",
    stroom: "1A",
    naam: "RUBRIC BASISGELETTERDHEID 2: digitale vaardigheden",
    doelen: ["BG04.01"],
    criteria: {
      blauw: "Je communiceert zelfstandig en doelgericht met digitale toepassingen. Je kiest passende basisfuncties en gebruikt ze vlot om je boodschap duidelijk over te brengen en op digitale communicatie te reageren.",
      groen: "Je gebruikt de nodige basisfuncties van een digitale toepassing om doelgericht met anderen te communiceren. Je kan bijvoorbeeld een bericht versturen en beantwoorden en informatie delen. Je kan dit meestal zelfstandig.",
      geel: "Je kan enkele basisfuncties gebruiken om digitaal te communiceren, maar hebt nog regelmatig hulp nodig om bijvoorbeeld een bericht te versturen, te beantwoorden of informatie te delen.",
      rood: "Je kan de nodige basisfuncties van een digitale toepassing nog niet voldoende gebruiken om digitaal te communiceren. Ook met hulp lukt het nog moeilijk om een eenvoudige digitale boodschap te versturen of erop te reageren.",
    },
    leerlijn: "1ste graad – basisgeletterdheid: Je leert de basisfuncties van digitale toepassingen gebruiken om met anderen te communiceren. Je leert bijvoorbeeld een digitaal bericht opstellen, versturen en beantwoorden en informatie of een bestand delen. Je leert daarbij de functies gebruiken die je nodig hebt om je boodschap bij de juiste persoon of groep te krijgen. Het gaat niet om het beheersen van alle mogelijkheden van een programma, maar om functioneel en doelgericht digitaal kunnen communiceren.\n\nVerdere ontwikkeling: Vanuit dit basisniveau leer je steeds zelfstandiger verschillende digitale toepassingen gebruiken. Je leert bewuster kiezen welke toepassing en welke functies geschikt zijn voor je doel en situatie en houdt steeds meer rekening met de ontvanger en de manier waarop je digitaal communiceert.",
  },
  {
    id: "rbr-1A-7",
    cursus: "Vrije Tekst",
    stroom: "1A",
    naam: "RUBRIC 1: Motivatie en proces",
    doelen: ["02.07", "UD02.03", "03.04", "04.01", "04.04", "13.04", "15.01", "15.02", "16.05"],
    criteria: {
      blauw: "Je werkt zelfstandig en gemotiveerd aan je tekst. Je denkt actief na over feedback en tekstbesprekingen, gebruikt die doelgericht en herwerkt je tekst grondig waar nodig. Je blijft kritisch naar je eigen werk kijken en streeft naar de best mogelijke eindversie.",
      groen: "Je werkt gemotiveerd aan je tekst. Je leest en gebruikt feedback en tekstbesprekingen om je tekst te verbeteren en maakt waar nodig een herwerkte versie. Je werkt toe naar een verzorgde eindversie.",
      geel: "Je werkt aan je tekst, maar hebt nog veel aanmoediging of hulp nodig. Je probeert feedback en tekstbesprekingen te gebruiken, maar verwerkt die nog niet voldoende in een nieuwe versie.",
      rood: "Je werkt weinig of niet aan je tekst. Je gebruikt feedback en tekstbesprekingen niet of nauwelijks en herwerkt je tekst onvoldoende.",
    },
    leerlijn: "1ste graad: Je leert dat een goede tekst meestal niet in één keer ontstaat. Je leert een eerste versie schrijven, feedback ontvangen en je tekst bespreken. Daarna gebruik je die feedback om je tekst te verbeteren. Geleidelijk leer je zelfstandiger beslissen wat je moet aanpassen en werk je toe naar een verzorgde eindversie. Dit sluit rechtstreeks aan bij jullie bestaande leerlijn: leerlingen leren in de loop van de eerste graad wat het schrijfproces inhoudt en feedback en tekstbesprekingen doelgericht gebruiken.\n\nNaar de 2de graad: Je neemt steeds meer verantwoordelijkheid voor je eigen schrijfproces. Je wacht niet alleen op opmerkingen van de mentor, maar leert zelf kritisch naar je tekst kijken, gerichte feedback vragen, bruikbare feedback selecteren en bewust beslissen hoe je die verwerkt. Je werkt steeds zelfstandiger van een eerste versie naar een kwaliteitsvolle eindtekst.",
  },
  {
    id: "rbr-1A-8",
    cursus: "Vrije Tekst",
    stroom: "1A",
    naam: "RUBRIC 2: Samenhang",
    doelen: ["02.05", "02.11", "UD 02.01", "UD 02.04", "UD 02.10", "03.01", "03.03"],
    criteria: {
      blauw: "Je tekst vormt een sterk en logisch geheel. Je bouwt je tekst bewust op en verbindt ideeën, zinnen en alinea’s op een natuurlijke manier. Je structuur helpt de lezer om je boodschap vlot te begrijpen.",
      groen: "Je tekst is duidelijk en logisch opgebouwd. Je gebruikt een passende structuur, alinea’s en verbindende woorden waardoor de lezer je tekst goed kan volgen.",
      geel: "Je probeert je tekst logisch op te bouwen, maar hebt nog hulp nodig. Sommige ideeën, zinnen of alinea’s sluiten nog niet goed op elkaar aan.",
      rood: "Je tekst heeft nog weinig samenhang. Je ideeën staan niet in een logische volgorde en de opbouw is onduidelijk. De lezer kan je tekst moeilijk volgen.",
    },
    leerlijn: "1ste graad: Je leert dat een tekst meer is dan een verzameling losse zinnen. Je leert je ideeën ordenen en een herkenbare structuur gebruiken. Je gebruikt een titel, alinea’s, signaalwoorden en verwijswoorden om verbanden duidelijk te maken.\n\nNaar de 2de graad: Je bouwt langere en complexere teksten steeds zelfstandiger op. Je kiest een tekststructuur die past bij je tekstdoel en genre en gebruikt verbindingsmiddelen steeds bewuster. Je tekst wordt zo niet alleen begrijpelijk, maar ook vlot en natuurlijk leesbaar.",
  },
  {
    id: "rbr-1A-9",
    cursus: "Vrije Tekst",
    stroom: "1A",
    naam: "RUBRIC 3: taalzorg",
    doelen: ["02.10", "02.09", "03.03", "03.06", "03.07", "UD 02.07", "UD 02.08"],
    criteria: {
      blauw: "Je gebruikt taal bewust en zorgvuldig. Je controleert en verbetert zelfstandig je tekst en gebruikt een gevarieerde woordenschat en passende zinsbouw. Je past nieuwe taalkennis steeds beter toe in je eigen teksten.",
      groen: "Je schrijft verzorgd en past toe wat je geleerd hebt over spelling, grammatica, woordenschat en zinsbouw. Je controleert je tekst en verbetert fouten waar nodig.",
      geel: "Je probeert verzorgd te schrijven, maar maakt nog regelmatig fouten. Je hebt hulp nodig om fouten te herkennen en wat je geleerd hebt over taal toe te passen in je tekst.",
      rood: "Je besteedt nog weinig aandacht aan taalzorg. Je tekst bevat veel fouten in spelling, grammatica, woordkeuze en/of zinsbouw die je niet controleert of verbetert.",
    },
    leerlijn: "1ste graad: Je leert eerder en nieuwe taalkennis toepassen in je eigen teksten. Je leert letten op spelling, grammatica, woordkeuze en zinsbouw en gebruikt feedback en hulpmiddelen om fouten te herkennen en verbeteren. Het doel is niet meteen foutloos schrijven, maar dat je steeds bewuster met taal omgaat en eerdere leerstof opnieuw toepast.\n\nNaar de 2de graad: Je taalgebruik wordt zelfstandiger, correcter en gevarieerder. Je controleert je eigen teksten steeds meer zonder dat de mentor alle fouten moet aanduiden. Je gebruikt een rijkere woordenschat en complexere zinsbouw en maakt bewustere stilistische keuzes die passen bij je tekst.",
  },
  {
    id: "rbr-1A-10",
    cursus: "Vrije Tekst",
    stroom: "1A",
    naam: "RUBRIC 4: diversiteit in genres en registers",
    doelen: ["02.05", "02.06", "02.11", "UD 02.04", "UD 02.05", "UD 02.06", "03.01", "03.03", "03.04", "15.01"],
    criteria: {
      blauw: "Je schrijft bewust en gevarieerd in verschillende genres. Je past structuur, stijl, woordkeuze en register zelfstandig aan het doel, het genre en je publiek aan en durft verschillende manieren van schrijven uit te proberen.",
      groen: "Je schrijft verschillende soorten teksten en houdt rekening met de kenmerken van het genre, het doel en je publiek. Je gebruikt meestal een passend register en passende taal.",
      geel: "Je probeert verschillende soorten teksten te schrijven. Met hulp hou je rekening met enkele kenmerken van het genre, het doel en je publiek, maar dit lukt nog niet in je hele tekst.",
      rood: "Je schrijft steeds op dezelfde manier en houdt nog weinig rekening met het genre, het doel of je publiek. Je past je taalgebruik niet aan de situatie aan.",
    },
    leerlijn: "1ste graad: Je maakt kennis met verschillende tekstsoorten en genres en leert dat je niet elke tekst op dezelfde manier schrijft. Je ontdekt dat een verhaal, verslag, meningstekst, brief of creatieve tekst andere kenmerken kan hebben. Je leert ook rekening houden met voor wie je schrijft en waarom je schrijft.\n\nNaar de 2de graad: Je schrijft een grotere variatie aan teksten en kiest steeds zelfstandiger een passende structuur, stijl en register. Je houdt bewuster rekening met doel en publiek en leert ook binnen een genre spelen met stijl en taal om een bepaald effect bij de lezer te bereiken.",
  },
  {
    id: "rbr-1B-6",
    cursus: "Vrije Tekst",
    stroom: "1B",
    naam: "RUBRIC BASISGELETTERDHEID 1: lezen, luisteren, spreken en schrijven in het Nederlands",
    doelen: ["BG02.01", "BG02.02", "BG02.03"],
    criteria: {
      blauw: "Je begrijpt bij het lezen en luisteren vlot waarover een tekst gaat en haalt zelfstandig de belangrijke informatie eruit. Je spreekt en schrijft duidelijk en doelgericht en neemt actief deel aan eenvoudige gesprekken en schriftelijke communicatie.",
      groen: "Je begrijpt bij het lezen en luisteren waarover een eenvoudige tekst gaat en haalt de belangrijkste informatie eruit. Je kan in eenvoudige situaties duidelijk genoeg spreken en schrijven om je boodschap over te brengen. Je neemt deel aan eenvoudige gesprekken en schriftelijke communicatie, eventueel met hulpmiddelen.",
      geel: "Je begrijpt een deel van wat je leest of hoort, maar hebt nog regelmatig hulp nodig om het onderwerp of belangrijke informatie te vinden. Ook bij spreken, schrijven en communiceren heb je nog ondersteuning nodig om je boodschap duidelijk over te brengen.",
      rood: "Je vindt het nog moeilijk om te begrijpen waarover een eenvoudige tekst gaat of belangrijke informatie eruit te halen. Ook met hulp lukt het nog onvoldoende om een eenvoudige boodschap mondeling of schriftelijk over te brengen of deel te nemen aan eenvoudige communicatie.",
    },
    leerlijn: "1ste graad – basisgeletterdheid: Je leert de basisvaardigheden die je nodig hebt om het Nederlands functioneel te gebruiken. Bij eenvoudige, herkenbare teksten leer je bepalen waarover de tekst gaat en relevante informatie terugvinden. Je leert zelf een eenvoudige boodschap mondeling en schriftelijk overbrengen en deelnemen aan eenvoudige communicatie met anderen. Je mag hierbij ondersteunende middelen gebruiken. Voor schrijven verwachten we een eenvoudige tekststructuur, redelijk herkenbare samenhang, frequente woorden en concrete inhoud. Taalfouten zijn toegestaan zolang ze het begrijpen van je boodschap niet in de weg staan.\n\nVerdere ontwikkeling: Vanuit dit basisniveau leer je steeds zelfstandiger en doelgerichter lezen, luisteren, spreken en schrijven. Teksten worden gevarieerder en complexer en je leert informatie nauwkeuriger verwerken. Bij spreken en schrijven werk je verder aan structuur, samenhang, woordenschat, correctheid en het aanpassen van je taal aan doel, publiek en situatie.",
  },
  {
    id: "rbr-1B-7",
    cursus: "Vrije Tekst",
    stroom: "1B",
    naam: "RUBRIC BASISGELETTERDHEID 2: digitale vaardigheden",
    doelen: ["BG04.01"],
    criteria: {
      blauw: "Je communiceert zelfstandig and doelgericht met digitale toepassingen. Je kiest passende basisfuncties en gebruikt ze vlot om je boodschap duidelijk over te brengen en op digitale communicatie te reageren.",
      groen: "Je gebruikt de nodige basisfuncties van een digitale toepassing om doelgericht met anderen te communiceren. Je kan bijvoorbeeld een bericht versturen en beantwoorden en informatie delen. Je kan dit meestal zelfstandig.",
      geel: "Je kan enkele basisfuncties gebruiken om digitaal te communiceren, maar hebt nog regelmatig hulp nodig om bijvoorbeeld een bericht te versturen, te beantwoorden of informatie te delen.",
      rood: "Je kan de nodige basisfuncties van een digitale toepassing nog niet voldoende gebruiken om digitaal te communiceren. Ook met hulp lukt het nog moeilijk om een eenvoudige digitale boodschap te versturen of erop te reageren.",
    },
    leerlijn: "1ste graad – basisgeletterdheid: Je leert de basisfuncties van digitale toepassingen gebruiken om met anderen te communiceren. Je leert bijvoorbeeld een digitaal bericht opstellen, versturen en beantwoorden en informatie of een bestand delen. Je leert daarbij de functies gebruiken die je nodig hebt om je boodschap bij de juiste persoon of groep te krijgen. Het gaat niet om het beheersen van alle mogelijkheden van een programma, maar om functioneel en doelgericht digitaal kunnen communiceren.\n\nVerdere ontwikkeling: Vanuit dit basisniveau leer je steeds zelfstandiger verschillende digitale toepassingen gebruiken. Je leert bewuster kiezen welke toepassing en welke functies geschikt zijn voor je doel en situatie en houdt steeds meer rekening met de ontvanger en de manier waarop je digitaal communiceert.",
  },
  {
    id: "rbr-1B-8",
    cursus: "Vrije Tekst",
    stroom: "1B",
    naam: "RUBRIC 1: Motivatie en proces",
    doelen: ["04.01", "04.04", "3.04", "15.01", "15.02", "16.05", "FR1", "FR3"],
    criteria: {
      blauw: "Je gaat zelfstandig en gemotiveerd aan de slag. Je neemt initiatief, probeert ideeën uit en blijft doorzetten wanneer iets moeilijk is. Je gebruikt hulp and feedback doelgericht, werkt respectvol samen and neemt verantwoordelijkheid for je eigen werk and proces.",
      groen: "Je gaat gemotiveerd aan de slag en werkt actief aan je tekst. Je probeert ideeën uit en zet door wanneer iets moeilijker gaat. Je staat open voor hulp en feedback, werkt respectvol samen and neemt voldoende verantwoordelijkheid voor je eigen werk.",
      geel: "Je gaat aan de slag, maar hebt regelmatig aanmoediging of hulp nodig om verder te werken. Je vindt het soms moeilijk om ideeën uit te proberen, door te zetten, feedback te gebruiken of verantwoordelijkheid voor je werk te nemen.",
      rood: "Je zet je nog onvoldoende in voor je tekst en schrijfproces. Ook met ondersteuning kom je moeilijk tot werken, geef je snel op of neem je weinig verantwoordelijkheid voor je eigen werk.",
    },
    leerlijn: "1ste graad B-stroom: Je leert actief aan een Vrije Tekst werken en verantwoordelijkheid nemen voor je eigen schrijfproces. Je leert een idee uitproberen, hulp of feedback aanvaarden en verder werken wanneer iets niet onmiddellijk lukt. Je leert ook samenwerken en respectvol omgaan met anderen tijdens tekstbesprekingen. Geleidelijk heb je minder aanmoediging nodig en neem je meer initiatief.\n\nTe schrijven teksten: Je hebt steeds een Vrije Tekstopdracht lopen en werkt gedurende een langere periode aan hun tekst.\n\nNaar de 2de graad: Je neemt steeds meer zelf de leiding over je schrijfproces. Je wacht minder op instructies of aanmoediging, maar plant je werk, neemt initiatief, zoekt oplossingen wanneer je vastloopt en vraagt gericht hulp of feedback. Je leert kritisch naar je eigen werk kijken en blijft eraan werken om tot een zo goed mogelijke tekst te komen.",
  },
  {
    id: "rbr-1B-9",
    cursus: "Vrije Tekst",
    stroom: "1B",
    naam: "RUBRIC 2: Samenhang",
    doelen: ["02.05", "02.10", "UD02.01", "UD02.04", "UD02.10", "03.01", "03.03"],
    criteria: {
      blauw: "Je tekst vormt een duidelijk en logisch geheel. Je ordent je ideeën bewust en verbindt de verschillende delen van je tekst op een passende manier. Je gebruikt zelfstandig tekstopbouwende elementen, signaalwoorden en/of verwijswoorden om de lezer door je tekst te leiden.",
      groen: "Je tekst is duidelijk en logisch opgebouwd met ondersteuning. Je zet je ideeën in een begrijpelijke volgorde en verbindt de verschillende delen van je tekst. Je gebruikt eenvoudige tekstopbouwende elementen, signaalwoorden en/of verwijswoorden waardoor de lezer je tekst kan volgen.",
      geel: "Je probeert je tekst logisch op te bouwen, maar sommige ideeën of delen sluiten nog niet goed op elkaar aan. Je hebt regelmatig hulp nodig om je ideeën te ordenen of verbindende woorden en tekstopbouwende elementen te gebruiken.",
      rood: "Je tekst heeft nog onvoldoende samenhang. Je ideeën staan vaak los van elkaar of in een onduidelijke volgorde. Ook met hulp lukt het nog moeilijk om je tekst zo op te bouwen dat de lezer hem kan volgen.",
    },
    leerlijn: "1ste graad B-stroom: Je leert dat een goede tekst uit delen bestaat die met elkaar verbonden zijn. Je leert je ideeën in een begrijpelijke volgorde zetten en eenvoudige middelen gebruiken om je tekst overzichtelijk te maken, zoals een titel, afbeeldingen, een eenvoudige lay-out, signaalwoorden en verwijswoorden.\n\nLezen ter ondersteuning: Je leert daarnaast steeds beter herkennen waarover een tekst gaat en hoe informatie in een tekst georganiseerd is. Zo ondersteunt lezen ook je eigen schrijven: door te zien hoe andere teksten zijn opgebouwd, leer je jouw eigen teksten duidelijker structureren.\n\nNaar de 2de graad: Je bouwt je teksten steeds zelfstandiger en bewuster op. Je kiest een structuur die past bij wat je wilt vertellen en gebruikt verbindingsmiddelen om ideeën, zinnen en tekstdelen logisch met elkaar te verbinden. Je teksten worden langer en complexer, maar blijven voor de lezer duidelijk te volgen.",
  },
  {
    id: "rbr-1B-10",
    cursus: "Vrije Tekst",
    stroom: "1B",
    naam: "RUBRIC 3: TAALZORG",
    doelen: ["02.04", "02.09", "UD02.08", "UD02.09", "02.08", "03.04"],
    criteria: {
      blauw: "Je gebruikt taal zorgvuldig en controleert je tekst zelfstandig. Je past aangeleerde spelling, grammatica, zinsbouw en woordenschat bewust toe en verbetert fouten. Je gebruikt nieuwe woorden en taalregels steeds zelfstandiger in je eigen teksten.",
      groen: "Je schrijft voldoende verzorgd. Je past aangeleerde spelling, grammatica, zinsbouw en woordenschat meestal correct toe. Je controleert je tekst and verbetert fouten met beperkte hulp of met hulpmiddelen.",
      geel: "Je probeert verzorgd te schrijven, maar past aangeleerde spelling, grammatica, zinsbouw en woordenschat nog niet altijd toe. Je hebt regelmatig hulp nodig om fouten te herkennen en te verbeteren.",
      rood: "Je besteedt nog onvoldoende aandacht aan taalzorg. Ook met hulp pas je aangeleerde spelling, grammatica, zinsbouw en woordenschat nog weinig toe en verbeter je fouten onvoldoende.",
    },
    leerlijn: "1ste graad B-stroom: Je leert eerder geziene en nieuwe taalregels en woordenschat gebruiken in je eigen teksten. Je werkt onder andere aan spelling, interpunctie, woordkeuze en zinsbouw. Je leert je tekst opnieuw lezen, fouten herkennen en verbeteren. Daarbij mag je gebruikmaken van feedback en hulpmiddelen. Het belangrijkste is dat je wat je tijdens taalopdrachten leert steeds meer gaat toepassen in je eigen teksten.\n\nNaar de 2de graad: Je past spelling, grammatica, zinsbouw en woordenschat steeds zelfstandiger toe. Je leert je eigen teksten kritischer nalezen en verbeteren zonder dat de mentor alle fouten voor jou aanduidt. Je woordenschat wordt ruimer en je gebruikt je kennis van taal steeds bewuster om duidelijke, correcte en verzorgde teksten te schrijven.",
  },
  {
    id: "rbr-1B-11",
    cursus: "Vrije Tekst",
    stroom: "1B",
    naam: "RUBRIC 4: diversiteit in genres en registers",
    doelen: ["02.05", "02.06", "UD02.05", "UD02.06", "03.04"],
    criteria: {
      blauw: "Je gebruikt taal op een gevarieerde en creatieve manier. Je probeert verschillende soorten teksten en communicatievormen uit en past je taal bewust aan je doel en situatie aan. Je durft ook zelfstandig Frans te gebruiken en zet aangeleerde Franse woorden, zinnen en uitdrukkingen passend in om met anderen te communiceren.",
      groen: "Je gebruikt taal op verschillende manieren en probeert verschillende soorten teksten en communicatievormen uit. Je houdt rekening met wat je wilt vertellen en de situatie. Je durft ook eenvoudig Frans te gebruiken en gebruikt aangereikte of aangeleerde woorden en zinnen om met anderen te communiceren.",
      geel: "Je probeert verschillende manieren van schrijven en communiceren uit, maar hebt hierbij nog regelmatig hulp nodig. Je vindt het soms moeilijk om je taal aan de situatie aan te passen. Ook in het Frans heb je veel ondersteuning nodig om eenvoudige woorden of zinnen te gebruiken en te reageren.",
      rood: "Je gebruikt taal nog weinig gevarieerd en vindt het moeilijk om verschillende manieren van schrijven of communiceren uit te proberen. Ook met ondersteuning lukt het nog moeilijk om eenvoudig Frans te gebruiken om met anderen te communiceren.",
    },
    leerlijn: "1ste graad B-stroom: Je ontdekt dat je taal op verschillende manieren kunt gebruiken. Je probeert verschillende teksten en communicatievormen uit en leert jezelf creatief uitdrukken. Je leert dat the manier waarop je communiceert kan veranderen afhankelijk van wat je wilt bereiken and met wie je communiceert. Daarbij krijg je ook kansen om Frans functioneel te gebruiken.\n\nNaar de 2de graad: Je gebruikt taal steeds zelfstandiger in verschillende situaties. Je probeert un grotere variatie aan teksten en communicatievormen uit en leert je taal bewuster aanpassen aan doel, situatie en gesprekspartner. Ook in het Frans breid je je woordenschat en communicatiemogelijkheden verder uit, zodat je steeds zelfstandiger kunt deelnemen aan interacties.",
  },
  {
    id: "rbr-2A-5",
    cursus: "Vrije Tekst",
    stroom: "2A",
    naam: "RUBRIC 1: Motivatie en proces",
    doelen: ["02.07", "02.08", "03.02", "04.04", "05.01", "U04.01.01", "U04.01.03", "FR1", "13.02", "15.02", "16.04", "U02.14.02", "U02.14.04", "U04.01.02", "U04.01.04", "FR3"],
    criteria: {
      blauw: "Je werkt zelfstandig en gemotiveerd aan je tekst en neemt duidelijk verantwoordelijkheid voor je eigen proces. Je neemt initiatief, maakt bewuste keuzes, zoekt zelf oplossingen en relevante informatie en gebruikt feedback kritisch en doelgericht. Je blijft je werk ontwikkelen en streeft naar een zo sterk mogelijk eindresultaat.",
      groen: "Je werkt gemotiveerd en meestal zelfstandig aan je tekst. Je neemt verantwoordelijkheid voor je werk, maakt keuzes en zoekt oplossingen of informatie wanneer dat nodig is. Je staat open voor feedback en gebruikt die om je tekst en proces te verbeteren.",
      geel: "Je werkt aan je tekst, maar hebt nog regelmatig aanmoediging of ondersteuning nodig om verder te gaan. Je neemt nog niet altijd zelf initiatief of verantwoordelijkheid en hebt veel hulp nodig om informatie te zoeken, oplossingen te vinden of feedback te gebruiken.",
      rood: "Je zet je nog onvoldoende in voor je tekst en schrijfproces. Je neemt weinig tot geen initiatief of verantwoordelijkheid en komt ook met ondersteuning moeilijk tot verder werken. Je gebruikt aangereikte hulp, informatie of feedback nog onvoldoende om je werk te verbeteren.",
    },
    leerlijn: "2de graad: Je neemt steeds meer zelf de verantwoordelijkheid voor je schrijfproces. Je kiest waarover en hoe je wilt schrijven, gaat actief op zoek naar ideeën en relevante informatie en maakt bewuste keuzes tijdens het werken. Je leert niet onmiddellijk op te geven wanneer iets moeilijk loopt, maar probeert verschillende mogelijkheden uit en zoekt oplossingen. Feedback van anderen gebruik je niet zomaar omdat het moet: je leert er kritisch over nadenken en beslist hoe je die kunt inzetten om je tekst te verbeteren.\n\nNaar de 3de graad: Je stuurt je schrijfproces steeds zelfstandiger. Je bepaalt eigen doelen, plant en bewaakt je werk, zoekt zelfstandig geschikte bronnen en feedback en maakt onderbouwde keuzes. Je reflecteert kritisch over je proces en eindproduct en kunt uitleggen waarom je bepaalde keuzes hebt gemaakt. De mentor verschuift steeds meer van iemand die het proces stuurt naar iemand die je gericht ondersteunt wanneer dat nodig is.",
  },
  {
    id: "rbr-2A-6",
    cursus: "Vrije Tekst",
    stroom: "2A",
    naam: "RUBRIC 2: Samenhang",
    doelen: ["02.01", "02.12", "03.01", "03.03", "U02.14.01"],
    criteria: {
      blauw: "Je tekst vormt een sterk en logisch geheel. Je kiest bewust een passende structuur en bouwt je tekst duidelijk op met een inleiding, midden en slot waar dat past. Je verdeelt je tekst doordacht in alinea's en gebruikt signaalwoorden, verwijswoorden en andere verbindingen om ideeën vlot met elkaar te verbinden. Het onderwerp, de hoofdgedachte en de belangrijkste punten zijn doorheen de hele tekst duidelijk.",
      groen: "Je tekst vormt een duidelijk en logisch geheel. Je gebruikt een passende structuur en verdeelt je tekst in duidelijke delen en alinea's. Je gebruikt signaalwoorden en verwijswoorden om ideeën met elkaar te verbinden. Het onderwerp en de hoofdgedachte zijn duidelijk en de lezer kan je gedachtegang goed volgen.",
      geel: "Je tekst heeft een herkenbare opbouw, maar de samenhang is nog niet overal duidelijk. Sommige ideeën staan niet in een logische volgorde of zijn onvoldoende met elkaar verbonden. Je gebruikt nog te weinig of niet altijd passende alinea's, signaalwoorden of verwijswoorden. De lezer moet soms zoeken naar wat je precies wilt vertellen.",
      rood: "Je tekst mist nog een duidelijke samenhang. Ideeën staan los van elkaar of in een onduidelijke volgorde. Er is weinig herkenbare structuur en je gebruikt nauwelijks middelen om delen en ideeën met elkaar te verbinden. Daardoor is het voor de lezer moeilijk om je tekst te volgen of de hoofdgedachte te herkennen.",
    },
    leerlijn: "2de graad: Je leert teksten steeds bewuster structureren. Je zorgt niet alleen voor een duidelijke volgorde, maar kiest een tekststructuur die past bij wat je wilt vertellen. Je gebruikt alinea's, tussentitels, signaalwoorden en verwijswoorden om verbanden zichtbaar te maken. Je leert bijvoorbeeld verbanden uitdrukken zoals chronologie, opsomming, oorzaak en tegenstelling. Je zorgt ervoor dat onderwerp, hoofdgedachte en hoofdpunten herkenbaar blijven voor de lezer.\n\nNaar de 3de graad: Je bouwt langere en complexere teksten zelfstandig en doelgericht op. Je kiest bewust een geschikte tekststructuur en gebruikt verschillende soorten tekstverbanden om je gedachtegang helder te maken. Je bewaakt de samenhang van de volledige tekst en kunt je structuur aanpassen aan het doel, de tekstsoort en de lezer.",
  },
  {
    id: "rbr-2A-7",
    cursus: "Vrije Tekst",
    stroom: "2A",
    naam: "RUBRIC 3: TAALZORG",
    doelen: ["02.11", "02.10", "03.06", "13.03", "U02.14.05", "U02.08.01"],
    criteria: {
      blauw: "Je gebruikt taal bewust, correct en gevarieerd. Je past aangeleerde en nieuwe woordenschat, spelling, grammatica en zinsbouw zelfstandig toe en controleert en verbetert je tekst kritisch. Je gebruikt passende school- en vaktaal en past ook in het Engels en Frans steeds zelfstandiger de geleerde woordenschat en grammaticale structuren toe.",
      groen: "Je gebruikt taal verzorgd en meestal correct. Je past aangeleerde woordenschat, spelling, grammatica en zinsbouw toe en controleert je tekst. Je verbetert fouten waar nodig en gebruikt passende school- en vaktaal. Ook in het Engels en Frans pas je de aangeleerde woordenschat en grammaticale structuren voldoende toe.",
      geel: "Je probeert verzorgd te schrijven, maar past aangeleerde woordenschat, spelling, grammatica en zinsbouw nog niet altijd toe. Je hebt regelmatig hulp nodig om fouten te herkennen en te verbeteren of om passende woorden en taalstructuren te gebruiken, ook in het Engels en Frans.",
      rood: "Je besteedt nog onvoldoende aandacht aan taalzorg. Je past aangeleerde woordenschat en taalregels weinig tot niet toe en controleert of verbetert je tekst onvoldoende/niet, ook met ondersteuning. Fouten en onduidelijk taalgebruik bemoeilijken regelmatig het begrijpen van je tekst.",
    },
    leerlijn: "2de graad: Je bouwt verder op de taalzorg uit de 1ste graad. Je controleert steeds zelfstandiger spelling, grammatica, woordkeuze en zinsbouw en past eerder geziene taalregels opnieuw toe wanneer je schrijft. Je breidt je woordenschat uit en leert preciezer formuleren. Het doel is niet alleen minder fouten maken, maar je taalkennis bewust inzetten om je boodschap duidelijker, correcter en rijker te formuleren.\n\nNaar de 3de graad: Je gebruikt taal steeds preciezer, gevarieerder en zelfstandiger. Je herkent eigen terugkerende fouten, gebruikt taalbronnen en feedback doelgericht en maakt bewustere keuzes in woordenschat, zinsbouw, grammatica, stijl en register. Je kunt ook steeds beter uitleggen waarom een formulering correcter of sterker is.",
  },
  {
    id: "rbr-2A-8",
    cursus: "Vrije Tekst",
    stroom: "2A",
    naam: "RUBRIC 4: diversiteit in genres en registers",
    doelen: ["02.06", "03.01", "03.03", "03.04", "03.05", "03.08", "U02.14.03"],
    criteria: {
      blauw: "Je gebruikt taal bewust en gevarieerd in verschillende genres, talen en registers. Je past je taal zelfstandig aan je doel, publiek en situatie aan en durft ook in het Engels en Frans uitgebreidere teksten of communicatie aan. Je gebruikt passende strategieën wanneer je vastloopt en toont bewustzijn van culturele verschillen in taal en communicatie.",
      groen: "Je varieert voldoende in genres, talen en registers. Je past je taal meestal passend aan je doel, publiek en situatie aan. Je gebruikt Nederlands, Engels en Frans wanneer dit gevraagd wordt en kan in de vreemde talen een begrijpelijke boodschap overbrengen. Wanneer nodig gebruik je strategieën of hulpmiddelen om verder te kunnen communiceren.",
      geel: "Je probeert verschillende genres, talen en registers te gebruiken, maar valt nog vaak terug op dezelfde manier van schrijven of communiceren. Je hebt nog te regelmatig hulp nodig om je taal aan doel, publiek of situatie aan te passen. Ook in het Engels of Frans heb je veel ondersteuning nodig om je boodschap over te brengen of verder te communiceren.",
      rood: "Je varieert nog onvoldoende in genres, talen en registers. Je houdt weinig rekening met doel, publiek of situatie en vermijdt het gebruik van Engels of Frans wanneer dit gevraagd wordt. Ook met ondersteuning lukt het nog moeilijk om verschillende manieren van communiceren uit te proberen.",
    },
    leerlijn: "2de graad: Je gaat verder dan alleen kennismaken met verschillende tekstsoorten. Je leert bewust kiezen hoe je schrijft of communiceert op basis van je doel, je publiek en de situatie. Je schrijft in een ruimere waaier aan genres en leert schakelen tussen verschillende registers.\n\nMeertaligheid: Je schrijft en communiceert niet alleen in het Nederlands, maar ook in het Engels en Frans. Er wordt verwacht dat je doelgericht spreekt en schrijft met een herkenbare structuur, duidelijke tekstverbanden en een passend register. Daarnaast verdiep je je verder: je leert in Engels en Frans communiceren over een bredere waaier aan thema's, met meer complexe zinsbouw en een ruime variatie aan tekstsoorten.\n\nStrategieën: Je leert ook strategieën gebruiken wanneer communicatie moeilijker wordt. Dat kan bijvoorbeeld betekenen dat je de betekenis van een onbekend woord uit de context afleidt, een hulpmiddel gebruikt, iets anders formuleert, om verduidelijking vraagt of je taal aan de ontvanger aanpast.\n\nCultuur: Je kunt bij Engelse en Franse teksten kenmerkende aspecten van de maatschappijen en culturen waarin de doeltaal wordt gesproken, illustreren. Daardoor kan Diversiteit ook betekenen dat je beseft dat taalgebruik niet in elke taal of cultuur exact hetzelfde werkt.\n\nNaar de 3de graad: Je kiest steeds zelfstandiger een genre, taal en register dat past bij je communicatieve bedoeling. Je communiceert flexibeler in Nederlands, Engels en Frans, gebruikt strategieën steeds zelfstandiger and houdt bewuster rekening met culturele en sociale verschillen in communicatie.",
  },
];
