// AUTO-GEGENEREERD uit docs/reference/fictieve_gebruikers_150ll_20mentoren.csv
// Fictieve accounts voor de demo-login. Wachtwoorden zijn NIET echt.
import type { Mentor, Student } from "./types";

export const seedLeerlingen: Student[] = [
  { id: "cilou.aerts", firstName: "Cilou", lastName: "Aerts", vestiging: "Gent", leerjaar: 4, klasgroep: "A", email: "cilou.aerts@keerpuntscholen.be", wachtwoord: "4Xv9JrK7" },
  { id: "jade.aerts", firstName: "Jade", lastName: "Aerts", vestiging: "Oudenaarde", leerjaar: 6, klasgroep: "A", email: "jade.aerts@keerpuntscholen.be", wachtwoord: "8k8MwZXJ" },
  { id: "julie.aerts", firstName: "Julie", lastName: "Aerts", vestiging: "Brussel", leerjaar: 2, klasgroep: "A", email: "julie.aerts@keerpuntscholen.be", wachtwoord: "jmHPp19f" },
  { id: "juliette.aerts", firstName: "Juliette", lastName: "Aerts", vestiging: "Geraardsbergen", leerjaar: 3, klasgroep: "A", email: "juliette.aerts@keerpuntscholen.be", wachtwoord: "ku9QBNpx" },
  { id: "milan.aerts", firstName: "Milan", lastName: "Aerts", vestiging: "Hasselt", leerjaar: 1, klasgroep: "B", email: "milan.aerts@keerpuntscholen.be", wachtwoord: "jC2k2Pk1" },
  { id: "stella.aerts", firstName: "Stella", lastName: "Aerts", vestiging: "Herselt", leerjaar: 1, klasgroep: "A", email: "stella.aerts@keerpuntscholen.be", wachtwoord: "OxwYk3G2" },
  { id: "estelle.claes", firstName: "Estelle", lastName: "Claes", vestiging: "Houthalen", leerjaar: 1, klasgroep: "B", email: "estelle.claes@keerpuntscholen.be", wachtwoord: "DZB5H7oa" },
  { id: "fleur.claes", firstName: "Fleur", lastName: "Claes", vestiging: "Mol", leerjaar: 5, klasgroep: "A", email: "fleur.claes@keerpuntscholen.be", wachtwoord: "ReCa7bS1" },
  { id: "hamza.claes", firstName: "Hamza", lastName: "Claes", vestiging: "Turnhout", leerjaar: 3, klasgroep: "A", email: "hamza.claes@keerpuntscholen.be", wachtwoord: "dL2E2cG5" },
  { id: "liam.claes", firstName: "Liam", lastName: "Claes", vestiging: "Gent", leerjaar: 6, klasgroep: "A", email: "liam.claes@keerpuntscholen.be", wachtwoord: "SGOD2Yh8" },
  { id: "luca.claes", firstName: "Luca", lastName: "Claes", vestiging: "Oudenaarde", leerjaar: 2, klasgroep: "A", email: "luca.claes@keerpuntscholen.be", wachtwoord: "yy3vQCo7" },
  { id: "lina.claeys", firstName: "Lina", lastName: "Claeys", vestiging: "Brussel", leerjaar: 5, klasgroep: "A", email: "lina.claeys@keerpuntscholen.be", wachtwoord: "sE8M6tJZ" },
  { id: "lucie.claeys", firstName: "Lucie", lastName: "Claeys", vestiging: "Geraardsbergen", leerjaar: 5, klasgroep: "A", email: "lucie.claeys@keerpuntscholen.be", wachtwoord: "5ikvCCq4" },
  { id: "nina.claeys", firstName: "Nina", lastName: "Claeys", vestiging: "Hasselt", leerjaar: 1, klasgroep: "A", email: "nina.claeys@keerpuntscholen.be", wachtwoord: "3CHvWIp8" },
  { id: "sofia.claeys", firstName: "Sofia", lastName: "Claeys", vestiging: "Herselt", leerjaar: 5, klasgroep: "A", email: "sofia.claeys@keerpuntscholen.be", wachtwoord: "tHjfN4ts" },
  { id: "stella.claeys", firstName: "Stella", lastName: "Claeys", vestiging: "Houthalen", leerjaar: 2, klasgroep: "B", email: "stella.claeys@keerpuntscholen.be", wachtwoord: "H30w45xe" },
  { id: "warre.claeys", firstName: "Warre", lastName: "Claeys", vestiging: "Mol", leerjaar: 2, klasgroep: "B", email: "warre.claeys@keerpuntscholen.be", wachtwoord: "Q5DkwH6E" },
  { id: "charlotte.de.clercq", firstName: "Charlotte", lastName: "De Clercq", vestiging: "Turnhout", leerjaar: 5, klasgroep: "A", email: "charlotte.de.clercq@keerpuntscholen.be", wachtwoord: "JL03qlKk" },
  { id: "clara.de.clercq", firstName: "Clara", lastName: "De Clercq", vestiging: "Gent", leerjaar: 4, klasgroep: "A", email: "clara.de.clercq@keerpuntscholen.be", wachtwoord: "Ja6kOsNa" },
  { id: "eloise.de.clercq", firstName: "Eloïse", lastName: "De Clercq", vestiging: "Oudenaarde", leerjaar: 3, klasgroep: "A", email: "eloise.de.clercq@keerpuntscholen.be", wachtwoord: "pLVYd8U9" },
  { id: "florence.de.clercq", firstName: "Florence", lastName: "De Clercq", vestiging: "Brussel", leerjaar: 6, klasgroep: "A", email: "florence.de.clercq@keerpuntscholen.be", wachtwoord: "hsS6kkDW" },
  { id: "hamza.de.clercq", firstName: "Hamza", lastName: "De Clercq", vestiging: "Geraardsbergen", leerjaar: 2, klasgroep: "B", email: "hamza.de.clercq@keerpuntscholen.be", wachtwoord: "c3mI9RVw" },
  { id: "jack.de.clercq", firstName: "Jack", lastName: "De Clercq", vestiging: "Hasselt", leerjaar: 6, klasgroep: "A", email: "jack.de.clercq@keerpuntscholen.be", wachtwoord: "S0ULi9Cn" },
  { id: "leo.de.clercq", firstName: "Leo", lastName: "De Clercq", vestiging: "Herselt", leerjaar: 6, klasgroep: "A", email: "leo.de.clercq@keerpuntscholen.be", wachtwoord: "AhYjf62x" },
  { id: "morris.de.clercq", firstName: "Morris", lastName: "De Clercq", vestiging: "Houthalen", leerjaar: 1, klasgroep: "A", email: "morris.de.clercq@keerpuntscholen.be", wachtwoord: "4LA8NVl8" },
  { id: "ralph.de.clercq", firstName: "Ralph", lastName: "De Clercq", vestiging: "Mol", leerjaar: 5, klasgroep: "A", email: "ralph.de.clercq@keerpuntscholen.be", wachtwoord: "i7z39FvS" },
  { id: "finn.de.smet", firstName: "Finn", lastName: "De Smet", vestiging: "Turnhout", leerjaar: 1, klasgroep: "B", email: "finn.de.smet@keerpuntscholen.be", wachtwoord: "Knt2oIER" },
  { id: "mila.de.smet", firstName: "Mila", lastName: "De Smet", vestiging: "Gent", leerjaar: 1, klasgroep: "A", email: "mila.de.smet@keerpuntscholen.be", wachtwoord: "CU9bcvO4" },
  { id: "anna.desmet", firstName: "Anna", lastName: "Desmet", vestiging: "Oudenaarde", leerjaar: 5, klasgroep: "A", email: "anna.desmet@keerpuntscholen.be", wachtwoord: "8jhug2Im" },
  { id: "billie.desmet", firstName: "Billie", lastName: "Desmet", vestiging: "Brussel", leerjaar: 4, klasgroep: "A", email: "billie.desmet@keerpuntscholen.be", wachtwoord: "gie4k0BZ" },
  { id: "jade.desmet", firstName: "Jade", lastName: "Desmet", vestiging: "Geraardsbergen", leerjaar: 6, klasgroep: "A", email: "jade.desmet@keerpuntscholen.be", wachtwoord: "mb02vCyT" },
  { id: "julie.desmet", firstName: "Julie", lastName: "Desmet", vestiging: "Hasselt", leerjaar: 6, klasgroep: "A", email: "julie.desmet@keerpuntscholen.be", wachtwoord: "TX2UuxOk" },
  { id: "leon.desmet", firstName: "Leon", lastName: "Desmet", vestiging: "Herselt", leerjaar: 1, klasgroep: "A", email: "leon.desmet@keerpuntscholen.be", wachtwoord: "F60btFgU" },
  { id: "lucas.desmet", firstName: "Lucas", lastName: "Desmet", vestiging: "Houthalen", leerjaar: 2, klasgroep: "A", email: "lucas.desmet@keerpuntscholen.be", wachtwoord: "5aZTsaqJ" },
  { id: "marcel.desmet", firstName: "Marcel", lastName: "Desmet", vestiging: "Mol", leerjaar: 6, klasgroep: "A", email: "marcel.desmet@keerpuntscholen.be", wachtwoord: "IYOFKkJ8" },
  { id: "maya.desmet", firstName: "Maya", lastName: "Desmet", vestiging: "Turnhout", leerjaar: 6, klasgroep: "A", email: "maya.desmet@keerpuntscholen.be", wachtwoord: "8BP7FZjg" },
  { id: "mil.desmet", firstName: "Mil", lastName: "Desmet", vestiging: "Gent", leerjaar: 1, klasgroep: "A", email: "mil.desmet@keerpuntscholen.be", wachtwoord: "CW5JyuIS" },
  { id: "nolan.desmet", firstName: "Nolan", lastName: "Desmet", vestiging: "Oudenaarde", leerjaar: 1, klasgroep: "A", email: "nolan.desmet@keerpuntscholen.be", wachtwoord: "ahvI2Hvb" },
  { id: "nora.desmet", firstName: "Nora", lastName: "Desmet", vestiging: "Brussel", leerjaar: 6, klasgroep: "A", email: "nora.desmet@keerpuntscholen.be", wachtwoord: "8I4AjhMt" },
  { id: "elena.diallo", firstName: "Elena", lastName: "Diallo", vestiging: "Geraardsbergen", leerjaar: 3, klasgroep: "A", email: "elena.diallo@keerpuntscholen.be", wachtwoord: "gNGJtWk4" },
  { id: "estelle.diallo", firstName: "Estelle", lastName: "Diallo", vestiging: "Hasselt", leerjaar: 6, klasgroep: "A", email: "estelle.diallo@keerpuntscholen.be", wachtwoord: "4FlB3pE2" },
  { id: "zayn.diallo", firstName: "Zayn", lastName: "Diallo", vestiging: "Herselt", leerjaar: 4, klasgroep: "A", email: "zayn.diallo@keerpuntscholen.be", wachtwoord: "Xq6O8XnK" },
  { id: "clara.dubois", firstName: "Clara", lastName: "Dubois", vestiging: "Houthalen", leerjaar: 2, klasgroep: "A", email: "clara.dubois@keerpuntscholen.be", wachtwoord: "wjH91eEN" },
  { id: "emiel.dubois", firstName: "Emiel", lastName: "Dubois", vestiging: "Mol", leerjaar: 2, klasgroep: "A", email: "emiel.dubois@keerpuntscholen.be", wachtwoord: "qG93V3E2" },
  { id: "gabriel.dubois", firstName: "Gabriel", lastName: "Dubois", vestiging: "Turnhout", leerjaar: 2, klasgroep: "A", email: "gabriel.dubois@keerpuntscholen.be", wachtwoord: "uon3L60W" },
  { id: "levi.dubois", firstName: "Levi", lastName: "Dubois", vestiging: "Gent", leerjaar: 2, klasgroep: "A", email: "levi.dubois@keerpuntscholen.be", wachtwoord: "C1J2pwpv" },
  { id: "lowie.dubois", firstName: "Lowie", lastName: "Dubois", vestiging: "Oudenaarde", leerjaar: 5, klasgroep: "A", email: "lowie.dubois@keerpuntscholen.be", wachtwoord: "DvEaORT8" },
  { id: "luca.dubois", firstName: "Luca", lastName: "Dubois", vestiging: "Brussel", leerjaar: 5, klasgroep: "A", email: "luca.dubois@keerpuntscholen.be", wachtwoord: "0pkuJFx6" },
  { id: "otis.dubois", firstName: "Otis", lastName: "Dubois", vestiging: "Geraardsbergen", leerjaar: 2, klasgroep: "B", email: "otis.dubois@keerpuntscholen.be", wachtwoord: "ZQyAZ5Fr" },
  { id: "rosalie.dubois", firstName: "Rosalie", lastName: "Dubois", vestiging: "Hasselt", leerjaar: 4, klasgroep: "A", email: "rosalie.dubois@keerpuntscholen.be", wachtwoord: "rSXS3jEY" },
  { id: "florence.dupont", firstName: "Florence", lastName: "Dupont", vestiging: "Herselt", leerjaar: 6, klasgroep: "A", email: "florence.dupont@keerpuntscholen.be", wachtwoord: "aOxgYyh4" },
  { id: "henri.dupont", firstName: "Henri", lastName: "Dupont", vestiging: "Houthalen", leerjaar: 6, klasgroep: "A", email: "henri.dupont@keerpuntscholen.be", wachtwoord: "cLS3wnvv" },
  { id: "julie.dupont", firstName: "Julie", lastName: "Dupont", vestiging: "Mol", leerjaar: 2, klasgroep: "A", email: "julie.dupont@keerpuntscholen.be", wachtwoord: "hIrUdcW7" },
  { id: "lea.dupont", firstName: "Lea", lastName: "Dupont", vestiging: "Turnhout", leerjaar: 2, klasgroep: "A", email: "lea.dupont@keerpuntscholen.be", wachtwoord: "rACy9cIe" },
  { id: "mathis.dupont", firstName: "Mathis", lastName: "Dupont", vestiging: "Gent", leerjaar: 1, klasgroep: "A", email: "mathis.dupont@keerpuntscholen.be", wachtwoord: "5laVPHar" },
  { id: "tuur.dupont", firstName: "Tuur", lastName: "Dupont", vestiging: "Oudenaarde", leerjaar: 5, klasgroep: "A", email: "tuur.dupont@keerpuntscholen.be", wachtwoord: "u2SrQDq6" },
  { id: "amira.goossens", firstName: "Amira", lastName: "Goossens", vestiging: "Brussel", leerjaar: 6, klasgroep: "A", email: "amira.goossens@keerpuntscholen.be", wachtwoord: "jkTnmZ2V" },
  { id: "ellie.goossens", firstName: "Ellie", lastName: "Goossens", vestiging: "Geraardsbergen", leerjaar: 6, klasgroep: "A", email: "ellie.goossens@keerpuntscholen.be", wachtwoord: "Do2jdzhq" },
  { id: "emile.goossens", firstName: "Emile", lastName: "Goossens", vestiging: "Hasselt", leerjaar: 6, klasgroep: "A", email: "emile.goossens@keerpuntscholen.be", wachtwoord: "jrSCWRD2" },
  { id: "hamza.goossens", firstName: "Hamza", lastName: "Goossens", vestiging: "Herselt", leerjaar: 5, klasgroep: "A", email: "hamza.goossens@keerpuntscholen.be", wachtwoord: "mOrN5f8z" },
  { id: "ida.goossens", firstName: "Ida", lastName: "Goossens", vestiging: "Houthalen", leerjaar: 1, klasgroep: "A", email: "ida.goossens@keerpuntscholen.be", wachtwoord: "eToo1Eyc" },
  { id: "jack.goossens", firstName: "Jack", lastName: "Goossens", vestiging: "Mol", leerjaar: 1, klasgroep: "A", email: "jack.goossens@keerpuntscholen.be", wachtwoord: "Xw2AdgNC" },
  { id: "nora.goossens", firstName: "Nora", lastName: "Goossens", vestiging: "Turnhout", leerjaar: 6, klasgroep: "A", email: "nora.goossens@keerpuntscholen.be", wachtwoord: "GE0ymNPT" },
  { id: "oona.goossens", firstName: "Oona", lastName: "Goossens", vestiging: "Gent", leerjaar: 4, klasgroep: "A", email: "oona.goossens@keerpuntscholen.be", wachtwoord: "2XJHgfOy" },
  { id: "sara.goossens", firstName: "Sara", lastName: "Goossens", vestiging: "Oudenaarde", leerjaar: 1, klasgroep: "A", email: "sara.goossens@keerpuntscholen.be", wachtwoord: "UFbU4YdN" },
  { id: "zayn.goossens", firstName: "Zayn", lastName: "Goossens", vestiging: "Brussel", leerjaar: 1, klasgroep: "B", email: "zayn.goossens@keerpuntscholen.be", wachtwoord: "VoEwXkc5" },
  { id: "ellie.hermans", firstName: "Ellie", lastName: "Hermans", vestiging: "Geraardsbergen", leerjaar: 4, klasgroep: "A", email: "ellie.hermans@keerpuntscholen.be", wachtwoord: "Aljfql14" },
  { id: "leonie.hermans", firstName: "Leonie", lastName: "Hermans", vestiging: "Hasselt", leerjaar: 3, klasgroep: "A", email: "leonie.hermans@keerpuntscholen.be", wachtwoord: "Fa0O1Jjr" },
  { id: "mauro.hermans", firstName: "Mauro", lastName: "Hermans", vestiging: "Herselt", leerjaar: 6, klasgroep: "A", email: "mauro.hermans@keerpuntscholen.be", wachtwoord: "7zgc5sFW" },
  { id: "nina.hermans", firstName: "Nina", lastName: "Hermans", vestiging: "Houthalen", leerjaar: 4, klasgroep: "A", email: "nina.hermans@keerpuntscholen.be", wachtwoord: "8OzEF4In" },
  { id: "noah.hermans", firstName: "Noah", lastName: "Hermans", vestiging: "Mol", leerjaar: 5, klasgroep: "A", email: "noah.hermans@keerpuntscholen.be", wachtwoord: "NUu3b8cu" },
  { id: "noe.hermans", firstName: "Noé", lastName: "Hermans", vestiging: "Turnhout", leerjaar: 3, klasgroep: "A", email: "noe.hermans@keerpuntscholen.be", wachtwoord: "vT6Jf3lO" },
  { id: "elena.jacobs", firstName: "Elena", lastName: "Jacobs", vestiging: "Gent", leerjaar: 2, klasgroep: "A", email: "elena.jacobs@keerpuntscholen.be", wachtwoord: "b73jYRIS" },
  { id: "flo.jacobs", firstName: "Flo", lastName: "Jacobs", vestiging: "Oudenaarde", leerjaar: 3, klasgroep: "A", email: "flo.jacobs@keerpuntscholen.be", wachtwoord: "RNf8pn9z" },
  { id: "julia.jacobs", firstName: "Julia", lastName: "Jacobs", vestiging: "Brussel", leerjaar: 4, klasgroep: "A", email: "julia.jacobs@keerpuntscholen.be", wachtwoord: "2nYOtIXi" },
  { id: "luna.jacobs", firstName: "Luna", lastName: "Jacobs", vestiging: "Geraardsbergen", leerjaar: 4, klasgroep: "A", email: "luna.jacobs@keerpuntscholen.be", wachtwoord: "oatS9SZn" },
  { id: "amelia.janssens", firstName: "Amelia", lastName: "Janssens", vestiging: "Hasselt", leerjaar: 2, klasgroep: "A", email: "amelia.janssens@keerpuntscholen.be", wachtwoord: "Ua896Pj4" },
  { id: "august.janssens", firstName: "August", lastName: "Janssens", vestiging: "Herselt", leerjaar: 1, klasgroep: "B", email: "august.janssens@keerpuntscholen.be", wachtwoord: "d8zBp9TX" },
  { id: "eloise.janssens", firstName: "Eloïse", lastName: "Janssens", vestiging: "Houthalen", leerjaar: 2, klasgroep: "A", email: "eloise.janssens@keerpuntscholen.be", wachtwoord: "80OWrEpX" },
  { id: "gabriel.janssens", firstName: "Gabriel", lastName: "Janssens", vestiging: "Mol", leerjaar: 1, klasgroep: "A", email: "gabriel.janssens@keerpuntscholen.be", wachtwoord: "hwRl7gGu" },
  { id: "hamza.janssens", firstName: "Hamza", lastName: "Janssens", vestiging: "Turnhout", leerjaar: 2, klasgroep: "A", email: "hamza.janssens@keerpuntscholen.be", wachtwoord: "x5WuWQq3" },
  { id: "jack.janssens", firstName: "Jack", lastName: "Janssens", vestiging: "Gent", leerjaar: 5, klasgroep: "A", email: "jack.janssens@keerpuntscholen.be", wachtwoord: "dH9zU1E5" },
  { id: "leonie.janssens", firstName: "Leonie", lastName: "Janssens", vestiging: "Oudenaarde", leerjaar: 2, klasgroep: "A", email: "leonie.janssens@keerpuntscholen.be", wachtwoord: "h6urARRB" },
  { id: "millie.janssens", firstName: "Millie", lastName: "Janssens", vestiging: "Brussel", leerjaar: 1, klasgroep: "A", email: "millie.janssens@keerpuntscholen.be", wachtwoord: "oh2Sxupn" },
  { id: "oscar.janssens", firstName: "Oscar", lastName: "Janssens", vestiging: "Geraardsbergen", leerjaar: 1, klasgroep: "A", email: "oscar.janssens@keerpuntscholen.be", wachtwoord: "CspVn4Zp" },
  { id: "alexander.lambert", firstName: "Alexander", lastName: "Lambert", vestiging: "Hasselt", leerjaar: 1, klasgroep: "B", email: "alexander.lambert@keerpuntscholen.be", wachtwoord: "bBHG4Pf4" },
  { id: "david.lambert", firstName: "David", lastName: "Lambert", vestiging: "Herselt", leerjaar: 4, klasgroep: "A", email: "david.lambert@keerpuntscholen.be", wachtwoord: "3OkCkvL6" },
  { id: "ida.lambert", firstName: "Ida", lastName: "Lambert", vestiging: "Houthalen", leerjaar: 1, klasgroep: "B", email: "ida.lambert@keerpuntscholen.be", wachtwoord: "h2Ht1rL2" },
  { id: "mats.lambert", firstName: "Mats", lastName: "Lambert", vestiging: "Mol", leerjaar: 4, klasgroep: "A", email: "mats.lambert@keerpuntscholen.be", wachtwoord: "3A9vvHgw" },
  { id: "victor.lambert", firstName: "Victor", lastName: "Lambert", vestiging: "Turnhout", leerjaar: 3, klasgroep: "A", email: "victor.lambert@keerpuntscholen.be", wachtwoord: "oxO13iRx" },
  { id: "aya.maes", firstName: "Aya", lastName: "Maes", vestiging: "Gent", leerjaar: 3, klasgroep: "A", email: "aya.maes@keerpuntscholen.be", wachtwoord: "vg5e9Oy3" },
  { id: "elias.maes", firstName: "Elias", lastName: "Maes", vestiging: "Oudenaarde", leerjaar: 2, klasgroep: "A", email: "elias.maes@keerpuntscholen.be", wachtwoord: "p1lVVg2A" },
  { id: "estelle.maes", firstName: "Estelle", lastName: "Maes", vestiging: "Brussel", leerjaar: 4, klasgroep: "A", email: "estelle.maes@keerpuntscholen.be", wachtwoord: "Ty1EjtpY" },
  { id: "ibrahim.maes", firstName: "Ibrahim", lastName: "Maes", vestiging: "Geraardsbergen", leerjaar: 2, klasgroep: "B", email: "ibrahim.maes@keerpuntscholen.be", wachtwoord: "kJT6nnDs" },
  { id: "liam.maes", firstName: "Liam", lastName: "Maes", vestiging: "Hasselt", leerjaar: 1, klasgroep: "B", email: "liam.maes@keerpuntscholen.be", wachtwoord: "lTg8pKr1" },
  { id: "mauro.maes", firstName: "Mauro", lastName: "Maes", vestiging: "Herselt", leerjaar: 3, klasgroep: "A", email: "mauro.maes@keerpuntscholen.be", wachtwoord: "Etn7UUI8" },
  { id: "mia.maes", firstName: "Mia", lastName: "Maes", vestiging: "Houthalen", leerjaar: 2, klasgroep: "A", email: "mia.maes@keerpuntscholen.be", wachtwoord: "vZdr1BKT" },
  { id: "noe.maes", firstName: "Noé", lastName: "Maes", vestiging: "Mol", leerjaar: 4, klasgroep: "A", email: "noe.maes@keerpuntscholen.be", wachtwoord: "kNArIxG7" },
  { id: "finn.martens", firstName: "Finn", lastName: "Martens", vestiging: "Turnhout", leerjaar: 2, klasgroep: "A", email: "finn.martens@keerpuntscholen.be", wachtwoord: "k2QD98O3" },
  { id: "jeanne.martens", firstName: "Jeanne", lastName: "Martens", vestiging: "Gent", leerjaar: 4, klasgroep: "A", email: "jeanne.martens@keerpuntscholen.be", wachtwoord: "6P8Cs8tR" },
  { id: "lou.martens", firstName: "Lou", lastName: "Martens", vestiging: "Oudenaarde", leerjaar: 6, klasgroep: "A", email: "lou.martens@keerpuntscholen.be", wachtwoord: "aAKcrF1s" },
  { id: "loic.martens", firstName: "Loïc", lastName: "Martens", vestiging: "Brussel", leerjaar: 6, klasgroep: "A", email: "loic.martens@keerpuntscholen.be", wachtwoord: "ZF4sHwPj" },
  { id: "noor.martens", firstName: "Noor", lastName: "Martens", vestiging: "Geraardsbergen", leerjaar: 1, klasgroep: "A", email: "noor.martens@keerpuntscholen.be", wachtwoord: "3OrS6Toc" },
  { id: "renee.martens", firstName: "Renée", lastName: "Martens", vestiging: "Hasselt", leerjaar: 5, klasgroep: "A", email: "renee.martens@keerpuntscholen.be", wachtwoord: "VIKkmYJ9" },
  { id: "eloise.mertens", firstName: "Eloïse", lastName: "Mertens", vestiging: "Herselt", leerjaar: 6, klasgroep: "A", email: "eloise.mertens@keerpuntscholen.be", wachtwoord: "lVrW2E8c" },
  { id: "gabriel.mertens", firstName: "Gabriel", lastName: "Mertens", vestiging: "Houthalen", leerjaar: 1, klasgroep: "A", email: "gabriel.mertens@keerpuntscholen.be", wachtwoord: "NskPv1d8" },
  { id: "jade.mertens", firstName: "Jade", lastName: "Mertens", vestiging: "Mol", leerjaar: 6, klasgroep: "A", email: "jade.mertens@keerpuntscholen.be", wachtwoord: "c05eGQ1z" },
  { id: "jeanne.mertens", firstName: "Jeanne", lastName: "Mertens", vestiging: "Turnhout", leerjaar: 5, klasgroep: "A", email: "jeanne.mertens@keerpuntscholen.be", wachtwoord: "X0KzbJWS" },
  { id: "juliette.mertens", firstName: "Juliette", lastName: "Mertens", vestiging: "Gent", leerjaar: 6, klasgroep: "A", email: "juliette.mertens@keerpuntscholen.be", wachtwoord: "0gA6dK3q" },
  { id: "lea.mertens", firstName: "Lea", lastName: "Mertens", vestiging: "Oudenaarde", leerjaar: 3, klasgroep: "A", email: "lea.mertens@keerpuntscholen.be", wachtwoord: "HDw3Ixr3" },
  { id: "liam.mertens", firstName: "Liam", lastName: "Mertens", vestiging: "Brussel", leerjaar: 2, klasgroep: "B", email: "liam.mertens@keerpuntscholen.be", wachtwoord: "MHEqVRz7" },
  { id: "mia.mertens", firstName: "Mia", lastName: "Mertens", vestiging: "Geraardsbergen", leerjaar: 6, klasgroep: "A", email: "mia.mertens@keerpuntscholen.be", wachtwoord: "OoWJy3zm" },
  { id: "theo.mertens", firstName: "Theo", lastName: "Mertens", vestiging: "Hasselt", leerjaar: 1, klasgroep: "B", email: "theo.mertens@keerpuntscholen.be", wachtwoord: "4Qu0BzZV" },
  { id: "alice.michiels", firstName: "Alice", lastName: "Michiels", vestiging: "Herselt", leerjaar: 6, klasgroep: "A", email: "alice.michiels@keerpuntscholen.be", wachtwoord: "6f7nXBIi" },
  { id: "arthur.michiels", firstName: "Arthur", lastName: "Michiels", vestiging: "Houthalen", leerjaar: 2, klasgroep: "B", email: "arthur.michiels@keerpuntscholen.be", wachtwoord: "zefLsoU7" },
  { id: "oliver.michiels", firstName: "Oliver", lastName: "Michiels", vestiging: "Mol", leerjaar: 4, klasgroep: "A", email: "oliver.michiels@keerpuntscholen.be", wachtwoord: "qnVYh7kO" },
  { id: "amelia.pauwels", firstName: "Amelia", lastName: "Pauwels", vestiging: "Turnhout", leerjaar: 5, klasgroep: "A", email: "amelia.pauwels@keerpuntscholen.be", wachtwoord: "IcZ4bd5v" },
  { id: "anna.pauwels", firstName: "Anna", lastName: "Pauwels", vestiging: "Gent", leerjaar: 4, klasgroep: "A", email: "anna.pauwels@keerpuntscholen.be", wachtwoord: "UyF7wBSc" },
  { id: "georges.pauwels", firstName: "Georges", lastName: "Pauwels", vestiging: "Oudenaarde", leerjaar: 2, klasgroep: "A", email: "georges.pauwels@keerpuntscholen.be", wachtwoord: "DhPdEsT6" },
  { id: "maurice.pauwels", firstName: "Maurice", lastName: "Pauwels", vestiging: "Brussel", leerjaar: 1, klasgroep: "B", email: "maurice.pauwels@keerpuntscholen.be", wachtwoord: "ln4vGRwI" },
  { id: "chloe.peeters", firstName: "Chloé", lastName: "Peeters", vestiging: "Geraardsbergen", leerjaar: 2, klasgroep: "A", email: "chloe.peeters@keerpuntscholen.be", wachtwoord: "dRVsNx8W" },
  { id: "eloise.peeters", firstName: "Eloïse", lastName: "Peeters", vestiging: "Hasselt", leerjaar: 1, klasgroep: "A", email: "eloise.peeters@keerpuntscholen.be", wachtwoord: "jel8DZj9" },
  { id: "jade.peeters", firstName: "Jade", lastName: "Peeters", vestiging: "Herselt", leerjaar: 1, klasgroep: "A", email: "jade.peeters@keerpuntscholen.be", wachtwoord: "Vp6k2Cyp" },
  { id: "julia.peeters", firstName: "Julia", lastName: "Peeters", vestiging: "Houthalen", leerjaar: 5, klasgroep: "A", email: "julia.peeters@keerpuntscholen.be", wachtwoord: "HC3eBPJz" },
  { id: "juliette.peeters", firstName: "Juliette", lastName: "Peeters", vestiging: "Mol", leerjaar: 3, klasgroep: "A", email: "juliette.peeters@keerpuntscholen.be", wachtwoord: "56BIsuSF" },
  { id: "romee.peeters", firstName: "Romée", lastName: "Peeters", vestiging: "Turnhout", leerjaar: 2, klasgroep: "B", email: "romee.peeters@keerpuntscholen.be", wachtwoord: "gR0Qh9HW" },
  { id: "tuur.peeters", firstName: "Tuur", lastName: "Peeters", vestiging: "Gent", leerjaar: 5, klasgroep: "A", email: "tuur.peeters@keerpuntscholen.be", wachtwoord: "2cYpe6yh" },
  { id: "chloe.smets", firstName: "Chloé", lastName: "Smets", vestiging: "Oudenaarde", leerjaar: 2, klasgroep: "B", email: "chloe.smets@keerpuntscholen.be", wachtwoord: "7rLi4p6X" },
  { id: "jeanne.smets", firstName: "Jeanne", lastName: "Smets", vestiging: "Brussel", leerjaar: 1, klasgroep: "B", email: "jeanne.smets@keerpuntscholen.be", wachtwoord: "bCZhl1Pn" },
  { id: "louise.smets", firstName: "Louise", lastName: "Smets", vestiging: "Geraardsbergen", leerjaar: 3, klasgroep: "A", email: "louise.smets@keerpuntscholen.be", wachtwoord: "tCMS9S2l" },
  { id: "maria.smets", firstName: "Maria", lastName: "Smets", vestiging: "Hasselt", leerjaar: 5, klasgroep: "A", email: "maria.smets@keerpuntscholen.be", wachtwoord: "3bxY1a5N" },
  { id: "millie.smets", firstName: "Millie", lastName: "Smets", vestiging: "Herselt", leerjaar: 1, klasgroep: "A", email: "millie.smets@keerpuntscholen.be", wachtwoord: "iTGSA7u2" },
  { id: "nour.smets", firstName: "Nour", lastName: "Smets", vestiging: "Houthalen", leerjaar: 4, klasgroep: "A", email: "nour.smets@keerpuntscholen.be", wachtwoord: "aZa9joj0" },
  { id: "remi.smets", firstName: "Remi", lastName: "Smets", vestiging: "Mol", leerjaar: 3, klasgroep: "A", email: "remi.smets@keerpuntscholen.be", wachtwoord: "uwI5KZ3W" },
  { id: "tuur.smets", firstName: "Tuur", lastName: "Smets", vestiging: "Turnhout", leerjaar: 4, klasgroep: "A", email: "tuur.smets@keerpuntscholen.be", wachtwoord: "Yy1Lx8of" },
  { id: "alexander.van.damme", firstName: "Alexander", lastName: "Van Damme", vestiging: "Gent", leerjaar: 3, klasgroep: "A", email: "alexander.van.damme@keerpuntscholen.be", wachtwoord: "3YDRrmrC" },
  { id: "estelle.van.damme", firstName: "Estelle", lastName: "Van Damme", vestiging: "Oudenaarde", leerjaar: 5, klasgroep: "A", email: "estelle.van.damme@keerpuntscholen.be", wachtwoord: "PaqLA5kt" },
  { id: "gabriel.van.damme", firstName: "Gabriel", lastName: "Van Damme", vestiging: "Brussel", leerjaar: 3, klasgroep: "A", email: "gabriel.van.damme@keerpuntscholen.be", wachtwoord: "cNaRVm7n" },
  { id: "lia.van.damme", firstName: "Lia", lastName: "Van Damme", vestiging: "Geraardsbergen", leerjaar: 6, klasgroep: "A", email: "lia.van.damme@keerpuntscholen.be", wachtwoord: "77p923Zv" },
  { id: "leonie.vermeulen", firstName: "Leonie", lastName: "Vermeulen", vestiging: "Hasselt", leerjaar: 3, klasgroep: "A", email: "leonie.vermeulen@keerpuntscholen.be", wachtwoord: "0h2n6xjS" },
  { id: "ada.willems", firstName: "Ada", lastName: "Willems", vestiging: "Herselt", leerjaar: 4, klasgroep: "A", email: "ada.willems@keerpuntscholen.be", wachtwoord: "RZ59RDMu" },
  { id: "chloe.willems", firstName: "Chloé", lastName: "Willems", vestiging: "Houthalen", leerjaar: 3, klasgroep: "A", email: "chloe.willems@keerpuntscholen.be", wachtwoord: "aKkK2V1s" },
  { id: "leonie.willems", firstName: "Leonie", lastName: "Willems", vestiging: "Mol", leerjaar: 5, klasgroep: "A", email: "leonie.willems@keerpuntscholen.be", wachtwoord: "i0JYo8Ob" },
  { id: "livia.willems", firstName: "Livia", lastName: "Willems", vestiging: "Turnhout", leerjaar: 6, klasgroep: "A", email: "livia.willems@keerpuntscholen.be", wachtwoord: "TBAD6hNm" },
  { id: "noe.willems", firstName: "Noé", lastName: "Willems", vestiging: "Gent", leerjaar: 6, klasgroep: "A", email: "noe.willems@keerpuntscholen.be", wachtwoord: "vP7Xemas" },
  { id: "rosalie.willems", firstName: "Rosalie", lastName: "Willems", vestiging: "Oudenaarde", leerjaar: 3, klasgroep: "A", email: "rosalie.willems@keerpuntscholen.be", wachtwoord: "8W5k3Fh8" },
  { id: "amelia.wouters", firstName: "Amelia", lastName: "Wouters", vestiging: "Brussel", leerjaar: 2, klasgroep: "B", email: "amelia.wouters@keerpuntscholen.be", wachtwoord: "WjYpdT6i" },
  { id: "hamza.wouters", firstName: "Hamza", lastName: "Wouters", vestiging: "Geraardsbergen", leerjaar: 4, klasgroep: "A", email: "hamza.wouters@keerpuntscholen.be", wachtwoord: "EWLP0yWi" },
  { id: "levi.wouters", firstName: "Levi", lastName: "Wouters", vestiging: "Hasselt", leerjaar: 2, klasgroep: "A", email: "levi.wouters@keerpuntscholen.be", wachtwoord: "HzLq43rE" },
  { id: "louise.wouters", firstName: "Louise", lastName: "Wouters", vestiging: "Herselt", leerjaar: 3, klasgroep: "A", email: "louise.wouters@keerpuntscholen.be", wachtwoord: "Y7jNpJdP" },
];

export const seedMentoren: Mentor[] = [
  { id: "gabriel.aerts", voornaam: "Gabriel", naam: "Aerts", vestiging: "Gent", email: "gabriel.aerts@keerpuntscholen.be", wachtwoord: "ry3mm1LU" },
  { id: "leonie.claes", voornaam: "Leonie", naam: "Claes", vestiging: "Oudenaarde", email: "leonie.claes@keerpuntscholen.be", wachtwoord: "6mzNElce" },
  { id: "cilou.de.clercq", voornaam: "Cilou", naam: "De Clercq", vestiging: "Brussel", email: "cilou.de.clercq@keerpuntscholen.be", wachtwoord: "hnpYK5kC" },
  { id: "millie.desmet", voornaam: "Millie", naam: "Desmet", vestiging: "Geraardsbergen", email: "millie.desmet@keerpuntscholen.be", wachtwoord: "WZLgU979" },
  { id: "august.diallo", voornaam: "August", naam: "Diallo", vestiging: "Hasselt", email: "august.diallo@keerpuntscholen.be", wachtwoord: "OQ1DbG5x" },
  { id: "lewis.diallo", voornaam: "Lewis", naam: "Diallo", vestiging: "Herselt", email: "lewis.diallo@keerpuntscholen.be", wachtwoord: "kHlqsj8O" },
  { id: "mila.diallo", voornaam: "Mila", naam: "Diallo", vestiging: "Houthalen", email: "mila.diallo@keerpuntscholen.be", wachtwoord: "ctWJyRY1" },
  { id: "eva.dubois", voornaam: "Eva", naam: "Dubois", vestiging: "Mol", email: "eva.dubois@keerpuntscholen.be", wachtwoord: "81PXzPQu" },
  { id: "lio.dubois", voornaam: "Lio", naam: "Dubois", vestiging: "Turnhout", email: "lio.dubois@keerpuntscholen.be", wachtwoord: "R6IKTQfR" },
  { id: "finn.jacobs", voornaam: "Finn", naam: "Jacobs", vestiging: "Gent", email: "finn.jacobs@keerpuntscholen.be", wachtwoord: "2Z0y1yja" },
  { id: "viktor.jacobs", voornaam: "Viktor", naam: "Jacobs", vestiging: "Oudenaarde", email: "viktor.jacobs@keerpuntscholen.be", wachtwoord: "DdXMLU8z" },
  { id: "gabriel.lambert", voornaam: "Gabriel", naam: "Lambert", vestiging: "Brussel", email: "gabriel.lambert@keerpuntscholen.be", wachtwoord: "sWWMn2d1" },
  { id: "cas.martens", voornaam: "Cas", naam: "Martens", vestiging: "Geraardsbergen", email: "cas.martens@keerpuntscholen.be", wachtwoord: "A3nmz51Y" },
  { id: "cezanne.martens", voornaam: "Cézanne", naam: "Martens", vestiging: "Hasselt", email: "cezanne.martens@keerpuntscholen.be", wachtwoord: "oFJGRIw5" },
  { id: "ellie.martens", voornaam: "Ellie", naam: "Martens", vestiging: "Herselt", email: "ellie.martens@keerpuntscholen.be", wachtwoord: "9b4MxcAl" },
  { id: "noe.martens", voornaam: "Noé", naam: "Martens", vestiging: "Houthalen", email: "noe.martens@keerpuntscholen.be", wachtwoord: "mMlHZ7k5" },
  { id: "gust.mertens", voornaam: "Gust", naam: "Mertens", vestiging: "Mol", email: "gust.mertens@keerpuntscholen.be", wachtwoord: "3LZjVfhK" },
  { id: "leonie.smets", voornaam: "Leonie", naam: "Smets", vestiging: "Turnhout", email: "leonie.smets@keerpuntscholen.be", wachtwoord: "9jD6FH16" },
  { id: "eva.van.damme", voornaam: "Eva", naam: "Van Damme", vestiging: "Gent", email: "eva.van.damme@keerpuntscholen.be", wachtwoord: "7udEUcPs" },
  { id: "marie.vermeulen", voornaam: "Marie", naam: "Vermeulen", vestiging: "Oudenaarde", email: "marie.vermeulen@keerpuntscholen.be", wachtwoord: "7WI8Ozfj" },
];
